### ISSUE TITLE
Exception in ChangeTracker

### ISSUE THREAD

**Issue by jamiltz** [couchbase/couchbase-lite-java-core#1007]
Here's the exception that was thrown in logcat:
```
W/ChangeTracker: com.couchbase.lite.replicator.ChangeTracker@37452d: Exception in change tracker
   java.net.SocketTimeoutException
       at java.net.PlainSocketImpl.read(PlainSocketImpl.java:488)
       at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:37)
       at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)
       at org.apache.http.impl.io.AbstractSessionInputBuffer.fillBuffer(AbstractSessionInputBuffer.java:108)
       at org.apache.http.impl.io.AbstractSessionInputBuffer.readLine(AbstractSessionInputBuffer.java:196)
       at org.apache.http.impl.conn.DefaultResponseParser.parseHead(DefaultResponseParser.java:88)
       at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:179)
       at org.apache.http.impl.AbstractHttpClientConnection.receiveResponseHeader(AbstractHttpClientConnection.java:185)
       at org.apache.http.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:240)
       at org.apache.http.impl.conn.AbstractClientConnAdapter.receiveResponseHeader(AbstractClientConnAdapter.java:264)
       at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:284)
       at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:126)
       at org.apache.http.impl.client.DefaultRequestDirector.executeOriginal(DefaultRequestDirector.java:1398)
       at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:707)
       at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:699)
       at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:520)
       at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:498)
       at com.couchbase.lite.replicator.ChangeTracker.runLoop(ChangeTracker.java:327)
       at com.couchbase.lite.replicator.ChangeTracker.run(ChangeTracker.java:228)
       at java.lang.Thread.run(Thread.java:818)
```

To reproduce:

- Start this app (https://github.com/jamiltz/P2PSync-Android) and check out on the `issue/change_tracker_exception` branch.
- Use two phones connected to same wifi
- On device 1, click expose service button
- On device 2, click discover services
- Add documents on each side, the document count should be the same
- The change tracker exception appears in logs of device 2

**Comment by jamiltz** [comment]
Looks similar to https://github.com/couchbase/couchbase-lite-android/issues/777.

**Comment by hideki** [comment]
SocketTimeoutException could happen if there is connectivity issue.

Does app recover from this exception? If yes, this could be logging issue. If not, we need to investigate deeper.

**Comment by hideki** [comment]
This is duplicate with #1026.
