### ISSUE TITLE
Change tracker stopping during replication exception

### ISSUE THREAD

**Issue by jamiltz** [couchbase/couchbase-lite-java-core#1026]
Exception:

```
Replicator error: java.lang.Exception: Change tracker stopped during continuous replication.
Repl: com.couchbase.lite.replicator.Replication@3179e982. 
Source: http://192.168.1.6:5984/ek0073, Target: ek0073
```

Scenario:

5 devices are connected to the same WiFi. One is the master device where it manages push/pull replications to the other 4 devices.

- Take master device to the `edge` of the network.
- Out of 4 push/pull replications, 3 had the I/O exception and 1 had the change tracker exception above.

If the network goes down I'm assuming that all replications should have the I/O exception. Any idea what could be causing the change tracker to stop in this scenario?

**Comment by hideki** [comment]
Followings are my expectation
- master device: Detects device offline
- 4 slave devices: Receives SocketTimeoutException

Do you have additional log message from the device prints above message?

**Comment by hideki** [comment]
4 devices runs listener
1 master device - no listener - use pull push replicator

expectation:
Once master became online, master should push to slave devices

**Comment by hideki** [comment]
Log message from master: https://gist.github.com/jamiltz/042d625e84e7b02fdc37

**Comment by jamiltz** [comment]
May be related to https://github.com/couchbase/couchbase-lite-java-core/issues/1015

**Comment by hideki** [comment]
Push fails to restart by NPE in changesSince() method
```
java.lang.NullPointerException: Attempt to invoke virtual method 'com.couchbase.lite.RevisionList com.couchbase.lite.Database.changesSince(long, com.couchbase.lite.ChangesOptions, com.couchbase.lite.ReplicationFilter, java.util.Map)' on a null object reference
 at com.couchbase.lite.replicator.PusherInternal.beginReplicating(PusherInternal.java:271)
``

**Comment by hideki** [comment]
4 places to call `triggerStopGraceful()'
- As GrocerySync holds Manager/Database instances from Activity, first two calls are expected when App goes to background to switch Wifi.


```
02-10 17:28:28.186: W/System.err(10585): java.lang.Exception: [triggerStopGraceful()] com.couchbase.lite.replicator.PusherInternal@5631918
02-10 17:28:28.187: W/System.err(10585): 	at com.couchbase.lite.replicator.ReplicationInternal.triggerStopGraceful(ReplicationInternal.java:176)
02-10 17:28:28.187: W/System.err(10585): 	at com.couchbase.lite.replicator.PusherInternal.triggerStopGraceful(PusherInternal.java:50)
02-10 17:28:28.187: W/System.err(10585): 	at com.couchbase.lite.replicator.ReplicationInternal.databaseClosing(ReplicationInternal.java:286)
02-10 17:28:28.187: W/System.err(10585): 	at com.couchbase.lite.replicator.PusherInternal.databaseClosing(PusherInternal.java:50)
02-10 17:28:28.187: W/System.err(10585): 	at com.couchbase.lite.replicator.Replication.databaseClosing(Replication.java:827)
02-10 17:28:28.187: W/System.err(10585): 	at com.couchbase.lite.Database.close(Database.java:1298)
02-10 17:28:28.187: W/System.err(10585): 	at com.couchbase.lite.Manager.close(Manager.java:268)
02-10 17:28:28.187: W/System.err(10585): 	at com.couchbase.grocerysync.MainActivity.onDestroy(MainActivity.java:105)
```

```
02-10 17:28:28.194: W/System.err(10585): java.lang.Exception: [triggerStopGraceful()] com.couchbase.lite.replicator.PullerInternal@f0939df
02-10 17:28:28.195: D/Sync(10585): State transition: OFFLINE -> STOPPING (via STOP_GRACEFUL).  this: com.couchbase.lite.replicator.PusherInternal@5631918
02-10 17:28:28.195: V/Sync(10585): com.couchbase.lite.support.RemoteRequest@3cda5fe: RemoteRequest finally block.  url: http://demo-mobile.couchbase.com/grocery-sync/_local/97c81517101f3e300eb0c55c1af6dbc6fc84d7f0
02-10 17:28:28.195: V/Sync(10585): com.couchbase.lite.support.RemoteRequest@3cda5fe: RemoteRequest calling respondWithResult.  url: http://demo-mobile.couchbase.com/grocery-sync/_local/97c81517101f3e300eb0c55c1af6dbc6fc84d7f0, error: java.net.UnknownHostException: Unable to resolve host "demo-mobile.couchbase.com": No address associated with hostname
02-10 17:28:28.195: D/Sync(10585): com.couchbase.lite.replicator.PusherInternal@5631918 STOPPING...
02-10 17:28:28.195: D/Sync(10585): com.couchbase.lite.support.RemoteRequestRetry$1@45a240a: RemoteRequestRetry inner request finished, url: http://demo-mobile.couchbase.com/grocery-sync/_local/97c81517101f3e300eb0c55c1af6dbc6fc84d7f0
02-10 17:28:28.196: W/System.err(10585): 	at com.couchbase.lite.replicator.ReplicationInternal.triggerStopGraceful(ReplicationInternal.java:176)
02-10 17:28:28.196: D/Sync(10585): com.couchbase.lite.support.RemoteRequestRetry@c884db9: isTransientError called, httpResponse: null e: java.net.UnknownHostException: Unable to resolve host "demo-mobile.couchbase.com": No address associated with hostname
02-10 17:28:28.196: W/System.err(10585): 	at com.couchbase.lite.replicator.PullerInternal.triggerStopGraceful(PullerInternal.java:49)
02-10 17:28:28.196: D/Sync(10585): com.couchbase.lite.support.RemoteRequestRetry@c884db9: its an ioexception, return true
02-10 17:28:28.196: W/System.err(10585): 	at com.couchbase.lite.replicator.ReplicationInternal.databaseClosing(ReplicationInternal.java:286)
02-10 17:28:28.196: W/System.err(10585): 	at com.couchbase.lite.replicator.PullerInternal.databaseClosing(PullerInternal.java:49)
02-10 17:28:28.196: D/Sync(10585): com.couchbase.lite.support.RemoteRequestRetry$1@45a240a: RemoteRequestRetry failed, but transient error.  will retry. url: http://demo-mobile.couchbase.com/grocery-sync/_local/97c81517101f3e300eb0c55c1af6dbc6fc84d7f0
02-10 17:28:28.196: W/System.err(10585): 	at com.couchbase.lite.replicator.Replication.databaseClosing(Replication.java:827)
02-10 17:28:28.196: W/System.err(10585): 	at com.couchbase.lite.Database.close(Database.java:1298)
02-10 17:28:28.196: W/System.err(10585): 	at com.couchbase.lite.Manager.close(Manager.java:268)
02-10 17:28:28.196: W/System.err(10585): 	at com.couchbase.grocerysync.MainActivity.onDestroy(MainActivity.java:105)
```

```
02-10 17:29:00.492: W/Sync(10585): com.couchbase.lite.replicator.ReplicationInternal$10@24fa7e2: error getting remote checkpoint
02-10 17:29:00.492: E/Sync(10585): com.couchbase.lite.replicator.PusherInternal@9b35eff: Progress: set error = java.net.UnknownHostException: Unable to resolve host "demo-mobile.couchbase.com": No address associated with hostname
02-10 17:29:00.493: D/GrocerySync(10585): Replication : com.couchbase.lite.replicator.Replication@ecff55d changed.
02-10 17:29:00.493: W/System.err(10585): java.lang.Exception: [triggerStopGraceful()] com.couchbase.lite.replicator.PusherInternal@9b35eff
02-10 17:29:00.494: W/System.err(10585): 	at com.couchbase.lite.replicator.ReplicationInternal.triggerStopGraceful(ReplicationInternal.java:176)
02-10 17:29:00.495: W/System.err(10585): 	at com.couchbase.lite.replicator.PusherInternal.triggerStopGraceful(PusherInternal.java:50)
02-10 17:29:00.495: W/System.err(10585): 	at com.couchbase.lite.replicator.ReplicationInternal$10.onCompletion(ReplicationInternal.java:875)
02-10 17:29:00.496: W/System.err(10585): 	at com.couchbase.lite.support.RemoteRequestRetry$1.completed(RemoteRequestRetry.java:213)
02-10 17:29:00.496: V/Sync(10585): com.couchbase.lite.support.RemoteRequest@915ac18: RemoteRequest finally block.  url: http://demo-mobile.couchbase.com/grocery-sync/_local/a5064fdcc1a3c5ab13c71b48cb9635d1606fe9c4
02-10 17:29:00.496: W/System.err(10585): 	at com.couchbase.lite.support.RemoteRequestRetry$1.onCompletion(RemoteRequestRetry.java:245)
02-10 17:29:00.497: W/System.err(10585): 	at com.couchbase.lite.support.RemoteRequest.respondWithResult(RemoteRequest.java:299)
02-10 17:29:00.497: V/Sync(10585): com.couchbase.lite.support.RemoteRequest@915ac18: RemoteRequest calling respondWithResult.  url: http://demo-mobile.couchbase.com/grocery-sync/_local/a5064fdcc1a3c5ab13c71b48cb9635d1606fe9c4, error: java.net.UnknownHostException: Unable to resolve host "demo-mobile.couchbase.com": No address associated with hostname
02-10 17:29:00.497: W/System.err(10585): 	at com.couchbase.lite.support.RemoteRequest.executeRequest(RemoteRequest.java:248)
02-10 17:29:00.497: D/Sync(10585): com.couchbase.lite.support.RemoteRequestRetry$1@f1c962a: RemoteRequestRetry inner request finished, url: http://demo-mobile.couchbase.com/grocery-sync/_local/a5064fdcc1a3c5ab13c71b48cb9635d1606fe9c4
02-10 17:29:00.497: W/System.err(10585): 	at com.couchbase.lite.support.RemoteRequest.run(RemoteRequest.java:102)
```

```
02-10 17:29:00.507: V/Sync(10585): com.couchbase.lite.support.RemoteRequestRetry@d44602e: RemoteRequestRetry created, url: http://demo-mobile.couchbase.com/grocery-sync/_local/97c81517101f3e300eb0c55c1af6dbc6fc84d7f0
02-10 17:29:00.507: V/Sync(10585): com.couchbase.lite.support.RemoteRequest@cff27cf: RemoteRequest created, url: http://demo-mobile.couchbase.com/grocery-sync/_local/97c81517101f3e300eb0c55c1af6dbc6fc84d7f0
02-10 17:29:00.502: W/System.err(10585): java.lang.Exception: [triggerStopGraceful()] com.couchbase.lite.replicator.PullerInternal@383b607
02-10 17:29:00.509: W/System.err(10585): 	at com.couchbase.lite.replicator.ReplicationInternal.triggerStopGraceful(ReplicationInternal.java:176)
02-10 17:29:00.509: V/Sync(10585): com.couchbase.lite.support.RemoteRequest@cff27cf: RemoteRequest run() called, url: http://demo-mobile.couchbase.com/grocery-sync/_local/97c81517101f3e300eb0c55c1af6dbc6fc84d7f0
02-10 17:29:00.509: W/System.err(10585): 	at com.couchbase.lite.replicator.PullerInternal.triggerStopGraceful(PullerInternal.java:49)
02-10 17:29:00.509: W/System.err(10585): 	at com.couchbase.lite.replicator.ReplicationInternal$10.onCompletion(ReplicationInternal.java:875)
02-10 17:29:00.510: W/System.err(10585): 	at com.couchbase.lite.support.RemoteRequestRetry$1.completed(RemoteRequestRetry.java:213)
02-10 17:29:00.510: W/System.err(10585): 	at com.couchbase.lite.support.RemoteRequestRetry$1.onCompletion(RemoteRequestRetry.java:245)
02-10 17:29:00.510: W/System.err(10585): 	at com.couchbase.lite.support.RemoteRequest.respondWithResult(RemoteRequest.java:299)
02-10 17:29:00.510: W/System.err(10585): 	at com.couchbase.lite.support.RemoteRequest.executeRequest(RemoteRequest.java:248)
02-10 17:29:00.510: W/System.err(10585): 	at com.couchbase.lite.support.RemoteRequest.run(RemoteRequest.java:102)
```
https://gist.github.com/hideki/34490b0db463095b7783

**Comment by hideki** [comment]
CBL received goOnline() then replicator tries to access server/URL, but it fails by network error. So we might need to implement server reachability check when goOnline event is received. Followings are .NET implementation.

https://github.com/couchbase/couchbase-lite-net/blob/master/src/Couchbase.Lite.Shared/Replication.cs#L1994
https://github.com/couchbase/couchbase-lite-net/blob/master/src/Couchbase.Lite.Shared/Manager/NetworkReachabilityManager.cs#L48

**Comment by zgramana** [comment]
@hideki you should also reference these other locations where `CanReach` is called:

When [initializing the state machine](https://github.com/couchbase/couchbase-lite-net/blob/941681077283ba33f1d78530c6e7e90562db23a3/src/Couchbase.Lite.Shared/Replication.cs#L1994-L1995):
```csharp
   _stateMachine.Configure(ReplicationState.Offline).PermitIf(ReplicationTrigger.GoOnline, ReplicationState.Running, 
      () => LocalDatabase.Manager.NetworkReachabilityManager.CanReach(RemoteUrl.AbsoluteUri));
```
and in [`StartInternal`](https://github.com/couchbase/couchbase-lite-net/blob/941681077283ba33f1d78530c6e7e90562db23a3/src/Couchbase.Lite.Shared/Replication.cs#L971):
```sharp
if (!LocalDatabase.Manager.NetworkReachabilityManager.CanReach(RemoteUrl.AbsoluteUri)) {
    LastError = LocalDatabase.Manager.NetworkReachabilityManager.LastError;
    FireTrigger(ReplicationTrigger.GoOffline);
}
```

**Comment by hideki** [comment]
Note from comparison with iOS
- goOnline -> should not start beginTransaction right away. It starts ChangeTracker before local checkpoint.
- Replicator is stopped state, should stop reachability too.
