### ISSUE TITLE
Custom property with the name 'type' results in an exception

### ISSUE THREAD

**Issue by thies-at-work** [couchbase/couchbase-lite-java-core#1041]
An exception occurred when I try to put a property with the name 'type' with the Couchbase Android 1.2.0 release.

java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
at com.couchbase.lite.store.SQLiteStore.add(SQLiteStore.java:1448)
at com.couchbase.lite.Database.put(Database.java:1748)
at com.couchbase.lite.Database.putRevision(Database.java:1701)
at com.couchbase.lite.Database.putRevision(Database.java:1692)
at com.couchbase.lite.Document.putProperties(Document.java:428)
at com.couchbase.lite.Document.putProperties(Document.java:260)

in SQLiteStore.java:1448 'type' is used without an underscore character as a prefix.

To reproduce just run the follow testcase
https://gist.github.com/thies-at-work/e922a3abb00fea5c831c

**Comment by hideki** [comment]
Hi @thies-at-work ,

Thank you for your bug report. We already fixed this issue. If you can use the build from master branch, please try 0.0.0-581 which is built from master branch.

Couchbase custom maven repo:
http://files.couchbase.com/maven2/com/couchbase/lite/couchbase-lite-android/0.0.0-581/

Zipped download:
http://latestbuilds.hq.couchbase.com/couchbase-lite-android/0.0.0/0.0.0-581/

NOTE: Duplicated with https://github.com/couchbase/couchbase-lite-android/issues/783

Thanks you!
