### ISSUE TITLE
Listener exception in remote database of a replication

### ISSUE THREAD

**Issue by jamiltz** [couchbase/couchbase-lite-java-core#1043]
This exception is thrown in the logs of the remote database running the listener.

```
W/Router: IOException writing to internal streams
         java.io.IOException: Can't write to closed stream.
             at com.couchbase.lite.router.BufferOutputStream.write(BufferOutputStream.java:19)
             at java.io.OutputStream.write(OutputStream.java:106)
             at java.io.OutputStream.write(OutputStream.java:82)
             at com.couchbase.lite.router.Router.changed(Router.java:1522)
             at com.couchbase.lite.Database.postChangeNotifications(Database.java:2267)
             at com.couchbase.lite.Database.storageExitedTransaction(Database.java:703)
             at com.couchbase.lite.store.SQLiteStore.endTransaction(SQLiteStore.java:2146)
             at com.couchbase.lite.store.SQLiteStore.runInTransaction(SQLiteStore.java:680)
             at com.couchbase.lite.router.Router.do_POST_Document_bulk_docs(Router.java:1179)
             at java.lang.reflect.Method.invoke(Native Method)
             at java.lang.reflect.Method.invoke(Method.java:372)
             at com.couchbase.lite.router.Router.start(Router.java:490)
             at com.couchbase.lite.listener.LiteServlet.service(LiteServlet.java:127)
             at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)
             at Acme.Serve.Serve$ServeConnection.runServlet(Serve.java:2251)
             at Acme.Serve.Serve$ServeConnection.parseRequest(Serve.java:2176)
             at Acme.Serve.Serve$ServeConnection.run(Serve.java:1988)
             at Acme.Utils$ThreadPool$PooledThread.run(Utils.java:1223)
             at java.lang.Thread.run(Thread.java:818)
```

**Comment by jamiltz** [comment]
Approximately 4000 docs were pushed.

**Comment by hideki** [comment]
##### Test condition:
- `/db/_changes?feed=longpoll&since=5000`
- /db`/_bulk_docs` with 8000 docs

##### Response from `/db/_changes?feed=longpoll&since=5000`
```
{"results":[
{"id":"0a4e2610-a3de-4c7c-810a-6432d0a2e555","seq":5001,"changes":[{"rev":"1-c32c4ecfef150863b2507a46406c4347"}]},
...
...
{"id":"f0e547c6-898b-4f5a-82d0-61dedfe177e0","seq":13000,"changes":[{"rev":"1-c32c4ecfef150863b2507a46406c4347"}]}
],
"last_seq":13000}
```

##### NOTE
- it seems single thread `/_bulk_docs` does not cause this error

**Comment by hideki** [comment]
It is hard to reproduce this here internally. It seems following things happened.

1. Calling `/db/_changes?feed=longpoll&since=xxx`. This thread is waiting `Database.ChangeEvent`
1. Calling multiple requests of `/db/_bulk_docs`. Number of documents in this request is not matter.
1. Multiple `Database.ChangeEvent`s are fired because of multiple `/_bulk_docs` requests.
1. Second  `Database.ChangeEvent` is fired before connection closed. It causes "java.io.IOException: Can't write to closed stream."

Needs to verify:
- which thread calls `Database.ChangeEvent`
- which timing connection is closed.

**Comment by hideki** [comment]
Note to self:
- `Database.ChangeEvent` is fired by Servlet Thread that handles `_bulk_docs` request 
```
Router: changed(Database.ChangeEvent) thread=Acme.Utils.ThreadPool(1)-PooledThread: Acme.Serve.Serve$ServeConnection@5294c788
```
