### ISSUE TITLE
CBL 1.1: _changes when pull replication is continuous mode  and Exception in change tracker java.net.SocketTimeoutException: Read timed out.

### ISSUE THREAD

**Issue by NitzDKoder** [couchbase/couchbase-lite-java-core#1081]
Hi folks,
 1)Have pull replication in continuous mode and no data is pulled as there is no change in data.
 2)Does the _changes will be sent every 5 mins or old connection will be kept indefinitely?
3)If so below logs had "Exception in change tracker java.net.SocketTimeoutException: Read timed out." and _changes not sent every 5 mins.
```
"[**03/03 12:27:30.322**] [9] ChangeTracker: com.couchbase.lite.replicator.ChangeTracker@34033b73: readValue
[**03/03 12:47:30.424**] [9] ChangeTracker: com.couchbase.lite.replicator.ChangeTracker@34033b73: Exception in change tracker"
```
4)is it proper behaviour to get exception and then do _changes?

```
03/03 12:12:28.519] [9] ChangeTracker: com.couchbase.lite.replicator.ChangeTracker@34033b73: Exception in change tracker
java.net.SocketTimeoutException: Read timed out
	at com.android.org.conscrypt.NativeCrypto.SSL_read(Native Method)
	at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:805)
	at org.apache.http.impl.io.AbstractSessionInputBuffer.fillBuffer(AbstractSessionInputBuffer.java:108)
	at org.apache.http.impl.io.AbstractSessionInputBuffer.readLine(AbstractSessionInputBuffer.java:196)
	at org.apache.http.impl.io.ChunkedInputStream.getChunkSize(ChunkedInputStream.java:225)
	at org.apache.http.impl.io.ChunkedInputStream.nextChunk(ChunkedInputStream.java:188)
	at org.apache.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:160)
	at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:164)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.loadMore(UTF8StreamJsonParser.java:180)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._skipWSOrEnd2(UTF8StreamJsonParser.java:2777)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._skipWSOrEnd(UTF8StreamJsonParser.java:2772)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:652)
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.deserialize(UntypedObjectDeserializer.java:443)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringMap(MapDeserializer.java:473)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:330)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:25)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3560)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2646)
	at com.couchbase.lite.replicator.ChangeTracker.runLoop(ChangeTracker.java:349)
	at com.couchbase.lite.replicator.ChangeTracker.run(ChangeTracker.java:224)
	at java.lang.Thread.run(Thread.java:818)

[03/03 12:12:28.529] [9] ChangeTracker: com.couchbase.lite.replicator.ChangeTracker@34033b73: Making request to https://---:---@43.225.119.183:443/pttdata/_changes?feed=longpoll&limit=50&heartbeat=300000&style=all_docs&since=6180416&filter=sync_gateway%2Fbychannel&channels=*
[03/03 12:12:28.684] [9] Sync: Saving cookie: TS0197cde443.225.119.183 w/ encoded value: ACED00057372002D636F6D2E636F756368626173652E6C6974652E737570706F72742E53657269616C697A61626C65436F6F6B696558765A8013AEB70C030000787074000A5453303139376364653474004A30313639346261323030313232363161656235646130303534376337643465613736306636393930316266356666343361353331376431383665346662396539353934396162626639337074000E34332E3232352E3131392E313833707400012F7705000000000078
[03/03 12:12:28.695] [9] ChangeTracker: com.couchbase.lite.replicator.ChangeTracker@34033b73: got response. status: HTTP/1.1 200 OK mode: LongPoll
[03/03 12:12:28.697] [9] ChangeTracker: com.couchbase.lite.replicator.ChangeTracker@34033b73: /entity.getContent().  mode: LongPoll
[03/03 12:12:28.699] [9] ChangeTracker: com.couchbase.lite.replicator.ChangeTracker@34033b73: readValue
[03/03 12:17:28.818] [9] ChangeTracker: com.couchbase.lite.replicator.ChangeTracker@34033b73: Exception in change tracker
java.net.SocketTimeoutException: Read timed out
	at com.android.org.conscrypt.NativeCrypto.SSL_read(Native Method)
	at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:805)
	at org.apache.http.impl.io.AbstractSessionInputBuffer.fillBuffer(AbstractSessionInputBuffer.java:108)
	at org.apache.http.impl.io.AbstractSessionInputBuffer.readLine(AbstractSessionInputBuffer.java:196)
	at org.apache.http.impl.io.ChunkedInputStream.getChunkSize(ChunkedInputStream.java:225)
	at org.apache.http.impl.io.ChunkedInputStream.nextChunk(ChunkedInputStream.java:188)
	at org.apache.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:160)
	at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:164)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.loadMore(UTF8StreamJsonParser.java:180)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._skipWSOrEnd2(UTF8StreamJsonParser.java:2777)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._skipWSOrEnd(UTF8StreamJsonParser.java:2772)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:652)
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.deserialize(UntypedObjectDeserializer.java:443)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringMap(MapDeserializer.java:473)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:330)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:25)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3560)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2646)
	at com.couchbase.lite.replicator.ChangeTracker.runLoop(ChangeTracker.java:349)
	at com.couchbase.lite.replicator.ChangeTracker.run(ChangeTracker.java:224)
	at java.lang.Thread.run(Thread.java:818)

[03/03 12:17:28.849] [9] ChangeTracker: com.couchbase.lite.replicator.ChangeTracker@34033b73: Making request to https://---:---@43.225.119.183:443/pttdata/_changes?feed=longpoll&limit=50&heartbeat=300000&style=all_docs&since=6180416&filter=sync_gateway%2Fbychannel&channels=*
[03/03 12:17:28.908] [9] ChangeTracker: com.couchbase.lite.replicator.ChangeTracker@34033b73: got response. status: HTTP/1.1 200 OK mode: LongPoll
[03/03 12:17:28.909] [9] ChangeTracker: com.couchbase.lite.replicator.ChangeTracker@34033b73: /entity.getContent().  mode: LongPoll
[03/03 12:17:28.910] [9] ChangeTracker: com.couchbase.lite.replicator.ChangeTracker@34033b73: readValue
[03/03 12:22:29.025] [9] ChangeTracker: com.couchbase.lite.replicator.ChangeTracker@34033b73: Exception in change tracker
java.net.SocketTimeoutException: Read timed out
	at com.android.org.conscrypt.NativeCrypto.SSL_read(Native Method)
	at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:805)
	at org.apache.http.impl.io.AbstractSessionInputBuffer.fillBuffer(AbstractSessionInputBuffer.java:108)
	at org.apache.http.impl.io.AbstractSessionInputBuffer.readLine(AbstractSessionInputBuffer.java:196)
	at org.apache.http.impl.io.ChunkedInputStream.getChunkSize(ChunkedInputStream.java:225)
	at org.apache.http.impl.io.ChunkedInputStream.nextChunk(ChunkedInputStream.java:188)
	at org.apache.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:160)
	at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:164)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.loadMore(UTF8StreamJsonParser.java:180)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._skipWSOrEnd2(UTF8StreamJsonParser.java:2777)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._skipWSOrEnd(UTF8StreamJsonParser.java:2772)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:652)
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.deserialize(UntypedObjectDeserializer.java:443)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringMap(MapDeserializer.java:473)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:330)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:25)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3560)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2646)
	at com.couchbase.lite.replicator.ChangeTracker.runLoop(ChangeTracker.java:349)
	at com.couchbase.lite.replicator.ChangeTracker.run(ChangeTracker.java:224)
	at java.lang.Thread.run(Thread.java:818)

[03/03 12:22:29.038] [9] ChangeTracker: com.couchbase.lite.replicator.ChangeTrackerBackoff@14e1609f: sleeping for 100
[03/03 12:22:29.143] [9] ChangeTracker: com.couchbase.lite.replicator.ChangeTracker@34033b73: Making request to https://---:---@43.225.119.183:443/pttdata/_changes?feed=longpoll&limit=50&heartbeat=300000&style=all_docs&since=6180416&filter=sync_gateway%2Fbychannel&channels=*
[03/03 12:22:29.560] [9] Sync: Saving cookie: TS0197cde443.225.119.183 w/ encoded value: ACED00057372002D636F6D2E636F756368626173652E6C6974652E737570706F72742E53657269616C697A61626C65436F6F6B696558765A8013AEB70C030000787074000A5453303139376364653474004A30313639346261323030643963306135356363653232663738646261616133663264613562363136303333323434306132613039363239393339336134373162666532393264626138377074000E34332E3232352E3131392E313833707400012F7705000000000078
[03/03 12:22:29.578] [9] ChangeTracker: com.couchbase.lite.replicator.ChangeTracker@34033b73: got response. status: HTTP/1.1 200 OK mode: LongPoll
[03/03 12:22:29.580] [9] ChangeTracker: com.couchbase.lite.replicator.ChangeTracker@34033b73: /entity.getContent().  mode: LongPoll
[03/03 12:22:29.582] [9] ChangeTracker: com.couchbase.lite.replicator.ChangeTracker@34033b73: readValue
[03/03 12:27:29.706] [9] ChangeTracker: com.couchbase.lite.replicator.ChangeTracker@34033b73: Exception in change tracker
java.net.SocketTimeoutException: Read timed out
	at com.android.org.conscrypt.NativeCrypto.SSL_read(Native Method)
	at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:805)
	at org.apache.http.impl.io.AbstractSessionInputBuffer.fillBuffer(AbstractSessionInputBuffer.java:108)
	at org.apache.http.impl.io.AbstractSessionInputBuffer.readLine(AbstractSessionInputBuffer.java:196)
	at org.apache.http.impl.io.ChunkedInputStream.getChunkSize(ChunkedInputStream.java:225)
	at org.apache.http.impl.io.ChunkedInputStream.nextChunk(ChunkedInputStream.java:188)
	at org.apache.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:160)
	at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:164)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.loadMore(UTF8StreamJsonParser.java:180)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._skipWSOrEnd2(UTF8StreamJsonParser.java:2777)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._skipWSOrEnd(UTF8StreamJsonParser.java:2772)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:652)
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.deserialize(UntypedObjectDeserializer.java:443)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringMap(MapDeserializer.java:473)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:330)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:25)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3560)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2646)
	at com.couchbase.lite.replicator.ChangeTracker.runLoop(ChangeTracker.java:349)
	at com.couchbase.lite.replicator.ChangeTracker.run(ChangeTracker.java:224)
	at java.lang.Thread.run(Thread.java:818)

[03/03 12:27:29.709] [9] ChangeTracker: com.couchbase.lite.replicator.ChangeTrackerBackoff@14e1609f: sleeping for 400
[03/03 12:27:30.118] [9] ChangeTracker: com.couchbase.lite.replicator.ChangeTracker@34033b73: Making request to https://---:---@43.225.119.183:443/pttdata/_changes?feed=longpoll&limit=50&heartbeat=300000&style=all_docs&since=6180416&filter=sync_gateway%2Fbychannel&channels=*
[03/03 12:27:30.296] [9] Sync: Saving cookie: TS0197cde443.225.119.183 w/ encoded value: ACED00057372002D636F6D2E636F756368626173652E6C6974652E737570706F72742E53657269616C697A61626C65436F6F6B696558765A8013AEB70C030000787074000A5453303139376364653474004A30313639346261323030386530663630356638396364346334336364383139393635316561363536333732663962393634626664316333303332343036663637643335633363653033397074000E34332E3232352E3131392E313833707400012F7705000000000078
[03/03 12:27:30.318] [9] ChangeTracker: com.couchbase.lite.replicator.ChangeTracker@34033b73: got response. status: HTTP/1.1 200 OK mode: LongPoll
[03/03 12:27:30.320] [9] ChangeTracker: com.couchbase.lite.replicator.ChangeTracker@34033b73: /entity.getContent().  mode: LongPoll
[03/03 12:27:30.322] [9] ChangeTracker: com.couchbase.lite.replicator.ChangeTracker@34033b73: readValue
[03/03 12:47:30.424] [9] ChangeTracker: com.couchbase.lite.replicator.ChangeTracker@34033b73: Exception in change tracker
java.net.SocketTimeoutException: Read timed out
	at com.android.org.conscrypt.NativeCrypto.SSL_read(Native Method)
	at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:805)
	at org.apache.http.impl.io.AbstractSessionInputBuffer.fillBuffer(AbstractSessionInputBuffer.java:108)
	at org.apache.http.impl.io.AbstractSessionInputBuffer.readLine(AbstractSessionInputBuffer.java:196)
	at org.apache.http.impl.io.ChunkedInputStream.getChunkSize(ChunkedInputStream.java:225)
	at org.apache.http.impl.io.ChunkedInputStream.nextChunk(ChunkedInputStream.java:188)
	at org.apache.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:160)
	at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:164)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.loadMore(UTF8StreamJsonParser.java:180)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._skipWSOrEnd2(UTF8StreamJsonParser.java:2777)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._skipWSOrEnd(UTF8StreamJsonParser.java:2772)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:652)
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.deserialize(UntypedObjectDeserializer.java:443)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringMap(MapDeserializer.java:473)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:330)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:25)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3560)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2646)
	at com.couchbase.lite.replicator.ChangeTracker.runLoop(ChangeTracker.java:349)
	at com.couchbase.lite.replicator.ChangeTracker.run(ChangeTracker.java:224)
	at java.lang.Thread.run(Thread.java:818)

[03/03 12:47:30.435] [9] ChangeTracker: com.couchbase.lite.replicator.ChangeTrackerBackoff@14e1609f: sleeping for 700
[03/03 12:47:31.138] [9] ChangeTracker: com.couchbase.lite.replicator.ChangeTracker@34033b73: Making request to https://---:---@43.225.119.183:443/pttdata/_changes?feed=longpoll&limit=50&heartbeat=300000&style=all_docs&since=6180416&filter=sync_gateway%2Fbychannel&channels=*
[03/03 12:47:31.928] [9] Sync: Saving cookie: TS0197cde443.225.119.183 w/ encoded value: ACED00057372002D636F6D2E636F756368626173652E6C6974652E737570706F72742E53657269616C697A61626C65436F6F6B696558765A8013AEB70C030000787074000A5453303139376364653474004A30313639346261323030353065653364333866313365393432313933393437323131656162373439393331333034646561633037333765386533663830633365653734333163313561357074000E34332E3232352E3131392E313833707400012F7705000000000078
[03/03 12:47:31.950] [9] ChangeTracker: com.couchbase.lite.replicator.ChangeTracker@34033b73: got response. status: HTTP/1.1 200 OK mode: LongPoll
[03/03 12:47:31.952] [9] ChangeTracker: com.couchbase.lite.replicator.ChangeTracker@34033b73: /entity.getContent().  mode: LongPoll
[03/03 12:47:31.953] [9] ChangeTracker: com.couchbase.lite.replicator.ChangeTracker@34033b73: readValue


```

Thanks
Nithin

**Comment by NitzDKoder** [comment]
@hideki Device was in idle state in this above case.

Note that when device is idle the java timer wont schedule as intended.Any measure taken?

**Comment by hideki** [comment]
Hi @NitzDKoder 
What do you use for server side? Sync Gateway? or CouchDB?

**Comment by NitzDKoder** [comment]
@hideki Sync Gateway..

**Comment by NitzDKoder** [comment]
@hideki we have f5 in the middle before reaching Sync Gateway..
https://f5.com/solutions/enterprise/application-delivery
also pls see..
https://forums.couchbase.com/t/more-info-on-how-replication-setcontinuous-continuous-vs-oneshot/7183/3

**Comment by hideki** [comment]
Hi @NitzDKoder,

Is f5 a proxy server? If so, I guess f5 might close connection with replicator, it might close connection to Sync Gateway too. Do you know connection timeout setting of this proxy?

ChangeTracker initially sends /_changes with heartbeat=300000 (5min) to sync gateway. If proxy closes connection before 5 min, SocketTimeoutException is expected behavior.

If you can know proxy server time out, please try to use following build that was built master branch with calling `Replication.DEFAULT_HEARTBEAT = <second>;` before replicator starts?
This value should be smaller than proxy timeout.
http://files.couchbase.com/maven2/com/couchbase/lite/couchbase-lite-android/0.0.0-605/

I hope this helps you.

**Comment by zgramana** [comment]
@NitzDKoder upgrading to 1.2 will fix this problem.
