### ISSUE TITLE
Android API 10: java.lang.UnsatisfiedLinkError: nativeOpen

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-java-core#1090]
Android API 10

```
java.lang.UnsatisfiedLinkError: nativeOpen
at com.couchbase.lite.internal.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
at com.couchbase.lite.internal.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:194)
at com.couchbase.lite.internal.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:178)
at com.couchbase.lite.internal.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:461)
at com.couchbase.lite.internal.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:191)
at com.couchbase.lite.internal.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:183)
at com.couchbase.lite.internal.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:814)
at com.couchbase.lite.internal.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:798)
at com.couchbase.lite.internal.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:693)
at com.couchbase.lite.storage.SQLiteStorageEngineBase.open(SQLiteStorageEngineBase.java:62)
at com.couchbase.lite.store.SQLiteStore.open(SQLiteStore.java:183)
at com.couchbase.lite.Database.open(Database.java:1143)
at com.couchbase.lite.Manager.openDatabase(Manager.java:336)
at com.couchbase.lite.Manager.getDatabase(Manager.java:300)
at com.couchbase.lite.LiteTestCaseWithDB.ensureEmptyDatabase(LiteTestCaseWithDB.java:245)
at com.couchbase.lite.LiteTestCaseWithDB.startDatabase(LiteTestCaseWithDB.java:230)
at com.couchbase.lite.LiteTestCaseWithDB.setUp(LiteTestCaseWithDB.java:132)
at com.couchbase.lite.LiteTestCase.runBare(LiteTestCase.java:20)
at com.couchbase.lite.LiteTestCaseWithDB.runBare(LiteTestCaseWithDB.java:88)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:169)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:154)
at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:529)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1448)
```

#####  **sqlite3_stmt_readonly** is not supported by SQLite version which is bundled with Android API 10
- https://www.sqlite.org/c3ref/stmt_readonly.html
- Android API 10 bundles SQLite 3.6.22
- sqlite3_stmt_readonly is supported since SQLite v3.7.5

```
03-07 17:49:59.094 1134-1142/? E/Database: Unknown load() error : cbljavasqlitedefault
 java.lang.UnsatisfiedLinkError: Cannot load library: reloc_library[1311]:    33 cannot locate 'sqlite3_stmt_readonly'...
03-07 17:49:59.094 1134-1142/? E/Database: Cannot load native library
```

##### Alternative Solution:
- Please use Custom SQLite - https://bintray.com/couchbase/couchbase/couchbase-lite-android-sqlite-custom/view

**Comment by zgramana** [comment]
Anyone needing to support API 10 can do so using the Custom SQLite that we provide, as @hideki notes above.
