### ISSUE TITLE
Replication doesn't start when peer are rediscovered

### ISSUE THREAD

**Issue by ashvindersingh** [couchbase/couchbase-lite-java-core#1096]
Found on Android 6.0.1, API -23
Steps to reproduce:
- Create a hotspot wifi on your mac. 
- From the android slave and master device connect to the hotspot wifi. 
- Install F_and_B sharing app: https://github.com/jamiltz/P2PSync-Android/tree/master/F_and_B_Training
- Login into one device as Cabin and other as Galley
- Ensure the cabin device shows 'green' in the top bar as status
- Add some docs on the cabin 
- Disconnect and the network and reconnect the galley device. 

Expecting docs to be replicated to galley device
Observed: only one doc got replicated to the galley device and replication stops and does not resume after that. 

Master device logs: https://gist.github.com/f3d13047136b5ca613a8
Slave device logs: https://gist.github.com/ea5cda6da0936a25da1a

Also found exception on the master device:
```
03-10 12:13:13.153 11740-20956/com.emirates.skybook E/RemoteRequest: io exception.  url: http://192.168.2.2:5984/ek0073/_revs_diff
                                                                     java.net.SocketTimeoutException
                                                                         at java.net.PlainSocketImpl.read(PlainSocketImpl.java:484)
                                                                         at java.net.PlainSocketImpl.-wrap0(PlainSocketImpl.java)
                                                                         at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)
                                                                         at org.apache.http.impl.io.AbstractSessionInputBuffer.fillBuffer(AbstractSessionInputBuffer.java:108)
                                                                         at org.apache.http.impl.io.AbstractSessionInputBuffer.readLine(AbstractSessionInputBuffer.java:196)
                                                                         at org.apache.http.impl.conn.DefaultResponseParser.parseHead(DefaultResponseParser.java:88)
                                                                         at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:179)
                                                                         at org.apache.http.impl.AbstractHttpClientConnection.receiveResponseHeader(AbstractHttpClientConnection.java:185)
                                                                         at org.apache.http.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:240)
                                                                         at org.apache.http.impl.conn.AbstractClientConnAdapter.receiveResponseHeader(AbstractClientConnAdapter.java:264)
                                                                         at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:284)
                                                                         at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:126)
                                                                         at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:440)
                                                                         at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:560)
                                                                         at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:492)
                                                                         at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:470)
                                                                         at com.couchbase.lite.support.RemoteRequest.executeRequest(RemoteRequest.java:181)
                                                                         at com.couchbase.lite.support.RemoteRequest.run(RemoteRequest.java:101)
                                                                         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                         at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                         at java.lang.Thread.run(Thread.java:818)

```

Exception on the slave:

```
03-10 12:13:59.103 12968-25334/com.emirates.skybook E/Database: java.lang.RuntimeException: com.couchbase.lite.CouchbaseLiteException, Status: 409 (HTTP 409 conflict)
                                                                java.lang.RuntimeException: com.couchbase.lite.CouchbaseLiteException, Status: 409 (HTTP 409 conflict)
                                                                    at com.couchbase.lite.router.Router$8.run(Router.java:1973)
                                                                    at com.couchbase.lite.store.SQLiteStore.runInTransaction(SQLiteStore.java:684)
                                                                    at com.couchbase.lite.router.Router.update(Router.java:1965)
                                                                    at com.couchbase.lite.router.Router.update(Router.java:2037)
                                                                    at com.couchbase.lite.router.Router.do_PUT_Document(Router.java:2072)
                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                    at com.couchbase.lite.router.Router.start(Router.java:503)
                                                                    at com.couchbase.lite.listener.LiteServlet.service(LiteServlet.java:127)
                                                                    at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)
                                                                    at Acme.Serve.Serve$ServeConnection.runServlet(Serve.java:2251)
                                                                    at Acme.Serve.Serve$ServeConnection.parseRequest(Serve.java:2176)
                                                                    at Acme.Serve.Serve$ServeConnection.run(Serve.java:1988)
                                                                    at Acme.Utils$ThreadPool$PooledThread.run(Utils.java:1223)
                                                                    at java.lang.Thread.run(Thread.java:818)
                                                                 Caused by: com.couchbase.lite.CouchbaseLiteException, Status: 409 (HTTP 409 conflict)
                                                                    at com.couchbase.lite.store.SQLiteStore.putLocalRevision(SQLiteStore.java:1912)
                                                                    at com.couchbase.lite.router.Router$8.run(Router.java:1969)
                                                                    at com.couchbase.lite.store.SQLiteStore.runInTransaction(SQLiteStore.java:684) 
                                                                    at com.couchbase.lite.router.Router.update(Router.java:1965) 
                                                                    at com.couchbase.lite.router.Router.update(Router.java:2037) 
                                                                    at com.couchbase.lite.router.Router.do_PUT_Document(Router.java:2072) 
                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                    at com.couchbase.lite.router.Router.start(Router.java:503) 
                                                                    at com.couchbase.lite.listener.LiteServlet.service(LiteServlet.java:127) 
                                                                    at javax.servlet.http.HttpServlet.service(HttpServlet.java:802) 
                                                                    at Acme.Serve.Serve$ServeConnection.runServlet(Serve.java:2251) 
                                                                    at Acme.Serve.Serve$ServeConnection.parseRequest(Serve.java:2176) 
                                                                    at Acme.Serve.Serve$ServeConnection.run(Serve.java:1988) 
                                                                    at Acme.Utils$ThreadPool$PooledThread.run(Utils.java:1223) 
                                                                    at java.lang.Thread.run(Thread.java:818) 

```

**Comment by hideki** [comment]
Notes:

We confirmed this issue is reproducible with using OS X's `Internet Sharing` (hotspot) feature. However this is not reproducible with couchbase-mobile wifi (Apple router).

IP address discovery works fine. But, after IP was discovered, Replicator (master) can not connect to Listener (slave). Listener is not accessible even from web browser. Currently we are not sure where problems are. Router? Application code? or Couchbase Lite codes?

**Comment by ashvindersingh** [comment]
Confirmed fixed with build: 616, android-marshmallow, nexus5 and nexus6(as galley). Was able to to replicated the docs less than 5 seconds.
