### ISSUE TITLE
Thread stuck in `RemoteRequestRetry.get`

### ISSUE THREAD

**Issue by zgramana** [couchbase/couchbase-lite-java-core#1114]

**Comment by zgramana** [comment]
#### Puller
```
  at java.lang.Thread.parkFor$(Thread.java:1220)	
  at sun.misc.Unsafe.park(Unsafe.java:299)	
  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:158)	
  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2013)	
  at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)	
  at com.couchbase.lite.support.RemoteRequestRetry.get(RemoteRequestRetry.java:339)	
  at com.couchbase.lite.replicator.ReplicationInternal.waitPendingFuturesCompleted(ReplicationInternal.java:1802)	
  at com.couchbase.lite.replicator.PullerInternal.waitForAllTasksCompleted(PullerInternal.java:1009)	
  at com.couchbase.lite.replicator.ReplicationInternal.waitForPendingFutures(ReplicationInternal.java:1752)	
  at com.couchbase.lite.replicator.PullerInternal$14.run(PullerInternal.java:918)	
  at java.lang.Thread.run(Thread.java:818)	
```
#### Pusher
```
  at java.lang.Object.wait(Native Method)	
  at java.lang.Thread.parkFor$(Thread.java:1220)	
  at sun.misc.Unsafe.park(Unsafe.java:299)	
  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:158)	
  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2013)	
  at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)	
  at com.couchbase.lite.support.RemoteRequestRetry.get(RemoteRequestRetry.java:339)	
  at com.couchbase.lite.replicator.ReplicationInternal.waitPendingFuturesCompleted(ReplicationInternal.java:1802)	
  at com.couchbase.lite.replicator.ReplicationInternal.waitForAllTasksCompleted(ReplicationInternal.java:1781)	
  at com.couchbase.lite.replicator.ReplicationInternal.waitForPendingFutures(ReplicationInternal.java:1752)	
  at com.couchbase.lite.replicator.ReplicationInternal$24.run(ReplicationInternal.java:1713)	
  at java.lang.Thread.run(Thread.java:818)	
```
