### ISSUE TITLE
UnitTest, ReplicatoinTest.testStartReplicationClosedDb(), fails with recent commit.

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-java-core#1131]
Recent commit:
https://github.com/couchbase/couchbase-lite-java-core/commit/4cc2f7d66a9be58ca774d102497b7a725885e168

Test failure on Jenkins:
http://mobile.jenkins.couchbase.com/job/couchbase-lite-android-build/631/

Actual test code:
```
    public void testStartReplicationClosedDb() throws Exception {

        Database db = this.manager.getDatabase("closed");
        final CountDownLatch countDownLatch = new CountDownLatch(1);
        final Replication replication = db.createPullReplication(new URL("http://fake.com/foo"));
        replication.setContinuous(true);
        replication.addChangeListener(new Replication.ChangeListener() {
            @Override
            public void changed(Replication.ChangeEvent event) {
                Log.d(TAG, "changed event: %s", event);
                if (replication.isRunning() == false) {
                    countDownLatch.countDown();
                }
            }
        });

        db.close();
        replication.start();

        boolean success = countDownLatch.await(60, TimeUnit.SECONDS);
        assertTrue(success);

        assertTrue(replication.getLastError() != null);
    }
```

stacktrace:
```
junit.framework.AssertionFailedError
at com.couchbase.lite.replicator.ReplicationTest.testStartReplicationClosedDb(ReplicationTest.java:263)
at java.lang.reflect.Method.invokeNative(Native Method)
at com.couchbase.lite.LiteTestCase.runBare(LiteTestCase.java:20)
at com.couchbase.lite.LiteTestCaseWithDB.runBare(LiteTestCaseWithDB.java:88)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:191)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:176)
at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:554)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1701)
```

**Comment by hideki** [comment]
```
03-20 04:23:15.183 1266-1279/com.couchbase.lite.test D/Sync: Unable to format log: %s [fireTrigger()] => START
                                                             java.lang.NullPointerException
                                                                 at com.couchbase.lite.Database.privateUUID(Database.java:1326)
                                                                 at com.couchbase.lite.replicator.ReplicationInternal.remoteCheckpointDocID(ReplicationInternal.java:929)
                                                                 at com.couchbase.lite.replicator.PullerInternal.remoteCheckpointDocID(PullerInternal.java:48)
                                                                 at com.couchbase.lite.replicator.PullerInternal.toString(PullerInternal.java:1055)
                                                                 at java.util.Formatter.transform(Formatter.java:1421)
                                                                 at java.util.Formatter.doFormat(Formatter.java:1081)
                                                                 at java.util.Formatter.format(Formatter.java:1042)
                                                                 at java.util.Formatter.format(Formatter.java:1011)
                                                                 at java.lang.String.format(String.java:1999)
                                                                 at java.lang.String.format(String.java:1973)
                                                                 at com.couchbase.lite.util.Log.d(Log.java:202)
                                                                 at com.couchbase.lite.replicator.ReplicationInternal.fireTrigger(ReplicationInternal.java:204)
                                                                 at com.couchbase.lite.replicator.ReplicationInternal.triggerStart(ReplicationInternal.java:176)
                                                                 at com.couchbase.lite.replicator.PullerInternal.triggerStart(PullerInternal.java:48)
                                                                 at com.couchbase.lite.replicator.Replication.start(Replication.java:235)
                                                                 at com.couchbase.lite.replicator.ReplicationTest.testStartReplicationClosedDb(ReplicationTest.java:260)
                                                                 at java.lang.reflect.Method.invokeNative(Native Method)
                                                                 at java.lang.reflect.Method.invoke(Method.java:515)
                                                                 at junit.framework.TestCase.runTest(TestCase.java:168)
                                                                 at junit.framework.TestCase.runBare(TestCase.java:134)
                                                                 at com.couchbase.lite.LiteTestCase.runBare(LiteTestCase.java:20)
                                                                 at com.couchbase.lite.LiteTestCaseWithDB.runBare(LiteTestCaseWithDB.java:88)
                                                                 at junit.framework.TestResult$1.protect(TestResult.java:115)
                                                                 at junit.framework.TestResult.runProtected(TestResult.java:133)
                                                                 at junit.framework.TestResult.run(TestResult.java:118)
                                                                 at junit.framework.TestCase.run(TestCase.java:124)
                                                                 at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:191)
                                                                 at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:176)
                                                                 at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:554)
                                                                 at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1701)
03-20 04:23:15.193 1266-1280/com.couchbase.lite.test D/Sync: firing trigger: START
03-20 04:23:15.203 1266-1280/com.couchbase.lite.test E/Sync: Unknown Error in stateMachine.fire(trigger)
                                                             java.lang.NullPointerException
                                                                 at com.couchbase.lite.Database.privateUUID(Database.java:1326)
                                                                 at com.couchbase.lite.replicator.ReplicationInternal.remoteCheckpointDocID(ReplicationInternal.java:929)
                                                                 at com.couchbase.lite.replicator.PullerInternal.remoteCheckpointDocID(PullerInternal.java:48)
                                                                 at com.couchbase.lite.replicator.PullerInternal.toString(PullerInternal.java:1055)
                                                                 at com.couchbase.lite.replicator.ReplicationInternal$13.doIt(ReplicationInternal.java:1232)
                                                                 at com.couchbase.lite.replicator.ReplicationInternal$13.doIt(ReplicationInternal.java:1229)
                                                                 at com.github.oxo42.stateless4j.StateConfiguration$3.doIt(StateConfiguration.java:135)
                                                                 at com.github.oxo42.stateless4j.StateConfiguration$3.doIt(StateConfiguration.java:133)
                                                                 at com.github.oxo42.stateless4j.StateRepresentation.executeEntryActions(StateRepresentation.java:118)
                                                                 at com.github.oxo42.stateless4j.StateRepresentation.enter(StateRepresentation.java:97)
                                                                 at com.github.oxo42.stateless4j.StateMachine.publicFire(StateMachine.java:199)
                                                                 at com.github.oxo42.stateless4j.StateMachine.fire(StateMachine.java:126)
                                                                 at com.couchbase.lite.replicator.ReplicationInternal$1.run(ReplicationInternal.java:213)
                                                                 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                 at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
                                                                 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                 at java.lang.Thread.run(Thread.java:841)
```
