### ISSUE TITLE
Thread-waitForPendingFutures is leaking

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-java-core#1141]
Currently there is no replicator running but `Thread-waitForPendingFutures` still exists.

```
"Acme.Utils.ThreadPool(0)-PooledThread: Acme.Serve.Serve$ServeConnection@38a39ab@5446" daemon prio=5 runnable
  java.lang.Thread.State: RUNNABLE
	  at libcore.io.Posix.recvfromBytes(Posix.java:-1)
	  at libcore.io.Posix.recvfrom(Posix.java:189)
	  at libcore.io.BlockGuardOs.recvfrom(BlockGuardOs.java:250)
	  at libcore.io.IoBridge.recvfrom(IoBridge.java:549)
	  at java.net.PlainSocketImpl.read(PlainSocketImpl.java:481)
	  at java.net.PlainSocketImpl.-wrap0(PlainSocketImpl.java:-1)
	  at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)
	  at java.io.InputStream.read(InputStream.java:162)
	  at java.io.BufferedInputStream.fillbuf(BufferedInputStream.java:149)
	  at java.io.BufferedInputStream.read(BufferedInputStream.java:295)
	  - locked <0x155e> (a java.io.BufferedInputStream)
	  at Acme.Serve.Serve$ServeInputStream.read(Serve.java:4290)
	  - locked <0x155f> (a Acme.Serve.Serve$ServeInputStream)
	  at Acme.Serve.Serve$ServeInputStream.read(Serve.java:4253)
	  at javax.servlet.ServletInputStream.readLine(ServletInputStream.java:93)
	  at Acme.Serve.Serve$ServeConnection.parseRequest(Serve.java:2041)
	  at Acme.Serve.Serve$ServeConnection.run(Serve.java:1988)
	  at Acme.Utils$ThreadPool$PooledThread.run(Utils.java:1223)
	  - locked <0x1560> (a Acme.Utils$ThreadPool$PooledThread)
	  at java.lang.Thread.run(Thread.java:818)

"Acme.Utils.ThreadPool(5)-PooledThread: Acme.Serve.Serve$ServeConnection@b835ffa@5451" daemon prio=5 runnable
  java.lang.Thread.State: RUNNABLE
	  at libcore.io.Posix.recvfromBytes(Posix.java:-1)
	  at libcore.io.Posix.recvfrom(Posix.java:189)
	  at libcore.io.BlockGuardOs.recvfrom(BlockGuardOs.java:250)
	  at libcore.io.IoBridge.recvfrom(IoBridge.java:549)
	  at java.net.PlainSocketImpl.read(PlainSocketImpl.java:481)
	  at java.net.PlainSocketImpl.-wrap0(PlainSocketImpl.java:-1)
	  at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)
	  at java.io.InputStream.read(InputStream.java:162)
	  at java.io.BufferedInputStream.fillbuf(BufferedInputStream.java:149)
	  at java.io.BufferedInputStream.read(BufferedInputStream.java:295)
	  - locked <0x1565> (a java.io.BufferedInputStream)
	  at Acme.Serve.Serve$ServeInputStream.read(Serve.java:4290)
	  - locked <0x1566> (a Acme.Serve.Serve$ServeInputStream)
	  at Acme.Serve.Serve$ServeInputStream.read(Serve.java:4253)
	  at javax.servlet.ServletInputStream.readLine(ServletInputStream.java:93)
	  at Acme.Serve.Serve$ServeConnection.parseRequest(Serve.java:2041)
	  at Acme.Serve.Serve$ServeConnection.run(Serve.java:1988)
	  at Acme.Utils$ThreadPool$PooledThread.run(Utils.java:1223)
	  - locked <0x1567> (a Acme.Utils$ThreadPool$PooledThread)
	  at java.lang.Thread.run(Thread.java:818)

"Thread-waitForPendingFutures[PusherInternal{http://192.168.1.132:5984/ek0073, push, c25a2}]@5457" prio=5 waiting
  java.lang.Thread.State: WAITING
	 blocks Thread-waitForPendingFutures[PusherInternal{http://192.168.1.132:5984/ek0073, push, c25a2}]@5457
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.Thread.parkFor$(Thread.java:1220)
	  - locked <0x156b> (a java.lang.Object)
	  at sun.misc.Unsafe.park(Unsafe.java:299)
	  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:158)
	  at java.util.concurrent.FutureTask.awaitDone(FutureTask.java:421)
	  at java.util.concurrent.FutureTask.get(FutureTask.java:163)
	  at com.couchbase.lite.support.RemoteRequestRetry.get(RemoteRequestRetry.java:324)
	  at com.couchbase.lite.replicator.ReplicationInternal.waitPendingFuturesCompleted(ReplicationInternal.java:1800)
	  at com.couchbase.lite.replicator.ReplicationInternal.waitForAllTasksCompleted(ReplicationInternal.java:1779)
	  at com.couchbase.lite.replicator.ReplicationInternal.waitForPendingFutures(ReplicationInternal.java:1750)
	  at com.couchbase.lite.replicator.ReplicationInternal$24.run(ReplicationInternal.java:1711)
	  at java.lang.Thread.run(Thread.java:818)

"CBLManagerWorkExecutor@5456" prio=5 waiting
  java.lang.Thread.State: WAITING
	 blocks CBLManagerWorkExecutor@5456
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.Thread.parkFor$(Thread.java:1220)
	  - locked <0x156a> (a java.lang.Object)
	  at sun.misc.Unsafe.park(Unsafe.java:299)
	  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:158)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2013)
	  at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1078)
	  at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1071)
	  at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1038)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1098)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	  at java.lang.Thread.run(Thread.java:818)

"AsyncTask #1@5417" prio=5 waiting
  java.lang.Thread.State: WAITING
	 blocks AsyncTask #1@5417
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.Thread.parkFor$(Thread.java:1220)
	  - locked <0x1554> (a java.lang.Object)
	  at sun.misc.Unsafe.park(Unsafe.java:299)
	  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:158)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2013)
	  at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
	  at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1038)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1098)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	  at java.lang.Thread.run(Thread.java:818)

"pool-3-thread-1@5418" prio=5 waiting
  java.lang.Thread.State: WAITING
	 blocks pool-3-thread-1@5418
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.Thread.parkFor$(Thread.java:1220)
	  - locked <0x1555> (a java.lang.Object)
	  at sun.misc.Unsafe.park(Unsafe.java:299)
	  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:158)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2013)
	  at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
	  at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1038)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1098)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	  at java.lang.Thread.run(Thread.java:818)

"AsyncTask #2@5427" prio=5 waiting
  java.lang.Thread.State: WAITING
	 blocks AsyncTask #2@5427
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.Thread.parkFor$(Thread.java:1220)
	  - locked <0x1556> (a java.lang.Object)
	  at sun.misc.Unsafe.park(Unsafe.java:299)
	  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:158)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2013)
	  at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
	  at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1038)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1098)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	  at java.lang.Thread.run(Thread.java:818)

"Shell Output@5435" prio=5 runnable
  java.lang.Thread.State: RUNNABLE
	  at libcore.io.Posix.readBytes(Posix.java:-1)
	  at libcore.io.Posix.read(Posix.java:169)
	  at libcore.io.BlockGuardOs.read(BlockGuardOs.java:230)
	  at libcore.io.IoBridge.read(IoBridge.java:468)
	  at java.io.FileInputStream.read(FileInputStream.java:177)
	  at java.io.InputStreamReader.read(InputStreamReader.java:233)
	  - locked <0x155b> (a java.lang.ProcessManager$ProcessInputStream)
	  at java.io.BufferedReader.fillBuf(BufferedReader.java:145)
	  at java.io.BufferedReader.readLine(BufferedReader.java:397)
	  - locked <0x155c> (a java.io.InputStreamReader)
	  at com.stericson.RootShell.execution.Shell$3.run(Shell.java:650)
	  at java.lang.Thread.run(Thread.java:818)

"pool-5-thread-1@5455" prio=5 waiting
  java.lang.Thread.State: WAITING
	 blocks pool-5-thread-1@5455
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.Thread.parkFor$(Thread.java:1220)
	  - locked <0x1569> (a java.lang.Object)
	  at sun.misc.Unsafe.park(Unsafe.java:299)
	  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:158)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2013)
	  at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
	  at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1038)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1098)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	  at java.lang.Thread.run(Thread.java:818)

"Thread-389@5430" prio=5 runnable
  java.lang.Thread.State: RUNNABLE
	  at libcore.io.Posix.accept(Posix.java:-1)
	  at libcore.io.BlockGuardOs.accept(BlockGuardOs.java:63)
	  at java.net.PlainSocketImpl.accept(PlainSocketImpl.java:89)
	  at java.net.ServerSocket.implAccept(ServerSocket.java:217)
	  - locked <0x1558> (a java.net.ServerSocket)
	  at java.net.ServerSocket.accept(ServerSocket.java:141)
	  at Acme.Serve.SimpleAcceptor.accept(SimpleAcceptor.java:40)
	  at Acme.Serve.Serve.serve(Serve.java:809)
	  at com.couchbase.lite.listener.LiteServer.serve(LiteServer.java:63)
	  at com.couchbase.lite.listener.LiteListener.run(LiteListener.java:90)
	  at java.lang.Thread.run(Thread.java:818)

"FinalizerDaemon@5412" daemon prio=5 waiting
  java.lang.Thread.State: WAITING
	 blocks FinalizerDaemon@5412
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.Object.wait(Object.java:423)
	  at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:101)
	  - locked <0x1552> (a java.lang.ref.ReferenceQueue)
	  at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:72)
	  at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:185)
	  at java.lang.Thread.run(Thread.java:818)

"main@5409" prio=5 runnable
  java.lang.Thread.State: RUNNABLE
	  at android.os.MessageQueue.nativePollOnce(MessageQueue.java:-1)
	  at android.os.MessageQueue.next(MessageQueue.java:323)
	  at android.os.Looper.loop(Looper.java:135)
	  at android.app.ActivityThread.main(ActivityThread.java:5417)
	  at java.lang.reflect.Method.invoke(Method.java:-1)
	  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

"CleanupReference@5428" daemon prio=5 waiting
  java.lang.Thread.State: WAITING
	 blocks CleanupReference@5428
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.Object.wait(Object.java:423)
	  at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:101)
	  - locked <0x1557> (a java.lang.ref.ReferenceQueue)
	  at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:72)
	  at org.chromium.content.common.CleanupReference$1.run(CleanupReference.java:50)

"FinalizerWatchdogDaemon@5414" daemon prio=5 waiting
  java.lang.Thread.State: WAITING
	 blocks FinalizerWatchdogDaemon@5414
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.Daemons$FinalizerWatchdogDaemon.waitForObject(Daemons.java:255)
	  - locked <0x1553> (a java.lang.Daemons$FinalizerWatchdogDaemon)
	  at java.lang.Daemons$FinalizerWatchdogDaemon.run(Daemons.java:227)
	  at java.lang.Thread.run(Thread.java:818)

"ReferenceQueueDaemon@5411" daemon prio=5 waiting
  java.lang.Thread.State: WAITING
	 blocks ReferenceQueueDaemon@5411
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.Daemons$ReferenceQueueDaemon.run(Daemons.java:147)
	  - locked <0x1171> (a java.lang.Class)
	  at java.lang.Thread.run(Thread.java:818)

"java.lang.ProcessManager@5431" daemon prio=5 runnable
  java.lang.Thread.State: RUNNABLE
	  at libcore.io.Posix.waitpid(Posix.java:-1)
	  at libcore.io.ForwardingOs.waitpid(ForwardingOs.java:173)
	  at java.lang.ProcessManager.watchChildren(ProcessManager.java:86)
	  at java.lang.ProcessManager.-wrap0(ProcessManager.java:-1)
	  at java.lang.ProcessManager$1.run(ProcessManager.java:58)

"Shell Input@5436" prio=5 waiting
  java.lang.Thread.State: WAITING
	 blocks Shell Input@5436
	  at java.lang.Object.wait(Object.java:-1)
	  at com.stericson.RootShell.execution.Shell$1.run(Shell.java:567)
	  - locked <0x155d> (a java.util.ArrayList)
	  at java.lang.Thread.run(Thread.java:818)

"Acme.Utils.ThreadPool-PooledThread: FREE@5447" daemon prio=5 waiting
  java.lang.Thread.State: WAITING
	 blocks Acme.Utils.ThreadPool-PooledThread: FREE@5447
	  at java.lang.Object.wait(Object.java:-1)
	  at Acme.Utils$ThreadPool$PooledThread.run(Utils.java:1217)
	  - locked <0x1561> (a Acme.Utils$ThreadPool$PooledThread)
	  at java.lang.Thread.run(Thread.java:818)

"Acme.Utils.ThreadPool-PooledThread: FREE@5448" daemon prio=5 waiting
  java.lang.Thread.State: WAITING
	 blocks Acme.Utils.ThreadPool-PooledThread: FREE@5448
	  at java.lang.Object.wait(Object.java:-1)
	  at Acme.Utils$ThreadPool$PooledThread.run(Utils.java:1217)
	  - locked <0x1562> (a Acme.Utils$ThreadPool$PooledThread)
	  at java.lang.Thread.run(Thread.java:818)

"Acme.Utils.ThreadPool-PooledThread: FREE@5449" daemon prio=5 waiting
  java.lang.Thread.State: WAITING
	 blocks Acme.Utils.ThreadPool-PooledThread: FREE@5449
	  at java.lang.Object.wait(Object.java:-1)
	  at Acme.Utils$ThreadPool$PooledThread.run(Utils.java:1217)
	  - locked <0x1563> (a Acme.Utils$ThreadPool$PooledThread)
	  at java.lang.Thread.run(Thread.java:818)

"Acme.Utils.ThreadPool-PooledThread: FREE@5450" daemon prio=5 waiting
  java.lang.Thread.State: WAITING
	 blocks Acme.Utils.ThreadPool-PooledThread: FREE@5450
	  at java.lang.Object.wait(Object.java:-1)
	  at Acme.Utils$ThreadPool$PooledThread.run(Utils.java:1217)
	  - locked <0x1564> (a Acme.Utils$ThreadPool$PooledThread)
	  at java.lang.Thread.run(Thread.java:818)

"JmDNS(android-ff094116f3220d8f.local.).Timer@5453" daemon prio=5 waiting
  java.lang.Thread.State: WAITING
	 blocks JmDNS(android-ff094116f3220d8f.local.).Timer@5453
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.Object.wait(Object.java:423)
	  at java.util.Timer$TimerImpl.run(Timer.java:238)
	  - locked <0x154d> (a java.util.Timer$TimerImpl)

"JmDNS(android-ff094116f3220d8f.local.).State.Timer@5454" prio=5 waiting
  java.lang.Thread.State: WAITING
	 blocks JmDNS(android-ff094116f3220d8f.local.).State.Timer@5454
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.Object.wait(Object.java:423)
	  at java.util.Timer$TimerImpl.run(Timer.java:238)
	  - locked <0x154e> (a java.util.Timer$TimerImpl)

"WifiManager@5440" prio=5 runnable
  java.lang.Thread.State: RUNNABLE
	  at android.os.MessageQueue.nativePollOnce(MessageQueue.java:-1)
	  at android.os.MessageQueue.next(MessageQueue.java:323)
	  at android.os.Looper.loop(Looper.java:135)
	  at android.os.HandlerThread.run(HandlerThread.java:61)

"JavaBridge@5441" prio=5 runnable
  java.lang.Thread.State: RUNNABLE
	  at android.os.MessageQueue.nativePollOnce(MessageQueue.java:-1)
	  at android.os.MessageQueue.next(MessageQueue.java:323)
	  at android.os.Looper.loop(Looper.java:135)
	  at android.os.HandlerThread.run(HandlerThread.java:61)

"HeapTaskDaemon@5413" daemon prio=5 waiting for monitor entry
  java.lang.Thread.State: BLOCKED
	  at dalvik.system.VMRuntime.runHeapTasks(VMRuntime.java:-1)
	  at java.lang.Daemons$HeapTaskDaemon.run(Daemons.java:355)
	  at java.lang.Thread.run(Thread.java:818)

"SocketListener(android-ff094116f3220d8f.local.)@5452" daemon prio=5 runnable
  java.lang.Thread.State: RUNNABLE
	  at libcore.io.Posix.recvfromBytes(Posix.java:-1)
	  at libcore.io.Posix.recvfrom(Posix.java:189)
	  at libcore.io.BlockGuardOs.recvfrom(BlockGuardOs.java:250)
	  at libcore.io.IoBridge.recvfrom(IoBridge.java:549)
	  at java.net.PlainDatagramSocketImpl.doRecv(PlainDatagramSocketImpl.java:163)
	  at java.net.PlainDatagramSocketImpl.receive(PlainDatagramSocketImpl.java:171)
	  at java.net.DatagramSocket.receive(DatagramSocket.java:274)
	  - locked <0x1568> (a java.net.MulticastSocket)
	  at javax.jmdns.impl.SocketListener.run(SocketListener.java:41)

"Session cleaner@5433" prio=1 sleeping
  java.lang.Thread.State: TIMED_WAITING
	 blocks Session cleaner@5433
	  at java.lang.Thread.sleep(Thread.java:-1)
	  at java.lang.Thread.sleep(Thread.java:1031)
	  - locked <0x1559> (a java.lang.Object)
	  at java.lang.Thread.sleep(Thread.java:985)
	  at Acme.Serve.Serve$2.run(Serve.java:753)
	  at java.lang.Thread.run(Thread.java:818)

"KeepAlive cleaner@5434" daemon prio=5 sleeping
  java.lang.Thread.State: TIMED_WAITING
	 blocks KeepAlive cleaner@5434
	  at java.lang.Thread.sleep(Thread.java:-1)
	  at java.lang.Thread.sleep(Thread.java:1031)
	  - locked <0x155a> (a java.lang.Object)
	  at java.lang.Thread.sleep(Thread.java:985)
	  at Acme.Serve.Serve$KeepAliveCleaner.run(Serve.java:1610)

"Signal Catcher@5410" daemon prio=5 waiting
  java.lang.Thread.State: WAITING
	 Incompatible thread state: thread not suspended

"Binder_1@5415" prio=5 runnable
  java.lang.Thread.State: RUNNABLE
	 Incompatible thread state: thread not suspended

"Binder_2@5416" prio=5 runnable
  java.lang.Thread.State: RUNNABLE
	 Incompatible thread state: thread not suspended

"Chrome_DBThread@5419" prio=5 runnable
  java.lang.Thread.State: RUNNABLE
	 Incompatible thread state: thread not suspended

"Chrome_FileThread@5420" prio=5 runnable
  java.lang.Thread.State: RUNNABLE
	 Incompatible thread state: thread not suspended

"Chrome_ProcessLauncherThread@5421" prio=5 runnable
  java.lang.Thread.State: RUNNABLE
	 Incompatible thread state: thread not suspended

"Chrome_CacheThread@5422" prio=5 runnable
  java.lang.Thread.State: RUNNABLE
	 Incompatible thread state: thread not suspended

"Chrome_FileUserBlockingThread@5423" prio=5 runnable
  java.lang.Thread.State: RUNNABLE
	 Incompatible thread state: thread not suspended

"Chrome_IOThread@5424" prio=9 runnable
  java.lang.Thread.State: RUNNABLE
	 Incompatible thread state: thread not suspended

"Thread-384@5425" prio=5 runnable
  java.lang.Thread.State: RUNNABLE
	 Incompatible thread state: thread not suspended

"Thread-385@5426" prio=5 runnable
  java.lang.Thread.State: RUNNABLE
	 Incompatible thread state: thread not suspended

"Thread-388@5429" prio=5 runnable
  java.lang.Thread.State: RUNNABLE
	 Incompatible thread state: thread not suspended

"Binder_3@5432" prio=5 runnable
  java.lang.Thread.State: RUNNABLE
	 Incompatible thread state: thread not suspended

"Thread-417@5437" prio=5 runnable
  java.lang.Thread.State: RUNNABLE
	 Incompatible thread state: thread not suspended

"Thread-418@5438" prio=5 runnable
  java.lang.Thread.State: RUNNABLE
	 Incompatible thread state: thread not suspended

"RenderThread@5439" prio=5 runnable
  java.lang.Thread.State: RUNNABLE
	 Incompatible thread state: thread not suspended

"Thread-422@5442" prio=5 runnable
  java.lang.Thread.State: RUNNABLE
	 Incompatible thread state: thread not suspended

"Thread-423@5443" prio=5 runnable
  java.lang.Thread.State: RUNNABLE
	 Incompatible thread state: thread not suspended

"Thread-424@5444" prio=5 runnable
  java.lang.Thread.State: RUNNABLE
	 Incompatible thread state: thread not suspended

"Thread-425@5445" prio=4 runnable
  java.lang.Thread.State: RUNNABLE
	 Incompatible thread state: thread not suspended
```

**Comment by hideki** [comment]
This could be duplicate with #1142.

**Comment by hideki** [comment]
See #1157

**Comment by hideki** [comment]
#1157 is dead-lock in Batcher. But this one is in `RemoteRequestRetry.get(RemoteRequestRetry.java:324)`

**Comment by hideki** [comment]
`ReplicationInternal.waitForPendingFutures()` is thread-safe. From above thread-dump, non of RemoteRequest threads are working. I guess that `future.get()` (RemoteRequestRetry.java:324) might wait for DONE or CANCELED state future. It seems `FutureTask.get()` is not thread safe.

In FutureTask.java
```java
    public V get() throws InterruptedException, ExecutionException {
        int s = state;
        if (s <= COMPLETING)
            s = awaitDone(false, 0L);
        return report(s);
    }
```

Suggestion:
Use `V get(long timeout, TimeUnit unit)` and check `isCancelled()` and `isDone()` before calling `get()`
