### ISSUE TITLE
Document's changeListeners list should be thread safe

### ISSUE THREAD

**Issue by ashihaby** [couchbase/couchbase-lite-java-core#1174]
This exception sometimes appears with me
```
 03-30 16:47:53.350    3737-3808/E/CBLite﹕ com.couchbase.lite.Database[/data/data/files/demo_cb1701336908.cblite] got exception posting change notifications
    java.util.ConcurrentModificationException
            at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)
            at com.couchbase.lite.Document.revisionAdded(Document.java:507)
            at com.couchbase.lite.Database.postChangeNotifications(Database.java:3810)
            at com.couchbase.lite.Database.databaseStorageChanged(Database.java:3843)
            at com.couchbase.lite.Database.putRevision(Database.java:4154)
            at com.couchbase.lite.Database.putRevision(Database.java:3923)
            at com.couchbase.lite.Document.putProperties(Document.java:420)
            at com.couchbase.lite.UnsavedRevision.save(UnsavedRevision.java:107) 
```

**Comment by hideki** [comment]
Hi @ashihaby,
Thank you very much for reporting this issue. We will make `changeListeners` variable a thread-safe.

**Comment by hideki** [comment]
Note to self:

in Document.java
```java
private List<ChangeListener> changeListeners = new ArrayList<ChangeListener>();

for (ChangeListener listener : changeListeners) {
   listener.changed(new ChangeEvent(this, change));
}
```
