### ISSUE TITLE
duplicated native/linux/x86/libsqlcipher.so in couchbase-lite-java-sqlcipher-1.2.1.jar

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-java-core#1185]
```
java.util.zip.ZipException: duplicate entry: native/linux/x86/libsqlcipher.so
	at java.util.zip.ZipOutputStream.putNextEntry(ZipOutputStream.java:215)
	at java.util.jar.JarOutputStream.putNextEntry(JarOutputStream.java:109)
	at sun.tools.jar.Main.update(Main.java:579)
	at sun.tools.jar.Main.run(Main.java:223)
	at sun.tools.jar.Main.main(Main.java:1177)
```

**Comment by hideki** [comment]
Fixed in couchbase-lite-java-native. PR: https://github.com/couchbase/couchbase-lite-java-native/pull/44
