### ISSUE TITLE
Support for underscores in DNS is missing in couchbase-lite-java-core

### ISSUE THREAD

**Issue by kamal-mann** [couchbase/couchbase-lite-java-core#1219]
[couchbase-lite-java-core](https://github.com/couchbase/couchbase-lite-java-core/releases/tag/1.2.0) (tag:1.2.0) crashes for url with underscores whereas ios client lib works fine.
[crash logs](https://github.com/couchbase/couchbase-lite-java-core/blob/master/src/main/java/com/couchbase/lite/support/RemoteRequest.java#L103):
_Test url:_ ` ABC_qaz_dev_PUBLIC_QWERTY-gateway.run.foo-bar.appspot.com`
```
WARNING: Sync: com.couchbase.lite.replicator.ReplicationInternal$10@1ec4b12: error getting remote checkpoint
java.lang.IllegalArgumentException: Host name may not be null
        at org.apache.http.HttpHost.<init>(HttpHost.java:83)
        at org.apache.http.impl.client.AbstractHttpClient.determineTarget(AbstractHttpClient.java:497)
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:487)
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:465)
        at com.couchbase.lite.support.RemoteRequest.executeRequest(RemoteRequest.java:182)
        at com.couchbase.lite.support.RemoteRequest.run(RemoteRequest.java:102)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by hideki** [comment]
Hi @kamal-mann, Thank you for your bug report. Could you  please provide URL that causes crash?

**Comment by kamal-mann** [comment]
Hi @hideki,  updated initial comment with a dummy test url.

**Comment by hideki** [comment]
@kamal-mann Thank you!

**Comment by hideki** [comment]
In general, underscore (`_`) is not allowed for hostname
http://stackoverflow.com/questions/2180465/can-domain-name-subdomains-have-an-underscore-in-it

**Comment by kamal-mann** [comment]
but same discussion suggests its allowed (as per the[ RFC 2181](http://www.ietf.org/rfc/rfc2181.txt), section 11, "Name syntax": )

**Comment by snej** [comment]
What RFC 2181 is saying is that DNS can store more than just hostnames, and that non-hostnames are not limited to the same character set. And underscores are commonly used in non-hostname DNS records such as DomainKeys. (See [this FAQ](http://domainkeys.sourceforge.net/underscore.html) entry from the DomainKeys project.

But the host portion of a URL _is_ a hostname, and _is_ limited to alphanumerics and hyphens.

**Comment by snej** [comment]
In any case, it's some other library (looks like the Apache HTTP client) that's interpreting the hostname, not Couchbase Lite. So this doesn't look like something that we could work around (even if we wanted to) without something ugly like forking that library and bundling the fork.

I suggest re-registering your server with a hostname using the standard character set that won't cause compatibility problems.

**Comment by kamal-mann** [comment]
@snej I agree with that. But what about the feature parity between iOS vs java based clients?

**Comment by snej** [comment]
"It's a bug, not a feature."

**Comment by hideki** [comment]
[HttpClient is deprecated now.](http://developer.android.com/about/versions/marshmallow/android-6.0-changes.html#behavior-apache-http-client) So we are considering to move to other library. One of candidates is [OkHttp](http://square.github.io/okhttp/).  OkHttp also does not allow underscore. [Ticket](https://github.com/square/okhttp/issues/242). As CBL relies on the http client library,  this issue is not is not fixable.
