### ISSUE TITLE
ManagerTest.testClose() failed with latest master branch

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-java-core#1232]
http://mobile.jenkins.couchbase.com/job/couchbase-lite-android-build/ws/couchbase-lite-android/build/reports/androidTests/connected/com.couchbase.lite.ManagerTest.html#s

```
junit.framework.AssertionFailedError: expected:<0> but was:<1>
at com.couchbase.lite.ManagerTest.testClose(ManagerTest.java:402)
at java.lang.reflect.Method.invokeNative(Native Method)
at com.couchbase.lite.LiteTestCase.runBare(LiteTestCase.java:20)
at com.couchbase.lite.LiteTestCaseWithDB.runBare(LiteTestCaseWithDB.java:95)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:191)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:176)
at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:554)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1701)
```

**Comment by hideki** [comment]
Fixed in couchbase-lite-android: https://github.com/couchbase/couchbase-lite-android/pull/870
