### ISSUE TITLE
Use String.format(Locale, String, Object...)

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-java-core#1260]
[`String.format(String, Object...)`](https://docs.oracle.com/javase/6/docs/api/java/lang/String.html#format(java.lang.String, java.lang.Object...)) could translate integer values to localized number. Instead, we should use [`String.format(Locale, String, Object...)`](https://docs.oracle.com/javase/6/docs/api/java/lang/String.html#format(java.util.Locale, java.lang.String, java.lang.Object...)) with [Locale.US](https://docs.oracle.com/javase/6/docs/api/java/util/Locale.html#US) or `Locale.ENGLISH`.

Integer values are translated to Persian
https://github.com/couchbase/couchbase-lite-android/issues/880#issuecomment-224536668

**Comment by hideki** [comment]
Notes to self:

Test cases fail with Persian language. following is after applying `String.format(Locale.English, ...)` 

```
Running tests
Test running started
junit.framework.AssertionFailedError: Expected: <null> but was: {foo #۱-cafebabe @1}
at com.couchbase.lite.DatabaseTest.test29_autoPruneOnForceInsert(DatabaseTest.java:755)
at java.lang.reflect.Method.invokeNative(Native Method)
at com.couchbase.lite.LiteTestCase.runBare(LiteTestCase.java:33)
at com.couchbase.lite.LiteTestCaseWithDB.runBare(LiteTestCaseWithDB.java:97)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:191)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:176)
at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:554)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1701)


junit.framework.ComparisonFailure: expected:<"[۳]"> but was:<"[3]">
at com.couchbase.lite.RouterTest.testTotalRowsAttributeOnViewQuery(RouterTest.java:952)
at java.lang.reflect.Method.invokeNative(Native Method)
at com.couchbase.lite.LiteTestCase.runBare(LiteTestCase.java:33)
at com.couchbase.lite.LiteTestCaseWithDB.runBare(LiteTestCaseWithDB.java:97)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:191)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:176)
at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:554)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1701)


junit.framework.ComparisonFailure: expected:<"[۳]"> but was:<"[3]">
at com.couchbase.lite.RouterTest.testViews(RouterTest.java:538)
at java.lang.reflect.Method.invokeNative(Native Method)
at com.couchbase.lite.LiteTestCase.runBare(LiteTestCase.java:33)
at com.couchbase.lite.LiteTestCaseWithDB.runBare(LiteTestCaseWithDB.java:97)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:191)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:176)
at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:554)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1701)


junit.framework.AssertionFailedError
at com.couchbase.lite.replicator.ReplicationTest.test18_PendingDocumentIDs(ReplicationTest.java:5124)
at java.lang.reflect.Method.invokeNative(Native Method)
at com.couchbase.lite.LiteTestCase.runBare(LiteTestCase.java:33)
at com.couchbase.lite.LiteTestCaseWithDB.runBare(LiteTestCaseWithDB.java:97)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:191)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:176)
at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:554)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1701)


java.util.concurrent.TimeoutException
at com.couchbase.lite.mockserver.MockDispatcher.takeRequestBlocking(MockDispatcher.java:242)
at com.couchbase.lite.mockserver.MockDispatcher.takeRequestBlocking(MockDispatcher.java:219)
at com.couchbase.lite.LiteTestCaseWithDB.waitForPutCheckpointRequestWithSeq(LiteTestCaseWithDB.java:666)
at com.couchbase.lite.replicator.ReplicationTest.testAttachmentsDeletedOnPull(ReplicationTest.java:813)
at java.lang.reflect.Method.invokeNative(Native Method)
at com.couchbase.lite.LiteTestCase.runBare(LiteTestCase.java:33)
at com.couchbase.lite.LiteTestCaseWithDB.runBare(LiteTestCaseWithDB.java:103)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:191)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:176)
at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:554)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1701)


junit.framework.AssertionFailedError
at com.couchbase.lite.replicator.ReplicationTest.testPullReplicatonWithManyAttachmentRevisions(ReplicationTest.java:4612)
at java.lang.reflect.Method.invokeNative(Native Method)
at com.couchbase.lite.LiteTestCase.runBare(LiteTestCase.java:33)
at com.couchbase.lite.LiteTestCaseWithDB.runBare(LiteTestCaseWithDB.java:97)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:191)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:176)
at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:554)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1701)

Finish
```
