### ISSUE TITLE
Deleting a db takes over 1 min.

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/couchbase-lite-java-core#1263]
Steps to reproduce:
1. Start LiteServ 0.0.0-736 + sync_gateway
2. Create a SQLite db on LiteServ
3. Setup continuous push / replication with sync_gateway db (walrus is fine)
4. Issue a DELETE to the LiteServ db

1.2.1-18 behavior: db is deleted (<1 sec)
0.0.0.736 behavior: db is deleted (> 1min)

This is a non trivial amount of time. Currently our tests delete the database between every run so this behavior explains (1 min * # of tests) increase in runtime.

**Comment by pasin** [comment]
@sethrosetter For Step 3, do I require to push some docs to SGW?

**Comment by sethrosetter** [comment]
@pasin I have noticed that this may not happen every time, however, pushing docs seems to increase the  chance this will happen.

**Comment by sethrosetter** [comment]
<img width="509" alt="screenshot 2016-06-21 14 23 57" src="https://cloud.githubusercontent.com/assets/1365736/16246836/d609fb94-37bb-11e6-85ea-115933c5aaf1.png">

**Comment by sethrosetter** [comment]
The above REST called reproduce the issue on my end. I have also tried push and pull individually. It seems that continuous push and pull from the LiteServ db <-> sg db is required to repro this issue.

**Comment by sethrosetter** [comment]
Also reproducible with 0.0.0-738

**Comment by pasin** [comment]
How big is each doc?

**Comment by pasin** [comment]
It seems like the issue is at stopping the pull replicator. If I started only push replicator, the delete request finish immediately.

**Comment by pasin** [comment]
From logcat, there is an exception thrown from the state machine.

```
06-21 22:44:02.692  22570-23339/com.couchbase.liteservandroid D/Sync﹕ PullerInternal{unknown, pull, 3ebad} [fireTrigger()] => STOP_GRACEFUL
06-21 22:44:02.692  22570-23349/com.couchbase.liteservandroid D/Sync﹕ firing trigger: STOP_GRACEFUL
06-21 22:44:02.692  22570-23349/com.couchbase.liteservandroid V/Sync﹕ PullerInternal{unknown, pull, 3ebad} [onExit()] RUNNING => STOPPING
06-21 22:44:02.692  22570-23349/com.couchbase.liteservandroid V/Sync﹕ PullerInternal{unknown, pull, 3ebad} [onEntry()] RUNNING => STOPPING
06-21 22:44:02.692  22570-23349/com.couchbase.liteservandroid D/Sync﹕ PullerInternal{unknown, pull, 3ebad} STOPPING...
06-21 22:44:02.692  22570-23349/com.couchbase.liteservandroid V/CBLite﹕ setPaused: false
06-21 22:44:02.692  22570-23349/com.couchbase.liteservandroid E/Sync﹕ Unknown Error in stateMachine.fire(trigger)
    java.lang.IllegalStateException: Unbalanced enter/exit
            at okio.AsyncTimeout.enter(AsyncTimeout.java:72)
            at okio.AsyncTimeout$2.read(AsyncTimeout.java:236)
            at okio.RealBufferedSource.indexOf(RealBufferedSource.java:325)
            at okio.RealBufferedSource.indexOf(RealBufferedSource.java:314)
            at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:210)
            at okhttp3.internal.http.Http1xStream$ChunkedSource.readChunkSize(Http1xStream.java:438)
            at okhttp3.internal.http.Http1xStream$ChunkedSource.read(Http1xStream.java:422)
            at okhttp3.internal.Util.skipAll(Util.java:178)
            at okhttp3.internal.Util.discard(Util.java:160)
            at okhttp3.internal.http.Http1xStream$ChunkedSource.close(Http1xStream.java:459)
            at okio.RealBufferedSource.close(RealBufferedSource.java:411)
            at okio.RealBufferedSource$1.close(RealBufferedSource.java:399)
            at java.io.FilterInputStream.close(FilterInputStream.java:64)
            at java.util.zip.InflaterInputStream.close(InflaterInputStream.java:252)
            at java.util.zip.GZIPInputStream.close(GZIPInputStream.java:148)
            at com.couchbase.lite.replicator.ChangeTracker.stop(ChangeTracker.java:517)
            at com.couchbase.lite.replicator.PullerInternal.stop(PullerInternal.java:969)
            at com.couchbase.lite.replicator.ReplicationInternal$20.doIt(ReplicationInternal.java:1359)
            at com.couchbase.lite.replicator.ReplicationInternal$20.doIt(ReplicationInternal.java:1346)
            at com.github.oxo42.stateless4j.StateConfiguration$3.doIt(StateConfiguration.java:135)
            at com.github.oxo42.stateless4j.StateConfiguration$3.doIt(StateConfiguration.java:133)
            at com.github.oxo42.stateless4j.StateRepresentation.executeEntryActions(StateRepresentation.java:118)
            at com.github.oxo42.stateless4j.StateRepresentation.enter(StateRepresentation.java:97)
            at com.github.oxo42.stateless4j.StateMachine.publicFire(StateMachine.java:199)
            at com.github.oxo42.stateless4j.StateMachine.fire(StateMachine.java:126)
            at com.couchbase.lite.replicator.ReplicationInternal$1.run(ReplicationInternal.java:219)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:841)
06-21 22:44:02.692  22570-23339/com.couchbase.liteservandroid D/Sync﹕ PusherInternal{http://10.17.2.133:4984/db/, push, a6594} [fireTrigger()] => STOP_GRACEFUL
06-21 22:44:02.692  22570-23344/com.couchbase.liteservandroid D/Sync﹕ firing trigger: STOP_GRACEFUL
06-21 22:44:02.692  22570-23344/com.couchbase.liteservandroid V/Sync﹕ PusherInternal{http://10.17.2.133:4984/db/, push, a6594} [onExit()] RUNNING => STOPPING
06-21 22:44:02.692  22570-23344/com.couchbase.liteservandroid V/Sync﹕ PusherInternal{http://10.17.2.133:4984/db/, push, a6594} [onEntry()] RUNNING => STOPPING
06-21 22:44:02.692  22570-23344/com.couchbase.liteservandroid D/Sync﹕ PusherInternal{http://10.17.2.133:4984/db/, push, a6594} STOPPING...
06-21 22:44:02.692  22570-23344/com.couchbase.liteservandroid W/RemoteRequest﹕ RemoteRequest{GET, http://10.17.2.133:4984/db/_local/a65944861ae76e88e4fe01098275fa7dd291dc44}: aborting request: okhttp3.RealCall@528a8064
06-21 22:44:02.692  22570-23344/com.couchbase.liteservandroid D/Sync﹕ State transition: RUNNING -> STOPPING (via STOP_GRACEFUL).  this: PusherInternal{http://10.17.2.133:4984/db/, push, a6594}
06-21 22:44:02.692  22570-23356/com.couchbase.liteservandroid D/Sync﹕ PusherInternal{http://10.17.2.133:4984/db/, push, a6594} [fireTrigger()] => STOP_IMMEDIATE
06-21 22:44:02.692  22570-23344/com.couchbase.liteservandroid D/Sync﹕ firing trigger: STOP_IMMEDIATE
06-21 22:44:02.692  22570-23344/com.couchbase.liteservandroid V/Sync﹕ PusherInternal{http://10.17.2.133:4984/db/, push, a6594} [onEntry()] STOPPING => STOPPED
06-21 22:44:02.692  22570-23344/com.couchbase.liteservandroid V/Sync﹕ PusherInternal{http://10.17.2.133:4984/db/, push, a6594}: clearDbRef() called
06-21 22:44:02.692  22570-23349/com.couchbase.liteservandroid D/Sync﹕ changeTrackerStopped.  lifecycle: CONTINUOUS
06-21 22:44:02.692  22570-23349/com.couchbase.liteservandroid D/Sync﹕ Change tracker stopped because replicator is stopping or stopped.
06-21 22:44:02.696  22570-23344/com.couchbase.liteservandroid V/Sync﹕ PusherInternal{http://10.17.2.133:4984/db/, push, a6594}: clearDbRef() setting db to null
06-21 22:44:02.696  22570-23344/com.couchbase.liteservandroid D/Sync﹕ State transition: STOPPING -> STOPPED (via STOP_IMMEDIATE).  this: PusherInternal{http://10.17.2.133:4984/db/, push, a6594}
06-21 22:44:02.696  22570-23356/com.couchbase.liteservandroid D/Sync﹕ PusherInternal stop.run() finished
06-21 22:44:02.740  22570-23346/com.couchbase.liteservandroid D/Sync﹕ PusherInternal{http://10.17.2.133:4984/db/, push, a6594} [fireTrigger()] => STOP_GRACEFUL
06-21 22:44:02.740  22570-23346/com.couchbase.liteservandroid V/Sync﹕ [waitForPendingFutures()] END - thread id: 105
06-21 22:44:02.740  22570-23344/com.couchbase.liteservandroid D/Sync﹕ firing trigger: STOP_GRACEFUL
06-21 22:44:02.908  22570-23349/com.couchbase.liteservandroid V/Sync﹕ *** com.couchbase.lite.replicator.ReplicationInternal$2@52856888: BEGIN processInbox (11 sequences)
06-21 22:44:02.908  22570-23349/com.couchbase.liteservandroid D/Sync﹕ processInbox called
06-21 22:44:02.912  22570-23349/com.couchbase.liteservandroid V/Sync﹕ PullerInternal{unknown, pull, 3ebad}: processInbox() setting changesCount to: 1
06-21 22:44:02.912  22570-23349/com.couchbase.liteservandroid V/Sync﹕ PullerInternal{unknown, pull, 3ebad}: Incrementing changesCount count from 11 by adding -10 -> 1
06-21 22:44:02.912  22570-23349/com.couchbase.liteservandroid V/Sync﹕ PullerInternal{unknown, pull, 3ebad}: fetching 1 remote revisions...
06-21 22:44:02.912  22570-23349/com.couchbase.liteservandroid D/Sync﹕ PullerInternal{unknown, pull, 3ebad}: pullRemoteRevision with rev: {test_ls_db1_0 #1-896bd01164c462e47735b70581265973 @1}
06-21 22:44:02.912  22570-23349/com.couchbase.liteservandroid V/Sync﹕ RemoteRequest{GET, http://10.17.2.133:4984/db/test_ls_db1_0?rev=1-896bd01164c462e47735b70581265973&revs=true&attachments=true}: RemoteRequest created, url: http://10.17.2.133:4984/db/test_ls_db1_0?rev=1-896bd01164c462e47735b70581265973&revs=true&attachments=true
06-21 22:44:02.912  22570-23350/com.couchbase.liteservandroid V/Sync﹕ RemoteRequest{GET, http://10.17.2.133:4984/db/test_ls_db1_0?rev=1-896bd01164c462e47735b70581265973&revs=true&attachments=true}: RemoteRequest execute() called, url: http://10.17.2.133:4984/db/test_ls_db1_0?rev=1-896bd01164c462e47735b70581265973&revs=true&attachments=true
06-21 22:44:02.912  22570-23349/com.couchbase.liteservandroid V/CBLite﹕ setPaused: false
06-21 22:44:02.912  22570-23349/com.couchbase.liteservandroid V/Sync﹕ *** com.couchbase.lite.replicator.ReplicationInternal$2@52856888: END processInbox (lastSequence=null)
06-21 22:44:02.912  22570-23350/com.couchbase.liteservandroid D/Sync﹕ PullerInternal{unknown, pull, 3ebad}: pullRemoteRevision add rev: {test_ls_db1_0 #1-896bd01164c462e47735b70581265973 @1} to batcher: com.couchbase.lite.support.Batcher@528ca220
06-21 22:44:02.912  22570-23350/com.couchbase.liteservandroid V/Sync﹕ RemoteRequest{GET, http://10.17.2.133:4984/db/test_ls_db1_0?rev=1-896bd01164c462e47735b70581265973&revs=true&attachments=true}: RemoteRequest execute() finished, url: http://10.17.2.133:4984/db/test_ls_db1_0?rev=1-896bd01164c462e47735b70581265973&revs=true&attachments=true
06-21 22:44:03.168  22570-23349/com.couchbase.liteservandroid D/Sync﹕ PullerInternal{unknown, pull, 3ebad} inserting 1 revisions...
06-21 22:44:03.168  22570-23349/com.couchbase.liteservandroid V/Database﹕ CBLReplicationExecutor-http://10.17.2.133:4984/db/-pull-3ebad Begin transaction (level 0)
06-21 22:44:03.168  22570-23349/com.couchbase.liteservandroid V/Sync﹕ com.couchbase.lite.replicator.PullerInternal$9@528c7db8: inserting test_ls_db1_0 [1-896bd01164c462e47735b70581265973]
06-21 22:44:03.168  22570-23349/com.couchbase.liteservandroid V/Database﹕ INSERT {test_ls_db1_0 #1-896bd01164c462e47735b70581265973 @1}, history[1]
06-21 22:44:03.168  22570-23349/com.couchbase.liteservandroid V/Database﹕ CBLReplicationExecutor-http://10.17.2.133:4984/db/-pull-3ebad Begin transaction (level 1)
06-21 22:44:03.168  22570-23349/com.couchbase.liteservandroid V/CBLite﹕ ---> Added: {test_ls_db1_0 #1-896bd01164c462e47735b70581265973 @11} as seq 11
06-21 22:44:03.168  22570-23349/com.couchbase.liteservandroid V/Sync﹕ com.couchbase.lite.replicator.PullerInternal$9@528c7db8: finished inserting 1 revisions
06-21 22:44:03.168  22570-23349/com.couchbase.liteservandroid V/Sync﹕ PullerInternal{unknown, pull, 3ebad}: Setting lastSequence to 12 from(null)
06-21 22:44:03.168  22570-23349/com.couchbase.liteservandroid V/Sync﹕ com.couchbase.lite.replicator.PullerInternal$9@528c7db8: inserted 1 revs in 4 milliseconds
06-21 22:44:03.168  22570-23349/com.couchbase.liteservandroid D/Sync﹕ com.couchbase.lite.replicator.PullerInternal$9@528c7db8 insertDownloads() updating completedChangesCount from 0 -> 1
06-21 22:44:03.168  22570-23349/com.couchbase.liteservandroid V/Sync﹕ PullerInternal{unknown, pull, 3ebad}: Incrementing completedChangesCount count from 0 by adding 1 -> 1
06-21 22:44:03.168  22570-23349/com.couchbase.liteservandroid V/CBLite﹕ setPaused: false
06-21 22:44:03.168  22570-23349/com.couchbase.liteservandroid V/Database﹕ CBLReplicationExecutor-http://10.17.2.133:4984/db/-pull-3ebad Committing transaction (level 0)
06-21 22:44:03.168  22570-23351/com.couchbase.liteservandroid D/Sync﹕ PullerInternal{unknown, pull, 3ebad} [fireTrigger()] => WAITING_FOR_CHANGES
06-21 22:44:03.168  22570-23351/com.couchbase.liteservandroid V/Sync﹕ [waitForPendingFutures()] END - thread id: 110
06-21 22:44:03.168  22570-23349/com.couchbase.liteservandroid V/Database﹕ CBLReplicationExecutor-http://10.17.2.133:4984/db/-pull-3ebad Committing transaction (level 1)
06-21 22:44:03.172  22570-23349/com.couchbase.liteservandroid D/Sync﹕ firing trigger: WAITING_FOR_CHANGES
06-21 22:44:08.172  22570-23349/com.couchbase.liteservandroid D/Sync﹕ PullerInternal{unknown, pull, 3ebad}: saveLastSequence() called. lastSequence: 12 remoteCheckpoint: null
06-21 22:44:08.172  22570-23349/com.couchbase.liteservandroid D/Sync﹕ PullerInternal{unknown, pull, 3ebad}: start put remote _local document.  checkpointID: 3ebad2a3d5c87f5b9f47adf361ebfd8de62b3c58 body: {lastSequence=12}
06-21 22:44:08.172  22570-23349/com.couchbase.liteservandroid D/Sync﹕ [sendAsyncRequest()] PUT => http://10.17.2.133:4984/db/_local/3ebad2a3d5c87f5b9f47adf361ebfd8de62b3c58
06-21 22:44:08.172  22570-23349/com.couchbase.liteservandroid V/Sync﹕ RemoteRequest{PUT, http://10.17.2.133:4984/db/_local/3ebad2a3d5c87f5b9f47adf361ebfd8de62b3c58}: RemoteRequest created, url: http://10.17.2.133:4984/db/_local/3ebad2a3d5c87f5b9f47adf361ebfd8de62b3c58
06-21 22:44:08.172  22570-23362/com.couchbase.liteservandroid V/Sync﹕ RemoteRequest{PUT, http://10.17.2.133:4984/db/_local/3ebad2a3d5c87f5b9f47adf361ebfd8de62b3c58}: RemoteRequest execute() called, url: http://10.17.2.133:4984/db/_local/3ebad2a3d5c87f5b9f47adf361ebfd8de62b3c58
06-21 22:44:08.176  22570-23349/com.couchbase.liteservandroid D/Sync﹕ PullerInternal{unknown, pull, 3ebad} [fireTrigger()] => RESUME
06-21 22:44:08.176  22570-23349/com.couchbase.liteservandroid D/Sync﹕ firing trigger: RESUME
06-21 22:44:08.176  22570-23362/com.couchbase.liteservandroid D/Sync﹕ com.couchbase.lite.replicator.ReplicationInternal$8@528c9c24: put remote _local document request finished.  checkpointID: 3ebad2a3d5c87f5b9f47adf361ebfd8de62b3c58 body: {lastSequence=12}
06-21 22:44:08.176  22570-23362/com.couchbase.liteservandroid D/Sync﹕ com.couchbase.lite.replicator.ReplicationInternal$8@528c9c24: saved remote checkpoint, updating local checkpoint. RemoteCheckpoint: {_rev=0-1, lastSequence=12}
06-21 22:44:08.176  22570-23362/com.couchbase.liteservandroid V/Sync﹕ RemoteRequest{PUT, http://10.17.2.133:4984/db/_local/3ebad2a3d5c87f5b9f47adf361ebfd8de62b3c58}: RemoteRequest execute() finished, url: http://10.17.2.133:4984/db/_local/3ebad2a3d5c87f5b9f47adf361ebfd8de62b3c58
06-21 22:44:08.176  22570-23405/com.couchbase.liteservandroid V/Sync﹕ [waitForPendingFutures()] STARTED - thread id: 120
06-21 22:44:08.928  22570-23405/com.couchbase.liteservandroid D/Sync﹕ PullerInternal{unknown, pull, 3ebad} [fireTrigger()] => WAITING_FOR_CHANGES
06-21 22:44:08.928  22570-23405/com.couchbase.liteservandroid V/Sync﹕ [waitForPendingFutures()] END - thread id: 120
06-21 22:44:08.928  22570-23349/com.couchbase.liteservandroid D/Sync﹕ firing trigger: WAITING_FOR_CHANGES
06-21 22:44:11.776  22570-22576/com.couchbase.liteservandroid I/dalvikvm﹕ Debugger is active
06-21 22:45:02.700  22570-23339/com.couchbase.liteservandroid V/Listener﹕ RouterCallbackBlock.onResponseReady() START
06-21 22:45:02.700  22570-23339/com.couchbase.liteservandroid V/Listener﹕ RouterCallbackBlock.onResponseReady() END
06-21 22:45:02.700  22570-23339/com.couchbase.liteservandroid V/Listener﹕ CountDownLatch.await() START
06-21 22:45:02.700  22570-23339/com.couchbase.liteservandroid V/Listener﹕ CountDownLatch.await() END
06-21 22:45:02.704  22570-23339/com.couchbase.liteservandroid D/dalvikvm﹕ GC_FOR_ALLOC freed 464K, 14% free 3794K/4396K, paused 3ms, total 4ms
06-21 22:45:02.704  22570-23339/com.couchbase.liteservandroid I/dalvikvm-heap﹕ Grow heap (frag case) to 3.870MB for 65548-byte allocation
06-21 22:45:02.712  22570-22579/com.couchbase.liteservandroid D/dalvikvm﹕ GC_FOR_ALLOC freed 28K, 15% free 3830K/4464K, paused 4ms, total 4ms
```

**Comment by sethrosetter** [comment]
I added this a couple days ago - https://github.com/couchbase/couchbase-lite-java-core/issues/1271
