### ISSUE TITLE
Forestdb Handle is being used by another thread (Note: ForestDB error code = -39)

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/couchbase-lite-java-core#1270]
test failing: https://github.com/couchbaselabs/sync-gateway-tests/blob/master/tests/cbl-replication-mismatch-restart-gateway.js

Using `0.0.0-738 ForestDB`

The scenario is as follows:
1. Create db on LiteServ
2. Add Docs to the db
3. Setup continuous push / pull replication with sg (using walrus)
4. Kill / Restart sync_gateway
5. Update docs on LiteServ (Failed)

I am seeing the following errors in logcat. 

```
06-15 10:33:00.745 22000 22072 E Database: Failed to begin transaction
06-15 10:33:00.745 22000 22072 E Database: com.couchbase.cbforest.ForestException: Forestdb Handle is being used by another thread
06-15 10:33:00.745 22000 22072 E Database: 	at com.couchbase.cbforest.Database.beginTransaction(Native Method)
06-15 10:33:00.745 22000 22072 E Database: 	at com.couchbase.lite.store.ForestDBStore.beginTransaction(ForestDBStore.java:1213)
06-15 10:33:00.745 22000 22072 E Database: 	at com.couchbase.lite.store.ForestDBStore.add(ForestDBStore.java:817)
06-15 10:33:00.745 22000 22072 E Database: 	at com.couchbase.lite.Database.put(Database.java:1821)
06-15 10:33:00.745 22000 22072 E Database: 	at com.couchbase.lite.Database.putRevision(Database.java:1771)
06-15 10:33:00.745 22000 22072 E Database: 	at com.couchbase.lite.Database.putRevision(Database.java:1762)
06-15 10:33:00.745 22000 22072 E Database: 	at com.couchbase.lite.router.Router.update(Router.java:2144)
06-15 10:33:00.745 22000 22072 E Database: 	at com.couchbase.lite.router.Router.update(Router.java:2197)
06-15 10:33:00.745 22000 22072 E Database: 	at com.couchbase.lite.router.Router.do_PUT_Document(Router.java:2233)
06-15 10:33:00.745 22000 22072 E Database: 	at java.lang.reflect.Method.invoke(Native Method)
06-15 10:33:00.745 22000 22072 E Database: 	at com.couchbase.lite.router.Router.start(Router.java:568)
06-15 10:33:00.745 22000 22072 E Database: 	at com.couchbase.lite.listener.LiteServlet.service(LiteServlet.java:141)
06-15 10:33:00.745 22000 22072 E Database: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)
06-15 10:33:00.745 22000 22072 E Database: 	at Acme.Serve.Serve$ServeConnection.runServlet(Serve.java:2251)
06-15 10:33:00.745 22000 22072 E Database: 	at Acme.Serve.Serve$ServeConnection.parseRequest(Serve.java:2176)
06-15 10:33:00.745 22000 22072 E Database: 	at Acme.Serve.Serve$ServeConnection.run(Serve.java:1988)
06-15 10:33:00.745 22000 22072 E Database: 	at Acme.Utils$ThreadPool$PooledThread.run(Utils.java:1223)
06-15 10:33:00.745 22000 22072 E Database: 	at java.lang.Thread.run(Thread.java:818)
06-15 10:33:00.746 22000 22072 E Database: Error in saveForest()
06-15 10:33:00.746 22000 22072 E Database: com.couchbase.cbforest.ForestException: internal assertion failure
06-15 10:33:00.746 22000 22072 E Database: 	at com.couchbase.cbforest.Document.save(Native Method)
06-15 10:33:00.746 22000 22072 E Database: 	at com.couchbase.cbforest.Document.save(Document.java:87)
06-15 10:33:00.746 22000 22072 E Database: 	at com.couchbase.lite.store.ForestDBStore.saveForest(ForestDBStore.java:1199)
06-15 10:33:00.746 22000 22072 E Database: 	at com.couchbase.lite.store.ForestDBStore.add(ForestDBStore.java:910)
06-15 10:33:00.746 22000 22072 E Database: 	at com.couchbase.lite.Database.put(Database.java:1821)
06-15 10:33:00.746 22000 22072 E Database: 	at com.couchbase.lite.Database.putRevision(Database.java:1771)
06-15 10:33:00.746 22000 22072 E Database: 	at com.couchbase.lite.Database.putRevision(Database.java:1762)
06-15 10:33:00.746 22000 22072 E Database: 	at com.couchbase.lite.router.Router.update(Router.java:2144)
06-15 10:33:00.746 22000 22072 E Database: 	at com.couchbase.lite.router.Router.update(Router.java:2197)
06-15 10:33:00.746 22000 22072 E Database: 	at com.couchbase.lite.router.Router.do_PUT_Document(Router.java:2233)
06-15 10:33:00.746 22000 22072 E Database: 	at java.lang.reflect.Method.invoke(Native Method)
06-15 10:33:00.746 22000 22072 E Database: 	at com.couchbase.lite.router.Router.start(Router.java:568)
06-15 10:33:00.746 22000 22072 E Database: 	at com.couchbase.lite.listener.LiteServlet.service(LiteServlet.java:141)
06-15 10:33:00.746 22000 22072 E Database: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)
06-15 10:33:00.746 22000 22072 E Database: 	at Acme.Serve.Serve$ServeConnection.runServlet(Serve.java:2251)
06-15 10:33:00.746 22000 22072 E Database: 	at Acme.Serve.Serve$ServeConnection.parseRequest(Serve.java:2176)
06-15 10:33:00.746 22000 22072 E Database: 	at Acme.Serve.Serve$ServeConnection.run(Serve.java:1988)
06-15 10:33:00.746 22000 22072 E Database: 	at Acme.Utils$ThreadPool$PooledThread.run(Utils.java:1223)
06-15 10:33:00.746 22000 22072 E Database: 	at java.lang.Thread.run(Thread.java:818)
06-15 10:33:00.747 22000 22072 E Router  : Error updating doc: mismatch-restart-sg-one_6
06-15 10:33:00.747 22000 22072 E Router  : com.couchbase.lite.CouchbaseLiteException, Status: 590 (HTTP 500 Database error!)
06-15 10:33:00.747 22000 22072 E Router  : 	at com.couchbase.lite.store.ForestDBStore.add(ForestDBStore.java:913)
06-15 10:33:00.747 22000 22072 E Router  : 	at com.couchbase.lite.Database.put(Database.java:1821)
06-15 10:33:00.747 22000 22072 E Router  : 	at com.couchbase.lite.Database.putRevision(Database.java:1771)
06-15 10:33:00.747 22000 22072 E Router  : 	at com.couchbase.lite.Database.putRevision(Database.java:1762)
06-15 10:33:00.747 22000 22072 E Router  : 	at com.couchbase.lite.router.Router.update(Router.java:2144)
06-15 10:33:00.747 22000 22072 E Router  : 	at com.couchbase.lite.router.Router.update(Router.java:2197)
06-15 10:33:00.747 22000 22072 E Router  : 	at com.couchbase.lite.router.Router.do_PUT_Document(Router.java:2233)
06-15 10:33:00.747 22000 22072 E Router  : 	at java.lang.reflect.Method.invoke(Native Method)
06-15 10:33:00.747 22000 22072 E Router  : 	at com.couchbase.lite.router.Router.start(Router.java:568)
06-15 10:33:00.747 22000 22072 E Router  : 	at com.couchbase.lite.listener.LiteServlet.service(LiteServlet.java:141)
06-15 10:33:00.747 22000 22072 E Router  : 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)
06-15 10:33:00.747 22000 22072 E Router  : 	at Acme.Serve.Serve$ServeConnection.runServlet(Serve.java:2251)
06-15 10:33:00.747 22000 22072 E Router  : 	at Acme.Serve.Serve$ServeConnection.parseRequest(Serve.java:2176)
06-15 10:33:00.747 22000 22072 E Router  : 	at Acme.Serve.Serve$ServeConnection.run(Serve.java:1988)
06-15 10:33:00.747 22000 22072 E Router  : 	at Acme.Utils$ThreadPool$PooledThread.run(Utils.java:1223)
06-15 10:33:00.747 22000 22072 E Router  : 	at java.lang.Thread.run(Thread.java:818)
06-15 10:33:03.819 22000 22077 W Sync    : PullerInternal{unknown, pull, 8625d}: Progress: set error = java.net.ConnectException: Failed to connect to /10.0.2.2:9888
06-15 10:33:03.866 22000 22087 E Sync    : Unknown Error in stateMachine.fire(trigger)
06-15 10:33:03.866 22000 22087 E Sync    : java.lang.IllegalStateException: Unbalanced enter/exit
06-15 10:33:03.866 22000 22087 E Sync    : 	at okio.AsyncTimeout.enter(AsyncTimeout.java:72)
06-15 10:33:03.866 22000 22087 E Sync    : 	at okio.AsyncTimeout$2.read(AsyncTimeout.java:236)
06-15 10:33:03.866 22000 22087 E Sync    : 	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:325)
06-15 10:33:03.866 22000 22087 E Sync    : 	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:314)
06-15 10:33:03.866 22000 22087 E Sync    : 	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:210)
06-15 10:33:03.866 22000 22087 E Sync    : 	at okhttp3.internal.http.Http1xStream$ChunkedSource.readChunkSize(Http1xStream.java:438)
06-15 10:33:03.866 22000 22087 E Sync    : 	at okhttp3.internal.http.Http1xStream$ChunkedSource.read(Http1xStream.java:422)
06-15 10:33:03.866 22000 22087 E Sync    : 	at okhttp3.internal.Util.skipAll(Util.java:178)
06-15 10:33:03.866 22000 22087 E Sync    : 	at okhttp3.internal.Util.discard(Util.java:160)
06-15 10:33:03.866 22000 22087 E Sync    : 	at okhttp3.internal.http.Http1xStream$ChunkedSource.close(Http1xStream.java:459)
06-15 10:33:03.866 22000 22087 E Sync    : 	at okio.RealBufferedSource.close(RealBufferedSource.java:411)
06-15 10:33:03.866 22000 22087 E Sync    : 	at okio.RealBufferedSource$1.close(RealBufferedSource.java:399)
06-15 10:33:03.866 22000 22087 E Sync    : 	at java.io.FilterInputStream.close(FilterInputStream.java:64)
06-15 10:33:03.866 22000 22087 E Sync    : 	at java.util.zip.InflaterInputStream.close(InflaterInputStream.java:252)
06-15 10:33:03.866 22000 22087 E Sync    : 	at java.util.zip.GZIPInputStream.close(GZIPInputStream.java:125)
06-15 10:33:03.866 22000 22087 E Sync    : 	at com.couchbase.lite.replicator.ChangeTracker.stop(ChangeTracker.java:517)
06-15 10:33:03.866 22000 22087 E Sync    : 	at com.couchbase.lite.replicator.PullerInternal.stop(PullerInternal.java:969)
06-15 10:33:03.866 22000 22087 E Sync    : 	at com.couchbase.lite.replicator.ReplicationInternal$20.doIt(ReplicationInternal.java:1359)
06-15 10:33:03.866 22000 22087 E Sync    : 	at com.couchbase.lite.replicator.ReplicationInternal$20.doIt(ReplicationInternal.java:1346)
06-15 10:33:03.866 22000 22087 E Sync    : 	at com.github.oxo42.stateless4j.StateConfiguration$3.doIt(StateConfiguration.java:135)
06-15 10:33:03.866 22000 22087 E Sync    : 	at com.github.oxo42.stateless4j.StateConfiguration$3.doIt(StateConfiguration.java:133)
06-15 10:33:03.866 22000 22087 E Sync    : 	at com.github.oxo42.stateless4j.StateRepresentation.executeEntryActions(StateRepresentation.java:118)
06-15 10:33:03.866 22000 22087 E Sync    : 	at com.github.oxo42.stateless4j.StateRepresentation.enter(StateRepresentation.java:97)
06-15 10:33:03.866 22000 22087 E Sync    : 	at com.github.oxo42.stateless4j.StateMachine.publicFire(StateMachine.java:199)
06-15 10:33:03.866 22000 22087 E Sync    : 	at com.github.oxo42.stateless4j.StateMachine.fire(StateMachine.java:126)
06-15 10:33:03.866 22000 22087 E Sync    : 	at com.couchbase.lite.replicator.ReplicationInternal$1.run(ReplicationInternal.java:219)
06-15 10:33:03.866 22000 22087 E Sync    : 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
06-15 10:33:03.866 22000 22087 E Sync    : 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
06-15 10:33:03.866 22000 22087 E Sync    : 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
06-15 10:33:03.866 22000 22087 E Sync    : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
06-15 10:33:03.866 22000 22087 E Sync    : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
06-15 10:33:03.866 22000 22087 E Sync    : 	at java.lang.Thread.run(Thread.java:818)
```

**Comment by hideki** [comment]
I think this is duplicate with https://github.com/couchbase/couchbase-lite-android/issues/909. Once we fix 909, we should run functional/robot test again.

**Comment by hideki** [comment]
This is duplicate issue with  couchbase/couchbase-lite-android#909. I will track this issue with 909. I will close this.
