### ISSUE TITLE
Error in stateMachine.fire(trigger)

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/couchbase-lite-java-core#1271]
I am seeing a lot of these errors in adb logcat for `0.0.0-738` 

```
06-15 11:00:06.433 31112 31215 E Sync    : Unknown Error in stateMachine.fire(trigger)
06-15 11:00:06.433 31112 31215 E Sync    : java.lang.IllegalStateException: Unbalanced enter/exit
06-15 11:00:06.433 31112 31215 E Sync    :     at okio.AsyncTimeout.enter(AsyncTimeout.java:72)
06-15 11:00:06.433 31112 31215 E Sync    :     at okio.AsyncTimeout$2.read(AsyncTimeout.java:236)
06-15 11:00:06.433 31112 31215 E Sync    :     at okio.RealBufferedSource.indexOf(RealBufferedSource.java:325)
06-15 11:00:06.433 31112 31215 E Sync    :     at okio.RealBufferedSource.indexOf(RealBufferedSource.java:314)
06-15 11:00:06.433 31112 31215 E Sync    :     at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:210)
06-15 11:00:06.433 31112 31215 E Sync    :     at okhttp3.internal.http.Http1xStream$ChunkedSource.readChunkSize(Http1xStream.java:438)
06-15 11:00:06.433 31112 31215 E Sync    :     at okhttp3.internal.http.Http1xStream$ChunkedSource.read(Http1xStream.java:422)
06-15 11:00:06.433 31112 31215 E Sync    :     at okhttp3.internal.Util.skipAll(Util.java:178)
06-15 11:00:06.433 31112 31215 E Sync    :     at okhttp3.internal.Util.discard(Util.java:160)
06-15 11:00:06.433 31112 31215 E Sync    :     at okhttp3.internal.http.Http1xStream$ChunkedSource.close(Http1xStream.java:459)
06-15 11:00:06.433 31112 31215 E Sync    :     at okio.RealBufferedSource.close(RealBufferedSource.java:411)
06-15 11:00:06.433 31112 31215 E Sync    :     at okio.RealBufferedSource$1.close(RealBufferedSource.java:399)
06-15 11:00:06.433 31112 31215 E Sync    :     at java.io.FilterInputStream.close(FilterInputStream.java:64)
06-15 11:00:06.433 31112 31215 E Sync    :     at java.util.zip.InflaterInputStream.close(InflaterInputStream.java:252)
06-15 11:00:06.433 31112 31215 E Sync    :     at java.util.zip.GZIPInputStream.close(GZIPInputStream.java:125)
06-15 11:00:06.433 31112 31215 E Sync    :     at com.couchbase.lite.replicator.ChangeTracker.stop(ChangeTracker.java:517)
06-15 11:00:06.433 31112 31215 E Sync    :     at com.couchbase.lite.replicator.PullerInternal.stop(PullerInternal.java:969)
06-15 11:00:06.433 31112 31215 E Sync    :     at com.couchbase.lite.replicator.ReplicationInternal$20.doIt(ReplicationInternal.java:1359)
06-15 11:00:06.433 31112 31215 E Sync    :     at com.couchbase.lite.replicator.ReplicationInternal$20.doIt(ReplicationInternal.java:1346)
06-15 11:00:06.433 31112 31215 E Sync    :     at com.github.oxo42.stateless4j.StateConfiguration$3.doIt(StateConfiguration.java:135)
06-15 11:00:06.433 31112 31215 E Sync    :     at com.github.oxo42.stateless4j.StateConfiguration$3.doIt(StateConfiguration.java:133)
06-15 11:00:06.433 31112 31215 E Sync    :     at com.github.oxo42.stateless4j.StateRepresentation.executeEntryActions(StateRepresentation.java:118)
06-15 11:00:06.433 31112 31215 E Sync    :     at com.github.oxo42.stateless4j.StateRepresentation.enter(StateRepresentation.java:97)
06-15 11:00:06.433 31112 31215 E Sync    :     at com.github.oxo42.stateless4j.StateMachine.publicFire(StateMachine.java:199)
06-15 11:00:06.433 31112 31215 E Sync    :     at com.github.oxo42.stateless4j.StateMachine.fire(StateMachine.java:126)
06-15 11:00:06.433 31112 31215 E Sync    :     at com.couchbase.lite.replicator.ReplicationInternal$1.run(ReplicationInternal.java:219)
06-15 11:00:06.433 31112 31215 E Sync    :     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
06-15 11:00:06.433 31112 31215 E Sync    :     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
06-15 11:00:06.433 31112 31215 E Sync    :     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
06-15 11:00:06.433 31112 31215 E Sync    :     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
06-15 11:00:06.433 31112 31215 E Sync    :     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
06-15 11:00:06.433 31112 31215 E Sync    :     at java.lang.Thread.run(Thread.java:818)
```

**Comment by hideki** [comment]
this should be solved by https://github.com/couchbase/couchbase-lite-java-core/pull/1281
