### ISSUE TITLE
ForestDB throws exception from native call (Note: ForestDB error code = -39)

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-java-core#1301]
This issue is from forums.couchbase.com
https://forums.couchbase.com/t/forest-db-throws-exception-from-native-call/8881

```
Env
Android API 22
compile 'com.couchbase.lite:couchbase-lite-android:1.2.0'
compile 'com.couchbase.lite:couchbase-lite-android-forestdb:1.2.0'

While performing one of the query in my app, ForestDB throws exception. The result is non-deterministic - the exception was thrown sometime but not always for the same query. See the following stack trace. Can you please provide some information/help on what would potentially cause this exception and how to fix the issue.
```
```
Caused by: com.couchbase.lite.CouchbaseLiteException: ForestException{domain=2, code=-39}, Status: -39 (HTTP 500 Internal error)
    at com.couchbase.lite.store.ForestDBViewStore.updateIndexes(ForestDBViewStore.java:283)
    at com.couchbase.lite.View.updateIndexes(View.java:321)
    at com.couchbase.lite.View.updateIndex(View.java:294)
    at com.couchbase.lite.Database.queryViewNamed(Database.java:2092)
    at com.couchbase.lite.Query.run(Query.java:433)
    ....    
    at android.os.AsyncTask$2.call(AsyncTask.java:295) 
    at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234) 
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
    at java.lang.Thread.run(Thread.java:818) 

Caused by: ForestException{domain=2, code=-39}
    at com.couchbase.cbforest.Indexer.iterateDocuments(Native Method)
    at com.couchbase.cbforest.Indexer.iterateDocuments(Indexer.java:18)
    at com.couchbase.lite.store.ForestDBViewStore.updateIndexes(ForestDBViewStore.java:250)
    at com.couchbase.lite.View.updateIndexes(View.java:321) 
    at com.couchbase.lite.View.updateIndex(View.java:294) 
    at com.couchbase.lite.Database.queryViewNamed(Database.java:2092) 
    at com.couchbase.lite.Query.run(Query.java:433)
```

**Comment by hideki** [comment]
This is duplicate issue with  couchbase/couchbase-lite-android#909. I will track this issue with 909. I will close this.
