### ISSUE TITLE
Encrypted attachments fail to sync

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/couchbase-lite-java-core#1308]
Using 
- CBL Android 1.3.0-2, SQLCipher or ForestDB + Encryption
- TodoLite
- Android 6P emulator with Android N

1. Create a list
2. Share with another person
3. Create task with image
4. Task syncs but image does not

Expected: Image should sync

This is a regression and works with 1.2.0.

**Comment by sethrosetter** [comment]
```
06-29 15:45:26.982 16347 16347 E ToDoLite: Cannot decode the attached image
06-29 15:45:26.982 16347 16347 E ToDoLite: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
06-29 15:45:26.982 16347 16347 E ToDoLite: 	at com.couchbase.todolite.TasksFragment$TaskAdapter.getView(TasksFragment.java:452)
06-29 15:45:26.982 16347 16347 E ToDoLite: 	at android.widget.HeaderViewListAdapter.getView(HeaderViewListAdapter.java:220)
06-29 15:45:26.982 16347 16347 E ToDoLite: 	at android.widget.AbsListView.obtainView(AbsListView.java:2360)
06-29 15:45:26.982 16347 16347 E ToDoLite: 	at android.widget.ListView.makeAndAddView(ListView.java:1972)
06-29 15:45:26.982 16347 16347 E ToDoLite: 	at android.widget.ListView.fillDown(ListView.java:704)
06-29 15:45:26.982 16347 16347 E ToDoLite: 	at android.widget.ListView.fillSpecific(ListView.java:1412)
06-29 15:45:26.982 16347 16347 E ToDoLite: 	at android.widget.ListView.layoutChildren(ListView.java:1708)
06-29 15:45:26.982 16347 16347 E ToDoLite: 	at android.widget.AbsListView.onLayout(AbsListView.java:2161)
06-29 15:45:26.982 16347 16347 E ToDoLite: 	at android.view.View.layout(View.java:17519)
06-29 15:45:26.982 16347 16347 E ToDoLite: 	at android.view.ViewGroup.layout(ViewGroup.java:5612)
06-29 15:45:26.982 16347 16347 E ToDoLite: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
06-29 15:45:26.982 16347 16347 E ToDoLite: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
06-29 15:45:26.982 16347 16347 E ToDoLite: 	at android.view.View.layout(View.java:17519)
06-29 15:45:26.982 16347 16347 E ToDoLite: 	at android.view.ViewGroup.layout(ViewGroup.java:5612)
06-29 15:45:26.982 16347 16347 E ToDoLite: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1737)
06-29 15:45:26.982 16347 16347 E ToDoLite: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1581)
06-29 15:45:26.982 16347 16347 E ToDoLite: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1490)
06-29 15:45:26.982 16347 16347 E ToDoLite: 	at android.view.View.layout(View.java:17519)
06-29 15:45:26.982 16347 16347 E ToDoLite: 	at android.view.ViewGroup.layout(ViewGroup.java:5612)
06-29 15:45:26.982 16347 16347 E ToDoLite: 	at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:907)
06-29 15:45:26.982 16347 16347 E ToDoLite: 	at android.view.View.layout(View.java:17519)
06-29 15:45:26.982 16347 16347 E ToDoLite: 	at android.view.ViewGroup.layout(ViewGroup.java:5612)
06-29 15:45:26.982 16347 16347 E ToDoLite: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1737)
06-29 15:45:26.982 16347 16347 E ToDoLite: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1581)
06-29 15:45:26.982 16347 16347 E ToDoLite: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1490)
06-29 15:45:26.982 16347 16347 E ToDoLite: 	at android.view.View.layout(View.java:17519)
06-29 15:45:26.982 16347 16347 E ToDoLite: 	at android.view.ViewGroup.layout(ViewGroup.java:5612)
06-29 15:45:26.982 16347 16347 E ToDoLite: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
06-29 15:45:26.982 16347 16347 E ToDoLite: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
06-29 15:45:26.982 16347 16347 E ToDoLite: 	at android.view.View.layout(View.java:17519)
06-29 15:45:26.982 16347 16347 E ToDoLite: 	at android.view.ViewGroup.layout(ViewGroup.java:5612)
06-29 15:45:26.982 16347 16347 E ToDoLite: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1737)
06-29 15:45:26.982 16347 16347 E ToDoLite: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1581)
06-29 15:45:26.982 16347 16347 E ToDoLite: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1490)
06-29 15:45:26.982 16347 16347 E ToDoLite: 	at android.view.View.layout(View.java:17519)
06-29 15:45:26.982 16347 16347 E ToDoLite: 	at android.view.ViewGroup.layout(ViewGroup.java:5612)
06-29 15:45:26.982 16347 16347 E ToDoLite: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
06-29 15:45:26.982 16347 16347 E ToDoLite: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
06-29 15:45:26.982 16347 16347 E ToDoLite: 	at android.view.View.layout(View.java:17519)
06-29 15:45:26.982 16347 16347 E ToDoLite: 	at android.view.ViewGroup.layout(ViewGroup.java:5612)
06-29 15:45:26.982 16347 16347 E ToDoLite: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1737)
06-29 15:45:26.982 16347 16347 E ToDoLite: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1581)
06-29 15:45:26.982 16347 16347 E ToDoLite: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1490)
06-29 15:45:26.982 16347 16347 E ToDoLite: 	at android.view.View.layout(View.java:17519)
06-29 15:45:26.982 16347 16347 E ToDoLite: 	at android.view.ViewGroup.layout(ViewGroup.java:5612)
06-29 15:45:26.982 16347 16347 E ToDoLite: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
06-29 15:45:26.982 16347 16347 E ToDoLite: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
06-29 15:45:26.982 16347 16347 E ToDoLite: 	at com.android.internal.policy.DecorView.onLayout(DecorView.java:723)
06-29 15:45:26.982 16347 16347 E ToDoLite: 	at android.view.View.layout(View.java:17519)
06-29 15:45:26.982 16347 16347 E ToDoLite: 	at android.view.ViewGroup.layout(ViewGroup.java:5612)
06-29 15:45:26.982 16347 16347 E ToDoLite: 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2323)
06-29 15:45:26.982 16347 16347 E ToDoLite: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2053)
06-29 15:45:26.982 16347 16347 E ToDoLite: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1244)
06-29 15:45:26.982 16347 16347 E ToDoLite: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6271)
06-29 15:45:26.982 16347 16347 E ToDoLite: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
06-29 15:45:26.982 16347 16347 E ToDoLite: 	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
06-29 15:45:26.982 16347 16347 E ToDoLite: 	at android.view.Choreographer.doFrame(Choreographer.java:606)
06-29 15:45:26.982 16347 16347 E ToDoLite: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
06-29 15:45:26.982 16347 16347 E ToDoLite: 	at android.os.Handler.handleCallback(Handler.java:751)
06-29 15:45:26.982 16347 16347 E ToDoLite: 	at android.os.Handler.dispatchMessage(Handler.java:95)
06-29 15:45:26.982 16347 16347 E ToDoLite: 	at android.os.Looper.loop(Looper.java:154)
06-29 15:45:26.982 16347 16347 E ToDoLite: 	at android.app.ActivityThread.main(ActivityThread.java:6044)
06-29 15:45:26.982 16347 16347 E ToDoLite: 	at java.lang.reflect.Method.invoke(Native Method)
06-29 15:45:26.982 16347 16347 E ToDoLite: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
06-29 15:45:26.982 16347 16347 E ToDoLite: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

**Comment by hideki** [comment]
Notes: Full unit-test can pass with sqlcipher.

**Comment by hideki** [comment]
Note to self:
- This is not related with encryption. Most of photo attachments from Nexus 6P have this issue with any storage type. This issue is reproducible with SQLite.
- It seems push with large attachment causes this issue. Multi-part body for attachment could be corrupted.

**Comment by hideki** [comment]
Behind encrypted attachment issue, I found another critical issue. Multi-part document that CBL Android is not accepted by Sync-Gateway.

### 1.2.1 SQLite
##### Request header -> `Content-Type: multipart/related; ....`
![1 2 1 header](https://cloud.githubusercontent.com/assets/15889/16531747/be6f72e2-3f82-11e6-9970-c9d6e1ea9713.png)
##### Req/Res
![1 2 1 post data](https://cloud.githubusercontent.com/assets/15889/16531794/f22e83fc-3f82-11e6-9cf1-815d19e8a4f1.png)


### 1.3.0 SQLite
##### 1.3.0 tries to push replicated document twice
![1 3 1 sqlite - dup push](https://cloud.githubusercontent.com/assets/15889/16531814/0991fb32-3f83-11e6-9069-de48591b287b.png)
 SQLite
##### 1st attempt Request header -> `Content-Type: multipart/form-data; ....`
![1 3 1 header 1st](https://cloud.githubusercontent.com/assets/15889/16531840/27c73964-3f83-11e6-9765-e9f57481aa24.png)
##### Req/Res
![1 3 1 req res 1st error](https://cloud.githubusercontent.com/assets/15889/16531855/4308f47e-3f83-11e6-8aca-ea444f21972f.png)
##### 2nd attempt Request header -> `Content-Type: application/json; ....`
![1 3 1 header 2nd](https://cloud.githubusercontent.com/assets/15889/16531872/5c4ca750-3f83-11e6-9194-a16c0265ebc4.png)
##### Req/Res
![1 3 1 req res 2nd ok](https://cloud.githubusercontent.com/assets/15889/16531876/64c2016e-3f83-11e6-869e-3ffe6b345e49.png)

**Comment by hideki** [comment]
Two issues:
1. Content-Type for multipart document is incorrect. It makes request with multi-part doc fails.
2. JSON fallback solution does not work with encrypted attachment. `private void uploadJsonRevision(final RevisionInternal rev)` in PusherInternal.java
