### ISSUE TITLE
Library not found: /native/linux/armv7l/libCouchbaseLiteJavaForestDB.so

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-java-core#1328]
Originally reported at forum.couchbase.com
https://forums.couchbase.com/t/android-library-not-found-native-linux-armv7l-libcouchbaselitejavaforestdb-so/9019
```
In my gradle script I have:
dependencies {
compile fileTree(dir: 'libs', include: ['*.jar'])
testCompile 'junit:junit:4.12'
compile 'com.android.support:appcompat-v7:23.4.0'
compile 'com.android.support:design:23.4.0'
//compile 'com.couchbase.lite:couchbase-lite-android:1.2.1'
//compile 'com.couchbase.lite:couchbase-lite-java-forestdb:1.2.1'
compile 'com.couchbase.lite:couchbase-lite-android:+'
compile 'com.couchbase.lite:couchbase-lite-java-forestdb:+'
compile 'com.android.support:support-v4:23.4.0'
compile 'com.android.support:recyclerview-v7:23.4.0'
}
[After setting Manager to use ForestDB on NEW db,] When deploying apk to a hardware device on Android 4.2, I get:
System.err: Library not found: /native/linux/armv7l/libCouchbaseLiteJavaForestDB.so
System.err: Error loading library: CouchbaseLiteJavaForestDB
System.err: java.lang.NullPointerException
System.err: at com.couchbase.lite.util.NativeLibUtils.loadLibrary(NativeLibUtils.java:44)
System.err: at com.couchbase.lite.store.ForestDBStore.<clinit>(ForestDBStore.java:69)
System.err: at java.lang.Class.classForName(Native Method)
System.err: at java.lang.Class.forName(Class.java:217)
System.err: at java.lang.Class.forName(Class.java:172)
System.err: at com.couchbase.lite.Database.createStoreInstance(Database.java:1049)
System.err: at com.couchbase.lite.Database.open(Database.java:1105)
System.err: at com.couchbase.lite.Manager.openDatabase(Manager.java:336)
System.err: at com.couchbase.lite.Manager.getDatabase(Manager.java:300)
...

Thanks,
nat

Reply

created
18h
last reply
14m1
reply
19
views
1
user

natgross14m
@hideki Any input on this issue, please?

Thanks
nat

Reply
BookmarkShareFlagInviteReply
NormalYou will be notified if someone mentions your @name or replies to you.
Suggested Topics
Topic	Category	Replies	Views	Activity
Document.getProperties() for POJO values 1	
Couchbase Lite
8	1.3k	17h
Image attachment does not work on couchbase lite 1.2.1 android 1	
Couchbase Lite
16	352	24d
Couchbase Lite attachments syncing 1	
Couchbase Lite
6	278	29d
Couchbase Lite using phonegap plugin 1	
Couchbase Lite
4	1.2k	May 4
Failed to compile Couchbase lite with Java on Windows 1	
Couchbase Lite
8	955	Jan 22
There are 87 unread and 6 new topics remaining, or browse other topics in 
Couchbase Lite
```

**Comment by hideki** [comment]
Hi @natgross,

it seems `armv7l` is `armeabi` device. Currently we could not compile ForestDB for `armeabi` and `mips`.
ForestDB storage is only available for `armeabi-v7a`, `x86`, `arm64-v8a`, `x86_64` and `mips64`.

To support old arm devices, please use SQLite storage.

Thanks!

**Comment by orenyodfat** [comment]
I am encounter same issue when adding my app as a system app at (/system/app/ folder).
Library not found: /native/linux/armv7l/libCouchbaseLiteJavaForestDB.so

If it is not a system app so all is ok.
