### ISSUE TITLE
Unknown StateMachine Error

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-java-core#1360]
CBL Version: 1.3.0-35
Device Nexus 5
Android OS: 5.1.1

App: ToDoLite-Android  branch: feature/simplified
```
07-18 13:51:07.649 11337-11423/com.couchbase.todolite E/Sync: Unknown Error in stateMachine.fire(trigger)
  java.lang.IllegalStateException: No valid leaving transitions are permitted from state 'INITIAL' for trigger 'STOP_GRACEFUL'. Consider ignoring the trigger.
      at com.github.oxo42.stateless4j.StateMachine$1.doIt(StateMachine.java:37)
      at com.github.oxo42.stateless4j.StateMachine.publicFire(StateMachine.java:188)
      at com.github.oxo42.stateless4j.StateMachine.fire(StateMachine.java:126)
      at com.couchbase.lite.replicator.ReplicationInternal$1.run(ReplicationInternal.java:237)
      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
      at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
      at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
      at java.lang.Thread.run(Thread.java:818)
07-18 13:51:07.650 11337-11424/com.couchbase.todolite E/Sync: Unknown Error in stateMachine.fire(trigger)
  java.lang.IllegalStateException: No valid leaving transitions are permitted from state 'INITIAL' for trigger 'STOP_GRACEFUL'. Consider ignoring the trigger.
      at com.github.oxo42.stateless4j.StateMachine$1.doIt(StateMachine.java:37)
      at com.github.oxo42.stateless4j.StateMachine.publicFire(StateMachine.java:188)
      at com.github.oxo42.stateless4j.StateMachine.fire(StateMachine.java:126)
      at com.couchbase.lite.replicator.ReplicationInternal$1.run(ReplicationInternal.java:237)
      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
      at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
      at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
      at java.lang.Thread.run(Thread.java:818)
07-18 13:51:07.650 11337-11424/com.couchbase.todolite D/Sync: firing trigger: START
```

**Comment by pasin** [comment]
I think I hit into this issue and it seems like it happens when calling replication.stop() before start(). I think the error shown in the log is false alarm. We should handle this case without showing the state errors.
