### ISSUE TITLE
Compaction not working

### ISSUE THREAD

**Issue by mikef-dk** [couchbase/couchbase-lite-java-core#1381]
I've been trying to compact my database which is kinda big (1,1 GB). Unfortunately this doesn't work. The compaction runs for about two minutes until the app crashes since there's no more storage left on my device. During the compaction the application data grew from 1,1GB to 2,25GB.

Following the LogCat output during the compaction and the Stacktrace:

```
08-09 18:52:04.049 27490-27496 W/art: Suspending all threads took: 5.263ms
08-09 18:52:04.391 27490-27607 V/RenderScript: 0x9db18000 Launching thread(s), CPUs 4
08-09 18:52:08.865 27490-27500 I/art: Background sticky concurrent mark sweep GC freed 72426(3MB) AllocSpace objects, 6(824KB) LOS objects, 12% free, 27MB/31MB, paused 2.155ms total 111.762ms
08-09 18:52:09.557 27490-27496 W/art: Suspending all threads took: 5.850ms
08-09 18:52:11.801 27490-27500 I/art: Background sticky concurrent mark sweep GC freed 106019(6MB) AllocSpace objects, 64(5MB) LOS objects, 26% free, 30MB/41MB, paused 5.840ms total 82.391ms
08-09 18:52:48.642 27490-27496 W/art: Suspending all threads took: 16.668ms
08-09 18:52:49.861 27490-27500 I/art: Background sticky concurrent mark sweep GC freed 70893(3MB) AllocSpace objects, 21(2MB) LOS objects, 13% free, 36MB/41MB, paused 1.965ms total 160.193ms
08-09 18:52:51.148 27490-27496 W/art: Suspending all threads took: 17.373ms
08-09 18:52:51.152 27490-27500 I/art: Background partial concurrent mark sweep GC freed 88989(4MB) AllocSpace objects, 28(4MB) LOS objects, 32% free, 33MB/49MB, paused 2.618ms total 168.807ms
08-09 18:52:51.714 27490-27496 W/art: Suspending all threads took: 81.650ms
08-09 18:53:10.637 27490-27600 W/database: SQLiteConnectionPool: The connection pool for database '/data/user/0/my.package.name/files/couchbase_database.cblite2/db.sqlite3' has been unable to grant a connection to thread 24437 (AsyncTask #1) with flags 0x1 for 30.072 seconds.
 Connections: 1 active, 0 idle, 0 available.

 Requests in progress:
   executeForChangedRowCount started 20495ms ago - running, sql="DELETE FROM revs WHERE doc_id=? AND revid < ? AND current=0"
08-09 18:53:13.174 27490-27677 W/database: SQLiteConnectionPool: The connection pool for database '/data/user/0/my.package.name/files/couchbase_database.cblite2/db.sqlite3' has been unable to grant a connection to thread 24458 (CBLRequestWorker-http://my.url.com:80/my_database-push-f8785-4) with flags 0x1 for 30.000002 seconds.
 Connections: 1 active, 0 idle, 0 available.

 Requests in progress:
   executeForChangedRowCount started 23195ms ago - running, sql="DELETE FROM revs WHERE doc_id=? AND revid < ? AND current=0"
08-09 18:53:17.187 27490-27496 W/art: Suspending all threads took: 11.410ms
08-09 18:53:18.713 27490-27564 W/database: SQLiteConnectionPool: The connection pool for database '/data/user/0/my.package.name/files/couchbase_database.cblite2/db.sqlite3' has been unable to grant a connection to thread 24420 (CBLManagerWorkExecutor) with flags 0x2 for 30.000002 seconds.
 Connections: 1 active, 0 idle, 0 available.

 Requests in progress:
   executeForChangedRowCount started 28733ms ago - running, sql="DELETE FROM revs WHERE doc_id=? AND revid < ? AND current=0"
08-09 18:53:19.573 27490-27666 W/database: SQLiteConnectionPool: The connection pool for database '/data/user/0/my.package.name/files/couchbase_database.cblite2/db.sqlite3' has been unable to grant a connection to thread 24455 (CBLRequestWorker-http://my.url.com:80/my_database-push-f8785-3) with flags 0x1 for 30.001001 seconds.
 Connections: 1 active, 0 idle, 0 available.

 Requests in progress:
   executeForChangedRowCount started 29593ms ago - running, sql="DELETE FROM revs WHERE doc_id=? AND revid < ? AND current=0"
08-09 18:53:40.698 27490-27600 W/database: SQLiteConnectionPool: The connection pool for database '/data/user/0/my.package.name/files/couchbase_database.cblite2/db.sqlite3' has been unable to grant a connection to thread 24437 (AsyncTask #1) with flags 0x1 for 60.408005 seconds.
 Connections: 1 active, 0 idle, 0 available.

 Requests in progress:
   executeForChangedRowCount started 50710ms ago - running, sql="DELETE FROM revs WHERE doc_id=? AND revid < ? AND current=0"
08-09 18:53:43.175 27490-27677 W/database: SQLiteConnectionPool: The connection pool for database '/data/user/0/my.package.name/files/couchbase_database.cblite2/db.sqlite3' has been unable to grant a connection to thread 24458 (CBLRequestWorker-http://my.url.com:80/my_database-push-f8785-4) with flags 0x1 for 60.001003 seconds.
 Connections: 1 active, 0 idle, 0 available.

```

Stacktrace:

```
08-09 18:55:14.483 27490-27490 E/Database: main Error calling endTransaction()
com.couchbase.lite.storage.SQLException: com.couchbase.lite.internal.database.sqlite.exception.SQLiteException: no such savepoint: cbl_1 (code 1)
   at com.couchbase.lite.storage.SQLiteStorageEngineBase.execSQL(SQLiteStorageEngineBase.java:157)
   at com.couchbase.lite.store.SQLiteStore.endTransaction(SQLiteStore.java:2156)
   at [Some class - stripped]
08-09 18:55:14.483 27490-27490 E/SQLiteLog: (1) statement aborts at 2: [ROLLBACK;] cannot rollback - no transaction is active
08-09 18:55:14.486 27490-27490 D/AndroidRuntime: Shutting down VM
08-09 18:55:15.317 27490-27500 I/art: Background sticky concurrent mark sweep GC freed 131063(7MB) AllocSpace objects, 44(6MB) LOS objects, 27% free, 36MB/49MB, paused 5.834ms total 145.756ms
08-09 18:55:17.554 27490-27500 I/art: Background partial concurrent mark sweep GC freed 180382(9MB) AllocSpace objects, 19(2MB) LOS objects, 29% free, 38MB/54MB, paused 2.067ms total 122.946ms
08-09 18:55:18.569 27490-27490 W/GAv4: syncDispatchLocalHits timed out: java.util.concurrent.TimeoutException
08-09 18:55:19.001 27490-27496 W/art: Suspending all threads took: 122.485ms
08-09 18:55:19.008 27490-27529 W/SharedPreferencesImpl: writeToFile: Got exception:
            java.io.IOException: write failed: ENOSPC (No space left on device)
                at libcore.io.IoBridge.write(IoBridge.java:498)
                at java.io.FileOutputStream.write(FileOutputStream.java:186)
                at com.android.internal.util.FastXmlSerializer.flushBytes(FastXmlSerializer.java:232)
                at com.android.internal.util.FastXmlSerializer.flush(FastXmlSerializer.java:253)
                at com.android.internal.util.FastXmlSerializer.endDocument(FastXmlSerializer.java:198)
                at com.android.internal.util.XmlUtils.writeMapXml(XmlUtils.java:193)
                at android.app.SharedPreferencesImpl.writeToFile(SharedPreferencesImpl.java:600)
                at android.app.SharedPreferencesImpl.-wrap2(SharedPreferencesImpl.java)
                at android.app.SharedPreferencesImpl$2.run(SharedPreferencesImpl.java:515)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                at java.lang.Thread.run(Thread.java:818)
             Caused by: android.system.ErrnoException: write failed: ENOSPC (No space left on device)
                at libcore.io.Posix.writeBytes(Native Method)
                at libcore.io.Posix.write(Posix.java:271)
                at libcore.io.BlockGuardOs.write(BlockGuardOs.java:313)
                at libcore.io.IoBridge.write(IoBridge.java:493)
                at java.io.FileOutputStream.write(FileOutputStream.java:186) 
                at com.android.internal.util.FastXmlSerializer.flushBytes(FastXmlSerializer.java:232) 
                at com.android.internal.util.FastXmlSerializer.flush(FastXmlSerializer.java:253) 
                at com.android.internal.util.FastXmlSerializer.endDocument(FastXmlSerializer.java:198) 
                at com.android.internal.util.XmlUtils.writeMapXml(XmlUtils.java:193) 
                at android.app.SharedPreferencesImpl.writeToFile(SharedPreferencesImpl.java:600) 
                at android.app.SharedPreferencesImpl.-wrap2(SharedPreferencesImpl.java) 
                at android.app.SharedPreferencesImpl$2.run(SharedPreferencesImpl.java:515) 
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                at java.lang.Thread.run(Thread.java:818) 
08-09 18:55:19.353 27490-27540 E/Fabric: An error occurred in the fatal exception logger
java.io.IOException: write failed: ENOSPC (No space left on device)
 at libcore.io.IoBridge.write(IoBridge.java:498)
 at java.io.FileOutputStream.write(FileOutputStream.java:186)
 at com.b.a.c.f.c(CodedOutputStream.java:668)
 at com.b.a.c.f.a(CodedOutputStream.java:794)
 at com.b.a.c.f.c(CodedOutputStream.java:740)
 at com.b.a.c.f.a(CodedOutputStream.java:325)
 at com.b.a.c.f.a(CodedOutputStream.java:204)
 at com.b.a.c.aa.a(SessionDataWriter.java:342)
 at com.b.a.c.aa.a(SessionDataWriter.java:321)
 at com.b.a.c.aa.a(SessionDataWriter.java:241)
 at com.b.a.c.aa.a(SessionDataWriter.java:213)
 at com.b.a.c.aa.a(SessionDataWriter.java:201)
 at java.util.concurrent.FutureTask.run(FutureTask.java:237)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
 at a.a.a.a.a.b.n$1$1.a(ExecutorUtils.java:75)
 at a.a.a.a.a.b.h.run(BackgroundPriorityRunnable.java:30)
 at java.lang.Thread.run(Thread.java:818)
Caused by: android.system.ErrnoException: write failed: ENOSPC (No space left on device)
 at libcore.io.Posix.writeBytes(Native Method)
 at libcore.io.Posix.write(Posix.java:271)
 at libcore.io.BlockGuardOs.write(BlockGuardOs.java:313)
 at libcore.io.IoBridge.write(IoBridge.java:493)
 at java.io.FileOutputStream.write(FileOutputStream.java:186) 
 at com.b.a.c.f.c(CodedOutputStream.java:668) 
 at com.b.a.c.f.a(CodedOutputStream.java:794) 
 at com.b.a.c.f.c(CodedOutputStream.java:740) 
 at com.b.a.c.f.a(CodedOutputStream.java:325) 
 at com.b.a.c.f.a(CodedOutputStream.java:204) 
 at com.b.a.c.aa.a(SessionDataWriter.java:342) 
 at com.b.a.c.aa.a(SessionDataWriter.java:321) 
 at com.b.a.c.aa.a(SessionDataWriter.java:241) 
 at com.b.a.c.aa.a(SessionDataWriter.java:213) 
 at com.b.a.c.aa.a(SessionDataWriter.java:201) 
 at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
 at a.a.a.a.a.b.n$1$1.a(ExecutorUtils.java:75) 
 at a.a.a.a.a.b.h.run(BackgroundPriorityRunnable.java:30) 
 at java.lang.Thread.run(Thread.java:818) 
08-09 18:55:19.371 27490-27540 E/Fabric: Failed to flush to session begin file.
java.io.IOException: write failed: ENOSPC (No space left on device)
 at libcore.io.IoBridge.write(IoBridge.java:498)
 at java.io.FileOutputStream.write(FileOutputStream.java:186)
 at com.b.a.c.f.c(CodedOutputStream.java:668)
 at com.b.a.c.f.flush(CodedOutputStream.java:678)
 at a.a.a.a.a.b.i.a(CommonUtils.java:768)
 at java.util.concurrent.FutureTask.run(FutureTask.java:237)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
 at a.a.a.a.a.b.n$1$1.a(ExecutorUtils.java:75)
 at a.a.a.a.a.b.h.run(BackgroundPriorityRunnable.java:30)
 at java.lang.Thread.run(Thread.java:818)
Caused by: android.system.ErrnoException: write failed: ENOSPC (No space left on device)
 at libcore.io.Posix.writeBytes(Native Method)
 at libcore.io.Posix.write(Posix.java:271)
 at libcore.io.BlockGuardOs.write(BlockGuardOs.java:313)
 at libcore.io.IoBridge.write(IoBridge.java:493)
 at java.io.FileOutputStream.write(FileOutputStream.java:186) 
 at com.b.a.c.f.c(CodedOutputStream.java:668) 
 at com.b.a.c.f.flush(CodedOutputStream.java:678) 
 at a.a.a.a.a.b.i.a(CommonUtils.java:768) 
 at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
 at a.a.a.a.a.b.n$1$1.a(ExecutorUtils.java:75) 
 at a.a.a.a.a.b.h.run(BackgroundPriorityRunnable.java:30) 
 at java.lang.Thread.run(Thread.java:818) 
08-09 18:55:19.398 27490-27540 E/Fabric: Error flushing session file stream
java.io.IOException: write failed: ENOSPC (No space left on device)
 at libcore.io.IoBridge.write(IoBridge.java:498)
 at java.io.FileOutputStream.write(FileOutputStream.java:186)
 at com.b.a.c.f.c(CodedOutputStream.java:668)
 at com.b.a.c.f.flush(CodedOutputStream.java:678)
 at a.a.a.a.a.b.i.a(CommonUtils.java:768)
 at java.util.concurrent.FutureTask.run(FutureTask.java:237)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
 at a.a.a.a.a.b.n$1$1.a(ExecutorUtils.java:75)
 at a.a.a.a.a.b.h.run(BackgroundPriorityRunnable.java:30)
 at java.lang.Thread.run(Thread.java:818)
Caused by: android.system.ErrnoException: write failed: ENOSPC (No space left on device)
 at libcore.io.Posix.writeBytes(Native Method)
 at libcore.io.Posix.write(Posix.java:271)
 at libcore.io.BlockGuardOs.write(BlockGuardOs.java:313)
 at libcore.io.IoBridge.write(IoBridge.java:493)
 at java.io.FileOutputStream.write(FileOutputStream.java:186) 
 at com.b.a.c.f.c(CodedOutputStream.java:668) 
 at com.b.a.c.f.flush(CodedOutputStream.java:678) 
 at a.a.a.a.a.b.i.a(CommonUtils.java:768) 
 at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
 at a.a.a.a.a.b.n$1$1.a(ExecutorUtils.java:75) 
 at a.a.a.a.a.b.h.run(BackgroundPriorityRunnable.java:30) 
 at java.lang.Thread.run(Thread.java:818) 
08-09 18:55:19.455 27490-27490 E/AndroidRuntime: FATAL EXCEPTION: main
     Process: my.package.name, PID: 27490
     com.couchbase.lite.internal.database.sqlite.exception.SQLiteException: cannot rollback - no transaction is active (code 1)
         at com.couchbase.lite.internal.database.sqlite.SQLiteConnection.nativeExecute(Native Method)
         at com.couchbase.lite.internal.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:481)
         at com.couchbase.lite.internal.database.sqlite.SQLiteSession.endTransactionUnchecked(SQLiteSession.java:446)
         at com.couchbase.lite.internal.database.sqlite.SQLiteSession.endTransaction(SQLiteSession.java:408)
         at com.couchbase.lite.internal.database.sqlite.SQLiteDatabase.endTransaction(SQLiteDatabase.java:515)
         at com.couchbase.lite.storage.SQLiteStorageEngineBase.endTransaction(SQLiteStorageEngineBase.java:144)
         at com.couchbase.lite.store.SQLiteStore.endTransaction(SQLiteStore.java:2142)
         at com.couchbase.lite.store.SQLiteStore.compact(SQLiteStore.java:655)
         at com.couchbase.lite.Database.compact(Database.java:248)
         at [Some class]
08-09 18:55:19.694 27490-27490 I/Process: Sending signal. PID: 27490 SIG: 9
```

**Notes:**
- StorageEngine is set to SQLite.
- This issue is a follow-up of [this forum post](https://forums.couchbase.com/t/huge-local-storage-usage-because-of-cblite/9347)

**Comment by pasin** [comment]
What CBL version are you using?

**Comment by mikef-dk** [comment]
Sorry that I didn't mention it
1.2.1

**Comment by pasin** [comment]
FYI, in 1.3, we implement auto pruning to the SQLite storage and that should help the issue as the compaction will have less work.

**Comment by mikef-dk** [comment]
Didn't realize that 1.3 was out already. Just tested it and it did work indeed. However I'd say it's been close to crashing again since I got the notification reminding me that I'm short on storage.
Furthermore it did run for nearly seven minutes. So two question 

a) What takes so long
b) Why is even more data written to the storage before something is deleted?

**Comment by hideki** [comment]
Hi @mikef-dk,

CBL Android/Java uses SQLite as data storage. And, to compact database, CBL uses SQLite's `VACUUM` command. `VACUUM` commands requires twice the size of original database file. Please read following from SQLite web site.

>The VACUUM command works by copying the contents of the database into a temporary database file and then overwriting the original with the contents of the temporary file. When overwriting the original, a rollback journal or write-ahead log WAL file is used just as it would be for any other database transaction. This means that when VACUUMing a database, as much as twice the size of the original database file is required in free disk space.

https://sqlite.org/lang_vacuum.html

a) What takes so long

I don't know the implementation of SQLite `VACUUM` command. Recreating 1GB database could take time.

b) Why is even more data written to the storage before something is deleted?

see above

Thanks!
Hideki

**Comment by bpolanec** [comment]
Hi we had the same issue on version 1.3.1

Configuration for reproduction:
- maxRevTreeDepth : 1
- in database revs: 197000
- in database docs: 98000
- size od databae: 150MB

stack:
`[ 12-02 10:06:24.899  5403: 7035 V/Database ]
    pruned 1 revs with gen<2 from ?`
`[ 12-02 10:06:27.409  5403: 7035 V/Database ]
Thread-32512 CANCEL transaction (level 1)`
`[ 12-02 10:06:27.419  5403: 7035 E/Database ]
Thread-32512 Error calling endTransaction()
com.couchbase.lite.storage.SQLException: com.couchbase.lite.internal.database.sqlite.exception.SQLiteException: no such savepoint: cbl_1 (code 1)
 at com.couchbase.lite.storage.SQLiteStorageEngineBase.execSQL(SQLiteStorageEngineBase.java:168)
 at com.couchbase.lite.store.SQLiteStore.endTransaction(SQLiteStore.java:2377)
 at com.couchbase.lite.store.SQLiteStore.pruneRevsToMaxDepth(SQLiteStore.java:2477)
 at com.couchbase.lite.store.SQLiteStore.compact(SQLiteStore.java:669)
 at com.couchbase.lite.Database.compact(Database.java:269)
 at java.lang.Thread.run(Thread.java:818)
Caused by: com.couchbase.lite.internal.database.sqlite.exception.SQLiteException: no such savepoint: cbl_1 (code 1)
 at com.couchbase.lite.internal.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
 at com.couchbase.lite.internal.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:617)
 at com.couchbase.lite.internal.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:725)
 at com.couchbase.lite.internal.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:67)
 at com.couchbase.lite.internal.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1660)
 at com.couchbase.lite.internal.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1589)
 at com.couchbase.lite.storage.SQLiteStorageEngineBase.execSQL(SQLiteStorageEngineBase.java:166)
 ... 6 more`

`[ 12-02 10:06:27.419  5403: 7035 V/Database ]
Thread-32512 CANCEL transaction (level 0)
[ 12-02 10:06:27.439  5403: 7035 E/CustomExceptionHandler ]
com.couchbase.lite.internal.database.sqlite.exception.SQLiteException: cannot rollback - no transaction is active (code 1)
 at com.couchbase.lite.internal.database.sqlite.SQLiteConnection.nativeExecute(Native Method)
 at com.couchbase.lite.internal.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:486)
 at com.couchbase.lite.internal.database.sqlite.SQLiteSession.endTransactionUnchecked(SQLiteSession.java:446)
 at com.couchbase.lite.internal.database.sqlite.SQLiteSession.endTransaction(SQLiteSession.java:408)
 at com.couchbase.lite.internal.database.sqlite.SQLiteDatabase.endTransaction(SQLiteDatabase.java:516)
 at com.couchbase.lite.storage.SQLiteStorageEngineBase.endTransaction(SQLiteStorageEngineBase.java:155)
 at com.couchbase.lite.store.SQLiteStore.endTransaction(SQLiteStore.java:2363)
 at com.couchbase.lite.store.SQLiteStore.compact(SQLiteStore.java:688)
 at com.couchbase.lite.Database.compact(Database.java:269)
 at java.lang.Thread.run(Thread.java:818)`

**Comment by hideki** [comment]
Hi @bpolanec,

Can you reproduce this issue by yourself? If yes, can you provide more detailed information. Android version, Free Disk space, etc.

**Comment by hideki** [comment]
Note to Self:

I wonder if `toPrune` variable has too many keys and transaction could not handle all of them at once? 

```java
        // Now prune:
        int outPruned = 0;
        boolean shouldCommit = false;
        try {
            beginTransaction();
            for (Long docNumericID : toPrune.keySet())
                outPruned += pruneDocument("?", docNumericID, toPrune.get(docNumericID).intValue() + 1);
            shouldCommit = true;
        } catch (Throwable e) {
            throw new CouchbaseLiteException(e, Status.INTERNAL_SERVER_ERROR);
        } finally {
            endTransaction(shouldCommit);
        }
```
https://github.com/couchbase/couchbase-lite-java-core/blob/release/1.3.1/src/main/java/com/couchbase/lite/store/SQLiteStore.java#L2466-L2479

**Comment by bpolanec** [comment]
Yes, we had this issue on couple devices:
- Samsung S7 Edge - Android 6.01,  7GB free internal memory before executing compaction. Crashed 2 from 6 tries.
- Samsung Note3 - Android 5.0,  11GB free internal memory before executing compaction. Crashing always.
- Samsung Galaxy J5 - Android 6, 500MB free internal memory before executing compaction. Crashing always.

No other errors happen.

All devices used same set of data to execute compaction.
Let me know if you need any additional information.
