### ISSUE TITLE
CBLReplicatorExecutor still exists after stopping the replicator

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-java-core#1385]
Steps:
1. Create continuous push and pull replicators from REST API POST _replicate.
2. Start the replicators.
3. Observe the thread dump.
4. Stop the replicators.
5. Observe the thread dump.

I believe the native API has the same issue.

Thread dump after stop both push and pull replicators:
```
Full thread dump

"Acme.Utils.ThreadPool(0)-PooledThread: Acme.Serve.Serve$ServeConnection@b2d72b9@4333" daemon prio=5 runnable
  java.lang.Thread.State: RUNNABLE
	  at libcore.io.Posix.recvfromBytes(Posix.java:-1)
	  at libcore.io.Posix.recvfrom(Posix.java:189)
	  at libcore.io.BlockGuardOs.recvfrom(BlockGuardOs.java:250)
	  at libcore.io.IoBridge.recvfrom(IoBridge.java:549)
	  at java.net.PlainSocketImpl.read(PlainSocketImpl.java:481)
	  at java.net.PlainSocketImpl.-wrap0(PlainSocketImpl.java:-1)
	  at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)
	  at java.io.InputStream.read(InputStream.java:162)
	  at java.io.BufferedInputStream.fillbuf(BufferedInputStream.java:149)
	  at java.io.BufferedInputStream.read(BufferedInputStream.java:295)
	  - locked <0x1322> (a java.io.BufferedInputStream)
	  at Acme.Serve.Serve$ServeInputStream.read(Serve.java:4290)
	  - locked <0x1323> (a Acme.Serve.Serve$ServeInputStream)
	  at Acme.Serve.Serve$ServeInputStream.read(Serve.java:4253)
	  at javax.servlet.ServletInputStream.readLine(ServletInputStream.java:93)
	  at Acme.Serve.Serve$ServeConnection.parseRequest(Serve.java:2041)
	  at Acme.Serve.Serve$ServeConnection.run(Serve.java:1988)
	  at Acme.Utils$ThreadPool$PooledThread.run(Utils.java:1223)
	  - locked <0x1102> (a Acme.Utils$ThreadPool$PooledThread)
	  at java.lang.Thread.run(Thread.java:818)

"CBLReplicationExecutor-http://10.17.2.133:4984/db-push-8ead3@4613" prio=5 waiting
  java.lang.Thread.State: WAITING
	 blocks CBLReplicationExecutor-http://10.17.2.133:4984/db-push-8ead3@4613
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.Thread.parkFor$(Thread.java:1220)
	  - locked <0x1305> (a java.lang.Object)
	  at sun.misc.Unsafe.park(Unsafe.java:299)
	  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:158)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2013)
	  at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1078)
	  at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1071)
	  at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1038)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1098)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	  at java.lang.Thread.run(Thread.java:818)

"CBLReplicationExecutor-http://10.17.2.133:4984/db-pull-5f200@4823" prio=5 waiting
  java.lang.Thread.State: WAITING
	 blocks CBLReplicationExecutor-http://10.17.2.133:4984/db-pull-5f200@4823
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.Thread.parkFor$(Thread.java:1220)
	  - locked <0x130d> (a java.lang.Object)
	  at sun.misc.Unsafe.park(Unsafe.java:299)
	  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:158)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2013)
	  at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1078)
	  at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1071)
	  at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1038)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1098)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	  at java.lang.Thread.run(Thread.java:818)

"Thread-2855@4318" prio=5 runnable
  java.lang.Thread.State: RUNNABLE
	  at libcore.io.Posix.accept(Posix.java:-1)
	  at libcore.io.BlockGuardOs.accept(BlockGuardOs.java:63)
	  at java.net.PlainSocketImpl.accept(PlainSocketImpl.java:89)
	  at java.net.ServerSocket.implAccept(ServerSocket.java:217)
	  - locked <0x1300> (a java.net.ServerSocket)
	  at java.net.ServerSocket.accept(ServerSocket.java:141)
	  at Acme.Serve.SimpleAcceptor.accept(SimpleAcceptor.java:40)
	  at Acme.Serve.Serve.serve(Serve.java:809)
	  at com.couchbase.lite.listener.LiteServer.serve(LiteServer.java:63)
	  at com.couchbase.lite.listener.LiteListener.run(LiteListener.java:90)
	  at java.lang.Thread.run(Thread.java:818)

"FinalizerDaemon@4854" daemon prio=5 waiting
  java.lang.Thread.State: WAITING
	 blocks FinalizerDaemon@4854
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.Object.wait(Object.java:423)
	  at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:101)
	  - locked <0x12fe> (a java.lang.ref.ReferenceQueue)
	  at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:72)
	  at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:185)
	  at java.lang.Thread.run(Thread.java:818)

"main@4851" prio=5 runnable
  java.lang.Thread.State: RUNNABLE
	  at android.os.MessageQueue.nativePollOnce(MessageQueue.java:-1)
	  at android.os.MessageQueue.next(MessageQueue.java:323)
	  at android.os.Looper.loop(Looper.java:135)
	  at android.app.ActivityThread.main(ActivityThread.java:5417)
	  at java.lang.reflect.Method.invoke(Method.java:-1)
	  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

"OkHttp ConnectionPool@4712" daemon prio=5 waiting
  java.lang.Thread.State: WAITING
	 blocks OkHttp ConnectionPool@4712
	  at java.lang.Object.wait(Object.java:-1)
	  at okhttp3.ConnectionPool$1.run(ConnectionPool.java:66)
	  - locked <0x1307> (a okhttp3.ConnectionPool)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	  at java.lang.Thread.run(Thread.java:818)

"OkHttp ConnectionPool@4827" daemon prio=5 waiting
  java.lang.Thread.State: WAITING
	 blocks OkHttp ConnectionPool@4827
	  at java.lang.Object.wait(Object.java:-1)
	  at okhttp3.ConnectionPool$1.run(ConnectionPool.java:66)
	  - locked <0x130f> (a okhttp3.ConnectionPool)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	  at java.lang.Thread.run(Thread.java:818)
```

**Comment by pasin** [comment]
It seems like the executor will be destroyed when the ReplicationInternal is finalized. At least from the REST POST /_replicate, it seems like the ReplicationInternal doesn't get finalized and the new one get created every time that the replicator is started from /_replicate request.

**Comment by hideki** [comment]
After start:
https://gist.github.com/hideki/fb77776791b7cb99ceda5f0d22ece129
After stop:
https://gist.github.com/hideki/d2083f3c6c73f70d0cd48eb78c607034

**Comment by DavidAudrain** [comment]
@pasin In Release 1.3.1, ReplicationInternal.finalize will never been invoked as ReplicationInternal.initializeReplicationExecutor sets up a ThreadFactory that references current ReplicationInternal instance.
As a consequence ReplicationInternal can not be garbage collected and underlying ScheduledExecutor/Thread is not collected.

@hideki A possible would be introducing a private static implementation of ThreadFactory that weak references ReplicationInternal instance.

**Comment by mvysny** [comment]
I would suggest the usual way: make `ReplicationInternal` closable, by introducing `close()` or `shutdown()` method. The method would `stop()` the replication and then shutdown the executor, waiting endlessly for any tasks to finish. After `shutdown()` that instance `ReplicationInternal` could no longer be used, started nor stopped; basically, any method would simply fail with `throw new IllegalStateException("closed")`.

Note that I fail to see how `ReplicationInternal` is thread-safe: executor is not final nor volatile and is not guarded by any synchronization/lock. Once the executor is made final, you can employ the following code to make close() thread-safe:

```java
private final AtomicBoolean closed = new AtomicBoolean(false);
public void shutdown() {
if (closed.compareAndSet(false, true)) {
  stop();
  executor.shutdown();
  executor.awaitTermination(20, TimeUnit.SECOND);
}
}
```

Now, in your code, it is enough to call `pullReplicator.shutdown()` and `pushReplicator.shutdown()`.

Waiting for GC is fragile as one can't really force GC: `System.gc()` is not guaranteed to sweep all objects. Therefore, currently the only way to stop the app is `System.exit(0)` which is not very nice.

**Comment by DavidAudrain** [comment]
@mvysny In my use case the Replication is not continuous. It is started on purpose.

When `Replication.start` is invoked and the current `replicationInternal` state is stopped, `Replication.initReplicationInternal` is called. This is where the leak comes from since the current `replicationInternal` is not reused.

Your suggestion could be used in this specific situation, `ReplicationInternal.shutdown()` could be called before invoking `Replication.initReplicationInternal`. However `Replication.start` will have to wait `ReplicationInternal.shutdown()` execution.

**Comment by hideki** [comment]
Hi @DavidAudrain 

One-shot replicator memory leak issue is tracked by #290
