### ISSUE TITLE
MultiThreadsTest.testParallelViewQueriesWithPrefix() fails with forestdb

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-java-core#1424]
```
09-01 16:30:06.111 3120-3166/com.couchbase.lite.test E/CBForest: Assertion failed: !_inTransaction (/Users/hideki/github/couchbase-lite-android/libraries/couchbase-lite-java-forestdb/jni/../vendor/cbforest/CBForest/Database.cc:281, in void cbforest::Database::beginTransaction(cbforest::Transaction *))
09-01 16:30:06.111 3120-3166/com.couchbase.lite.test W/System.err: com.couchbase.lite.CouchbaseLiteException, Status: 590 (HTTP 500 Database error!)
09-01 16:30:06.111 3120-3166/com.couchbase.lite.test W/System.err:     at com.couchbase.lite.store.ForestDBViewStore.updateIndexes(ForestDBViewStore.java:321)
09-01 16:30:06.111 3120-3166/com.couchbase.lite.test W/System.err:     at com.couchbase.lite.View.updateIndexes(View.java:321)
09-01 16:30:06.111 3120-3166/com.couchbase.lite.test W/System.err:     at com.couchbase.lite.View.updateIndex(View.java:294)
09-01 16:30:06.111 3120-3166/com.couchbase.lite.test W/System.err:     at com.couchbase.lite.Database.queryViewNamed(Database.java:2178)
09-01 16:30:06.111 3120-3166/com.couchbase.lite.test W/System.err:     at com.couchbase.lite.Query.run(Query.java:446)
09-01 16:30:06.111 3120-3166/com.couchbase.lite.test W/System.err:     at com.couchbase.lite.multithreads.MultiThreadsTest.queryAction2(MultiThreadsTest.java:383)
09-01 16:30:06.111 3120-3166/com.couchbase.lite.test W/System.err:     at com.couchbase.lite.multithreads.MultiThreadsTest.access$600(MultiThreadsTest.java:39)
09-01 16:30:06.111 3120-3166/com.couchbase.lite.test W/System.err:     at com.couchbase.lite.multithreads.MultiThreadsTest$11.run(MultiThreadsTest.java:338)
09-01 16:30:06.111 3120-3166/com.couchbase.lite.test W/System.err:     at java.lang.Thread.run(Thread.java:841)
09-01 16:30:06.111 3120-3166/com.couchbase.lite.test W/dalvikvm: threadid=15: thread exiting with uncaught exception (group=0xa4cf7b20)
09-01 16:30:06.115 3120-3166/com.couchbase.lite.test E/AndroidRuntime: FATAL EXCEPTION: Thread-170
   Process: com.couchbase.lite.test, PID: 3120
   junit.framework.AssertionFailedError
       at junit.framework.Assert.fail(Assert.java:48)
       at com.couchbase.lite.multithreads.MultiThreadsTest$11.run(MultiThreadsTest.java:343)
       at java.lang.Thread.run(Thread.java:841)
09-01 16:30:06.115 559-751/system_process W/ActivityManager: Error in app com.couchbase.lite.test running instrumentation ComponentInfo{com.couchbase.lite.test/android.test.InstrumentationTestRunner}:
09-01 16:30:06.115 559-751/system_process W/ActivityManager:   junit.framework.AssertionFailedError
09-01 16:30:06.119 559-3169/system_process D/dalvikvm: GC_FOR_ALLOC freed 725K, 17% free 5782K/6908K, paused 5ms, total 5ms
09-01 16:30:06.119 3110-3110/? D/AndroidRuntime: Shutting down VM
09-01 16:30:06.119 559-751/system_process W/ActivityManager:   junit.framework.AssertionFailedError
09-01 16:30:06.123 3110-3116/? D/jdwp: Got wake-up signal, bailing out of select
```

**Comment by vbenso** [comment]
@hideki 
I've created another test that instead of using Threads uses Transactional tasks.
in this case, the error goes away.

```
/**
     * Adapted from testParallelViewQueries
     */
    public void testParallelViewQueriesWithTransactionalTasks() throws CouchbaseLiteException, IOException, InterruptedException {
        startCBLite();
        database = startDatabase();

        int[] data = new int[]{42, 184, 256, Integer.MAX_VALUE, 412};
        View vu = database.getView("prefix/vu");
        vu.setMap(new Mapper() {
            @Override
            public void map(Map<String, Object> document, Emitter emitter) {
                Map<String, Object> key = new HashMap<String, Object>();
                key.put("sequence", document.get("sequence"));
                emitter.emit(key, null);
            }
        }, "1.0");

        View vu2 = database.getView("prefix/vu2");
        vu2.setMap(new Mapper() {
            @Override
            public void map(Map<String, Object> document, Emitter emitter) {
                Map<String, Object> key = new HashMap<String, Object>();
                key.put("sequence", "FAKE");
                emitter.emit(key, null);
            }
        }, "1.0");

        //Log.w(TAG, "Testing with transactional tasks");
        createDocuments(database, 500);

        int expectCount = 1;
        parallelQueryTransaction(database, data, expectCount);

        createDocuments(database, 500);

        expectCount = 2;
        parallelQueryTransaction(database, data, expectCount);

        vu.delete();

        vu = database.getView("prefix/vu");
        vu.setMap(new Mapper() {
            @Override
            public void map(Map<String, Object> document, Emitter emitter) {
                Map<String, Object> key = new HashMap<String, Object>();
                key.put("sequence", document.get("sequence"));
                emitter.emit(key, null);
            }
        }, "1.0");

        Log.w(TAG, "Testing with Threads");
        expectCount = 2;
        parallelQueryTransaction(database, data, expectCount);

        vu2.delete();

        vu2 = database.getView("prefix/vu2");
        vu2.setMap(new Mapper() {
            @Override
            public void map(Map<String, Object> document, Emitter emitter) {
                Map<String, Object> key = new HashMap<String, Object>();
                key.put("sequence", "FAKE");
                emitter.emit(key, null);
            }
        }, "1.0");

        expectCount = 2;
        parallelQueryTransaction(database, data, expectCount);
    }

    private void parallelQueryTransaction(Database db, int[] numbers, final int expectCount) {
        TransactionalTask[] tts = new TransactionalTask[numbers.length];
        for (int i = 0; i < numbers.length; i++) {
            final int num = numbers[i];
            tts[i] = new TransactionalTask() {
                @Override
                public boolean run() {
                    try {
                        if (num == Integer.MAX_VALUE)
                            queryAction2(expectCount);
                        else
                            queryAction(num, expectCount);
                    } catch (CouchbaseLiteException e) {
                        e.printStackTrace();
                        fail(e.getMessage());
                    }
                    return false;
                }
            };
        }
        for (int i = 0; i < numbers.length; i++) {
            db.runInTransaction(tts[i]);
        }
    }
```

**Comment by hideki** [comment]
@vbenso,
With following codes, tasks are executed sequencially. That is reason that test does not fail.
```java
for (int i = 0; i < numbers.length; i++) {
            db.runInTransaction(tts[i]);
        }
```

**Comment by vbenso** [comment]
@hideki 
My bad :unamused: , 
Sorry for wasting our times. 
:disappointed:

**Comment by hideki** [comment]
Note to Self:
`testParallelViewQueriesWithPrefix()` test crashes, however `testParallelViewQueries()` does not.
Difference is indexing multiple views at once or not.

**Comment by hideki** [comment]
Note to Self:

By adding Android `__android_log_assert()`
```c++
    void Database::beginTransaction(Transaction* t) {
        LOG_ASSERT(!_inTransaction, "_inTransaction != NULL");
        CBFAssert(!_inTransaction);
        if (!isOpen())
            error::_throw(FDB_RESULT_INVALID_HANDLE);
```

crash log
```
09-19 16:51:42.360 6512-6536/com.couchbase.lite.test A/CBForest: _inTransaction != NULL
09-19 16:51:42.360 6512-6536/com.couchbase.lite.test A/libc: Fatal signal 4 (SIGILL) at 0xb7726c0d (code=2), thread 6536 (Thread-186)
09-19 16:51:42.416 6512-6533/com.couchbase.lite.test V/View: ... Finished re-indexing (prefix/vu, prefix/vuFake)
09-19 16:51:42.464 173-173/? I/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
09-19 16:51:42.464 173-173/? I/DEBUG: Build fingerprint: 'generic/vbox86p/vbox86p:4.4.4/KTU84P/eng.genymotion.20160825.201657:userdebug/test-keys'
09-19 16:51:42.464 173-173/? I/DEBUG: Revision: '0'
09-19 16:51:42.464 173-173/? I/DEBUG: pid: 6512, tid: 6536, name: Thread-186  >>> com.couchbase.lite.test <<<
09-19 16:51:42.464 173-173/? I/DEBUG: signal 4 (SIGILL), code 2 (ILL_ILLOPN), fault addr b7726c0d
09-19 16:51:42.832 173-173/? I/DEBUG:     eax 00000021  ebx b772bf60  ecx 079264d3  edx 079264d3
09-19 16:51:42.832 173-173/? I/DEBUG:     esi 94814c60  edi b95be7e8
09-19 16:51:42.832 173-173/? I/DEBUG:     xcs 00000073  xds 0000007b  xes 0000007b  xfs 00000000  xss 0000007b
09-19 16:51:42.832 173-173/? I/DEBUG:     eip b7726c0d  ebp 93a014ac  esp 93a01480  flags 00010246
09-19 16:51:42.832 173-173/? E/Corkscrew: unrecognized dwarf higher part encoding: 0xbb
09-19 16:51:42.832 173-173/? I/DEBUG: backtrace:
09-19 16:51:42.832 173-173/? I/DEBUG:     #00  pc 00001c0d  /system/lib/liblog.so (__android_log_assert+125)
09-19 16:51:42.832 173-173/? I/DEBUG:     #01  pc 000c14fc  /data/app-lib/com.couchbase.lite.test-1/libCouchbaseLiteJavaForestDB.so (cbforest::Database::beginTransaction(cbforest::Transaction*)+364)
09-19 16:51:42.832 173-173/? I/DEBUG: stack:
09-19 16:51:42.832 173-173/? I/DEBUG:          93a01440  00000000  
09-19 16:51:42.832 173-173/? I/DEBUG:          93a01444  00000000  
09-19 16:51:42.832 173-173/? I/DEBUG:          93a01448  00000000  
09-19 16:51:42.832 173-173/? I/DEBUG:          93a0144c  93a0140c  [stack:6536]
09-19 16:51:42.832 173-173/? I/DEBUG:          93a01450  00000000  
09-19 16:51:42.832 173-173/? I/DEBUG:          93a01454  00000000  
09-19 16:51:42.832 173-173/? I/DEBUG:          93a01458  00000003  
09-19 16:51:42.832 173-173/? I/DEBUG:          93a0145c  079264d3  
09-19 16:51:42.836 173-173/? I/DEBUG:          93a01460  00000000  
09-19 16:51:42.836 173-173/? I/DEBUG:          93a01464  00000000  
09-19 16:51:42.836 173-173/? I/DEBUG:          93a01468  00000000  
09-19 16:51:42.836 173-173/? I/DEBUG:          93a0146c  b772bf60  /system/lib/liblog.so
09-19 16:51:42.836 173-173/? I/DEBUG:          93a01470  94814c60  /data/app-lib/com.couchbase.lite.test-1/libCouchbaseLiteJavaForestDB.so
09-19 16:51:42.836 173-173/? I/DEBUG:          93a01474  b95be7e8  [heap]
09-19 16:51:42.836 173-173/? I/DEBUG:          93a01478  93a014ac  [stack:6536]
09-19 16:51:42.836 173-173/? I/DEBUG:          93a0147c  b7726c0d  /system/lib/liblog.so (__android_log_assert+125)
09-19 16:51:42.836 173-173/? I/DEBUG:     #00  93a01480  00000007  
09-19 16:51:42.836 173-173/? I/DEBUG:          93a01484  94814c6c  /data/app-lib/com.couchbase.lite.test-1/libCouchbaseLiteJavaForestDB.so
09-19 16:51:42.836 173-173/? I/DEBUG:          93a01488  93a014ac  [stack:6536]
09-19 16:51:42.836 173-173/? I/DEBUG:          93a0148c  93a018dc  [stack:6536]
09-19 16:51:42.836 173-173/? I/DEBUG:          93a01490  00000000  
09-19 16:51:42.836 173-173/? I/DEBUG:          93a01494  b95779dc  [heap]
09-19 16:51:42.836 173-173/? I/DEBUG:          93a01498  b7684da9  /system/lib/libc.so (pthread_mutex_lock+9)
09-19 16:51:42.836 173-173/? I/DEBUG:          93a0149c  94814c6c  /data/app-lib/com.couchbase.lite.test-1/libCouchbaseLiteJavaForestDB.so
09-19 16:51:42.836 173-173/? I/DEBUG:          93a014a0  00000000  
09-19 16:51:42.836 173-173/? I/DEBUG:          93a014a4  b9577b20  [heap]
09-19 16:51:42.836 173-173/? I/DEBUG:          93a014a8  b7684da9  /system/lib/libc.so (pthread_mutex_lock+9)
09-19 16:51:42.836 173-173/? I/DEBUG:          93a014ac  546e695f  
09-19 16:51:42.836 173-173/? I/DEBUG:          93a014b0  736e6172  
09-19 16:51:42.836 173-173/? I/DEBUG:          93a014b4  69746361  
09-19 16:51:42.836 173-173/? I/DEBUG:          93a014b8  21206e6f  
09-19 16:51:42.836 173-173/? I/DEBUG:          93a014bc  554e203d  
09-19 16:51:42.836 173-173/? I/DEBUG:          ........  ........
09-19 16:51:42.836 173-173/? I/DEBUG: memory map around fault addr b7726c0d:
09-19 16:51:42.836 173-173/? I/DEBUG:     b7716000-b7725000 rw- 
09-19 16:51:42.836 173-173/? I/DEBUG:     b7725000-b772b000 r-x /system/lib/liblog.so
09-19 16:51:42.836 173-173/? I/DEBUG:     b772b000-b772c000 r-- /system/lib/liblog.so
09-19 16:51:42.912 627-649/system_process I/BootReceiver: Copying /data/tombstones/tombstone_06 to DropBox (SYSTEM_TOMBSTONE)
09-19 16:51:42.924 627-649/system_process D/dalvikvm: GC_FOR_ALLOC freed 691K, 17% free 6130K/7340K, paused 9ms, total 9ms
09-19 16:51:42.928 627-649/system_process D/dalvikvm: GC_FOR_ALLOC freed 1K, 16% free 6225K/7340K, paused 5ms, total 5ms
09-19 16:51:42.928 627-649/system_process I/dalvikvm-heap: Grow heap (frag case) to 6.388MB for 196620-byte allocation
09-19 16:51:42.932 300-300/? D/Zygote: Process 6512 terminated by signal (4)
09-19 16:51:42.936 627-6539/system_process D/dalvikvm: GC_FOR_ALLOC freed 4K, 15% free 6413K/7536K, paused 7ms, total 7ms
09-19 16:51:42.940 627-649/system_process D/dalvikvm: GC_FOR_ALLOC freed 3K, 15% free 6436K/7536K, paused 6ms, total 6ms
09-19 16:51:42.944 627-649/system_process I/dalvikvm-heap: Grow heap (frag case) to 6.595MB for 196620-byte allocation
09-19 16:51:42.952 627-803/system_process D/dalvikvm: GC_FOR_ALLOC freed <1K, 15% free 6628K/7732K, paused 8ms, total 8ms
09-19 16:51:42.952 6502-6502/? D/AndroidRuntime: Shutting down VM
09-19 16:51:42.952 627-803/system_process I/ActivityManager: Process com.couchbase.lite.test (pid 6512) has died.
```

**Comment by hideki** [comment]
Fixed in cbforest, PR https://github.com/couchbaselabs/cbforest/pull/108
