### ISSUE TITLE
ForestDB+Encryption crash in cbl-replication-attachements.js test

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/couchbase-lite-java-core#1433]
Using `android 1.3.1-28` LiteServ + sync_gateway `1.3.0-274` and arm-v7a API 19 Nexus 4 emulator.

Test output

```
>>>>>>>>>>>>>>>>>>>cbl-replication-attachements.js Wed Sep 07 2016 14:17:34 GMT-0700 (PDT)
ForestDB+Encryption
8081

Success

Using ForestDB+Encryption!

cblite-test:pass,cbl-database1:pass,cbl-database2:pass,cbl-database3:pass,un_derscore:pass,dollar$ign:pass,left\(paren:pass,right\)paren:pass,c+plus+plus+:pass,t-minus1:pass,foward/slash:pass,cbl-document1:pass,cbl-document2:pass,cbl-document3:pass,bigtable:pass,large-revisions-compact:pass,large-revisions-not-continues:pass,large-revisions-revs_cache_size:pass,large-revisions:pass,api-test-once-push:pass,api-test-once-pull:pass,cbl-replication-attach1:pass,cbl-replication-attach2:pass,mismatch-gateways-one:pass,mismatch-gateways-two:pass,mismatch-restart-cb-one:pass,mismatch-restart-cb-two:pass,mismatch-restart-sg-one:pass,mismatch-restart-sg-two:pass,cbl-replication:pass,cbl-replication1:pass,cbl-replication2:pass,cbl-replication3:pass,cbl-replication4:pass,cbl-replication5:pass,cbl-replication6:pass,cbl-replication7:pass,cbl-replication8:pass,cbl-replication9:pass,api-revision-restart:pass,api-revisions:pass,simple-requests:pass,webhook_events:pass

LiteServAndroid launched on 8081
Starting: Intent { act=android.intent.action.MAIN cmp=com.couchbase.liteservandroid/.MainActivity (has extras) }


2016-09-07T14:17:57.658-07:00 Enabling logging: [CRUD REST+ CHANGES]
2016-09-07T14:17:57.658-07:00 ==== Couchbase Sync Gateway/1.3.0(274;8c3ee28) ====
2016-09-07T14:17:57.658-07:00 Configured process to allow 5000 open file descriptors
2016-09-07T14:17:57.658-07:00 Opening db /db as bucket "db", pool "default", server <walrus:>
2016-09-07T14:17:57.658-07:00 Opening Walrus database db on <walrus:>
2016-09-07T14:17:57.659-07:00     Reset guest user to config
2016-09-07T14:17:57.659-07:00 Starting admin server on :9889
2016-09-07T14:17:57.664-07:00 Starting server on :9888 ...
2016-09-07T14:17:58.795-07:00 HTTP:  #001: GET /db/
2016-09-07T14:18:02.834-07:00 HTTP:  #002: GET /db/_local/f59fbfcd32231c1b82010cb83d6674695ea5b0f0
2016-09-07T14:18:02.834-07:00 HTTP: #002:     --> 404 missing  (0.2 ms)
```

adb stack trace

https://gist.github.com/sethrosetter/64ba563b15b00564e2e211b9a4e2747e

```
D/Sync    (19566): PusherInternal{http://10.0.2.2:9888/db, push, f59fb}: beginReplicating() called
W/Sync    (19566): Error converting lastSequence: null to long.  Using 0
D/Sync    (19566): PusherInternal{http://10.0.2.2:9888/db, push, f59fb}: Getting changes since 0
D/Sync    (19566): PusherInternal{http://10.0.2.2:9888/db, push, f59fb}: No changes since 0
V/Sync    (19566): com.couchbase.lite.replicator.RemoteRequest {GET, http://10.0.2.2:9888/db/_local/f59fbfcd32231c1b82010cb83d6674695ea5b0f0}: RemoteRequest execute() finished, url: http://10.0.2.2:9888/db/_local/f59fbfcd32231c1b82010cb83d6674695ea5b0f0
I/DEBUG   (   49): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
I/DEBUG   (   49): Build fingerprint: 'generic/google_sdk/generic:4.4.2/KK/3079183:eng/test-keys'
I/DEBUG   (   49): Revision: '0'
I/DEBUG   (   49): pid: 19566, tid: 19592, name: db-pull-93839-0  >>> com.couchbase.liteservandroid <<<
I/DEBUG   (   49): signal 4 (SIGILL), code 1 (ILL_ILLOPC), fault addr a854b802
I/DEBUG   (   49):     r0 00000004  r1 00000023  r2 a854b7cf  r3 00000000
I/DEBUG   (   49):     r4 a8ae2666  r5 a6c07bb0  r6 b7df1d28  r7 00008635
I/DEBUG   (   49):     r8 b5a40d40  r9 0000000d  sl 00000001  fp 00000040
I/DEBUG   (   49):     ip b7c3f7c8  sp a6c03c40  lr 00000000  pc a854b802  cpsr 00000030
I/DEBUG   (   49):     d0  3f4000003f400000  d1  000000563fc00000
I/DEBUG   (   49):     d2  0000000000000000  d3  7e37e43c8800759c
I/DEBUG   (   49):     d4  4026000000000000  d5  3f40000042810000
I/DEBUG   (   49):     d6  4026000000000000  d7  0000000b00000000
I/DEBUG   (   49):     d8  0000000000000000  d9  0000000000000000
I/DEBUG   (   49):     d10 0000000000000000  d11 0000000000000000
I/DEBUG   (   49):     d12 0000000000000000  d13 0000000000000000
I/DEBUG   (   49):     d14 0000000000000000  d15 0000000000000000
I/DEBUG   (   49):     scr 60000010
I/DEBUG   (   49):
I/DEBUG   (   49): backtrace:
I/DEBUG   (   49):     #00  pc 0001b802  /dev/ashmem/dalvik-jit-code-cache (deleted)
I/DEBUG   (   49):
I/DEBUG   (   49): stack:
I/DEBUG   (   49):          a6c03c00  b1d2dc20  /dev/ashmem/dalvik-heap (deleted)
I/DEBUG   (   49):          a6c03c04  b5ad21f0  /system/lib/libdvm.so
I/DEBUG   (   49):          a6c03c08  00000024
I/DEBUG   (   49):          a6c03c0c  b5a4cdc0  /system/lib/libdvm.so (dvmMalloc(unsigned int, int)+68)
I/DEBUG   (   49):          a6c03c10  b6ee6fd8  /system/lib/libc.so
I/DEBUG   (   49):          a6c03c14  b6ee706c  /system/lib/libc.so
I/DEBUG   (   49):          a6c03c18  b5ad26c8  /system/lib/libdvm.so
I/DEBUG   (   49):          a6c03c1c  4c0e4590
I/DEBUG   (   49):          a6c03c20  000020f4
I/DEBUG   (   49):          a6c03c24  a8ae2666  /data/dalvik-cache/data@app@com.couchbase.liteservandroid-1.apk@classes.dex
I/DEBUG   (   49):          a6c03c28  a6c07bb0
I/DEBUG   (   49):          a6c03c2c  b7df1d28  [heap]
I/DEBUG   (   49):          a6c03c30  00008635
I/DEBUG   (   49):          a6c03c34  b5a40d40  /system/lib/libdvm.so
I/DEBUG   (   49):          a6c03c38  0000000d
I/DEBUG   (   49):          a6c03c3c  b5a49de0  /system/lib/libdvm.so
I/DEBUG   (   49):     #00  a6c03c40  00000000
I/DEBUG   (   49):          a6c03c44  b7df1d28  [heap]
I/DEBUG   (   49):          a6c03c48  b5a50ee8  /system/lib/libdvm.so (dvmMterpStd(Thread*))
I/DEBUG   (   49):          a6c03c4c  00000000
I/DEBUG   (   49):          a6c03c50  a6c03d78  [stack:19592]
I/DEBUG   (   49):          a6c03c54  b7df1d28  [heap]
I/DEBUG   (   49):          a6c03c58  a6c03c94  [stack:19592]
I/DEBUG   (   49):          a6c03c5c  af24aeb0  /dev/ashmem/dalvik-LinearAlloc (deleted)
I/DEBUG   (   49):          a6c03c60  b1d91438  /dev/ashmem/dalvik-heap (deleted)
I/DEBUG   (   49):          a6c03c64  b5a50f38  /system/lib/libdvm.so (dvmMterpStd(Thread*)+80)
I/DEBUG   (   49):          a6c03c68  00000000
I/DEBUG   (   49):          a6c03c6c  00000000
I/DEBUG   (   49):          a6c03c70  00000000
I/DEBUG   (   49):          a6c03c74  00000000
I/DEBUG   (   49):          a6c03c78  00000000
I/DEBUG   (   49):          a6c03c7c  fffffea0
I/DEBUG   (   49):
I/DEBUG   (   49): memory near r2:
I/DEBUG   (   49):     a854b7ac 00000002 b7c30000 af61dbd8 00b50105
I/DEBUG   (   49):     a854b7bc 00000001 00000000 a8ae266e b7cce7f0
I/DEBUG   (   49):     a854b7cc f85f0030 68010008 60013101 6a2969a8
I/DEBUG   (   49):     a854b7dc f2804288 e7ff8007 4300e000 47806e70
I/DEBUG   (   49):     a854b7ec a8ae266a 4300e000 47806e70 a8ae267e
I/DEBUG   (   49):     a854b7fc 00000002 b7c30000 af61dbd8 00b30101
I/DEBUG   (   49):     a854b80c 00000001 00000000 b7cce7f4 f85f00bc
I/DEBUG   (   49):     a854b81c 68010008 60013101 6aaa69a8 1c4168ac
I/DEBUG   (   49):     a854b82c 8010f8d5 f3441813 f1b80707 636f0f00
I/DEBUG   (   49):     a854b83c 6169632b f8d8d031 f2089008 454b0810
I/DEBUG   (   49):     a854b84c 802bf080 a02af896 7003f808 f1ba1c08
I/DEBUG   (   49):     a854b85c f8d50f00 61a8b020 4558d122 8028f280
I/DEBUG   (   49):     a854b86c c044f8d5 f1bc69a8 f8c50f00 d01ac000
I/DEBUG   (   49):     a854b87c 3008f8dc 2010f8dc 1014f8dc f0804288
I/DEBUG   (   49):     a854b88c 33108012 f8331812 27804012 632f42bc
I/DEBUG   (   49):     a854b89c f6ff60ac e00bafc1 f8dfde00 e0040054
I/DEBUG   (   49):
I/DEBUG   (   49): memory near r4:
I/DEBUG   (   49):     a8ae2644 acd1060c 00022000 20ee0013 00c0000b
I/DEBUG   (   49):     a8ae2654 05d8080a 0c900106 2d8d060a 0c040d4f
I/DEBUG   (   49):     a8ae2664 86355601 0008000c 20ee0011 00600001
I/DEBUG   (   49):     a8ae2674 0c13020a c2340080 0c90001a bdf20a06
I/DEBUG   (   49):     a8ae2684 0991001c bcf20d0c 9cb0001c 001cbcf5
I/DEBUG   (   49):     a8ae2694 00100008 00100cf3 ecbb9e81 00100008
I/DEBUG   (   49):     a8ae26a4 00100cf6 56016501 05d8b228 0c900106
I/DEBUG   (   49):     a8ae26b4 2d8d060a 0c040d4f d4285601 08000c13
I/DEBUG   (   49):     a8ae26c4 0017c235 06020ce1 00c0ccd6 00100008
I/DEBUG   (   49):     a8ae26d4 005620f8 0cdd00c0 ccd63f02 00080080
I/DEBUG   (   49):     a8ae26e4 20f80010 00c00056 010605d8 0c14dd28
I/DEBUG   (   49):     a8ae26f4 0000d800 0007c234 dfff0c14 c2370000
I/DEBUG   (   49):     a8ae2704 0ce10022 ccd60c02 000800e0 20f80010
I/DEBUG   (   49):     a8ae2714 00c00056 06020ce1 3f0c0cdd 0080ccd6
I/DEBUG   (   49):     a8ae2724 00100008 005620f8 0cdd00c0 ccd63f02
I/DEBUG   (   49):     a8ae2734 00080080 20f80010 00c00056 010605d8
I/DEBUG   (   49):
I/DEBUG   (   49): memory near r5:
I/DEBUG   (   49):     a6c07b90 00002000 b1d9dad0 00000001 a6c07c14
I/DEBUG   (   49):     a6c07ba0 a8ae24e6 af61dbd8 a8ae2666 00000000
I/DEBUG   (   49):     a6c07bb0 b1e12638 00000000 00000074 00000000
I/DEBUG   (   49):     a6c07bc0 b1e51a38 00000004 00000004 a6c07c10
I/DEBUG   (   49):     a6c07bd0 00000023 af61c630 0000004a b1d2dc20
I/DEBUG   (   49):     a6c07be0 0000004d 00000074 b1d2dc20 0000004a
I/DEBUG   (   49):     a6c07bf0 b1d9dad0 b1e12638 00000000 00000023
I/DEBUG   (   49):     a6c07c00 a6c07c38 a8ae3410 af61dba0 a8ae24e6
I/DEBUG   (   49):     a6c07c10 00000000 00000000 00000023 b1d9dad0
I/DEBUG   (   49):     a6c07c20 b1e12638 a6c07c5c a8a96a92 af619858
I/DEBUG   (   49):     a6c07c30 a8ae3410 00000000 b1d9dad0 00000001
I/DEBUG   (   49):     a6c07c40 b1d9dab8 b1e12638 a6c07c90 a8a96b72
I/DEBUG   (   49):     a6c07c50 af61e808 a8a96a92 00000000 00000000
I/DEBUG   (   49):     a6c07c60 00000005 b1d9dab8 b1e12638 b1d780f8
I/DEBUG   (   49):     a6c07c70 b1d92718 b1db30a0 b1d709f8 a6c07cb4
I/DEBUG   (   49):     a6c07c80 a8a97954 af61e878 a8a96b72 00000000
I/DEBUG   (   49):
I/DEBUG   (   49): memory near r6:
I/DEBUG   (   49):     b7df1d08 ffffffff ffffffff ffffffff ffffffff
I/DEBUG   (   49):     b7df1d18 ffffffff ffffffff 0000000a 0000045b
I/DEBUG   (   49):     b7df1d28 a89e8b20 a6c07bb0 af61dbd8 a886a000
I/DEBUG   (   49):     b7df1d38 00000074 00000000 a6c03c40 00000000
I/DEBUG   (   49):     b7df1d48 a6c03c94 00000017 00000000 b5a40d40
I/DEBUG   (   49):     b7df1d58 00000000 00000000 aec16c70 a6c04300
I/DEBUG   (   49):     b7df1d68 00000000 00000000 00000001 00004000
I/DEBUG   (   49):     b7df1d78 00000000 b7dfcea8 b5a40d40 b5a45c00
I/DEBUG   (   49):     b7df1d88 00000000 b5a49cfc b5a49d70 b5a49c20
I/DEBUG   (   49):     b7df1d98 b5a49c40 b5a49c9c 00000000 a854b7d9
I/DEBUG   (   49):     b7df1da8 b7c46cb8 00000028 00000000 00000000
I/DEBUG   (   49):     b7df1db8 00000000 00000006 00002000 b5ad291c
I/DEBUG   (   49):     b7df1dc8 b1a230e0 af249930 00000000 b7dfb528
I/DEBUG   (   49):     b7df1dd8 00000001 00000040 00000200 00000001
I/DEBUG   (   49):     b7df1de8 00000005 af016142 af016134 00000002
I/DEBUG   (   49):     b7df1df8 af01613c af353b58 718cfda5 718cfdaf
I/DEBUG   (   49):
I/DEBUG   (   49): memory near r7:
I/DEBUG   (   49):     00008614 ffffffff ffffffff ffffffff ffffffff
I/DEBUG   (   49):     00008624 ffffffff ffffffff ffffffff ffffffff
I/DEBUG   (   49):     00008634 ffffffff ffffffff ffffffff ffffffff
I/DEBUG   (   49):     00008644 ffffffff ffffffff ffffffff ffffffff
I/DEBUG   (   49):     00008654 ffffffff ffffffff ffffffff ffffffff
I/DEBUG   (   49):     00008664 ffffffff ffffffff ffffffff ffffffff
I/DEBUG   (   49):     00008674 ffffffff ffffffff ffffffff ffffffff
I/DEBUG   (   49):     00008684 ffffffff ffffffff ffffffff ffffffff
I/DEBUG   (   49):     00008694 ffffffff ffffffff ffffffff ffffffff
I/DEBUG   (   49):     000086a4 ffffffff ffffffff ffffffff ffffffff
I/DEBUG   (   49):     000086b4 ffffffff ffffffff ffffffff ffffffff
I/DEBUG   (   49):     000086c4 ffffffff ffffffff ffffffff ffffffff
I/DEBUG   (   49):     000086d4 ffffffff ffffffff ffffffff ffffffff
I/DEBUG   (   49):     000086e4 ffffffff ffffffff ffffffff ffffffff
I/DEBUG   (   49):     000086f4 ffffffff ffffffff ffffffff ffffffff
I/DEBUG   (   49):     00008704 ffffffff ffffffff ffffffff ffffffff
I/DEBUG   (   49):
I/DEBUG   (   49): memory near r8:
I/DEBUG   (   49):     b5a40d20 e320f000 e320f000 e320f000 e320f000
I/DEBUG   (   49):     b5a40d30 e320f000 e320f000 e320f000 e320f000
I/DEBUG   (   49):     b5a40d40 e1f470b2 e207c0ff e088f30c e92d4ff0
I/DEBUG   (   49):     b5a40d50 e24dd004 e320f000 e320f000 e320f000
I/DEBUG   (   49):     b5a40d60 e320f000 e320f000 e320f000 e320f000
I/DEBUG   (   49):     b5a40d70 e320f000 e320f000 e320f000 e320f000
I/DEBUG   (   49):     b5a40d80 e1a01627 e7e30457 e1f470b2 e7952101
I/DEBUG   (   49):     b5a40d90 e207c0ff e7852100 e088f30c e320f000
I/DEBUG   (   49):     b5a40da0 e320f000 e320f000 e320f000 e320f000
I/DEBUG   (   49):     b5a40db0 e320f000 e320f000 e320f000 e320f000
I/DEBUG   (   49):     b5a40dc0 e1d410b2 e1a00427 e1f470b4 e7952101
I/DEBUG   (   49):     b5a40dd0 e207c0ff e7852100 e088f30c e320f000
I/DEBUG   (   49):     b5a40de0 e320f000 e320f000 e320f000 e320f000
I/DEBUG   (   49):     b5a40df0 e320f000 e320f000 e320f000 e320f000
I/DEBUG   (   49):     b5a40e00 e1d410b4 e1d400b2 e1f470b6 e7952101
I/DEBUG   (   49):     b5a40e10 e207c0ff e7852100 e088f30c e320f000
I/DEBUG   (   49):
I/DEBUG   (   49): memory near ip:
I/DEBUG   (   49):     b7c3f7a8 af09fce0 a853b80b 10000000 00000000
I/DEBUG   (   49):     b7c3f7b8 00000000 10000000 00000000 00000000
I/DEBUG   (   49):     b7c3f7c8 10000298 a8ae2666 a854b7cf 10000000
I/DEBUG   (   49):     b7c3f7d8 00000000 00000000 10000298 a8ae266a
I/DEBUG   (   49):     b7c3f7e8 a854b753 10000000 00000000 00000000
I/DEBUG   (   49):     b7c3f7f8 10000000 00000000 00000000 10000000
I/DEBUG   (   49):     b7c3f808 00000000 00000000 10000000 00000000
I/DEBUG   (   49):     b7c3f818 00000000 10000000 00000000 00000000
I/DEBUG   (   49):     b7c3f828 10000000 00000000 00000000 10000000
I/DEBUG   (   49):     b7c3f838 00000000 00000000 10000298 aefb8320
I/DEBUG   (   49):     b7c3f848 a8549b6f 10000000 00000000 00000000
I/DEBUG   (   49):     b7c3f858 10000000 00000000 00000000 10000000
I/DEBUG   (   49):     b7c3f868 00000000 00000000 10000000 00000000
I/DEBUG   (   49):     b7c3f878 00000000 10000000 00000000 00000000
I/DEBUG   (   49):     b7c3f888 10000298 af09fc3a a853bc3b 10000298
I/DEBUG   (   49):     b7c3f898 aefe4342 a85433d3 10000298 af095c3c
I/DEBUG   (   49):
I/DEBUG   (   49): memory near sp:
I/DEBUG   (   49):     a6c03c20 000020f4 a8ae2666 a6c07bb0 b7df1d28
I/DEBUG   (   49):     a6c03c30 00008635 b5a40d40 0000000d b5a49de0
I/DEBUG   (   49):     a6c03c40 00000000 b7df1d28 b5a50ee8 00000000
I/DEBUG   (   49):     a6c03c50 a6c03d78 b7df1d28 a6c03c94 af24aeb0
I/DEBUG   (   49):     a6c03c60 b1d91438 b5a50f38 00000000 00000000
I/DEBUG   (   49):     a6c03c70 00000000 00000000 00000000 fffffea0
I/DEBUG   (   49):     a6c03c80 b5a50ee8 b5a4e5d0 00000000 00000000
I/DEBUG   (   49):     a6c03c90 00000000 00000000 a6c07fe4 00000000
I/DEBUG   (   49):     a6c03ca0 00000000 00000000 00000000 00000000
I/DEBUG   (   49):     a6c03cb0 00000000 00000000 00000000 00000000
I/DEBUG   (   49):     a6c03cc0 00000000 00000000 00000000 00000000
I/DEBUG   (   49):     a6c03cd0 00000000 00000000 00000000 00000000
I/DEBUG   (   49):     a6c03ce0 00000000 00000000 00000000 00000000
I/DEBUG   (   49):     a6c03cf0 00000000 00000000 a6c03d78 00000000
I/DEBUG   (   49):     a6c03d00 b7df1d28 a6c07fec af24aeb0 af114b4c
I/DEBUG   (   49):     a6c03d10 00000000 b5a8331d 0000001d 0000001c
I/DEBUG   (   49):
I/DEBUG   (   49): code around pc:
I/DEBUG   (   49):     a854b7e0 e7ff8007 4300e000 47806e70 a8ae266a
I/DEBUG   (   49):     a854b7f0 4300e000 47806e70 a8ae267e 00000002
I/DEBUG   (   49):     a854b800 b7c30000 af61dbd8 00b30101 00000001
I/DEBUG   (   49):     a854b810 00000000 b7cce7f4 f85f00bc 68010008
I/DEBUG   (   49):     a854b820 60013101 6aaa69a8 1c4168ac 8010f8d5
I/DEBUG   (   49):     a854b830 f3441813 f1b80707 636f0f00 6169632b
I/DEBUG   (   49):     a854b840 f8d8d031 f2089008 454b0810 802bf080
I/DEBUG   (   49):     a854b850 a02af896 7003f808 f1ba1c08 f8d50f00
I/DEBUG   (   49):     a854b860 61a8b020 4558d122 8028f280 c044f8d5
I/DEBUG   (   49):     a854b870 f1bc69a8 f8c50f00 d01ac000 3008f8dc
I/DEBUG   (   49):     a854b880 2010f8dc 1014f8dc f0804288 33108012
I/DEBUG   (   49):     a854b890 f8331812 27804012 632f42bc f6ff60ac
I/DEBUG   (   49):     a854b8a0 e00bafc1 f8dfde00 e0040054 0048f8df
I/DEBUG   (   49):     a854b8b0 f8dfe001 6ef10040 1c2d4788 4300e000
I/DEBUG   (   49):     a854b8c0 47806e70 a8ae267e 4300e000 47806e70
I/DEBUG   (   49):     a854b8d0 a8ae2500 00000001 b7cd0001 af61dbd8
I/DEBUG   (   49):
I/DEBUG   (   49): code around lr:
I/DEBUG   (   49):     00000000 ffffffff ffffffff ffffffff ffffffff
I/DEBUG   (   49):     00000010 ffffffff ffffffff ffffffff ffffffff
I/DEBUG   (   49):     00000020 ffffffff ffffffff ffffffff ffffffff
I/DEBUG   (   49):     00000030 ffffffff ffffffff ffffffff ffffffff
I/DEBUG   (   49):     00000040 ffffffff ffffffff ffffffff ffffffff
I/DEBUG   (   49):     00000050 ffffffff ffffffff ffffffff ffffffff
I/DEBUG   (   49):     00000060 ffffffff ffffffff ffffffff ffffffff
I/DEBUG   (   49):     00000070 ffffffff ffffffff ffffffff ffffffff
I/DEBUG   (   49):     00000080 ffffffff ffffffff ffffffff ffffffff
I/DEBUG   (   49):     00000090 ffffffff ffffffff ffffffff ffffffff
I/DEBUG   (   49):     000000a0 ffffffff ffffffff ffffffff ffffffff
I/DEBUG   (   49):     000000b0 ffffffff ffffffff ffffffff ffffffff
I/DEBUG   (   49):     000000c0 ffffffff ffffffff ffffffff ffffffff
I/DEBUG   (   49):     000000d0 ffffffff ffffffff ffffffff ffffffff
I/DEBUG   (   49):     000000e0 ffffffff ffffffff ffffffff ffffffff
I/DEBUG   (   49):     000000f0 ffffffff ffffffff ffffffff ffffffff
I/DEBUG   (   49):
I/DEBUG   (   49): memory map around fault addr a854b802:
I/DEBUG   (   49):     a7d2f000-a8530000 rw- [anon:libc_malloc]
I/DEBUG   (   49):     a8530000-a86a7000 r-x /dev/ashmem/dalvik-jit-code-cache (deleted)
I/DEBUG   (   49):     a86a7000-a883d000 r-x /data/app-lib/com.couchbase.liteservandroid-1/libCouchbaseLiteJavaForestDB.so
I/BootReceiver(  372): Copying /data/tombstones/tombstone_01 to DropBox (SYSTEM_TOMBSTONE)
W/InputDispatcher(  372): channel 'b28a60f0 com.couchbase.liteservandroid/com.couchbase.liteservandroid.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
E/InputDispatcher(  372): channel 'b28a60f0 com.couchbase.liteservandroid/com.couchbase.liteservandroid.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
I/WindowState(  372): WIN DEATH: Window{b28a60f0 u0 com.couchbase.liteservandroid/com.couchbase.liteservandroid.MainActivity}
D/Zygote  (   52): Process 19566 terminated by signal (4)
W/InputDispatcher(  372): Attempted to unregister already unregistered input channel 'b28a60f0 com.couchbase.liteservandroid/com.couchbase.liteservandroid.MainActivity (server)'
W/ActivityManager(  372):   Force finishing activity com.couchbase.liteservandroid/.MainActivity
W/ActivityManager(  372): Exception thrown during pause
W/ActivityManager(  372): android.os.DeadObjectException
W/ActivityManager(  372):       at android.os.BinderProxy.transact(Native Method)
W/ActivityManager(  372):       at android.app.ApplicationThreadProxy.schedulePauseActivity(ApplicationThreadNative.java:660)
W/ActivityManager(  372):       at com.android.server.am.ActivityStack.startPausingLocked(ActivityStack.java:761)
W/ActivityManager(  372):       at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:2455)
W/ActivityManager(  372):       at com.android.server.am.ActivityStack.finishTopRunningActivityLocked(ActivityStack.java:2329)
W/ActivityManager(  372):       at com.android.server.am.ActivityStackSupervisor.finishTopRunningActivityLocked(ActivityStackSupervisor.java:2035)
W/ActivityManager(  372):       at com.android.server.am.ActivityManagerService.handleAppCrashLocked(ActivityManagerService.java:9543)
W/ActivityManager(  372):       at com.android.server.am.ActivityManagerService.makeAppCrashingLocked(ActivityManagerService.java:9436)
W/ActivityManager(  372):       at com.android.server.am.ActivityManagerService.crashApplication(ActivityManagerService.java:10081)
W/ActivityManager(  372):       at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:9632)
W/ActivityManager(  372):       at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:86)
I/ActivityManager(  372): Process com.couchbase.liteservandroid (pid 19566) has died.
D/dalvikvm(  372): GC_CONCURRENT freed 544K, 41% free 9834K/16580K, paused 19ms+12ms, total 294ms
D/dalvikvm(  372): WAIT_FOR_CONCURRENT_GC blocked 283ms
D/dalvikvm(  372): WAIT_FOR_CONCURRENT_GC blocked 72ms
D/dalvikvm(  372): GC_FOR_ALLOC freed 1142K, 45% free 9271K/16580K, paused 108ms, total 111ms
I/dalvikvm-heap(  372): Grow heap (frag case) to 10.195MB for 1127536-byte allocation
D/dalvikvm(  372): GC_FOR_ALLOC freed 4K, 42% free 10367K/17684K, paused 100ms, total 100ms
I/Choreographer(  630): Skipped 38 frames!  The application may be doing too much work on its main thread.
D/        (  372): HostConnection::get() New Host Connection established 0xb7d747a0, tid 387
D/DropBoxEntryAddedChimeraService(  908): User is not opted-in to Usage & Diagnostics or Lockbox.
D/DropBoxEntryAddedChimeraService(  908): User is not opted-in to Usage & Diagnostics or Lockbox.
```

**Comment by hideki** [comment]
Crash might not happen in forestdb library. It seems crash occurs in standard library.

**Comment by hideki** [comment]
We have not seen this for a while. This could be fixed by other bug fixes. I will close this ticket.
