### ISSUE TITLE
ConnectionError: ('Connection aborted.', error(54, 'Connection reset by peer'))

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/couchbase-lite-java-core#1481]
This is using 1.3.1-61

When running certain tests, I hit this intermittently with the Android listener. 

Here is an example of one such failure - http://uberjenkins.sc.couchbase.com/job/net-listener-client-client/7/testReport/testsuites.listener.shared.client_client/test_peer_2_peer_sanity/test_peer_2_peer_sanity_pull/

We need to determine root cause, I have talked with @hideki and we think it may be due to the thread limit on the Android listener. 

I am able to reproduce so we should pair debug this.

**Comment by sethrosetter** [comment]
This a memory leak. It is easily reproducible running https://github.com/couchbaselabs/mobile-testkit/blob/master/testsuites/listener/shared/client_sg/test_replication.py#L728-L759 and monitoring the app in Android Studio. Increasing the number of docs or revs as well as increasing - https://github.com/couchbaselabs/mobile-testkit/blob/master/keywords/MobileRestClient.py#L873 to 10 workers

**Comment by hideki** [comment]
OOM
```
11-03 19:52:57.719 4850-8733/com.couchbase.liteservandroid I/dalvikvm-heap: Clamp target GC heap from 103.415MB to 96.000MB
11-03 19:52:57.719 4850-8733/com.couchbase.liteservandroid D/dalvikvm: GC_FOR_ALLOC freed 22K, 1% free 97589K/98304K, paused 149ms, total 150ms
11-03 19:52:57.719 4850-8733/com.couchbase.liteservandroid I/dalvikvm-heap: Forcing collection of SoftReferences for 65548-byte allocation
11-03 19:52:57.891 4850-8733/com.couchbase.liteservandroid I/dalvikvm-heap: Clamp target GC heap from 103.377MB to 96.000MB
11-03 19:52:57.891 4850-8733/com.couchbase.liteservandroid D/dalvikvm: GC_BEFORE_OOM freed 37K, 1% free 97551K/98304K, paused 169ms, total 169ms
11-03 19:52:57.891 4850-8733/com.couchbase.liteservandroid E/dalvikvm-heap: Out of memory on a 65548-byte allocation.
11-03 19:52:57.891 4850-8733/com.couchbase.liteservandroid I/dalvikvm: "Acme.Utils.ThreadPool(6)-PooledThread: Acme.Serve.Serve$ServeConnection@552acf70" daemon prio=5 tid=29 RUNNABLE
11-03 19:52:57.891 4850-8733/com.couchbase.liteservandroid I/dalvikvm:   | group="TJWS threads" sCount=0 dsCount=0 obj=0xa5127570 self=0xb8b227a8
11-03 19:52:57.891 4850-8733/com.couchbase.liteservandroid I/dalvikvm:   | sysTid=8733 nice=0 sched=0/0 cgrp=apps handle=-1196487856
11-03 19:52:57.891 4850-8733/com.couchbase.liteservandroid I/dalvikvm:   | state=R schedstat=( 39504873099 9663750612 82585 ) utm=2336 stm=1624 core=1
11-03 19:52:57.891 4850-8733/com.couchbase.liteservandroid I/dalvikvm:     at com.couchbase.lite.listener.LiteServlet.service(LiteServlet.java:~149)
11-03 19:52:57.891 4850-8733/com.couchbase.liteservandroid I/dalvikvm:     at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)
11-03 19:52:57.891 4850-8733/com.couchbase.liteservandroid I/dalvikvm:     at Acme.Serve.Serve$ServeConnection.runServlet(Serve.java:2251)
11-03 19:52:57.891 4850-8733/com.couchbase.liteservandroid I/dalvikvm:     at Acme.Serve.Serve$ServeConnection.parseRequest(Serve.java:2176)
11-03 19:52:57.891 4850-8733/com.couchbase.liteservandroid I/dalvikvm:     at Acme.Serve.Serve$ServeConnection.run(Serve.java:1988)
11-03 19:52:57.891 4850-8733/com.couchbase.liteservandroid I/dalvikvm:     at Acme.Utils$ThreadPool$PooledThread.run(Utils.java:1223)
11-03 19:52:57.891 4850-8733/com.couchbase.liteservandroid I/dalvikvm:     at java.lang.Thread.run(Thread.java:841)
11-03 19:52:57.891 4850-4899/com.couchbase.liteservandroid W/System.err:     at Acme.Utils$ThreadPool$PooledThread.run(Utils.java:1223)
11-03 19:52:57.891 4850-4899/com.couchbase.liteservandroid W/System.err:     at java.lang.Thread.run(Thread.java:841)
11-03 19:52:57.891 4850-8733/com.couchbase.liteservandroid W/System.err: java.lang.OutOfMemoryError
11-03 19:52:57.891 4850-8733/com.couchbase.liteservandroid W/System.err:     at com.couchbase.lite.listener.LiteServlet.service(LiteServlet.java:149)
11-03 19:52:57.891 4850-8733/com.couchbase.liteservandroid W/System.err:     at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)
11-03 19:52:57.891 4850-8733/com.couchbase.liteservandroid W/System.err:     at Acme.Serve.Serve$ServeConnection.runServlet(Serve.java:2251)
11-03 19:52:57.891 4850-8733/com.couchbase.liteservandroid W/System.err:     at Acme.Serve.Serve$ServeConnection.parseRequest(Serve.java:2176)
11-03 19:52:57.891 4850-8733/com.couchbase.liteservandroid W/System.err:     at Acme.Serve.Serve$ServeConnection.run(Serve.java:1988)
11-03 19:52:57.891 4850-8733/com.couchbase.liteservandroid W/System.err:     at Acme.Utils$ThreadPool$PooledThread.run(Utils.java:1223)
11-03 19:52:57.891 4850-8733/com.couchbase.liteservandroid W/System.err:     at java.lang.Thread.run(Thread.java:841)
```

**Comment by sethrosetter** [comment]
Also Genymotion API 16 is much easier to push to the limit than API 19

**Comment by hideki** [comment]
It seems Push replication holds many request objects in `LinkedBlockingQueue`.
![screen shot 2016-11-04 at 2 41 00 pm](https://cloud.githubusercontent.com/assets/15889/20023414/18b84378-a29d-11e6-97db-7cc13179782e.png)

**Comment by hideki** [comment]
Note to Self:

1. Start continuous push replication against Sync Gateway.
2. Put many documents against LiteServ. 
3. Step 2. causes push replication. -> OOM.

**Comment by hideki** [comment]
Note to Self:

As @sethrosetter mentioned earlier, it seems many concurrent PUT document requests might easily cause OOM.

**Comment by hideki** [comment]
Note to self:
During REST API handle PUT /{db}/{doc} requests, push replicator should handle updated document. But I can not observe any progress of it. I wonder if something blocks push replicator?

**Comment by hideki** [comment]
NOTE:

Connection abort is actually caused by out-of-memory (OOM). And OOM is caused by requests are queued up for push replication, as the client sends POST or PUT /{db}/{doc} too fast.

**Comment by hideki** [comment]
@sethrosetter 
Can you provide number of docs, number of updates, and document size?

**Comment by hideki** [comment]
According to the uberjenkins ( http://uberjenkins.sc.couchbase.com/job/net-listener-client-client/7/testReport/testsuites.listener.shared.client_client/test_peer_2_peer_sanity/test_peer_2_peer_sanity_pull/ ), number of docs seems to be 5000.

**Comment by hideki** [comment]
ref: https://github.com/couchbase/couchbase-lite-java-core/pull/1541
