### ISSUE TITLE
Was not able to delete the database directory, Status: 500 (HTTP 500 Internal Server Error)

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/couchbase-lite-java-core#1498]
Using `Android 1.3.1-75 (SQLite) Genymotion Google Nexus 7 - API 16` with sync_gateway `1.3.1-16`

Link to the test - http://uberjenkins.sc.couchbase.com/job/android-listener-client-sync-gateway/17/testReport/junit/testsuites.listener.shared.client_sg/test_replication/test_initial_pull_replication_True_/

```
V/Database( 7840): CBLRequestWorker-http://10.17.1.111:4985/db-pull-e57c4-4 Begin transaction (level 0)
V/Database( 7840): CBLRequestWorker-http://10.17.1.111:4985/db-pull-e57c4-4 Committing transaction (level 0)
V/Database( 7840): No pending doc expirations
D/Sync    ( 7840): com.couchbase.lite.replicator.ReplicationInternal$8@5375484c: saved remote checkpoint, updating local checkpoint. RemoteCheckpoint: {_rev=0-18, lastSequence=10001}
V/Sync    ( 7840): com.couchbase.lite.replicator.RemoteRequest {PUT, http://10.17.1.111:4985/db/_local/e57c4f0ccc177b80d9400a37cd89d379780edf76}: RemoteRequest execute() finished, url: http://10.17.1.111:4985/db/_local/e57c4f0ccc177b80d9400a37cd89d379780edf76
V/Sync    ( 7840): PullerInternal{http://10.17.1.111:4985/db, pull, e57c4}: clearDbRef() called
V/Sync    ( 7840): PullerInternal{http://10.17.1.111:4985/db, pull, e57c4}: clearDbRef() setting db to null
D/Sync    ( 7840): State transition: STOPPING -> STOPPED (via STOP_IMMEDIATE).  this: PullerInternal{http://10.17.1.111:4985/db, pull, e57c4}
D/Sync    ( 7840): firing trigger: STOP_GRACEFUL
W/Router  ( 7840): Router unable to route request to do_DELETE_Database
W/Router  ( 7840): java.lang.reflect.InvocationTargetException
W/Router  ( 7840):  at java.lang.reflect.Method.invokeNative(Native Method)
W/Router  ( 7840):  at java.lang.reflect.Method.invoke(Method.java:511)
W/Router  ( 7840):  at com.couchbase.lite.router.Router.start(Router.java:555)
W/Router  ( 7840):  at com.couchbase.lite.listener.LiteServlet.service(LiteServlet.java:141)
W/Router  ( 7840):  at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)
W/Router  ( 7840):  at Acme.Serve.Serve$ServeConnection.runServlet(Serve.java:2251)
W/Router  ( 7840):  at Acme.Serve.Serve$ServeConnection.parseRequest(Serve.java:2176)
W/Router  ( 7840):  at Acme.Serve.Serve$ServeConnection.run(Serve.java:1988)
W/Router  ( 7840):  at Acme.Utils$ThreadPool$PooledThread.run(Utils.java:1223)
W/Router  ( 7840):  at java.lang.Thread.run(Thread.java:856)
W/Router  ( 7840): Caused by: com.couchbase.lite.CouchbaseLiteException: Was not able to delete the database directory, Status: 500 (HTTP 500 Internal Server Error)
W/Router  ( 7840):  at com.couchbase.lite.Database.delete(Database.java:409)
W/Router  ( 7840):  at com.couchbase.lite.router.Router.do_DELETE_Database(Router.java:1132)
W/Router  ( 7840):  ... 10 more
V/Listener( 7840): RouterCallbackBlock.onResponseReady() START
V/Listener( 7840): RouterCallbackBlock.onResponseReady() END
V/Listener( 7840): CountDownLatch.await() START
V/Listener( 7840): CountDownLatch.await() END
D/Listener( 7840): authHeader is null
V/Listener( 7840): Not enforcing basic auth -- allowedCredentials null or empty
```

**Comment by hideki** [comment]
Hi @sethrosetter,
I believe CBL LiteServ could not delete the database file because other thread was handling request and it was using Database. If my assumption is correct, it is not bug.
If no other thread was accessing db, this could be bug.
Can you capture any additional info to investigate this?
Or can you help me to set up test environment?
Thanks!

**Comment by hideki** [comment]
@sethrosetter Do you still face this issue?

**Comment by sethrosetter** [comment]
@hideki I have not seen this with the latest 1.4 builds.

**Comment by hideki** [comment]
@sethrosetter Thanks!

I will close this ticket.
