### ISSUE TITLE
Continuous Sync causes out of memory error

### ISSUE THREAD

**Issue by robinvanemden** [couchbase/couchbase-lite-java-core#1513]
I seem to encounter the following "out of memory error" in our current Android project every now and then:

```
Fatal Exception: java.lang.OutOfMemoryError: pthread_create (stack size 16384 bytes) failed: Try again
       at java.lang.VMThread.create(VMThread.java)
       at java.lang.Thread.start(Thread.java:1029)
       at com.couchbase.lite.replicator.PullerInternal.waitForPendingFuturesWithNewThread(PullerInternal.java:931)
       at com.couchbase.lite.replicator.PullerInternal.changeTrackerCaughtUp(PullerInternal.java:821)
       at com.couchbase.lite.replicator.ChangeTracker.runLoop(ChangeTracker.java:379)
       at com.couchbase.lite.replicator.ChangeTracker.run(ChangeTracker.java:246)
       at java.lang.Thread.run(Thread.java:841)
```

The app makes use of Couchbase Lite (version Forestdb:1.3.1), and is set to continuously push and pull against Sync Gateway 1.3.1.

Full stacktrace can be found here: 

https://gist.github.com/robinvanemden/36c9ca90f9c6fac2a4f1a4a9367f5462

**Comment by hideki** [comment]
Hi @robinvanemden,
Thank you for reporting the issue.
Can you provide each document size, total number of documents, how many revisions each doc has? And also, do you use Sync Gateway for server? or CouchDB?
Thanks!

**Comment by robinvanemden** [comment]
Of course! 

- Data/Disk usage for the relevant bucket in Couchbase Console: 32.4MB
- Total number of documents: 3
- Each document contains about 130 revisions
- See example of one of the three documents here: https://gist.github.com/robinvanemden/fa219f390f71fe017fe438e099100d9e#file-example_birdy_document-js-L149
- I use Sync Gateway 1.3.1 for server (together with Couchbase Server 4.1.1-5914 Community Edition)

**Comment by hideki** [comment]
@robinvanemden Thank you for your additional inputs.

**Comment by zubaliy** [comment]
I'm having the same problem.
My db on the Android Watch contains more than 600000 documents.

**Comment by zubaliy** [comment]
I get a lot of following logs:

```
Verification of void okhttp3.internal.http.HttpEngine.maybeCache() took 111.640ms
12-06 11:12:37.102 8508-8516/ W/art: Suspending all threads took: 29.380ms
12-06 11:12:38.451 8508-12968/ W/Sync: Error converting lastSequence: null to long.  Using 0
12-06 11:12:39.545 8508-8520/ W/art: Suspending all threads took: 17.946ms
12-06 11:12:39.652 8508-8516/ W/art: Suspending all threads took: 71.271ms
12-06 11:12:39.677 8508-8520/ I/art: Background partial concurrent mark sweep GC freed 18(32KB) AllocSpace objects, 0(0B) LOS objects, 16% free, 9MB/11MB, paused 3.627ms total 122.992ms
12-06 11:12:40.382 8508-8520/ I/art: Background partial concurrent mark sweep GC freed 119(189KB) AllocSpace objects, 0(0B) LOS objects, 14% free, 12MB/14MB, paused 3.581ms total 192.916ms
12-06 11:12:40.515 8508-12970/ D/CouchDbManager: dbConfigPull: REPLICATION_ACTIVE
12-06 11:12:40.558 8508-12970/ D/CouchDbManager: dbConfigPull: REPLICATION_STOPPED
12-06 11:12:40.558 8508-12970/ D/CouchDbManager: Reload presets
12-06 11:12:41.126 8508-8516/ W/art: Suspending all threads took: 33.213ms
12-06 11:12:41.307 8508-8520/ I/art: Background sticky concurrent mark sweep GC freed 3136(149KB) AllocSpace objects, 0(0B) LOS objects, 0% free, 14MB/14MB, paused 3.916ms total 125.074ms
12-06 11:12:41.446 8508-8520/ I/art: Background partial concurrent mark sweep GC freed 202(9KB) AllocSpace objects, 0(0B) LOS objects, 12% free, 14MB/16MB, paused 4.095ms total 124.839ms
12-06 11:12:42.102 8508-8516/ W/art: Suspending all threads took: 11.774ms
12-06 11:12:42.132 8508-8520/ I/art: Background partial concurrent mark sweep GC freed 8(156KB) AllocSpace objects, 0(0B) LOS objects, 10% free, 16MB/18MB, paused 6.014ms total 134.431ms
12-06 11:12:42.846 8508-8520/ W/art: Suspending all threads took: 6.757ms
12-06 11:12:42.880 8508-8520/ I/art: Background sticky concurrent mark sweep GC freed 25(1136B) AllocSpace objects, 0(0B) LOS objects, 0% free, 18MB/18MB, paused 13.192ms total 191.721ms
12-06 11:12:43.234 8508-8516/ W/art: Suspending all threads took: 139.276ms
12-06 11:12:43.296 8508-8520/ W/art: Suspending all threads took: 15.427ms
12-06 11:12:43.355 8508-8520/ I/art: Background partial concurrent mark sweep GC freed 33(1376B) AllocSpace objects, 0(0B) LOS objects, 9% free, 19MB/21MB, paused 57.823ms total 463.549ms
12-06 11:12:44.111 8508-8516/ W/art: Suspending all threads took: 13.189ms
12-06 11:12:44.148 8508-8520/ I/art: Background sticky concurrent mark sweep GC freed 8(320B) AllocSpace objects, 0(0B) LOS objects, 0% free, 21MB/21MB, paused 7.980ms total 69.246ms
12-06 11:12:44.377 8508-8520/ I/art: Background partial concurrent mark sweep GC freed 140(238KB) AllocSpace objects, 0(0B) LOS objects, 8% free, 21MB/23MB, paused 7.097ms total 201.762ms
12-06 11:12:45.136 8508-8516/ W/art: Suspending all threads took: 34.121ms
12-06 11:12:45.207 8508-8520/ I/art: Background sticky concurrent mark sweep GC freed 6(240B) AllocSpace objects, 0(0B) LOS objects, 0% free, 23MB/23MB, paused 14.922ms total 150.404ms
12-06 11:12:45.520 8508-8520/ I/art: Background partial concurrent mark sweep GC freed 72(4KB) AllocSpace objects, 0(0B) LOS objects, 7% free, 24MB/26MB, paused 8.014ms total 280.579ms
12-06 11:12:46.047 8508-8520/ I/art: Background sticky concurrent mark sweep GC freed 6(240B) AllocSpace objects, 0(0B) LOS objects, 0% free, 26MB/26MB, paused 28.050ms total 187.369ms
12-06 11:12:46.209 8508-8516/ W/art: Suspending all threads took: 100.005ms
12-06 11:12:46.255 8508-8520/ I/art: Background partial concurrent mark sweep GC freed 169(357KB) AllocSpace objects, 0(0B) LOS objects, 7% free, 26MB/28MB, paused 17.366ms total 173.689ms
12-06 11:12:46.867 8508-8520/ I/art: Background sticky concurrent mark sweep GC freed 8(352B) AllocSpace objects, 0(0B) LOS objects, 0% free, 28MB/28MB, paused 9.713ms total 119.242ms
12-06 11:12:47.135 8508-8516/ W/art: Suspending all threads took: 14.582ms
12-06 11:12:47.166 8508-8520/ I/art: Background partial concurrent mark sweep GC freed 12(352B) AllocSpace objects, 0(0B) LOS objects, 6% free, 29MB/31MB, paused 11.095ms total 267.493ms
12-06 11:12:47.806 8508-8520/ I/art: Background sticky concurrent mark sweep GC freed 12(480B) AllocSpace objects, 0(0B) LOS objects, 0% free, 31MB/31MB, paused 10.499ms total 108.096ms
12-06 11:12:48.132 8508-8516/ W/art: Suspending all threads took: 20.114ms
12-06 11:12:48.144 8508-8520/ W/art: Suspending all threads took: 6.295ms
12-06 11:12:48.167 8508-8520/ I/art: Background partial concurrent mark sweep GC freed 8(224B) AllocSpace objects, 0(0B) LOS objects, 5% free, 31MB/33MB, paused 7.936ms total 324.404ms
12-06 11:12:48.665 8508-8516/ W/art: Suspending all threads took: 51.855ms
12-06 11:12:48.686 8508-8520/ I/art: Background sticky concurrent mark sweep GC freed 2(112B) AllocSpace objects, 0(0B) LOS objects, 0% free, 33MB/33MB, paused 6.347ms total 80.017ms
12-06 11:12:49.055 8508-8520/ I/art: Background partial concurrent mark sweep GC freed 17(576B) AllocSpace objects, 0(0B) LOS objects, 5% free, 34MB/36MB, paused 12.787ms total 348.411ms
12-06 11:12:49.516 8508-8520/ I/art: Background sticky concurrent mark sweep GC freed 6(240B) AllocSpace objects, 0(0B) LOS objects, 0% free, 36MB/36MB, paused 20.313ms total 176.438ms
12-06 11:12:49.522 8508-8520/ W/art: Suspending all threads took: 5.948ms
12-06 11:12:49.739 8508-8516/ W/art: Suspending all threads took: 122.832ms
12-06 11:12:49.751 8508-8520/ W/art: Suspending all threads took: 5.472ms
12-06 11:12:49.767 8508-8520/ I/art: Background partial concurrent mark sweep GC freed 9(520KB) AllocSpace objects, 0(0B) LOS objects, 5% free, 36MB/38MB, paused 7.018ms total 201.122ms
12-06 11:12:50.409 8508-8520/ I/art: Background sticky concurrent mark sweep GC freed 9(368B) AllocSpace objects, 0(0B) LOS objects, 0% free, 38MB/38MB, paused 15.048ms total 118.311ms
12-06 11:12:50.697 8508-8516/ W/art: Suspending all threads took: 78.713ms
12-06 11:12:50.730 8508-8520/ I/art: Background partial concurrent mark sweep GC freed 11(336B) AllocSpace objects, 0(0B) LOS objects, 4% free, 38MB/40MB, paused 6.262ms total 292.656ms
12-06 11:12:51.371 8508-8520/ I/art: Background sticky concurrent mark sweep GC freed 8(352B) AllocSpace objects, 0(0B) LOS objects, 0% free, 41MB/41MB, paused 15.721ms total 137.351ms
12-06 11:12:51.694 8508-8516/ W/art: Suspending all threads took: 73.238ms
12-06 11:12:51.748 8508-8520/ I/art: Background partial concurrent mark sweep GC freed 12(352B) AllocSpace objects, 0(0B) LOS objects, 4% free, 41MB/43MB, paused 15.971ms total 341.639ms
12-06 11:12:52.386 8508-8520/ I/art: Background sticky concurrent mark sweep GC freed 8(352B) AllocSpace objects, 0(0B) LOS objects, 0% free, 43MB/43MB, paused 18.211ms total 149.080ms
12-06 11:12:52.716 8508-8516/ W/art: Suspending all threads took: 89.271ms
12-06 11:12:52.731 8508-8520/ W/art: Suspending all threads took: 5.700ms
12-06 11:12:52.749 8508-8520/ I/art: Background partial concurrent mark sweep GC freed 12(352B) AllocSpace objects, 0(0B) LOS objects, 4% free, 44MB/46MB, paused 7.382ms total 292.726ms
12-06 11:12:53.133 8508-8516/ W/art: Suspending all threads took: 5.611ms
12-06 11:12:53.419 8508-8520/ I/art: Background sticky concurrent mark sweep GC freed 8(352B) AllocSpace objects, 0(0B) LOS objects, 0% free, 46MB/46MB, paused 17.200ms total 145.187ms
12-06 11:12:53.819 8508-8516/ W/art: Suspending all threads took: 188.525ms
12-06 11:12:53.835 8508-8520/ W/art: Suspending all threads took: 9.507ms
12-06 11:12:53.856 8508-8520/ I/art: Clamp target GC heap from 49MB to 48MB
12-06 11:12:53.857 8508-8520/ I/art: Background partial concurrent mark sweep GC freed 12(352B) AllocSpace objects, 0(0B) LOS objects, 2% free, 47MB/48MB, paused 11.296ms total 379.676ms
12-06 11:12:54.136 8508-8516/ I/art: Waiting for a blocking GC Alloc
12-06 11:12:54.145 8508-12968/ I/art: Waiting for a blocking GC Alloc
12-06 11:12:54.156 8508-8520/ I/art: Background sticky concurrent mark sweep GC freed 2(112B) AllocSpace objects, 0(0B) LOS objects, 0% free, 47MB/48MB, paused 1.703ms total 103.195ms
12-06 11:12:54.156 8508-8516/ I/art: WaitForGcToComplete blocked for 20.142ms for cause Alloc
12-06 11:12:54.156 8508-8516/ I/art: Starting a blocking GC Alloc
12-06 11:12:54.161 8508-12968/ I/art: WaitForGcToComplete blocked for 15.955ms for cause Alloc
12-06 11:12:54.161 8508-12968/ I/art: Starting a blocking GC Alloc
12-06 11:12:54.177 8508-12968/ I/art: Starting a blocking GC Alloc
12-06 11:12:54.177 8508-12968/ I/art: Starting a blocking GC Alloc
12-06 11:12:54.443 8508-8520/ W/art: Suspending all threads took: 265.433ms
12-06 11:12:54.471 8508-12968/ I/art: Clamp target GC heap from 49MB to 48MB
12-06 11:12:54.471 8508-12968/ I/art: Alloc partial concurrent mark sweep GC freed 11(336B) AllocSpace objects, 0(0B) LOS objects, 0% free, 47MB/48MB, paused 4.916ms total 293.138ms
12-06 11:12:54.496 8508-12968/ I/art: Waiting for a blocking GC Alloc
12-06 11:12:54.530 8508-8520/ I/art: Background sticky concurrent mark sweep GC freed 2(112B) AllocSpace objects, 0(0B) LOS objects, 0% free, 47MB/48MB, paused 16.318ms total 42.749ms
12-06 11:12:54.530 8508-12968/ I/art: WaitForGcToComplete blocked for 34.711ms for cause Alloc
12-06 11:12:54.530 8508-12968/ I/art: Starting a blocking GC Alloc
12-06 11:12:54.531 8508-12968/ I/art: Starting a blocking GC Alloc
12-06 11:12:54.531 8508-12968/ I/art: Starting a blocking GC Alloc
12-06 11:12:54.699 8508-8520/ W/art: Suspending all threads took: 153.409ms
12-06 11:12:54.714 8508-12968/ W/art: Suspending all threads took: 9.286ms
12-06 11:12:54.744 8508-12968/ I/art: Clamp target GC heap from 49MB to 48MB
12-06 11:12:54.744 8508-12968/ I/art: Alloc partial concurrent mark sweep GC freed 11(336B) AllocSpace objects, 0(0B) LOS objects, 0% free, 47MB/48MB, paused 10.937ms total 190.253ms
12-06 11:12:54.754 8508-12968/ W/art: Suspending all threads took: 10.455ms
12-06 11:12:54.791 8508-12968/ I/art: Starting a blocking GC Alloc
12-06 11:12:54.791 8508-12968/ I/art: Starting a blocking GC Alloc
12-06 11:12:54.968 8508-12969/ I/art: Waiting for a blocking GC Alloc
12-06 11:12:55.070 8508-12968/ I/art: Clamp target GC heap from 49MB to 48MB
12-06 11:12:55.071 8508-12968/ I/art: Alloc partial concurrent mark sweep GC freed 10(320B) AllocSpace objects, 0(0B) LOS objects, 0% free, 47MB/48MB, paused 1.495ms total 274.754ms
12-06 11:12:55.071 8508-12969/ I/art: WaitForGcToComplete blocked for 102.312ms for cause Alloc
12-06 11:12:55.071 8508-12969/ I/art: Starting a blocking GC Alloc
12-06 11:12:55.119 8508-12968/ I/art: Starting a blocking GC Alloc
12-06 11:12:55.119 8508-12968/ I/art: Starting a blocking GC Alloc
12-06 11:12:55.134 8508-8516/ I/art: Waiting for a blocking GC Alloc
12-06 11:12:55.296 8508-12968/ I/art: Clamp target GC heap from 49MB to 48MB
12-06 11:12:55.296 8508-12968/ I/art: Alloc partial concurrent mark sweep GC freed 7(208B) AllocSpace objects, 0(0B) LOS objects, 0% free, 47MB/48MB, paused 1.514ms total 175.170ms
12-06 11:12:55.297 8508-8516/ I/art: WaitForGcToComplete blocked for 162.217ms for cause Alloc
12-06 11:12:55.297 8508-8516/ I/art: Starting a blocking GC Alloc
12-06 11:12:55.340 8508-8520/ W/art: Suspending all threads took: 5.371ms
12-06 11:12:55.343 8508-8520/ I/art: Background sticky concurrent mark sweep GC freed 0(0B) AllocSpace objects, 0(0B) LOS objects, 0% free, 47MB/48MB, paused 7.015ms total 37.509ms
12-06 11:12:55.364 8508-12968/ I/art: Starting a blocking GC Alloc
12-06 11:12:55.364 8508-12968/ I/art: Starting a blocking GC Alloc
12-06 11:12:55.539 8508-12968/ I/art: Clamp target GC heap from 49MB to 48MB
12-06 11:12:55.539 8508-12968/ I/art: Alloc partial concurrent mark sweep GC freed 10(320B) AllocSpace objects, 0(0B) LOS objects, 0% free, 47MB/48MB, paused 1.510ms total 174.875ms
12-06 11:12:55.571 8508-12969/ I/art: Waiting for a blocking GC Alloc
12-06 11:12:55.571 8508-12968/ I/art: Waiting for a blocking GC Alloc
12-06 11:12:55.572 8508-8518/ I/art: Waiting for a blocking GC Alloc
12-06 11:12:55.572 8508-12969/ I/art: Starting a blocking GC Alloc
12-06 11:12:55.572 8508-12969/ I/art: Starting a blocking GC Alloc
12-06 11:12:55.573 8508-12968/ I/art: Waiting for a blocking GC Alloc
12-06 11:12:55.573 8508-8518/ I/art: Waiting for a blocking GC Alloc
12-06 11:12:55.838 8508-8520/ W/art: Suspending all threads took: 264.429ms
12-06 11:12:55.855 8508-12969/ W/art: Suspending all threads took: 9.401ms
12-06 11:12:55.864 8508-12969/ I/art: Clamp target GC heap from 49MB to 48MB
12-06 11:12:55.865 8508-12969/ I/art: Alloc partial concurrent mark sweep GC freed 4(112B) AllocSpace objects, 0(0B) LOS objects, 0% free, 47MB/48MB, paused 11.078ms total 292.575ms
12-06 11:12:55.865 8508-12968/ I/art: WaitForGcToComplete blocked for 293.555ms for cause Alloc
12-06 11:12:55.865 8508-12968/ I/art: Starting a blocking GC Alloc
12-06 11:12:55.865 8508-8518/ I/art: WaitForGcToComplete blocked for 293.414ms for cause Alloc
12-06 11:12:55.865 8508-8518/ I/art: Starting a blocking GC Alloc
12-06 11:12:55.866 8508-8516/ I/art: Starting a blocking GC Alloc
12-06 11:12:55.866 8508-8516/ I/art: Starting a blocking GC Alloc
12-06 11:12:55.867 8508-12968/ I/art: Waiting for a blocking GC Alloc
12-06 11:12:55.867 8508-8518/ I/art: Waiting for a blocking GC Alloc
12-06 11:12:55.913 8508-8516/ W/art: Suspending all threads took: 7.951ms
12-06 11:12:55.916 8508-8516/ I/art: Alloc sticky concurrent mark sweep GC freed 0(0B) AllocSpace objects, 0(0B) LOS objects, 0% free, 47MB/48MB, paused 9.608ms total 49.524ms
12-06 11:12:55.916 8508-12968/ I/art: WaitForGcToComplete blocked for 48.307ms for cause Alloc
12-06 11:12:55.916 8508-12968/ I/art: Starting a blocking GC Alloc
12-06 11:12:55.918 8508-8518/ I/art: Waiting for a blocking GC Alloc
12-06 11:12:55.943 8508-12968/ W/art: Suspending all threads took: 7.545ms
12-06 11:12:55.945 8508-12968/ I/art: Alloc sticky concurrent mark sweep GC freed 0(0B) AllocSpace objects, 0(0B) LOS objects, 0% free, 47MB/48MB, paused 9.155ms total 28.893ms
12-06 11:12:55.945 8508-8518/ I/art: WaitForGcToComplete blocked for 77.451ms for cause Alloc
12-06 11:12:55.945 8508-8518/ I/art: Starting a blocking GC Alloc
12-06 11:12:55.960 8508-12969/ I/art: Waiting for a blocking GC Alloc
12-06 11:12:55.977 8508-12968/ W/art: Suspending all threads took: 16.287ms
12-06 11:12:55.993 8508-8518/ I/art: Alloc sticky concurrent mark sweep GC freed 0(0B) AllocSpace objects, 0(0B) LOS objects, 0% free, 47MB/48MB, paused 5.012ms total 47.545ms
12-06 11:12:55.993 8508-12969/ I/art: WaitForGcToComplete blocked for 32.647ms for cause Alloc
12-06 11:12:55.993 8508-12969/ I/art: Starting a blocking GC Alloc
12-06 11:12:55.995 8508-12969/ I/art: Starting a blocking GC Alloc
12-06 11:12:56.156 8508-8518/ W/art: Suspending all threads took: 160.805ms
12-06 11:12:56.174 8508-12969/ W/art: Suspending all threads took: 7.028ms
12-06 11:12:56.182 8508-12969/ I/art: Clamp target GC heap from 49MB to 48MB
12-06 11:12:56.182 8508-12969/ I/art: Alloc partial concurrent mark sweep GC freed 6(240B) AllocSpace objects, 0(0B) LOS objects, 0% free, 47MB/48MB, paused 8.747ms total 186.292ms
12-06 11:12:56.182 8508-8516/ I/art: Starting a blocking GC Alloc
12-06 11:12:56.183 8508-8516/ I/art: Starting a blocking GC Alloc
12-06 11:12:56.184 8508-12968/ I/art: Waiting for a blocking GC Alloc
12-06 11:12:56.195 8508-8518/ I/art: Waiting for a blocking GC Alloc
12-06 11:12:56.216 8508-8516/ I/art: Alloc sticky concurrent mark sweep GC freed 0(0B) AllocSpace objects, 0(0B) LOS objects, 0% free, 47MB/48MB, paused 1.500ms total 33.208ms
12-06 11:12:56.216 8508-12968/ I/art: WaitForGcToComplete blocked for 31.953ms for cause Alloc
12-06 11:12:56.216 8508-12968/ I/art: Starting a blocking GC Alloc
12-06 11:12:56.216 8508-8518/ I/art: Waiting for a blocking GC Alloc
12-06 11:12:56.489 8508-8516/ W/art: Suspending all threads took: 263.618ms
12-06 11:12:56.505 8508-12968/ W/art: Suspending all threads took: 10.039ms
12-06 11:12:56.513 8508-12968/ I/art: Clamp target GC heap from 49MB to 48MB
12-06 11:12:56.513 8508-12968/ I/art: Alloc partial concurrent mark sweep GC freed 0(0B) AllocSpace objects, 0(0B) LOS objects, 0% free, 47MB/48MB, paused 11.692ms total 296.623ms
12-06 11:12:56.513 8508-8520/ I/art: WaitForGcToComplete blocked for 329.019ms for cause Background
12-06 11:12:56.513 8508-8518/ I/art: WaitForGcToComplete blocked for 317.946ms for cause Alloc
12-06 11:12:56.513 8508-8518/ I/art: Starting a blocking GC Alloc
```

**Comment by zubaliy** [comment]
And the last logs when the app crashes:

```
12-06 11:13:28.715 8508-8519/? I/art: Waiting for a blocking GC Alloc
12-06 11:13:28.715 8508-8516/? I/art: Waiting for a blocking GC Alloc
12-06 11:13:28.715 8508-8518/? I/art: Waiting for a blocking GC Alloc
12-06 11:13:31.676 8508-8519/? I/art: Alloc partial concurrent mark sweep GC freed 577147(41MB) AllocSpace objects, 0(0B) LOS objects, 24% free, 6MB/8MB, paused 5.064ms total 1.645s
12-06 11:13:31.676 8508-8518/? I/art: WaitForGcToComplete blocked for 2.200s for cause Alloc
12-06 11:13:31.676 8508-8518/? I/art: Starting a blocking GC Alloc
12-06 11:13:31.677 8508-8518/? E/System: java.lang.OutOfMemoryError: OutOfMemoryError thrown while trying to throw OutOfMemoryError; no stack trace available
12-06 11:13:31.677 8508-12968/? I/art: WaitForGcToComplete blocked for 1.897s for cause Alloc
12-06 11:13:31.677 8508-12968/? I/art: Starting a blocking GC Alloc
12-06 11:13:31.677 8508-8516/? I/art: WaitForGcToComplete blocked for 1.631s for cause Alloc
12-06 11:13:31.677 8508-8516/? I/art: Starting a blocking GC Alloc
12-06 11:13:31.677 8508-8516/? W/art: JNI WARNING: java.lang.OutOfMemoryError thrown while calling printStackTrace
12-06 11:13:31.680 8508-12969/? I/art: WaitForGcToComplete blocked for 1.602s for cause Alloc
12-06 11:13:31.680 8508-12969/? I/art: Starting a blocking GC Alloc
12-06 11:13:31.684 8508-12969/? E/AndroidRuntime: Error reporting crash
                                                  java.lang.OutOfMemoryError: Failed to allocate a 64 byte allocation with 3640 free bytes and 3KB until OOM
                                                      at java.lang.AbstractStringBuilder.enlargeBuffer(AbstractStringBuilder.java:95)
                                                      at java.lang.AbstractStringBuilder.append0(AbstractStringBuilder.java:146)
                                                      at java.lang.StringBuilder.append(StringBuilder.java:216)
                                                      at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:80)
                                                      at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
                                                      at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
```

**Comment by zubaliy** [comment]
And the last logs when the app crashes:

```
12-06 11:13:28.715 8508-8519/? I/art: Waiting for a blocking GC Alloc
12-06 11:13:28.715 8508-8516/? I/art: Waiting for a blocking GC Alloc
12-06 11:13:28.715 8508-8518/? I/art: Waiting for a blocking GC Alloc
12-06 11:13:31.676 8508-8519/? I/art: Alloc partial concurrent mark sweep GC freed 577147(41MB) AllocSpace objects, 0(0B) LOS objects, 24% free, 6MB/8MB, paused 5.064ms total 1.645s
12-06 11:13:31.676 8508-8518/? I/art: WaitForGcToComplete blocked for 2.200s for cause Alloc
12-06 11:13:31.676 8508-8518/? I/art: Starting a blocking GC Alloc
12-06 11:13:31.677 8508-8518/? E/System: java.lang.OutOfMemoryError: OutOfMemoryError thrown while trying to throw OutOfMemoryError; no stack trace available
12-06 11:13:31.677 8508-12968/? I/art: WaitForGcToComplete blocked for 1.897s for cause Alloc
12-06 11:13:31.677 8508-12968/? I/art: Starting a blocking GC Alloc
12-06 11:13:31.677 8508-8516/? I/art: WaitForGcToComplete blocked for 1.631s for cause Alloc
12-06 11:13:31.677 8508-8516/? I/art: Starting a blocking GC Alloc
12-06 11:13:31.677 8508-8516/? W/art: JNI WARNING: java.lang.OutOfMemoryError thrown while calling printStackTrace
12-06 11:13:31.680 8508-12969/? I/art: WaitForGcToComplete blocked for 1.602s for cause Alloc
12-06 11:13:31.680 8508-12969/? I/art: Starting a blocking GC Alloc
12-06 11:13:31.684 8508-12969/? E/AndroidRuntime: Error reporting crash
                                                  java.lang.OutOfMemoryError: Failed to allocate a 64 byte allocation with 3640 free bytes and 3KB until OOM
                                                      at java.lang.AbstractStringBuilder.enlargeBuffer(AbstractStringBuilder.java:95)
                                                      at java.lang.AbstractStringBuilder.append0(AbstractStringBuilder.java:146)
                                                      at java.lang.StringBuilder.append(StringBuilder.java:216)
                                                      at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:80)
                                                      at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
                                                      at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
```

**Comment by zubaliy** [comment]
I am using the latest version of cb lite:
couchbase-lite-android:1.3.1

**Comment by NitzDKoder** [comment]
@pasin @hideki please share your thoughts on this bug..

**Comment by pasin** [comment]
@NitzDKoder The stacktrace above couldn't tell much of the info what caused the memory issue. Is it the full stacktrace? Could you do memory profiling and share the result?

**Comment by NitzDKoder** [comment]
@pasin ok will try to get the full stacktrace.

**App:**
1) CBL 1.4.1 with phonegap- cbl listener active and remote sync on.
2)Heap size for per app is 96MB. Samsung J3 device.


**Test case Scenario::**


Client was activated over Wi-Fi.
Kept for network transitions automation 
Steps of the test: Wi-Fi and 3G data are enabled.
1. Wi-Fi goes down
2. 3G data goes down
3. 3G data comes up
4. Wi-Fi comes up 
5. Turn onAirplane mode
6. Turn of Airplane mode
Observation::

**App crashed after 450 iterations while creating threads in app.**

**09-18 00:10:47.443 E/AndroidRuntime(25495): FATAL EXCEPTION: main**
09-18 00:10:47.443 E/AndroidRuntime(25495): Process: com.att.eptt, PID: 25495
09-18 00:10:47.443 E/AndroidRuntime(25495): java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Try again
09-18 00:10:47.443 E/AndroidRuntime(25495): 	at java.lang.Thread.nativeCreate(Native Method)
09-18 00:10:47.443 E/AndroidRuntime(25495): 	at java.lang.Thread.start(Thread.java:733)
