### ISSUE TITLE
CouchbaseLiteException: getViewID() < 0, Status: 404 (HTTP 404 not_found)

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-java-core#1524]
https://github.com/couchbase/couchbase-lite-java-core/issues/1312#issuecomment-263731998

We have published an app update these days with CBL `1.3.1-90` and we have received for the first time errors like this:

Android OS: 6.0.1
```
AbstractView( 6667): Error querying view reminder_by_status_view.
Caused by: com.couchbase.lite.CouchbaseLiteException: getViewID() < 0, Status: 404 (HTTP 404 not_found)
at com.couchbase.lite.store.SQLiteViewStore.updateIndexes(SQLiteViewStore.java:250)
at com.couchbase.lite.View.updateIndexes(View.java:321)
at com.couchbase.lite.View.updateIndex(View.java:294)
at com.couchbase.lite.Database.queryViewNamed(Database.java:2442)
at com.couchbase.lite.Query.run(Query.java:446)
at net.dzomba.termin3.model.couchdb.dbviews.AbstractView.refresh(AbstractView.java:60)
... 24 more
```

The views that are mentioned in these errors are the one that did not exist before in the previous versions of our app and users that we get these errors from have already used the app, i.e. they have updated the app.

I've seen the milestone 1.3.1 for this issue. Am I using the wrong CBL version or there may be something else going on?

Thanks!

**Comment by kombadzomba** [comment]
Hi @hideki,

I was wondering if this issue may be the cause of #985 SQLiteDatabaseCorruptException. I am suggesting this since we got the SQLiteDatabaseCorruptException from the same user one hour after the  getViewID() < 0 error.

Thanks.

**Comment by hideki** [comment]
Hi @kombadzomba,

It is interesting. When `getViewID() < 0` error occurs, the database corruption could be occurred. Is it possible to capture logcat from the user's device?

Thanks!

**Comment by kombadzomba** [comment]
Hi @hideki,

[Here](https://gist.github.com/kombadzomba/64302d0a58e77b4474121b1e8057853e) is the logcat. Last 100 lines is all we have.

Thanks!
