### ISSUE TITLE
CBForest ERROR: key not found (-9)

### ISSUE THREAD

**Issue by mvysny** [couchbase/couchbase-lite-java-core#1529]
Occasionally (say, one of ten times), when the database is created, then the Views are created and then a Query is immediately executed, the Query will fail with the following exception:

```
CBForest ERROR: key not found (-9)

Dec 13, 2016 12:04:00 PM com.couchbase.lite.util.SystemLogger e
SEVERE: View: Error in regularQuery()
com.couchbase.cbforest.ForestException: key not found
	at com.couchbase.cbforest.ForestException.throwException(ForestException.java:24)
	at com.couchbase.cbforest.QueryIterator.next(Native Method)
	at com.couchbase.cbforest.QueryIterator.next(QueryIterator.java:21)
	at com.couchbase.lite.store.ForestDBViewStore.regularQuery(ForestDBViewStore.java:397)
	at com.couchbase.lite.View.query(View.java:358)
	at com.couchbase.lite.Database.queryViewNamed(Database.java:2194)
	at com.couchbase.lite.Query.run(Query.java:446)
	at sk.baka.aedict.userdatastorage.couchbaselite.ViewNotepadCategoryByItemKeys.find(NotepadCBL.kt:90)
	at sk.baka.aedict.userdatastorage.couchbaselite.NotepadCBL.findEntry(NotepadCBL.kt:276)
	at sk.baka.aedict.userdatastorage.couchbaselite.NotepadCBLTest$performanceFindEntry$3.invoke(NotepadCBLTest.kt:146)
	at sk.baka.aedict.userdatastorage.couchbaselite.NotepadCBLTest$performanceFindEntry$3.invoke(NotepadCBLTest.kt:11)
	at kotlin.test.AssertionsKt__TestAssertionsKt.expect(TestAssertions.kt:63)
	at kotlin.test.AssertionsKt.expect(Unknown Source)
	at sk.baka.aedict.userdatastorage.couchbaselite.NotepadCBLTest.performanceFindEntry(NotepadCBLTest.kt:146)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:119)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
```

I'm not using any background threads, this is all invoked in a single thread. Yet, there must be some threading issue at work here, because the issue only happens occasionally.

**Comment by mvysny** [comment]
I'm using com.couchbase.lite:couchbase-lite-java-forestdb:1.3.1
