### ISSUE TITLE
P2P fails between android and macosx

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/couchbase-lite-java-core#1552]
Using Android 1.4-8 and Mac OSX 1.4-22

Failing Jenkins job - http://uberjenkins.sc.couchbase.com/job/android-listener-client-client/16/

Failing test - https://github.com/couchbaselabs/mobile-testkit/blob/master/testsuites/listener/shared/client_client/test_peer_2_peer_sanity.py#L97-L181

```
01-12 20:57:58.940  1976  2009 V Listener: RouterCallbackBlock.onResponseReady() END
01-12 20:57:58.940  1976  2009 V Listener: CountDownLatch.await() START
01-12 20:57:58.940  1976  2009 V Listener: CountDownLatch.await() END
01-12 20:57:58.941  1976  2009 W System.err: [Thu Jan 12 20:57:58 EST 2017] TJWS: IO error: java.net.SocketException: sendto failed: EBADF (Bad file descriptor) in processing a request /ls_db1/_changes from /192.168.0.14:5984 / java.net.Socket
01-12 20:58:08.927  1976  2008 W ChangeTracker: ChangeTracker{http://192.168.0.14:51000/ls_db2, OneShot, @92d6d5b}: Exception in change tracker
01-12 20:58:08.927  1976  2008 W ChangeTracker: java.net.SocketTimeoutException
01-12 20:58:08.927  1976  2008 W ChangeTracker: 	at java.net.PlainSocketImpl.read(PlainSocketImpl.java:484)
01-12 20:58:08.927  1976  2008 W ChangeTracker: 	at java.net.PlainSocketImpl.-wrap0(PlainSocketImpl.java)
01-12 20:58:08.927  1976  2008 W ChangeTracker: 	at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)
01-12 20:58:08.927  1976  2008 W ChangeTracker: 	at okio.Okio$2.read(Okio.java:140)
01-12 20:58:08.927  1976  2008 W ChangeTracker: 	at okio.AsyncTimeout$2.read(AsyncTimeout.java:238)
01-12 20:58:08.927  1976  2008 W ChangeTracker: 	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:325)
01-12 20:58:08.927  1976  2008 W ChangeTracker: 	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:314)
01-12 20:58:08.927  1976  2008 W ChangeTracker: 	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:210)
01-12 20:58:08.927  1976  2008 W ChangeTracker: 	at okhttp3.internal.http.Http1xStream.readResponse(Http1xStream.java:184)
01-12 20:58:08.927  1976  2008 W ChangeTracker: 	at okhttp3.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:125)
01-12 20:58:08.927  1976  2008 W ChangeTracker: 	at okhttp3.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:775)
01-12 20:58:08.927  1976  2008 W ChangeTracker: 	at okhttp3.internal.http.HttpEngine.access$200(HttpEngine.java:86)
01-12 20:58:08.927  1976  2008 W ChangeTracker: 	at okhttp3.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:760)
01-12 20:58:08.927  1976  2008 W ChangeTracker: 	at okhttp3.internal.http.HttpEngine.readResponse(HttpEngine.java:613)
01-12 20:58:08.927  1976  2008 W ChangeTracker: 	at okhttp3.RealCall.getResponse(RealCall.java:244)
01-12 20:58:08.927  1976  2008 W ChangeTracker: 	at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:201)
01-12 20:58:08.927  1976  2008 W ChangeTracker: 	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:163)
01-12 20:58:08.927  1976  2008 W ChangeTracker: 	at okhttp3.RealCall.execute(RealCall.java:57)
01-12 20:58:08.927  1976  2008 W ChangeTracker: 	at com.couchbase.lite.replicator.ChangeTracker.runLoop(ChangeTracker.java:336)
01-12 20:58:08.927  1976  2008 W ChangeTracker: 	at com.couchbase.lite.replicator.ChangeTracker.run(ChangeTracker.java:246)
01-12 20:58:08.927  1976  2008 W ChangeTracker: 	at java.lang.Thread.run(Thread.java:818)
01-12 20:58:08.928  1976  2008 V ChangeTracker: ChangeTracker{http://192.168.0.14:51000/ls_db2, OneShot, @92d6d5b}: Making request to POST [http://192.168.0.14:51000/ls_db2/_changes?feed=longpoll&heartbeat=30000&style=all_docs&active_only=true]
01-12 20:58:30.951  1976  1996 D Listener: authHeader is null
01-12 20:58:30.951  1976  1996 V Listener: Not enforcing basic auth -- allowedCredentials null or empty
01-12 20:58:30.951  1976  1996 V Listener: remoteURL() addr=192.168.0.14
01-12 20:58:30.952  1976  1996 V Listener: RouterCallbackBlock.onResponseReady() START
01-12 20:58:30.952  1976  1996 V Listener: RouterCallbackBlock.onResponseReady() END
01-12 20:58:30.952  1976  1996 V Listener: CountDownLatch.await() START
01-12 20:58:30.952  1976  1996 V Listener: CountDownLatch.await() END
```

Full adb logcat - https://gist.github.com/sethrosetter/d10a10335a777b15510f4a753b8b5ae2

**Comment by hideki** [comment]
This solution does not work for `Map`
```java
.setSerializationInclusion(JsonInclude.Include.NON_NULL)
```
