### ISSUE TITLE
Database deletion failing with 1.4-25

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/couchbase-lite-java-core#1563]
Failing test - http://uberjenkins.sc.couchbase.com/job/android-listener-client-sync-gateway/65/testReport/junit/testsuites.listener.shared.client_sg/test_changes/test_longpoll_changes_termination_heartbeat/

```
V/Listener( 1677): remoteURL() addr=10.17.1.40
V/Database( 1677): Acme.Utils.ThreadPool(19)-PooledThread: Acme.Serve.Serve$ServeConnection@53593bb4 Committing transaction (level 0)
V/Database( 1677): No pending doc expirations
V/Router  ( 1677): waiting=true & db!=null: call Database.addDatabaseListener()
V/Listener( 1677): CountDownLatch.await() START
V/Router  ( 1677): waiting=true & db!=null: call Database.addDatabaseListener()
V/Listener( 1677): CountDownLatch.await() START
V/Router  ( 1677): waiting=true & db!=null: call Database.addDatabaseListener()
V/Listener( 1677): CountDownLatch.await() START
V/Router  ( 1677): waiting=true & db!=null: call Database.addDatabaseListener()
V/Listener( 1677): CountDownLatch.await() START
V/Router  ( 1677): waiting=true & db!=null: call Database.addDatabaseListener()
V/Listener( 1677): CountDownLatch.await() START
V/Router  ( 1677): waiting=true & db!=null: call Database.addDatabaseListener()
V/Listener( 1677): CountDownLatch.await() START
V/Database( 1677): Acme.Utils.ThreadPool(12)-PooledThread: Acme.Serve.Serve$ServeConnection@535c5b1c Begin transaction (level 0)
E/Database( 1677): Failed to execSQL: CREATE TABLE docs (         doc_id INTEGER PRIMARY KEY,         docid TEXT UNIQUE NOT NULL)
E/Database( 1677): com.couchbase.lite.storage.SQLException: com.couchbase.lite.internal.database.sqlite.exception.SQLiteException: table docs already exists (code 1)
E/Database( 1677): 	at com.couchbase.lite.storage.SQLiteStorageEngineBase.execSQL(SQLiteStorageEngineBase.java:168)
E/Database( 1677): 	at com.couchbase.lite.store.SQLiteStore.runStatements(SQLiteStore.java:2614)
E/Database( 1677): 	at com.couchbase.lite.store.SQLiteStore.initialize(SQLiteStore.java:2624)
E/Database( 1677): 	at com.couchbase.lite.store.SQLiteStore.open(SQLiteStore.java:254)
E/Database( 1677): 	at com.couchbase.lite.Database.open(Database.java:1338)
E/Database( 1677): 	at com.couchbase.lite.Database.open(Database.java:1272)
E/Database( 1677): 	at com.couchbase.lite.router.Router.openDB(Router.java:358)
E/Database( 1677): 	at com.couchbase.lite.router.Router.start(Router.java:477)
E/Database( 1677): 	at com.couchbase.lite.listener.LiteServlet.service(LiteServlet.java:141)
E/Database( 1677): 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)
E/Database( 1677): 	at Acme.Serve.Serve$ServeConnection.runServlet(Serve.java:2408)
E/Database( 1677): 	at Acme.Serve.Serve$ServeConnection.parseRequest(Serve.java:2330)
E/Database( 1677): 	at Acme.Serve.Serve$ServeConnection.run(Serve.java:2110)
E/Database( 1677): 	at Acme.Utils$ThreadPool$PooledThread.run(Utils.java:1238)
E/Database( 1677): 	at java.lang.Thread.run(Thread.java:856)
E/Database( 1677): Caused by: com.couchbase.lite.internal.database.sqlite.exception.SQLiteException: table docs already exists (code 1)
E/Database( 1677): 	at com.couchbase.lite.internal.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
E/Database( 1677): 	at com.couchbase.lite.internal.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:617)
E/Database( 1677): 	at com.couchbase.lite.internal.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:725)
E/Database( 1677): 	at com.couchbase.lite.internal.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:67)
E/Database( 1677): 	at com.couchbase.lite.internal.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1660)
E/Database( 1677): 	at com.couchbase.lite.internal.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1589)
E/Database( 1677): 	at com.couchbase.lite.storage.SQLiteStorageEngineBase.execSQL(SQLiteStorageEngineBase.java:166)
E/Database( 1677): 	... 14 more
E/Database( 1677): Cannot initialize database schema
E/Database( 1677): com.couchbase.lite.storage.SQLException: com.couchbase.lite.internal.database.sqlite.exception.SQLiteException: table docs already exists (code 1)
E/Database( 1677): 	at com.couchbase.lite.storage.SQLiteStorageEngineBase.execSQL(SQLiteStorageEngineBase.java:168)
E/Database( 1677): 	at com.couchbase.lite.store.SQLiteStore.runStatements(SQLiteStore.java:2614)
E/Database( 1677): 	at com.couchbase.lite.store.SQLiteStore.initialize(SQLiteStore.java:2624)
E/Database( 1677): 	at com.couchbase.lite.store.SQLiteStore.open(SQLiteStore.java:254)
E/Database( 1677): 	at com.couchbase.lite.Database.open(Database.java:1338)
E/Database( 1677): 	at com.couchbase.lite.Database.open(Database.java:1272)
E/Database( 1677): 	at com.couchbase.lite.router.Router.openDB(Router.java:358)
E/Database( 1677): 	at com.couchbase.lite.router.Router.start(Router.java:477)
E/Database( 1677): 	at com.couchbase.lite.listener.LiteServlet.service(LiteServlet.java:141)
E/Database( 1677): 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)
E/Database( 1677): 	at Acme.Serve.Serve$ServeConnection.runServlet(Serve.java:2408)
E/Database( 1677): 	at Acme.Serve.Serve$ServeConnection.parseRequest(Serve.java:2330)
E/Database( 1677): 	at Acme.Serve.Serve$ServeConnection.run(Serve.java:2110)
E/Database( 1677): 	at Acme.Utils$ThreadPool$PooledThread.run(Utils.java:1238)
E/Database( 1677): 	at java.lang.Thread.run(Thread.java:856)
E/Database( 1677): Caused by: com.couchbase.lite.internal.database.sqlite.exception.SQLiteException: table docs already exists (code 1)
E/Database( 1677): 	at com.couchbase.lite.internal.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
E/Database( 1677): 	at com.couchbase.lite.internal.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:617)
E/Database( 1677): 	at com.couchbase.lite.internal.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:725)
E/Database( 1677): 	at com.couchbase.lite.internal.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:67)
E/Database( 1677): 	at com.couchbase.lite.internal.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1660)
E/Database( 1677): 	at com.couchbase.lite.internal.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1589)
E/Database( 1677): 	at com.couchbase.lite.storage.SQLiteStorageEngineBase.execSQL(SQLiteStorageEngineBase.java:166)
E/Database( 1677): 	... 14 more
V/Database( 1677): Acme.Utils.ThreadPool(12)-PooledThread: Acme.Serve.Serve$ServeConnection@535c5b1c CANCEL transaction (level 0)
W/System.err( 1677): [Thu Jan 19 01:53:54 GMT 2017] TJWS: Unexpected problem running servlet
W/System.err( 1677): java.lang.NullPointerException
W/System.err( 1677): 	at com.couchbase.lite.store.SQLiteStore.endTransaction(SQLiteStore.java:2417)
W/System.err( 1677): 	at com.couchbase.lite.store.SQLiteStore.open(SQLiteStore.java:313)
W/System.err( 1677): 	at com.couchbase.lite.Database.open(Database.java:1338)
W/System.err( 1677): 	at com.couchbase.lite.Database.open(Database.java:1272)
W/System.err( 1677): 	at com.couchbase.lite.router.Router.openDB(Router.java:358)
W/System.err( 1677): 	at com.couchbase.lite.router.Router.start(Router.java:477)
W/System.err( 1677): 	at com.couchbase.lite.listener.LiteServlet.service(LiteServlet.java:141)
W/System.err( 1677): 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)
W/System.err( 1677): 	at Acme.Serve.Serve$ServeConnection.runServlet(Serve.java:2408)
W/System.err( 1677): 	at Acme.Serve.Serve$ServeConnection.parseRequest(Serve.java:2330)
W/System.err( 1677): 	at Acme.Serve.Serve$ServeConnection.run(Serve.java:2110)
W/System.err( 1677): 	at Acme.Utils$ThreadPool$PooledThread.run(Utils.java:1238)
W/System.err( 1677): 	at java.lang.Thread.run(Thread.java:856)
W/System.err( 1677): [Thu Jan 19 01:53:54 GMT 2017] TJWS: Unexpected problem running servlet: java.lang.NullPointerException
D/dalvikvm( 1677): GC_FOR_ALLOC freed 503K, 13% free 8196K/9415K, paused 3ms, total 3ms
D/dalvikvm( 1677): GC_CONCURRENT freed 22K, 14% free 8174K/9415K, paused 12ms+0ms, total 14ms
V/Router  ( 1677): waiting=true & db!=null: call Database.addDatabaseListener()
V/Listener( 1677): CountDownLatch.await() START
V/Router  ( 1677): waiting=true & db!=null: call Database.addDatabaseListener()
V/Listener( 1677): CountDownLatch.await() START
V/Router  ( 1677): waiting=true & db!=null: call Database.addDatabaseListener()
V/Listener( 1677): CountDownLatch.await() START
V/Router  ( 1677): waiting=true & db!=null: call Database.addDatabaseListener()
V/Listener( 1677): CountDownLatch.await() START
V/Router  ( 1677): waiting=true & db!=null: call Database.addDatabaseListener()
V/Listener( 1677): CountDownLatch.await() START
V/Router  ( 1677): waiting=true & db!=null: call Database.addDatabaseListener()
V/Listener( 1677): CountDownLatch.await() START
```

Full logcat - http://uberjenkins.sc.couchbase.com/job/android-listener-client-sync-gateway/65/artifact/results/logs/LiteServAndroid-test_longpoll_changes_termination_heartbeat-2017-01-18%2017%3A53%3A51.401301.txt

**Comment by hideki** [comment]
Note to self:
When `endTransaction()` is called, DB is already closed. I believe this is multi-threading issue.
