### ISSUE TITLE
SSL with allowSelfSignedSSLCertificates() method

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-java-core#1575]
https://forums.couchbase.com/t/android-couchbase-api/11470/7

```
01-30 12:19:42.544 3856-4260/fi.abo.signav W/RemoteRequest: com.couchbase.lite.replicator.RemoteRequest {GET, https://server/bucket/_local/ba173e52053639e34e7f0a7e12e89bbaf041c5b7}: executeRequest() Exception: javax.net.ssl.SSLPeerUnverifiedException: Hostname server not verified:
        certificate: sha256/caHUXyhGESZo2ETOnGYWcnymS5k3RdQsdbQJ8v+Q3+I=
        subjectAltNames: [].  url: https://server/bucket/_local/ba173e52053639e34e7f0a7e12e89bbaf041c5b7
    javax.net.ssl.SSLPeerUnverifiedException: Hostname server not verified:
        certificate: sha256/caHUXyhGESZo2ETOnGYWcnymS5k3RdQsdbQJ8v+Q3+I=
        subjectAltNames: []
        at okhttp3.internal.io.RealConnection.connectTls(RealConnection.java:248)
        at okhttp3.internal.io.RealConnection.establishProtocol(RealConnection.java:196)
        at okhttp3.internal.io.RealConnection.buildConnection(RealConnection.java:171)
        at okhttp3.internal.io.RealConnection.connect(RealConnection.java:111)
        at okhttp3.internal.http.StreamAllocation.findConnection(StreamAllocation.java:187)
        at okhttp3.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:123)
        at okhttp3.internal.http.StreamAllocation.newStream(StreamAllocation.java:93)
        at okhttp3.internal.http.HttpEngine.connect(HttpEngine.java:296)
        at okhttp3.internal.http.HttpEngine.sendRequest(HttpEngine.java:248)
        at okhttp3.RealCall.getResponse(RealCall.java:243)
        at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:201)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:163)
        at okhttp3.RealCall.execute(RealCall.java:57)
        at com.couchbase.lite.replicator.RemoteRequest.executeRequest(RemoteRequest.java:261)
        at com.couchbase.lite.replicator.RemoteRequest.execute(RemoteRequest.java:165)
        at com.couchbase.lite.replicator.RemoteRequest.run(RemoteRequest.java:105)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)
```

**Comment by hideki** [comment]
Note to self:

Error occurs with hostname verification.
```
 javax.net.ssl.SSLPeerUnverifiedException: Hostname server not verified:
```

Need to add `HostnameVerifier` for `allowSelfSignedSSLCertificates()` method.
```java
final OkHttpClient okHttpClient = new OkHttpClient.Builder()
        .sslSocketFactory(sslContext.getSocketFactory())
        .hostnameVerifier(new HostnameVerifier() {
            @Override
            public boolean verify(final String hostname, final SSLSession session) {
                return true;
            }
        })
        .build();
```
