### ISSUE TITLE
Replication failures when running Sync Gateway in distributed index

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/couchbase-lite-java-core#1581]
Android - 1.4-36
SG version - 1.4-65
SG mode - DI
CBS version - 4.5.1

Test failures - http://uberjenkins.sc.couchbase.com/job/android-listener-client-sync-gateway/129/. These tests pass when running in channel cache.

According to @hideki, the replicators are all in a wait state.

**Comment by hideki** [comment]
Notes to self:

- The test can pass if a number of documents is 1000 instead of 10000.

**Comment by hideki** [comment]
Notes to self:

All pull replicator threads become the wait state. Batcher size does not decrease.
```
Full thread dump

"<14> Acme.Utils.ThreadPool(0)-PooledThread: Acme.Serve.Serve$ServeConnection@528a1a60@831697594064" daemon prio=5 waiting
  java.lang.Thread.State: WAITING
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.Thread.parkFor(Thread.java:1205)
	  at sun.misc.Unsafe.park(Unsafe.java:325)
	  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:813)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:973)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1281)
	  at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:202)
	  at com.couchbase.lite.listener.LiteServlet.service(LiteServlet.java:145)
	  at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)
	  at Acme.Serve.Serve$ServeConnection.runServlet(Serve.java:2408)
	  at Acme.Serve.Serve$ServeConnection.parseRequest(Serve.java:2330)
	  at Acme.Serve.Serve$ServeConnection.run(Serve.java:2110)
	  at Acme.Utils$ThreadPool$PooledThread.run(Utils.java:1238)
	  at java.lang.Thread.run(Thread.java:841)

"<25> CBLRequestWorker-http://192.168.33.11:4985/db-pull-ff2b7-4@831700574032" prio=5 waiting
  java.lang.Thread.State: WAITING
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.Thread.parkFor(Thread.java:1205)
	  at sun.misc.Unsafe.park(Unsafe.java:325)
	  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2017)
	  at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1050)
	  at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:778)
	  at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1035)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1097)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	  at java.lang.Thread.run(Thread.java:841)

"<24> CBLRequestWorker-http://192.168.33.11:4985/db-pull-ff2b7-3@831701909976" prio=5 waiting
  java.lang.Thread.State: WAITING
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.Thread.parkFor(Thread.java:1205)
	  at sun.misc.Unsafe.park(Unsafe.java:325)
	  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2017)
	  at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1050)
	  at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:778)
	  at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1035)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1097)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	  at java.lang.Thread.run(Thread.java:841)

"<23> CBLRequestWorker-http://192.168.33.11:4985/db-pull-ff2b7-2@831699186264" prio=5 waiting
  java.lang.Thread.State: WAITING
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.Thread.parkFor(Thread.java:1205)
	  at sun.misc.Unsafe.park(Unsafe.java:325)
	  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2017)
	  at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1050)
	  at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:778)
	  at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1035)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1097)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	  at java.lang.Thread.run(Thread.java:841)

"<22> CBLRequestWorker-http://192.168.33.11:4985/db-pull-ff2b7-1@831698371520" prio=5 waiting
  java.lang.Thread.State: WAITING
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.Thread.parkFor(Thread.java:1205)
	  at sun.misc.Unsafe.park(Unsafe.java:325)
	  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2017)
	  at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1050)
	  at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:778)
	  at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1035)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1097)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	  at java.lang.Thread.run(Thread.java:841)

"<18> CBLRequestWorker-http://192.168.33.11:4985/db-pull-ff2b7-0@831698351960" prio=5 waiting
  java.lang.Thread.State: WAITING
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.Thread.parkFor(Thread.java:1205)
	  at sun.misc.Unsafe.park(Unsafe.java:325)
	  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2017)
	  at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1050)
	  at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:778)
	  at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1035)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1097)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	  at java.lang.Thread.run(Thread.java:841)

"<17> CBLReplicationExecutor-http://192.168.33.11:4985/db-pull-ff2b7@831698011160" prio=5 waiting
  java.lang.Thread.State: WAITING
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.Thread.parkFor(Thread.java:1205)
	  at sun.misc.Unsafe.park(Unsafe.java:325)
	  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2017)
	  at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1050)
	  at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:778)
	  at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1035)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1097)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	  at java.lang.Thread.run(Thread.java:841)

"<11> Thread-111@831697828400" prio=5 runnable
  java.lang.Thread.State: RUNNABLE
	  at libcore.io.Posix.accept(Posix.java:-1)
	  at libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55)
	  at java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98)
	  at java.net.ServerSocket.implAccept(ServerSocket.java:203)
	  at java.net.ServerSocket.accept(ServerSocket.java:128)
	  at Acme.Serve.SimpleAcceptor.accept(SimpleAcceptor.java:40)
	  at Acme.Serve.Serve.serve(Serve.java:849)
	  at com.couchbase.lite.listener.LiteServer.serve(LiteServer.java:63)
	  at com.couchbase.lite.listener.LiteListener.run(LiteListener.java:90)
	  at java.lang.Thread.run(Thread.java:841)
```

**Comment by hideki** [comment]
Some reason, some tasks in `downloadsToInsert` Batcher queue are not processed.

It seems following fix caused this problem.
https://github.com/couchbase/couchbase-lite-java-core/commit/9752afb007b885101638742c6db2d9b1cd270f10

By commented out the above changes, it is able to pass the tests.
