### ISSUE TITLE
Database error with peer-2-peer-sanity test

### ISSUE THREAD

**Issue by raghusarangapani** [couchbase/couchbase-lite-java-core#1595]
I was running the peer to peer sanity test in a loop between net-mono and android-forestdb.

`
while :; do; pytest -s --pdb --liteserv-one-platform=android --liteserv-one-version=1.4-41 --liteserv-one-host=<Android_IP> --liteserv-one-port=50000 --liteserv-one-storage-engine=ForestDB --liteserv-two-platform=net-mono --liteserv-two-version=1.4-39 --liteserv-two-host=<MacOSX_IP> --liteserv-two-port=51000 --liteserv-two-storage-engine=SQLite testsuites/listener/shared/client_client/; sleep 1; done
`

The test worked fine for a while and then errored out with the below trace:

```
V/Database( 6458): getDatabase() com.couchbase.lite.Manager@536d99c4 com.couchbase.lite.Database@536dac14[/data/data/com.couchbase.liteservandroid/files/ls_db1.cblite2]
E/CBForest( 6458): Assertion failed: _transaction (../vendor/cbforest/C/c4Impl.hh:164, in cbforest::Transaction *c4Database::transaction())
E/Database( 6458): [ForestDBStore.runInTransaction()] Error in TransactionalTask
E/Database( 6458): java.lang.RuntimeException: com.couchbase.lite.CouchbaseLiteException, Status: 590 (HTTP 500 Database error!)
E/Database( 6458): 	at com.couchbase.lite.router.Router$9.run(Router.java:2247)
E/Database( 6458): 	at com.couchbase.lite.store.ForestDBStore.runInTransaction(ForestDBStore.java:306)
E/Database( 6458): 	at com.couchbase.lite.Database.runInTransaction(Database.java:646)
E/Database( 6458): 	at com.couchbase.lite.router.Router.update(Router.java:2239)
E/Database( 6458): 	at com.couchbase.lite.router.Router.update(Router.java:2317)
E/Database( 6458): 	at com.couchbase.lite.router.Router.do_PUT_Document(Router.java:2353)
E/Database( 6458): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/Database( 6458): 	at java.lang.reflect.Method.invoke(Method.java:511)
E/Database( 6458): 	at com.couchbase.lite.router.Router.start(Router.java:557)
E/Database( 6458): 	at com.couchbase.lite.listener.LiteServlet.service(LiteServlet.java:147)
E/Database( 6458): 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)
E/Database( 6458): 	at Acme.Serve.Serve$ServeConnection.runServlet(Serve.java:2408)
E/Database( 6458): 	at Acme.Serve.Serve$ServeConnection.parseRequest(Serve.java:2330)
E/Database( 6458): 	at Acme.Serve.Serve$ServeConnection.run(Serve.java:2110)
E/Database( 6458): 	at Acme.Utils$ThreadPool$PooledThread.run(Utils.java:1238)
E/Database( 6458): 	at java.lang.Thread.run(Thread.java:856)
E/Database( 6458): Caused by: com.couchbase.lite.CouchbaseLiteException, Status: 590 (HTTP 500 Database error!)
E/Database( 6458): 	at com.couchbase.lite.store.ForestDBStore.putLocalRevision(ForestDBStore.java:1344)
E/Database( 6458): 	at com.couchbase.lite.Database.putLocalRevision(Database.java:2342)
E/Database( 6458): 	at com.couchbase.lite.router.Router$9.run(Router.java:2243)
E/Database( 6458): 	... 15 more
E/Router  ( 6458): Error updating doc: _local/e0b848ba4c01cf3c3a4e3ca3609f9da7a0b4d458
E/Router  ( 6458): com.couchbase.lite.CouchbaseLiteException, Status: 590 (HTTP 500 Database error!)
E/Router  ( 6458): 	at com.couchbase.lite.store.ForestDBStore.putLocalRevision(ForestDBStore.java:1344)
E/Router  ( 6458): 	at com.couchbase.lite.Database.putLocalRevision(Database.java:2342)
E/Router  ( 6458): 	at com.couchbase.lite.router.Router$9.run(Router.java:2243)
E/Router  ( 6458): 	at com.couchbase.lite.store.ForestDBStore.runInTransaction(ForestDBStore.java:306)
E/Router  ( 6458): 	at com.couchbase.lite.Database.runInTransaction(Database.java:646)
E/Router  ( 6458): 	at com.couchbase.lite.router.Router.update(Router.java:2239)
E/Router  ( 6458): 	at com.couchbase.lite.router.Router.update(Router.java:2317)
E/Router  ( 6458): 	at com.couchbase.lite.router.Router.do_PUT_Document(Router.java:2353)
E/Router  ( 6458): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/Router  ( 6458): 	at java.lang.reflect.Method.invoke(Method.java:511)
E/Router  ( 6458): 	at com.couchbase.lite.router.Router.start(Router.java:557)
E/Router  ( 6458): 	at com.couchbase.lite.listener.LiteServlet.service(LiteServlet.java:147)
E/Router  ( 6458): 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)
E/Router  ( 6458): 	at Acme.Serve.Serve$ServeConnection.runServlet(Serve.java:2408)
E/Router  ( 6458): 	at Acme.Serve.Serve$ServeConnection.parseRequest(Serve.java:2330)
E/Router  ( 6458): 	at Acme.Serve.Serve$ServeConnection.run(Serve.java:2110)
E/Router  ( 6458): 	at Acme.Utils$ThreadPool$PooledThread.run(Utils.java:1238)
E/Router  ( 6458): 	at java.lang.Thread.run(Thread.java:856)
```

**Comment by hideki** [comment]
This is duplicated with #1597.
