### ISSUE TITLE
Replication error: "No existing revision found with doc id" with p2p replication

### ISSUE THREAD

**Issue by tleyden** [couchbase/couchbase-lite-java-core#161]
As reported in [google groups](https://groups.google.com/d/msgid/mobile-couchbase/E1C36834-F6A2-4CF9-918B-13A6584541F4%40couchbase.com?utm_medium=email&utm_source=footer), the following error is happening:

```
04-16 11:31:25.033: W/System.err(749): com.couchbase.lite.CouchbaseLiteException: No existing revision found with doc id: 4237ce67-922b-46a9-9d5d-54f0c6504cc5
04-16 11:31:25.033: W/System.err(749):  at com.couchbase.lite.Database.putRevision(Database.java:2981)
04-16 11:31:25.033: W/System.err(749):  at com.couchbase.lite.Database.putRevision(Database.java:2916)
04-16 11:31:25.043: W/System.err(749):  at com.couchbase.lite.router.Router.update(Router.java:1453)
04-16 11:31:25.043: W/System.err(749):  at com.couchbase.lite.router.Router.do_POST_Document_bulk_docs(Router.java:904)
04-16 11:31:25.043: W/System.err(749):  at java.lang.reflect.Method.invokeNative(Native Method)
04-16 11:31:25.043: W/System.err(749):  at java.lang.reflect.Method.invoke(Method.java:515)
04-16 11:31:25.043: W/System.err(749):  at com.couchbase.lite.router.Router.start(Router.java:443)
04-16 11:31:25.043: W/System.err(749):  at com.couchbase.lite.listener.LiteServlet.service(LiteServlet.java:102)
04-16 11:31:25.043: W/System.err(749):  at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)
04-16 11:31:25.043: W/System.err(749):  at Acme.Serve.Serve$ServeConnection.runServlet(Serve.java:2251)
04-16 11:31:25.053: W/System.err(749):  at Acme.Serve.Serve$ServeConnection.parseRequest(Serve.java:2176)
04-16 11:31:25.053: W/System.err(749):  at Acme.Serve.Serve$ServeConnection.run(Serve.java:1988)
04-16 11:31:25.053: W/System.err(749):  at Acme.Utils$ThreadPool$PooledThread.run(Utils.java:1223)
04-16 11:31:25.053: W/System.err(749):  at java.lang.Thread.run(Thread.java:841)
04-16 11:31:25.053: E/Database(749): com.couchbase.lite.CouchbaseLiteException: No existing revision found with doc id: 4237ce67-922b-46a9-9d5d-54f0c6504cc5
```

with p2p replication.

@andreibaranouski how hard would it be run the functional test suite with two android liteservs replicating with each other?

Btw, I'm not sure which version of couchbase lite this bug was seen on.

**Comment by djpongh** [comment]
No activity for four years, closing out.
