### ISSUE TITLE
The specified SyncGatewaySession value with /_replicate REST API is not used.

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-java-core#1617]
REF: CBSE-3606

Version: Couchbase Lite Android/Java v1.4.0 or earlier

### The root cause of newly set SyncGatewaySesion value is not used.

1. CookieJar and how it is used:
Cookie values are stored with only responses from REST API call. It means the Cookie is stored if HTTP response header contains `SetCookie:` header value. In other scenarios, CBL does not store Cookie in the CookieJar.

2. What logic uses cookies in CookieJar
OkHttp always loads cookie values from CookieJar before sends a request to the server. Following is stacktrace to prove it:
```
 at com.couchbase.lite.support.PersistentCookieJar.loadForRequest(PersistentCookieJar.java:157)
 at okhttp3.internal.http.HttpEngine.networkRequest(HttpEngine.java:566)
 at okhttp3.internal.http.HttpEngine.sendRequest(HttpEngine.java:199)
 at okhttp3.RealCall.getResponse(RealCall.java:243)
 at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:201)
 at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:163)
 at okhttp3.RealCall.execute(RealCall.java:57)
 at com.couchbase.lite.replicator.RemoteRequest.executeRequest(RemoteRequest.java:261)
 at com.couchbase.lite.replicator.RemoteRequest.execute(RemoteRequest.java:165)
 at com.couchbase.lite.replicator.RemoteRequest.run(RemoteRequest.java:105)
 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
 at java.util.concurrent.FutureTask.run(FutureTask.java:237)
 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
 at java.lang.Thread.run(Thread.java:761)
```
3. Based on above two info, till cookie value is stored in the CookieJar, the replicator uses SyncGatewaySession value, which is set by _replicator REST API, in the memory.
4. What makes Cookies are stored into the CookieJar.
SyncGateway responds with `SetCookie:` header value in case SyncGatewaySession will be expired in 10% of total TTL. This is SyncGatewaySession auto-update feature. So this makes Cookie to be stored into the CookieJar.
5. Once a cookie is stored in CookieJar, this cookie is used till cookie expire or overwritten. Also, newly set Cookie (SyncGatewaySession) is overwritten by a cookie in CookieJar just before sending Http Request.

### Workaround
- When /_replicate REST API is called with `Cookie: SyncGatewaySession=....` header value, CBL stores it into CookieJar. So OkHttp always uses newly set SyncGatewaySession value.

**Comment by jamiltz** [comment]
Do you think the following steps would reproduce the issue?

1. create a session id from the SG `/{db}/_session` admin endpoint with an [expiry time](https://developer.couchbase.com/documentation/mobile/1.4/references/sync-gateway/admin-rest-api/index.html?language=ios#!/session/post_db_session) of 10 minutes.
2. use the session id in the `/_replicate` endpoint to start a push/pull replication.
3. add documents every 5 seconds to CBL to keep the push replication running.
4. wait for 1 minutes (10% of the expiry time) and expect a Sync Gateway response to contain the `SetCookie:` header.
5. stop replications and delete the session on the server side with the SG Admin endpoint `/{db}/_session/{id}` endpoint.
6. create a new session (step 1) and replications (step 2).

__Expected:__ the replication should use the new session id.

__Actual:__ the replication uses the first session id that was created instead of the new one.

**Comment by hideki** [comment]
@jamiltz  
YES.
