### ISSUE TITLE
RejectedExecutionException in PullerInternal.changeTrackerStopped.

### ISSUE THREAD

**Issue by NitzDKoder** [couchbase/couchbase-lite-java-core#1645]
Hi Folks,

1)CBL 1.4.0 used.
2)Stop continuous Pull replication was called.

```
[08/14 08:14:56.806] [80] ChangeTracker: ChangeTracker{https://---:---@mydomain/ptxdata, OneShot, @bd56d26}: Change tracker run loop exiting
[08/14 08:14:56.806] [80] ChangeTracker: ChangeTracker{https://---:---@mydomain/ptxdata, OneShot, @bd56d26}: Change tracker in stopped()
[08/14 08:14:56.807] [80] ChangeTracker: ChangeTracker{https://---:---@mydomain/ptxdata, OneShot, @bd56d26}: Change tracker calling changeTrackerStopped, client: PullerInternal{https://---:---@mydomain/ptxdata, pull, 53e3d}
[08/14 08:14:56.807] [77] Sync: changeTrackerStopped.  lifecycle: ONESHOT
[08/14 08:14:56.808] [77] ChangeTracker: ChangeTracker{https://---:---@mydomain/ptxdata, OneShot, @bd56d26}: getLastError() null
[08/14 08:14:56.811] [98] Sync: PullerInternal{https://---:---@mydomain/ptxdata, pull, 53e3d} [fireTrigger()] => STOP_IMMEDIATE
[08/14 08:14:56.814] [98] Sync: PullerInternal stop.run() finished
[08/14 08:14:56.814] [77] Sync: firing trigger: STOP_IMMEDIATE





[08/14 08:14:56.815] [77] Sync: PullerInternal{https://---:---@mydomain/ptxdata, pull, 53e3d} [onEntry()] STOPPING => STOPPED
[08/14 08:14:56.816] [77] Sync: PullerInternal{https://---:---@mydomain/ptxdata, pull, 53e3d}: clearDbRef() called
[08/14 08:14:56.817] [99] Sync: [waitForPendingFutures()] STARTED - thread id: 7685
[08/14 08:14:56.818] [99] Sync: PullerInternal{https://---:---@mydomain/ptxdata, pull, 53e3d} [fireTrigger()] => STOP_GRACEFUL
[08/14 08:14:56.819] [99] Sync: [waitForPendingFutures()] END - thread id: 7685
[08/14 08:14:56.824] [77] Sync: PullerInternal{https://---:---@mydomain/ptxdata, pull, 53e3d}: clearDbRef() setting db to null
[08/14 08:14:56.824] [77] Sync: State transition: STOPPING -> STOPPED (via STOP_IMMEDIATE).  this: PullerInternal{https://---:---@mydomain/ptxdata, pull, 53e3d}
[08/14 08:14:56.825] [77] Sync: firing trigger: STOP_GRACEFUL
[08/14 08:14:56.852] [8] Listener: [REQUEST] (Acme.Utils.ThreadPool(3)-PooledThread: Acme.Serve.Serve$ServeConnection@9af7106) POST: https://127.0.0.1:42038/_replicate

```
3)RejectedExecutionException in PullerInternal.changeTrackerStopped seen.

```
08-14 20:14:57.017 E/AndroidRuntime( 9689): java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@eab8d36 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@1d5c437[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 9]

08-14 20:14:57.017 E/AndroidRuntime( 9689): 	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2014)

08-14 20:14:57.017 E/AndroidRuntime( 9689): 	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:794)

08-14 20:14:57.017 E/AndroidRuntime( 9689): 	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:302)

08-14 20:14:57.017 E/AndroidRuntime( 9689): 	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:527)

08-14 20:14:57.017 E/AndroidRuntime( 9689): 	at java.util.concurrent.ScheduledThreadPoolExecutor.submit(ScheduledThreadPoolExecutor.java:626)

08-14 20:14:57.017 E/AndroidRuntime( 9689): 	at java.util.concurrent.Executors$DelegatedExecutorService.submit(Executors.java:594)

08-14 20:14:57.017 E/AndroidRuntime( 9689): 	at com.couchbase.lite.replicator.PullerInternal.changeTrackerStopped(SourceFile:835)

08-14 20:14:57.017 E/AndroidRuntime( 9689): 	at com.couchbase.lite.replicator.ChangeTracker.stopped(SourceFile:560)

08-14 20:14:57.017 E/AndroidRuntime( 9689): 	at com.couchbase.lite.replicator.ChangeTracker.run(SourceFile:249)

08-14 20:14:57.017 E/AndroidRuntime( 9689): 	at java.lang.Thread.run(Thread.java:818)

08-14 20:14:57.017 D/PhoneApp( 3033): PhoneAppBroadcastReceiver onReceive android.intent.action.BATTERY_CHANGED

```
https://github.com/couchbase/couchbase-lite-java-core/blob/1.4.0/src/main/java/com/couchbase/lite/replicator/PullerInternal.java#L835

4) Detail CBL logs put here..
https://gist.github.com/NitzDKoder/e1c06b862be2232d68aba1819ca407ee

Thanks
Nithin

**Comment by hideki** [comment]
@NitzDKoder, Are you familiar with the following Exception?
```
java.lang.IllegalStateException: Object has been freed
	at com.wolfssl.WolfSSLSession.read(SourceFile:564)
	at obfuscated.sh.b(SourceFile:255)
	at okio.Okio$2.read(SourceFile:167)
	at okio.AsyncTimeout$2.read(SourceFile:216)
	at okio.RealBufferedSource.indexOf(SourceFile:306)
	at okio.RealBufferedSource.indexOf(SourceFile:300)
	at okio.RealBufferedSource.readUtf8LineStrict(SourceFile:196)
	at okhttp3.internal.http.Http1xStream.readResponse(SourceFile:184)
	at okhttp3.internal.http.Http1xStream.readResponseHeaders(SourceFile:125)
	at okhttp3.internal.http.HttpEngine.readNetworkResponse(SourceFile:723)
	at okhttp3.internal.http.HttpEngine.access$200(SourceFile:81)
	at okhttp3.internal.http.HttpEngine$NetworkInterceptorChain.proceed(SourceFile:708)
	at okhttp3.internal.http.HttpEngine.readResponse(SourceFile:563)
	at okhttp3.RealCall.getResponse(SourceFile:241)
	at okhttp3.RealCall$ApplicationInterceptorChain.proceed(SourceFile:198)
	at okhttp3.RealCall.getResponseWithInterceptorChain(SourceFile:160)
	at okhttp3.RealCall.execute(SourceFile:57)
	at com.couchbase.lite.replicator.RemoteRequest.executeRequest(SourceFile:261)
	at com.couchbase.lite.replicator.RemoteRequest.execute(SourceFile:165)
	at com.couchbase.lite.replicator.RemoteRequest.run(SourceFile:105)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)
```

**Comment by NitzDKoder** [comment]
@hideki yes .. we have put a hook to do ssl(https) via wolfssl c library as opposed to stock openssl or boringssl.
some times the wolfssl object is been freed by thread1 and thread2 tries to read from same object hence leading to object has be freed.. is that can cause "RejectedExecutionException" here..??

**Comment by hideki** [comment]
Hi @NitzDKoder,
I can not find `RejectedExecutionException` in your log file. So I am not sure if `IllegalStateException` causes `RejectedExecutionException`.

**Comment by NitzDKoder** [comment]
@hideki log file i shared has only couchbase logs(12 hr format)and have put crash stacktrace from adb logs(24 hr format)..

Can we catch this exception and avoid crash.?

Have another set of logs which had same crash..will check if that had IllegalStateException scheme..

Thanks 
Nithin

**Comment by hideki** [comment]
Can you figure out where `RejectedExecutionException ` is thrown from?

**Comment by NitzDKoder** [comment]
@hideki thrown from here 

https://github.com/couchbase/couchbase-lite-java-core/blob/1.4.0/src/main/java/com/couchbase/lite/replicator/PullerInternal.java#L835

Will get you more details from my second logs.


Old fixes:
https://github.com/couchbase/couchbase-lite-java-core/commit/e22ce2955563c4c26bdfbdfaeabed580b41b060a


https://github.com/couchbase/couchbase-lite-java-core/issues/1637

**Comment by hideki** [comment]
Hi @NitzDKoder 

Based on current CBL implementation, [RejectedExecutionException](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/RejectedExecutionException.html) should not be thrown from https://github.com/couchbase/couchbase-lite-java-core/blob/1.4.0/src/main/java/com/couchbase/lite/replicator/PullerInternal.java#L835 .

It seems other thread shutdowns Executor service without obtaining the lock (executor).

**Comment by tikimcfee** [comment]
Adding a +1 to this, I'm getting the exact same problem.

I have a similar crash stack:

```
Fatal Exception: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@2235360 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@8b1f019[Shutting down, pool size = 1, active threads = 0, queued tasks = 1, completed tasks = 24]
       at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2014)
       at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:794)
       at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:302)
       at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:527)
       at java.util.concurrent.ScheduledThreadPoolExecutor.submit(ScheduledThreadPoolExecutor.java:626)
       at java.util.concurrent.Executors$DelegatedExecutorService.submit(Executors.java:594)
       at com.couchbase.lite.replicator.ReplicationInternal.fireTrigger(ReplicationInternal.java:234)
       at com.couchbase.lite.replicator.ReplicationInternal.triggerStopGraceful(ReplicationInternal.java:209)
       at com.couchbase.lite.replicator.PullerInternal.triggerStopGraceful(PullerInternal.java:60)
       at com.couchbase.lite.replicator.ReplicationInternal.waitForPendingFutures(ReplicationInternal.java:1935)
       at com.couchbase.lite.replicator.PullerInternal$14.run(PullerInternal.java:973)
       at java.lang.Thread.run(Thread.java:818)
```
