### ISSUE TITLE
ANDROID: Need of ICU database when sqlite is used as database option.

### ISSUE THREAD

**Issue by NitzDKoder** [couchbase/couchbase-lite-java-core#1646]
Hi folks,
1)Currently we use sqlite db and encryption is applied. 
2)All db operation and encryption is working. 
3) we have not put icudt53l.zip to assets folder..what is the need of ICU database ?

[08/24 03:58:54.816] [0] Database: Successfully load native library: cbljavasqlcipher
[08/24 03:58:55.007] [0] Database: Cannot load ICU database file
java.io.FileNotFoundException: icudt53l.zip
                at android.content.res.AssetManager.openAsset(Native Method)
                at android.content.res.AssetManager.open(AssetManager.java:363)

@hideki please confirm..

Thanks 
Nithin

**Comment by NitzDKoder** [comment]
@hideki please respond..

**Comment by hideki** [comment]
ICU4C is used for collation, which is used for ordering non-ASCII characters. icudt53l.zip is a dictionary file.
If your app does not sort with non-ASCII characters, you might be able to remove icudt53l.zip file.

**Comment by NitzDKoder** [comment]
Thanks @hideki for the info..
