### ISSUE TITLE
Router: Router unable to route request to do_PUT_Document (failing for attachments)

### ISSUE THREAD

**Issue by tjayesh** [couchbase/couchbase-lite-java-core#1647]
Client is not able to add attachment to DB. However, docs without inline attachment are getting added to DB.

Whenever client tries to PUT doc with inline attachment to CBL,  Database.java throwing below exception. 

> [08/24 10:47:26.579] [3] Listener: [REQUEST] (Acme.Utils.ThreadPool(2)-PooledThread: Acme.Serve.Serve$ServeConnection@3224be4) PUT: https://127.0.0.1:38981/ptxdata/s14257854755_ptx1503589646143_a1503589646158_attachment.doc
[08/24 10:47:26.582] [3] Listener: authHeader is null
[08/24 10:47:26.583] [3] Listener: Not enforcing basic auth -- allowedCredentials null or empty
[08/24 10:47:26.583] [3] Listener: remoteURL() addr=127.0.0.1
[08/24 10:47:26.584] [3] Database: getDatabase() com.couchbase.lite.Manager@ce07e5 com.couchbase.lite.Database@e3f52ba[/data/user/0/com.xxx.yyy/files/ptxdata.cblite2]
[08/24 10:47:26.595] [3] Database: PUT _id=s14257854755_ptx1503589646143_a1503589646158_attachment.doc, _rev=null (allowConflict=false)
[08/24 10:47:26.606] [3] Router: Router unable to route request to do_PUT_Document
java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.couchbase.lite.router.Router.start(SourceFile:560)
	at com.couchbase.lite.listener.LiteServlet.service(SourceFile:147)
	at obfuscated.wg.service(SourceFile:802)
	at Acme.Serve.Serve$ServeConnection.runServlet(SourceFile:2408)
	at Acme.Serve.Serve$ServeConnection.parseRequest(SourceFile:2330)
	at Acme.Serve.Serve$ServeConnection.run(SourceFile:2110)
	at obfuscated.a$c$a.run(SourceFile:1238)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.couchbase.lite.BlobStore.storeBlob(byte[], com.couchbase.lite.BlobKey)' on a null object reference
	at com.couchbase.lite.Database$5.invoke(SourceFile:1125)
	at com.couchbase.lite.Database$5.invoke(SourceFile:1111)
	at com.couchbase.lite.internal.RevisionInternal.mutateAttachments(SourceFile:248)
	at com.couchbase.lite.Database.processAttachmentsForRevision(SourceFile:1111)
	at com.couchbase.lite.Database.put(SourceFile:1997)
	at com.couchbase.lite.Database.putRevision(SourceFile:1967)
	at com.couchbase.lite.Database.putRevision(SourceFile:1958)
	at com.couchbase.lite.router.Router.update(SourceFile:2283)
	at com.couchbase.lite.router.Router.update(SourceFile:2336)
	at com.couchbase.lite.router.Router.do_PUT_Document(SourceFile:2372)
	... 9 more

Also, there's an exception on DB compaction

> [08/22 05:34:20.249] [1] Listener: [REQUEST] (Acme.Utils.ThreadPool(0)-PooledThread: Acme.Serve.Serve$ServeConnection@7798735) POST: https://127.0.0.1:38981/ptxdata/_compact
[08/22 05:34:20.249] [1] Listener: authHeader is null
[08/22 05:34:20.249] [1] Listener: Not enforcing basic auth -- allowedCredentials null or empty
[08/22 05:34:20.250] [1] Listener: remoteURL() addr=127.0.0.1
[08/22 05:34:20.251] [1] Database: getDatabase() com.couchbase.lite.Manager@ce07e5 com.couchbase.lite.Database@e3f52ba[/data/user/0/com.xxx.yyy/files/ptxdata.cblite2]
[08/22 05:34:20.251] [1] Database: Begin database compaction...
[08/22 05:34:20.252] [1] Database: Acme.Utils.ThreadPool(0)-PooledThread: Acme.Serve.Serve$ServeConnection@7798735 Begin transaction (level 0)
[08/22 05:34:20.255] [1] Database: Deleting JSON of old revisions...
[08/22 05:34:20.256] [1] Database: ... deleted 1 revisions
[08/22 05:34:20.256] [1] Database: Acme.Utils.ThreadPool(0)-PooledThread: Acme.Serve.Serve$ServeConnection@7798735 Committing transaction (level 0)
[08/22 05:34:20.266] [1] Database: Flushing SQLite WAL...
[08/22 05:34:20.275] [1] Database: Vacuuming SQLite database...
[08/22 05:34:20.310] [1] Database: ...Finished database compaction.
[08/22 05:34:20.311] [1] Database: Scanning database revisions for attachments...
[08/22 05:34:20.316] [1] Database:     ...found 0 attachments
[08/22 05:34:20.317] [1] Router: Router unable to route request to do_POST_Document_compact
java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.couchbase.lite.router.Router.start(SourceFile:560)
	at com.couchbase.lite.listener.LiteServlet.service(SourceFile:147)
	at obfuscated.wg.service(SourceFile:802)
	at Acme.Serve.Serve$ServeConnection.runServlet(SourceFile:2408)
	at Acme.Serve.Serve$ServeConnection.parseRequest(SourceFile:2330)
	at Acme.Serve.Serve$ServeConnection.run(SourceFile:2110)
	at obfuscated.a$c$a.run(SourceFile:1238)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.couchbase.lite.BlobStore.deleteBlobsExceptWithKeys(java.util.List)' on a null object reference
	at com.couchbase.lite.Database.garbageCollectAttachments(SourceFile:2835)
	at com.couchbase.lite.Database.compact(SourceFile:318)
	at com.couchbase.lite.router.Router.do_POST_Document_compact(SourceFile:1449)
	... 9 more

It seems due to some reason BlobStore object could not be initialized in "Database.java".

**Comment by hideki** [comment]
Hi @tjayesh,

As you pointed out, Router can not handle push doc with an attachment. It can handle only inline attachment.
REF: https://github.com/couchbase/couchbase-lite-java-core/issues/617

**Comment by tjayesh** [comment]
@hideki  Sorry for miss leading subject line. I have updated the same.

We are using inline attachments in our messaging app, which is working pretty well. However, in this particular issue CBL failing to add inline attachment to DB.
