### ISSUE TITLE
SQLiteDatabaseCorruptException and Need of cbljavasqlitecustom and sqlite3.

### ISSUE THREAD

**Issue by NitzDKoder** [couchbase/couchbase-lite-java-core#1649]
Hi Folks,

1)public static final String JNI_SQLITE_CUSTOM_LIBRARY = "cbljavasqlitecustom";
private static final String SHARED_SQLITE_LIBRARY = "sqlite3";

AFAIK above libs are required only when android devices won’t come with default inbuilt stock device SQLITE lib.. 

2)CBL 1.4 used with SQLITE storage options.

3)When using encryption option to DB below exception is seen only in some devices.

```
database: SQLiteDatabase: Failed to open database '/data/data/com.company.ui/files/ptxdata.cblite2/db.sqlite3'.
                                                         ```
com.couchbase.lite.internal.database.sqlite.exception.SQLiteDatabaseCorruptException: file is encrypted or is not a database (code 26): , while compiling: SELECT count(*) FROM sqlite_master
                                                             at com.couchbase.lite.internal.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
                                                             at com.couchbase.lite.internal.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:718)
                                                             at com.couchbase.lite.internal.database.sqlite.SQLiteConnection.executeForLong(SQLiteConnection.java:522)
                                                             at com.couchbase.lite.storage.SQLiteStorageEngineBase.decrypt(SQLiteStorageEngineBase.java:126)
                                                             at com.couchbase.lite.storage.SQLiteStorageEngineBase.access$200(SQLiteStorageEngineBase.java:32)
                                                             at com.couchbase.lite.storage.SQLiteStorageEngineBase$ConnectionListener.onOpen(SQLiteStorageEngineBase.java:96)
                                                             at com.couchbase.lite.internal.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:198)
                                                             at com.couchbase.lite.internal.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:178)
                                                             at com.couchbase.lite.internal.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:461)
                                                             at com.couchbase.lite.internal.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:191)
                                                             at com.couchbase.lite.internal.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:183)
                                                             at com.couchbase.lite.internal.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:820)
                                                             at com.couchbase.lite.internal.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:803)
                                                             at com.couchbase.lite.internal.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:698)
                                                             at com.couchbase.lite.storage.SQLiteStorageEngineBase.open(SQLiteStorageEngineBase.java:70)
                                                             at com.couchbase.lite.store.SQLiteStore.open(SQLiteStore.java:188)
                                                             at com.couchbase.lite.Database.open(Database.java:1369)
                                                             at com.couchbase.lite.Manager.openDatabase(Manager.java:341)
```


Thanks
Nithin

**Comment by NitzDKoder** [comment]
@hideki please share your thoughts..

**Comment by hideki** [comment]
Hi @NitzDKoder,

1) Android  N or higher, it does not allow the application to access system native libraries including sqlite. So  CBL Android always use Couchbase compiled sqlite library. 

3) About SQLiteDatabaseCorruptException, I assume SQLite with encryption tries to open the SQLite databsae file that is created by SQLite without Encryption.

**Comment by NitzDKoder** [comment]
@hideki 
1) ah missed this topic..thanks for the info.. strange part is  i dont include theae as part libs and android N and O works..
Will update how its working..

2)Have this problem in 4.4.4 when i include these library... how do i go by now??

PS: i dont use gradle build..instead add libs and jar on my own..

**Comment by NitzDKoder** [comment]
@hideki 
1) We do this https://github.com/couchbase/couchbase-lite-java-core/issues/1641

2) After loading DB with encryption fails.


```

10-16 18:19:08.024 D/Database(22471): ### Couchbase Lite devbuild (devbuild) ###

10-16 18:19:08.029 D/Database(22471): setFilterCompiler: com.couchbase.lite.javascript.JavaScriptReplicationFilterCompiler@425a2f00

10-16 18:19:08.030 D/Database(22471): getDatabase() com.couchbase.lite.Manager@42c1a170 com.couchbase.lite.Database@42d366c0[/data/data/com.my.product/files/ptxdata.cblite2]

10-16 18:19:08.030 D/Database(22471): Opening com.couchbase.lite.Database@42d366c0[/data/data/com.my.product/files/ptxdata.cblite2]

10-16 18:19:08.033 D/dalvikvm(22471): Trying to load lib /data/app-lib/com.my.product-1/libCouchbaseLiteJavaForestDB.so 0x42511720

10-16 18:19:08.041 D/dalvikvm(22471): Added shared lib /data/app-lib/com.my.product-1/libCouchbaseLiteJavaForestDB.so 0x42511720

10-16 18:19:08.043 D/dalvikvm(22471): Trying to load lib /data/app-lib/com.my.product-1/libsqlcipher.so 0x42511720

10-16 18:19:08.043 D/dalvikvm(22471): Shared lib '/data/app-lib/com.my.product-1/libsqlcipher.so' already loaded in same CL 0x42511720

10-16 18:19:08.043 D/dalvikvm(22471): Trying to load lib /data/app-lib/com.my.product-1/libcbljavakey.so 0x42511720

10-16 18:19:08.044 D/dalvikvm(22471): Shared lib '/data/app-lib/com.my.product-1/libcbljavakey.so' already loaded in same CL 0x42511720

10-16 18:19:08.044 D/dalvikvm(22471): Trying to load lib /data/app-lib/com.my.product-1/libcbljavasqlcipher.so 0x42511720

10-16 18:19:08.044 D/dalvikvm(22471): Shared lib '/data/app-lib/com.my.product-1/libcbljavasqlcipher.so' already loaded in same CL 0x42511720

10-16 18:19:08.045 D/Database(22471): Successfully load native library: cbljavasqlcipher

10-16 18:19:08.046 D/dalvikvm(22471): Trying to load lib /data/app-lib/com.my.product-1/libsqlcipher.so 0x42511720

10-16 18:19:08.046 D/dalvikvm(22471): Shared lib '/data/app-lib/com.my.product-1/libsqlcipher.so' already loaded in same CL 0x42511720

10-16 18:19:08.047 D/dalvikvm(22471): Trying to load lib /data/app-lib/com.my.product-1/libcbljavakey.so 0x42511720

10-16 18:19:08.047 D/dalvikvm(22471): Shared lib '/data/app-lib/com.my.product-1/libcbljavakey.so' already loaded in same CL 0x42511720

10-16 18:19:08.047 D/dalvikvm(22471): Trying to load lib /data/app-lib/com.my.product-1/libcbljavasqlcipher.so 0x42511720

10-16 18:19:08.047 D/dalvikvm(22471): Shared lib '/data/app-lib/com.my.product-1/libcbljavasqlcipher.so' already loaded in same CL 0x42511720

10-16 18:19:08.048 D/Database(22471): Successfully load native library: cbljavasqlcipher

10-16 18:19:08.049 D/Database(22471): SQLiteStore: encryption not available (app not built with SQLCipher)

10-16 18:19:08.050 V/AlarmManager(  944): sending alarm Alarm{433705f8 type 2 android}

10-16 18:19:08.052 D/CouchBaseLiteManager(22471): Encryption not available

10-16 18:19:08.052 W/System.err(22471): com.couchbase.lite.CouchbaseLiteException: Encryption not available, Status: 501 (HTTP 501 Not Implemented)
```


Please share your thoughts..

Thanks
Nithin

**Comment by hideki** [comment]
@NitzDKoder,
Two possibilities:
1) encryption key is null
2) SQLCipher module is not loaded.
https://github.com/couchbase/couchbase-lite-java-core/blob/d18e1e0ccad317bf9e3285451e430c49e961b7bf/src/main/java/com/couchbase/lite/storage/SQLiteStorageEngineBase.java#L62-L66

**Comment by hideki** [comment]
Hi @NitzDKoder,
Do you have any updates about this issue?

**Comment by NitzDKoder** [comment]
@hideki 
encryption key is null

**Is not null.**


SQLCipher module is not loaded.

It was loaded.

10-16 18:19:08.043 D/dalvikvm(22471): Trying to load lib /data/app-lib/com.my.product-1/libsqlcipher.so 0x42511720
10-16 18:19:08.043 D/dalvikvm(22471): Shared lib '/data/app-lib/com.my.product-1/libsqlcipher.so' already loaded in same CL 0x42511720

**Still issue is SEEN.**

**Current Solution:**


1)We use sqlite3 as part of our C engine.
2)Removed below libs.

public static final String JNI_SQLITE_CUSTOM_LIBRARY = "cbljavasqlitecustom";
private static final String SHARED_SQLITE_LIBRARY = "sqlite3";

3)CBL works in all devcies starting Android 4.1 to Android 8.0.

**Comment by hideki** [comment]
Hi @NitzDKoder,
It seems the app used customized CBL. And, as the app loaded `sqlite3`, it seems this library is used instead of `sqlcipher`.  It seems we can not do anything for this issue. 
By customizing the code to load the library, the app might be able to force to load `sqlcipher` lib for CBL.

**Comment by NitzDKoder** [comment]
@hideki 

1) How the encryption working in my app. using sqlcipher? sqlcipher on num 2 below?

https://github.com/couchbase/couchbase-lite-java-native

2)As we use sqlite3 as part of a C engine .SO. for internal sqlite DB support 
 a)is CBL using the same instance?


Thanks
Nithin

**Comment by hideki** [comment]
Hi @NitzDKoder,
`sqlcipher`  and `sqlite3` native library's method signatures are same. So your app loads sqlite3. So even loads `sqlcipher` the app keeps using methods from sqlite3 native library.

**Comment by hideki** [comment]
@NitzDKoder,
As a workaround, I believe your app could use sqlcipher native library as your sqlite library. They should behave same if encryption is not enabled.

**Comment by NitzDKoder** [comment]
@hideki 
1)[07/25 11:31:50:662] [264] Database: decrypt key: 1c2e19dd527ffb932960dc9eb32e7d72060ed27ee0bd133699e3983c94573670 ([28, 46, 25, -35, 82, 127, -5, -109, 41, 96, -36, -98, -77, 46, 125, 114, 6, 14, -46, 126, -32, -67, 19, 54, -103, -29, -104, 60, -108, 87, 54, 112])
[07/25 11:31:51:035] [264] Database: SQLiteStorageEngine {database=c30fc4c}: Opened Android sqlite db
1c2e19dd527ffb932960dc9eb32e7d72060ed27ee0bd133699e3983c94573670

**Encrypted DB opened .**

2)[07/25 13:03:28:133] [289] Database: Successfully load native library: cbljavasqlcipher
[07/25 13:03:28:148] [289] Database: Successfully load native library: cbljavasqlcipher
[07/25 13:03:28:627] [289] Database: decrypt key: 1c2e19dd527ffb932960dc9eb32e7d72060ed27ee0bd133699e3983c94573670 ([28, 46, 25, -35, 82, 127, -5, -109, 41, 96, -36, -98, -77, 46, 125, 114, 6, 14, -46, 126, -32, -67, 19, 54, -103, -29, -104, 60, -108, 87, 54, 112])
[07/25 13:03:28:682] [289] Database: Decrypting database failed
[07/25 13:03:28:869] [289] Database: Unauthorized to open the SQLite database
[07/25 13:03:28:870] [289] Database: Unable to create a storage engine

DB failed to decrypt using old decrypt key.

Please share your thoughts,.we see this issue very often..
