### ISSUE TITLE
1.x: Peer to Peer: InvocationTargetException in Router.java with PhotoDrop sample app

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-java-core#1660]
### Router unable to route request to do_GET_DesignDocument 

this is still happening to me while trying to use this [photo-drop app](https://github.com/couchbaselabs/photo-drop/tree/master/android) on android

Logcat
```
Router unable to route request to do_PUT_Document
   java.lang.reflect.InvocationTargetException
       at java.lang.reflect.Method.invoke(Native Method)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.couchbase.lite.router.Router.start(Router.java:560)
       at com.couchbase.lite.listener.LiteServlet.service(LiteServlet.java:147)
       at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)
       at Acme.Serve.Serve$ServeConnection.runServlet(Serve.java:2408)
       at Acme.Serve.Serve$ServeConnection.parseRequest(Serve.java:2330)
       at Acme.Serve.Serve$ServeConnection.run(Serve.java:2110)
       at Acme.Utils$ThreadPool$PooledThread.run(Utils.java:1238)
       at java.lang.Thread.run(Thread.java:818)
    Caused by: com.couchbase.lite.CouchbaseLiteException, Status: 406 (HTTP 406 not_acceptable)
       at com.couchbase.lite.router.Router.getBodyAsDictionary(Router.java:247)
       at com.couchbase.lite.router.Router.do_PUT_Document(Router.java:2364)
       at java.lang.reflect.Method.invoke(Native Method) 
       at java.lang.reflect.Method.invoke(Method.java:372) 
       at com.couchbase.lite.router.Router.start(Router.java:560) 
       at com.couchbase.lite.listener.LiteServlet.service(LiteServlet.java:147) 
       at javax.servlet.http.HttpServlet.service(HttpServlet.java:802) 
       at Acme.Serve.Serve$ServeConnection.runServlet(Serve.java:2408) 
       at Acme.Serve.Serve$ServeConnection.parseRequest(Serve.java:2330) 
       at Acme.Serve.Serve$ServeConnection.run(Serve.java:2110) 
       at Acme.Utils$ThreadPool$PooledThread.run(Utils.java:1238) 
       at java.lang.Thread.run(Thread.java:818) 
```

REF: https://github.com/couchbase/couchbase-lite-java-core/issues/1372

**Comment by hideki** [comment]
Task: Test CBL Android 1.4.0 library with Photo-Drop. And confirm if this issue is still reproducible. couchbaselabs/photo-drop#15

**Comment by hideki** [comment]
```
10-05 13:00:48.035 25097-22180/android.jamiltz.com.photodrop W/Router: Router unable to route request to do_PUT_Document
 java.lang.reflect.InvocationTargetException
     at java.lang.reflect.Method.invokeNative(Native Method)
     at java.lang.reflect.Method.invoke(Method.java:511)
     at com.couchbase.lite.router.Router.start(Router.java:560)
     at com.couchbase.lite.listener.LiteServlet.service(LiteServlet.java:147)
     at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)
     at Acme.Serve.Serve$ServeConnection.runServlet(Serve.java:2408)
     at Acme.Serve.Serve$ServeConnection.parseRequest(Serve.java:2330)
     at Acme.Serve.Serve$ServeConnection.run(Serve.java:2110)
     at Acme.Utils$ThreadPool$PooledThread.run(Utils.java:1238)
     at java.lang.Thread.run(Thread.java:856)
  Caused by: com.couchbase.lite.CouchbaseLiteException, Status: 406 (HTTP 406 not_acceptable)
     at com.couchbase.lite.router.Router.getBodyAsDictionary(Router.java:247)
     at com.couchbase.lite.router.Router.do_PUT_Document(Router.java:2364)
     at java.lang.reflect.Method.invokeNative(Native Method) 
     at java.lang.reflect.Method.invoke(Method.java:511) 
     at com.couchbase.lite.router.Router.start(Router.java:560) 
     at com.couchbase.lite.listener.LiteServlet.service(LiteServlet.java:147) 
     at javax.servlet.http.HttpServlet.service(HttpServlet.java:802) 
     at Acme.Serve.Serve$ServeConnection.runServlet(Serve.java:2408) 
     at Acme.Serve.Serve$ServeConnection.parseRequest(Serve.java:2330) 
     at Acme.Serve.Serve$ServeConnection.run(Serve.java:2110) 
     at Acme.Utils$ThreadPool$PooledThread.run(Utils.java:1238) 
     at java.lang.Thread.run(Thread.java:856) 
```

**Comment by hideki** [comment]
duplicated with #1605
