### ISSUE TITLE
Changetracker is CBLite: Waiting: true state and not fetching docs.

### ISSUE THREAD

**Issue by NitzDKoder** [couchbase/couchbase-lite-java-core#1670]
Hi Folks,

1)Changetracker gets deleted docs from syncgateway and validator rejects them.

2)@[10/09 13:10:23:429] [622] ChangeTracker: ChangeTracker{https://---:---@syncqc7.company.com/data, OneShot, @224820bc}: Making request to POST [https://---:---@syncqc7.company.com/data/_changes?feed=normal&heartbeat=90000&style=all_docs&since=9382042%3A8493520&filter=sync_gateway%2Fbychannel]

Changetracker makes request.

3)CBLite: setPaused: true

[10/09 13:10:24:937] [590] Sync: com.couchbase.lite.replicator.PullerInternal$9@e0903f2 insertDownloads() updating completedChangesCount from 2710 -> 2711 
[10/09 13:10:24:937] [590] Sync: PullerInternal{https://---:---@syncqc7.company.com/data, pull, 88db8}: Incrementing completedChangesCount count from 2710 by adding 1 -> 2711
[10/09 13:10:24:937] [590] CBLite: setPaused: true

https://github.com/couchbase/couchbase-lite-java-core/blob/release/1.4.0/src/main/java/com/couchbase/lite/replicator/PullerInternal.java#L1085

4 )     CBLite: Waiting: true and never recovers.

     6790: [10/09 13:10:34:110] [622] CBLite: Waiting: true
	Line 36821: [10/09 13:10:39:111] [622] CBLite: Waiting: true
	Line 36822: [10/09 13:10:44:111] [622] CBLite: Waiting: true
	Line 36853: [10/09 13:10:49:112] [622] CBLite: Waiting: true
	Line 36854: [10/09 13:10:54:113] [622] CBLite: Waiting: true
	Line 36855: [10/09 13:10:59:113] [622] CBLite: Waiting: true
	Line 36856: [10/09 13:11:04:114] [622] CBLite: Waiting: true
	Line 36887: [10/09 13:11:09:115] [622] CBLite: Waiting: true
	Line 36888: [10/09 13:11:14:115] [622] CBLite: Waiting: true
	Line 36919: [10/09 13:11:19:116] [622] CBLite: Waiting: true
	Line 36920: [10/09 13:11:24:117] [622] CBLite: Waiting: true
	Line 36921: [10/09 13:11:29:117] [622] CBLite: Waiting: true
	Line 36952: [10/09 13:11:34:118] [622] CBLite: Waiting: true
	Line 36953: [10/09 13:11:39:118] [622] CBLite: Waiting: true
	Line 36954: [10/09 13:11:44:119] [622] CBLite: Waiting: true
	Line 36970: [10/09 13:11:49:120] [622] CBLite: Waiting: true
	Line 37001: [10/09 13:11:54:120] [622] CBLite: Waiting: true
	Line 37002: [10/09 13:11:59:121] [622] CBLite: Waiting: true
	Line 37003: [10/09 13:12:04:122] [622] CBLite: Waiting: true
	Line 37034: [10/09 13:12:09:123] [622] CBLite: Waiting: true
	Line 37035: [10/09 13:12:14:124] [622] CBLite: Waiting: true
	Line 37036: [10/09 13:12:19:124] [622] CBLite: Waiting: true
	Line 37089: [10/09 13:12:24:125] [622] CBLite: Waiting: true
	Line 37090: [10/09 13:12:29:126] [622] CBLite: Waiting: true
	Line 37091: [10/09 13:12:34:127] [622] CBLite: Waiting: true
	Line 37122: [10/09 13:12:39:127] [622] CBLite: Waiting: true
	Line 37306: [10/09 13:12:44:128] [622] CBLite: Waiting: true
	Line 37506: [10/09 13:12:49:129] [622] CBLite: Waiting: true
	Line 37584: [10/09 13:12:54:129] [622] CBLite: Waiting: true
	Line 37585: [10/09 13:12:59:130] [622] CBLite: Waiting: true
	Line 37586: [10/09 13:13:04:131] [622] CBLite: Waiting: true
	Line 37617: [10/09 13:13:09:132] [622] CBLite: Waiting: true
	Line 37648: [10/09 13:13:14:133] [622] CBLite: Waiting: true
	Line 37664: [10/09 13:13:19:133] [622] CBLite: Waiting: true
	Line 37665: [10/09 13:13:24:134] [622] CBLite: Waiting: true
	Line 37666: [10/09 13:13:29:135] [622] CBLite: Waiting: true
	Line 37715: [10/09 13:13:34:136] [622] CBLite: Waiting: true
	Line 37716: [10/09 13:13:39:137] [622] CBLite: Waiting: true
	Line 37747: [10/09 13:13:44:137] [622] CBLite: Waiting: true
	Line 37758: [10/09 13:13:49:138] [622] CBLite: Waiting: true
	Line 37789: [10/09 13:13:54:139] [622] CBLite: Waiting: true

@hideki pls share your thoughts..

Thanks
Nithin

**Comment by NitzDKoder** [comment]
[cbl_logs.txt](https://github.com/couchbase/couchbase-lite-java-core/files/1383393/cbl_logs.txt)
Detail Logs attached..

**Comment by hideki** [comment]
A wait state is caused by the sum of items in `batcher` and `pendingSequences` are more than MAX_PENDING_DOCS which is 200. It indicates that tasks that pull the actual revision from the SG are slower than retrieving next changes information by ChangeTracker. It could frequently occur if many changes exist on the SG. If pull replication is never finished, pulling the actual revision or inserting it into the database encounters the problem. But from the log file, I could not find the indication.
```
    protected void pauseOrResume() {
        int pending = batcher.count() + pendingSequences.count();
        changeTracker.setPaused(pending >= MAX_PENDING_DOCS);
    }
```

In the log file, I could observe many 404 errors.
```
[10/09 13:09:05:630] [614] Sync: PullerInternal{https://---:---@syncqc7.company.com/data, pull, 88db8}: giving up on {s919999910122_ptx1506373952461_meta.doc #3-a1f3d7939d53685c1de36d4acd1c4919 @2027}: com.couchbase.lite.CouchbaseLiteException, Status: 404 (HTTP 404 not_found)
```
But, in case of facing 404, pull replicator remove items from `pendingSequence` container.
NOTE: 404 is not transientError
```
    private void revisionFailed(RevisionInternal rev, Throwable throwable) {
        if (!Utils.isTransientError(throwable)) {
            Log.v(TAG, "%s: giving up on %s: %s", this, rev, throwable);
            pendingSequences.removeSequence(rev.getSequence());
            pauseOrResume();
        }
        completedChangesCount.getAndIncrement();
    }
```

**Comment by NitzDKoder** [comment]
@hideki 
1)When CBL(user A) is busy fetching old seq numbered docs.
2)Will the latest pushed docs(It will processed by Syncgateway and belongs to user A) will be part of the changes immediately?



Please share your thoughts..

**Comment by hideki** [comment]
Hi @NitzDKoder,
I recommend asking Sync Gateway question at Couchbase Forum or file the ticket on sync_gateway repository issue if you found the Sync Gateway problem.
Thanks

**Comment by NitzDKoder** [comment]
@hideki One more instance..

	Line 23649: [09/27 19:39:44:192] [2017] CBLite: setPaused: true
	Line 23714: [09/27 19:39:44:444] [2010] CBLite: setPaused: true
	Line 23801: [09/27 19:39:44:574] [2017] CBLite: setPaused: true
	Line 23817: [09/27 19:39:44:851] [2010] CBLite: setPaused: true
	Line 23886: [09/27 19:39:44:951] [2017] CBLite: setPaused: true
	Line 23901: [09/27 19:39:44:967] [2017] CBLite: setPaused: true
	Line 23925: [09/27 19:39:45:243] [2010] CBLite: setPaused: true
	Line 23989: [09/27 19:39:45:329] [2017] CBLite: setPaused: true
	Line 24004: [09/27 19:39:45:344] [2017] CBLite: setPaused: true
	Line 24019: [09/27 19:39:45:597] [2010] CBLite: setPaused: true
	Line 24107: [09/27 19:39:45:750] [2017] CBLite: setPaused: true
	Line 24138: [09/27 19:39:46:073] [2010] CBLite: setPaused: true
	Line 25032: [09/27 19:40:49:950] [2081] CBLite: setPaused: true
	Line 25046: [09/27 19:40:50:507] [2010] CBLite: setPaused: true
	Line 25129: [09/27 19:40:51:080] [2011] CBLite: setPaused: true
	Line 39257: [09/27 19:51:42:137] [2174] CBLite: setPaused: true
	Line 39277: [09/27 19:51:42:390] [2167] CBLite: setPaused: true
	Line 39341: [09/27 19:51:42:471] [2174] CBLite: setPaused: true
	Line 39356: [09/27 19:51:42:483] [2174] CBLite: setPaused: true
	Line 39371: [09/27 19:51:42:495] [2174] CBLite: setPaused: true
	Line 39543: [09/27 19:51:42:702] [2174] CBLite: setPaused: true
	Line 39560: [09/27 19:51:42:744] [2167] CBLite: setPaused: true
	Line 39627: [09/27 19:51:42:825] [2174] CBLite: setPaused: true
	Line 39641: [09/27 19:51:42:834] [2174] CBLite: setPaused: true
	Line 39660: [09/27 19:51:42:846] [2174] CBLite: setPaused: true
	Line 39815: [09/27 19:51:42:969] [2174] CBLite: setPaused: true
	Line 39828: [09/27 19:51:43:094] [2167] CBLite: setPaused: true
	Line 40892: [09/27 19:52:45:078] [2204] CBLite: setPaused: true
	Line 40916: [09/27 19:52:45:375] [2167] CBLite: setPaused: true
	Line 40995: [09/27 19:52:45:569] [2179] CBLite: setPaused: true
	Line 49539: [09/27 19:58:08:775] [2235] CBLite: setPaused: true
	Line 49552: [09/27 19:58:08:958] [2229] CBLite: setPaused: true
	Line 49709: [09/27 19:58:09:190] [2235] CBLite: setPaused: true
	Line 49738: [09/27 19:58:09:329] [2229] CBLite: setPaused: true
	Line 49883: [09/27 19:58:09:618] [2235] CBLite: setPaused: true
	Line 49911: [09/27 19:58:09:755] [2229] CBLite: setPaused: true
	Line 50331: [09/27 19:59:13:162] [2255] CBLite: setPaused: true
	Line 50345: [09/27 19:59:13:458] [2229] CBLite: setPaused: true
	Line 50428: [09/27 19:59:14:190] [2248] CBLite: setPaused: true
	Line 63490: [09/27 19:59:33:883] [2268] CBLite: setPaused: true
	Line 63504: [09/27 19:59:33:963] [2262] CBLite: setPaused: true
	Line 63796: [09/27 19:59:34:460] [2268] CBLite: setPaused: true
	Line 63809: [09/27 19:59:34:478] [2262] CBLite: setPaused: true
	Line 64148: [09/27 19:59:35:087] [2268] CBLite: setPaused: true
	Line 64153: [09/27 19:59:35:099] [2262] CBLite: setPaused: true
	Line 64404: [09/27 19:59:35:507] [2268] CBLite: setPaused: true
	Line 64545: [09/27 19:59:35:783] [2268] CBLite: setPaused: true
	Line 64637: [09/27 19:59:36:034] [2262] CBLite: setPaused: true
	Line 64696: [09/27 19:59:36:155] [2268] CBLite: setPaused: true
	Line 64755: [09/27 19:59:36:212] [2268] CBLite: setPaused: true
	Line 64768: [09/27 19:59:36:434] [2262] CBLite: setPaused: true
	Line 64840: [09/27 19:59:36:638] [2268] CBLite: setPaused: true
	Line 64855: [09/27 19:59:36:673] [2268] CBLite: setPaused: true
	Line 64889: [09/27 19:59:36:729] [2268] CBLite: setPaused: true
	Line 64903: [09/27 19:59:36:934] [2262] CBLite: setPaused: true
	Line 64973: [09/27 19:59:37:146] [2268] CBLite: setPaused: true
	Line 65018: [09/27 19:59:37:231] [2268] CBLite: setPaused: true
	Line 65031: [09/27 19:59:37:438] [2262] CBLite: setPaused: true
	Line 65103: [09/27 19:59:37:627] [2268] CBLite: setPaused: true
	Line 65118: [09/27 19:59:37:662] [2268] CBLite: setPaused: true
	Line 65151: [09/27 19:59:37:730] [2268] CBLite: setPaused: true
	Line 65165: [09/27 19:59:37:907] [2262] CBLite: setPaused: true
	Line 65280: [09/27 19:59:38:190] [2268] CBLite: setPaused: true
	Line 65293: [09/27 19:59:38:410] [2262] CBLite: setPaused: true
	Line 65367: [09/27 19:59:38:650] [2268] CBLite: setPaused: true
	Line 65414: [09/27 19:59:38:752] [2268] CBLite: setPaused: true
	Line 65430: [09/27 19:59:38:924] [2262] CBLite: setPaused: true
	Line 65542: [09/27 19:59:39:183] [2268] CBLite: setPaused: true
	Line 65562: [09/27 19:59:39:410] [2262] CBLite: setPaused: true
	Line 65894: [09/27 20:00:40:826] [2280] CBLite: setPaused: true
	Line 65911: [09/27 20:00:41:098] [2262] CBLite: setPaused: true
	Line 65991: [09/27 20:00:41:554] [2273] CBLite: setPaused: true


	Line 65890: [09/27 20:00:40:815] [2280] Sync: PullerInternal{https://---:---@syncqc3.company.com/ptxdata, pull, 1fd1b}: Incrementing changesCount count from 734 by adding 1 -> 735


[stuck_new.txt](https://github.com/couchbase/couchbase-lite-java-core/files/1390221/stuck_new.txt)

**Comment by NitzDKoder** [comment]
@hideki one more instance..
Logs attached
[cbl_logs.txt](https://github.com/couchbase/couchbase-lite-java-core/files/1390277/cbl_logs.txt)
[cbl_logs_old.txt](https://github.com/couchbase/couchbase-lite-java-core/files/1390278/cbl_logs_old.txt)

..

**Comment by hideki** [comment]
Hi @NitzDKoder 
Do you have additional information that you can share with this regarding this issue?

**Comment by hideki** [comment]
Hi @NitzDKoder,

I just read your other ticket #1674. From that ticket, I assume this ticket #1670 could be caused by a deadlock. Can you also capture the thread-dump when you encounter this problem again?

Thanks!

**Comment by NitzDKoder** [comment]
@hideki we are trying to get threaddump..

**Comment by NitzDKoder** [comment]
@hideki 

Use case:
1)2 continuous pull replication started.
2)Server has many docs(~14577) for the Client.

Client stuck in CBLite: setPaused: true and not pulling any docs.

CBL and thread dump losg added.


issue seen when client has more docs.

[cbl_logs.txt](https://github.com/couchbase/couchbase-lite-java-core/files/1470653/cbl_logs.txt)
[threads_report.txt](https://github.com/couchbase/couchbase-lite-java-core/files/1470654/threads_report.txt)
[threads_report1.txt](https://github.com/couchbase/couchbase-lite-java-core/files/1470655/threads_report1.txt)
[threads_report2.txt](https://github.com/couchbase/couchbase-lite-java-core/files/1470656/threads_report2.txt)
[threads_report4.txt](https://github.com/couchbase/couchbase-lite-java-core/files/1470657/threads_report4.txt)
[threads_report5.txt](https://github.com/couchbase/couchbase-lite-java-core/files/1470658/threads_report5.txt)
[threads_report6.txt](https://github.com/couchbase/couchbase-lite-java-core/files/1470659/threads_report6.txt)
[threads_report8.txt](https://github.com/couchbase/couchbase-lite-java-core/files/1470660/threads_report8.txt)
[threads_report9.txt](https://github.com/couchbase/couchbase-lite-java-core/files/1470661/threads_report9.txt)

[threads_report10.txt](https://github.com/couchbase/couchbase-lite-java-core/files/1470662/threads_report10.txt)

**Comment by NitzDKoder** [comment]
@hideki **Syncgateway logs added..**
**Please check and raise if any syncgateway issue..**
[sync_gateway_access.log](https://github.com/couchbase/couchbase-lite-java-core/files/1470684/sync_gateway_access.log)
[sync_gateway_access-2017-11-14T17-01-16.584.log](https://github.com/couchbase/couchbase-lite-java-core/files/1470685/sync_gateway_access-2017-11-14T17-01-16.584.log)
[sync_gateway_access-2017-11-14T17-04-41.797.log](https://github.com/couchbase/couchbase-lite-java-core/files/1470686/sync_gateway_access-2017-11-14T17-04-41.797.log)
[sync_gateway_access-2017-11-14T17-05-51.885.log](https://github.com/couchbase/couchbase-lite-java-core/files/1470687/sync_gateway_access-2017-11-14T17-05-51.885.log)
[sync_gateway_access-2017-11-14T17-06-21.440.log](https://github.com/couchbase/couchbase-lite-java-core/files/1470688/sync_gateway_access-2017-11-14T17-06-21.440.log)
[sync_gateway_access-2017-11-14T17-07-10.957.log](https://github.com/couchbase/couchbase-lite-java-core/files/1470689/sync_gateway_access-2017-11-14T17-07-10.957.log)
[sync_gateway_access-2017-11-14T17-08-10.008.log](https://github.com/couchbase/couchbase-lite-java-core/files/1470690/sync_gateway_access-2017-11-14T17-08-10.008.log)
[sync_gateway_access-2017-11-14T17-08-43.940.log](https://github.com/couchbase/couchbase-lite-java-core/files/1470691/sync_gateway_access-2017-11-14T17-08-43.940.log)
[sync_gateway_access-2017-11-14T17-09-18.273.log](https://github.com/couchbase/couchbase-lite-java-core/files/1470692/sync_gateway_access-2017-11-14T17-09-18.273.log)
[sync_gateway_access-2017-11-14T17-09-52.473.log](https://github.com/couchbase/couchbase-lite-java-core/files/1470693/sync_gateway_access-2017-11-14T17-09-52.473.log)
[sync_gateway_access-2017-11-14T17-10-15.993.log](https://github.com/couchbase/couchbase-lite-java-core/files/1470694/sync_gateway_access-2017-11-14T17-10-15.993.log)
[sync_gateway_access-2017-11-14T17-11-02.612.log](https://github.com/couchbase/couchbase-lite-java-core/files/1470695/sync_gateway_access-2017-11-14T17-11-02.612.log)
[sync_gateway_access-2017-11-14T17-11-25.492.log](https://github.com/couchbase/couchbase-lite-java-core/files/1470696/sync_gateway_access-2017-11-14T17-11-25.492.log)
[sync_gateway_access-2017-11-14T17-11-51.614.log](https://github.com/couchbase/couchbase-lite-java-core/files/1470697/sync_gateway_access-2017-11-14T17-11-51.614.log)
[sync_gateway_access-2017-11-14T17-12-26.975.log](https://github.com/couchbase/couchbase-lite-java-core/files/1470698/sync_gateway_access-2017-11-14T17-12-26.975.log)
[sync_gateway_access-2017-11-14T17-12-49.960.log](https://github.com/couchbase/couchbase-lite-java-core/files/1470699/sync_gateway_access-2017-11-14T17-12-49.960.log)
[sync_gateway_access-2017-11-14T17-13-26.685.log](https://github.com/couchbase/couchbase-lite-java-core/files/1470700/sync_gateway_access-2017-11-14T17-13-26.685.log)
[sync_gateway_access-2017-11-14T17-13-47.647.log](https://github.com/couchbase/couchbase-lite-java-core/files/1470701/sync_gateway_access-2017-11-14T17-13-47.647.log)

**Comment by hideki** [comment]
Note to Self:

- From thread-dump, none of the threads are blocked by other threads. So no dead-locking is observed. All replicator related threads are a waiting state.
-  log message: `CBLite: Waiting: true` indicates too many tasks in a queue, so ChangeTracker will not take new tasks (changes). https://github.com/couchbase/couchbase-lite-java-core/blob/3ed5056ee4edfe27e67f816f08d6e342fd7f8b73/src/main/java/com/couchbase/lite/replicator/ChangeTracker.java#L650-L661
- log message: `CBLite: setPaused: true` indicates too many tasks in the queue, so tell ChangeTracker to pause to retrieve changes. https://github.com/couchbase/couchbase-lite-java-core/blob/3ed5056ee4edfe27e67f816f08d6e342fd7f8b73/src/main/java/com/couchbase/lite/replicator/ChangeTracker.java#L640-L648 https://github.com/couchbase/couchbase-lite-java-core/blob/4f52cd55b50d32d7ef2cf79a3c0eb4bf38cde770/src/main/java/com/couchbase/lite/replicator/PullerInternal.java#L1090-L1093
- log message: `ReplicationInternal$2@25cd0502: BEGIN processInbox (1 sequences)` indicates only one item is in the `batcher` queue. And, `pendingSequences.count()` returns `200 (MAX_PENDING_DOCS)` or more.

From above indications, items in `pendingSequences` is not correctly removed by `removeSequence(long)` method. It could be expected sequence number by CBL client and sequence number with revision from SG does not match?

**Comment by hideki** [comment]
@NitzDKoder,
Question: When you encounter this issue, Does Sync Gateway and Couchbase Server cluster switch or something happen on the server side?

**Comment by hideki** [comment]
Hi @NitzDKoder,

First I'd like to confirm that `Waiting: true` log message is not the error message and it shows the state of `ChangeTracker` module.  In general,  retrieving changes from Sync Gateway is much lighter weight task than fetching the document/revision content from Sync Gateway or inserting the content into the database. If `ChangeTracker` keeps retrieving changes from the SG and creating subsequent tasks (fetching doc/rev from SG), it causes Out of Memory because these tasks (consuming memory) are queued as subsequent tasks. To prevent `Out of Memory`, pull replicator makes `ChangeTracker` to `waiting state` till subsequent tasks size becomes smaller. Many `Waiting: true` is expected log messages.

Insight from `cbl_logs.txt` that was recently attached: If you observed that pull replication did not replicate all expected documents/revisions from Sync Gateway,  I believe it was caused by 503 Service Unavailable HTTP error that was occurred on the server side. I could not find `Service Unavailable` string in [sync_gateway repo](https://github.com/couchbase/sync_gateway/search?utf8=%E2%9C%93&q=503&type=). So, this error could be returned by Proxy or Load Balancer.

> [11/14 17:16:37:917] [2109] Sync: retryReplicationIfError() state=IDLE, error=com.couchbase.lite.replicator.RemoteRequestResponseException: {code=503, message=Service Unavailable}, isContinuous()=true, isTransientError()=true

Insight from thread-dump: Following is  ChangeTracker's thread's stack trace. The thread waited to read data from SSL socket. **The thread did not wait at `waitIfPaused()` method.** If this thread-dumps were captured at the right timing, it proves `Waiting: true`, pausing logic did not cause the problem that you observed. The root cause was something else. I guess 503 error from the server.

```
"ChangeTracker-https://---:---@locqc3.domain.com/ptxdata@24035" prio=10 runnable
  java.lang.Thread.State: RUNNABLE
	  at com.android.org.conscrypt.NativeCrypto.SSL_read(NativeCrypto.java:-1)
	  at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:728)
	  - locked <0x5ea7> (a java.lang.Object)
	  at okio.Okio$2.read(Okio.java:140)
	  at okio.AsyncTimeout$2.read(AsyncTimeout.java:238)
	  at okio.RealBufferedSource.request(RealBufferedSource.java:66)
	  at okio.RealBufferedSource.require(RealBufferedSource.java:59)
```
Thread should wait at LINE 656 if pausing logic causes problem.
https://github.com/couchbase/couchbase-lite-java-core/blob/3ed5056ee4edfe27e67f816f08d6e342fd7f8b73/src/main/java/com/couchbase/lite/replicator/ChangeTracker.java#L650-L661


Please let us know if this makes sense?

**Comment by NitzDKoder** [comment]
@hideki So you mean after fetching docs from Server the changetracker will move out of the wait state and starts pulling?

We see this issue when user has lot of data.

SO we need to wait for longer time such that CBL will pull all data?

Thanks
Nithin

**Comment by NitzDKoder** [comment]
@"retryReplicationIfError() state=IDLE, error=com.couchbase.lite.replicator.RemoteRequestResponseException: {code=503, message=Service Unavailable}, isContinuous()=true, isTransientError()=true"


Sever was not down at that point of time. Will check the use case again and see if i can get different use case.

Will share logs.

**Comment by hideki** [comment]
@NitzDKoder 

> So you mean after fetching docs from Server the changetracker will move out of the wait state and starts pulling?

Yes

> We see this issue when user has lot of data.

I tested pull replicating 400,000 documents today. With my test environment, I could not observe the problem.

`Waiting: true` log message itself is not the problem. If ChangeTracker can not move out from the state, it is a problem. However, I can not observe the indication from the latest log file and thread-dump.

> SO we need to wait for longer time such that CBL will pull all data?

It depends on the environment such as a number of docs, size of docs, network condition, or device.

**Comment by NitzDKoder** [comment]
@hideki other thing to notice is that client pulled lot of deleted docs(1000s) from server.

https://github.com/couchbase/couchbase-lite-java-core/issues/1264#issuecomment-323161266

We have validator to reject those.


"Database: reject PTX server TTL doc delete or channel remove"

**Comment by NitzDKoder** [comment]
@hideki
1)When CBL(user A) is busy fetching old seq numbered docs.
2)Will the latest pushed docs(It will processed by Syncgateway and belongs to user A) will be part of the changes immediately?
**Line 25410: [11/14 17:10:44:653] [1980] CBLite: ---> Added: {s919888880032_ptx1510659644491_meta.doc #1-bda4d3a410a0f2934e78397acb1f28d5 @30} as seq 30**

Please share your thoughts..

**Comment by hideki** [comment]
@NitzDKoder 
Can you ask the last question through the customer support,[ Couchbase Forum](https://forums.couchbase.com/c/mobile) or  [Sync Gateway](https://github.com/couchbase/sync_gateway/issues)?

**Comment by NitzDKoder** [comment]
@hideki 


@[10/09 13:10:24:935] [590] Sync: com.couchbase.lite.replicator.PullerInternal$9@e0903f2: Remote rev failed validation: {s919999910122_ptx1506127718008_meta.doc #3-fc81f6330ef76ade75e4f76ec8d36adb @2712 DEL}
[10/09 13:10:24:936] [590] Sync: com.couchbase.lite.replicator.PullerInternal$9@e0903f2: finished inserting 1 revisions
[10/09 13:10:24:936] [590] Sync: com.couchbase.lite.replicator.PullerInternal$9@e0903f2: inserted 1 revs in 11 milliseconds
[10/09 13:10:24:937] [590] Sync: com.couchbase.lite.replicator.PullerInternal$9@e0903f2 insertDownloads() updating completedChangesCount from 2710 -> 2711 



**Going back to initial logs which was shared.. CBLite: setPaused: true**


[10/09 13:10:24:937] [590] Sync: PullerInternal{https://---:---@syncqc7.company.com/data, pull, 88db8}: Incrementing completedChangesCount count from 2710 by adding 1 -> 2711




Change tracker thread **[622]** CBLite: Waiting: true for 3 mins..when would it recover and its not pulling any doc from sever either..



[cbl_logs (1).txt](https://github.com/couchbase/couchbase-lite-java-core/files/1473805/cbl_logs.1.txt)

**Comment by hideki** [comment]
@NitzDKoder 

> other thing to notice is that client pulled lot of deleted docs(1000s) from server.

I tested 1000 deleted pull replication and also 400000 regular docs and 1000 deleted document pull replication. Both scenarios work fine with my env.

**Comment by hideki** [comment]
@NitzDKoder 

From [cbl_logs (1).txt](https://github.com/couchbase/couchbase-lite-java-core/files/1473805/cbl_logs.1.txt), I could observe following messages between `Waiting: true`. `setPaused(false);` makes `ChangeTracker` out of `paused` state.  So `ChangeTracker` frequently entered `pause` state and out of `pause` state. So this is expected behavior to prevent `Out of Memory`.

```
[10/09 13:12:44:450] [599] Sync: setPaused: false
```

**Comment by hideki** [comment]
@NitzDKoder,
I have a suggestion. I believe you could compile CBL from source code. So you could add logging at LINE660 to make sure if ChangeTracker exists from pause state?
https://github.com/couchbase/couchbase-lite-java-core/blob/3ed5056ee4edfe27e67f816f08d6e342fd7f8b73/src/main/java/com/couchbase/lite/replicator/ChangeTracker.java#L660

**Comment by NitzDKoder** [comment]
@hideki 
@	Line 14: [10/09 13:12:49:129] [622] CBLite: Waiting: true
	Line 92: [10/09 13:12:54:129] [622] CBLite: Waiting: true
	Line 93: [10/09 13:12:59:130] [622] CBLite: Waiting: true
	Line 94: [10/09 13:13:04:131] [622] CBLite: Waiting: true
	Line 125: [10/09 13:13:09:132] [622] CBLite: Waiting: true
	Line 156: [10/09 13:13:14:133] [622] CBLite: Waiting: true
	Line 172: [10/09 13:13:19:133] [622] CBLite: Waiting: true
	Line 173: [10/09 13:13:24:134] [622] CBLite: Waiting: true
	Line 174: [10/09 13:13:29:135] [622] CBLite: Waiting: true
	Line 223: [10/09 13:13:34:136] [622] CBLite: Waiting: true
	Line 224: [10/09 13:13:39:137] [622] CBLite: Waiting: true
	Line 255: [10/09 13:13:44:137] [622] CBLite: Waiting: true
	Line 266: [10/09 13:13:49:138] [622] CBLite: Waiting: true
	Line 297: [10/09 13:13:54:139] [622] CBLite: Waiting: true

[622] is still in waiting state, can you clarify on that.

Will add logs to ChangeTracker exists from pause state.

**Comment by hideki** [comment]
@NitzDKoder As I wrote before, ChangeTracker enters the waiting (pausing) state and out of state repeatedly if there are many changes. CBL logs only the waiting state, not the non-waiting state. So, many `Watiting: true` logged strings cannot prove if ChangeTracker is stuck in `waitIfPaused()` method.

**Comment by NitzDKoder** [comment]
@hideki will expirement on with logs added..
Thanks!

**Comment by NitzDKoder** [comment]
@hideki 
Have added more logs..

 ```
   protected void waitIfPaused() {
        Log.v(Log.TAG, "waitIfPaused Start: " + paused  +" running: "+running);
        synchronized (pausedObj) {
            while (paused && running) {
                Log.v(Log.TAG, "Waiting: " + paused);
                try {
                    // every 5 sec, wake by myself to check if still needs to pause
                    pausedObj.wait(TIMEOUT_FOR_PAUSE);
                } catch (InterruptedException e) {
                }
            }
            Log.v(Log.TAG, "waitIfPaused Exit: " + paused  +" running: "+running);
        }
    }
```
@	**Line 102613: [11/23 11:43:35:864] [531] CBLite: waitIfPaused Start: true running: true**

Goes to wait state 

**@[11/23 14:05:09:453] [531] CBLite: Waiting: true**

Still in waiting.

**[11/23 14:05:09:453] [531] CBLite: Waiting: true**

Please check , logs added.
[3.txt](https://github.com/couchbase/couchbase-lite-java-core/files/1517454/3.txt)
[4.txt](https://github.com/couchbase/couchbase-lite-java-core/files/1517455/4.txt)
[5.txt](https://github.com/couchbase/couchbase-lite-java-core/files/1517456/5.txt)
[6.txt](https://github.com/couchbase/couchbase-lite-java-core/files/1517457/6.txt)
[one.txt](https://github.com/couchbase/couchbase-lite-java-core/files/1517458/one.txt)
[two.txt](https://github.com/couchbase/couchbase-lite-java-core/files/1517459/two.txt)


Thanks
Nithin

**Comment by hideki** [comment]
From the log files, `waitIfPaused Exit:` message is not observed.  It indicates `paused` variable was not changed to `false`. I assume other threads can not process succeeding tasks. Then `pending >= MAX_PENDING_DOCS` was always true.
```java
protected void pauseOrResume() { 
     int pending = batcher.count() + pendingSequences.count(); 
     changeTracker.setPaused(pending >= MAX_PENDING_DOCS); 
 } 
```

**Comment by NitzDKoder** [comment]
@hideki 
```
[11/23 11:43:36:724] [520] Sync: PullerInternal{https://---:---@syncqc3.kodiakhandset.com/ptxdata, pull, 6afd0}: Progress: set error = com.couchbase.lite.replicator.RemoteRequestResponseException: {code=503, message=Service Unavailable}
[11/23 11:43:36:725] [520] Sync: com.couchbase.lite.replicator.RemoteBulkDownloaderRequest[/ptxdata/_bulk_get]: RemoteRequest execute() finished, url: https://919888881462:3617cc40910fb5470b71f0647d78fb53@syncqc3.kodiakhandset.com/ptxdata/_bulk_get?revs=true&attachments=true
```
Puller is getting "**code=503, message=Service Unavailable**" is this issue here..Puller should retry and come out of wait state isnt..???

Thanks
Nihtin

**Comment by hideki** [comment]
503 is a tentative error. So the replicator should retry.

**Comment by NitzDKoder** [comment]
Same as https://github.com/couchbase/couchbase-lite-java-core/issues/1670
