### ISSUE TITLE
Expected ':status' header not present

### ISSUE THREAD

**Issue by daberni** [couchbase/couchbase-lite-java-core#1684]
When running a couchbase database behind a current release of nginx the following error is thrown when replication is set up with the latest couchbase-lite version 1.4.1:

```
com.couchbase.lite.replicator.RemoteRequest {GET, ***}: executeRequest() Exception: java.net.ProtocolException: Expected ':status' header not present.  url: ***
  java.net.ProtocolException: Expected ':status' header not present
      at okhttp3.internal.http.Http2xStream.readHttp2HeadersList(Http2xStream.java:267)
      at okhttp3.internal.http.Http2xStream.readResponseHeaders(Http2xStream.java:150)
      at okhttp3.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:775)
      at okhttp3.internal.http.HttpEngine.access$200(HttpEngine.java:86)
      at okhttp3.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:760)
      at okhttp3.internal.http.HttpEngine.readResponse(HttpEngine.java:613)
      at okhttp3.RealCall.getResponse(RealCall.java:244)
      at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:201)
      at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:163)
      at okhttp3.RealCall.execute(RealCall.java:57)
      at com.couchbase.lite.replicator.RemoteRequest.executeRequest(RemoteRequest.java:261)
      at com.couchbase.lite.replicator.RemoteRequest.execute(RemoteRequest.java:165)
      at com.couchbase.lite.replicator.RemoteRequest.run(RemoteRequest.java:105)
      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
      at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
      at java.lang.Thread.run(Thread.java:764)
```

This is due to a change in one of the latest ngnix releases and the current used version of okhttp not supporting it.
see <https://trac.nginx.org/nginx/ticket/1397>, and probably <https://github.com/square/okhttp/issues/640>
but I could not determinate the exact commit which resolved this. Anyway this exception doesn't occur in the latest release of okhttp

**Comment by hideki** [comment]
Hi @daberni,
Thank you very much for reporting this issue.
We will update OkHttp to latest.
Thanks,
Hideki

**Comment by hideki** [comment]
Note to self:

Simply upgrading OkHttp 3.9.1 causes some unit test failures.

**Comment by pasin** [comment]
I have updated OKHTTP to v3.11.0 and fixed unit test failures.
