### ISSUE TITLE
TimeoutException on free/finalize of `ResultSet`

### ISSUE THREAD

**Issue by dtchepak** [couchbase/couchbase-lite-java-core#1693]
Hi,

Unable to reproduce this locally so far, but have seen some crashes come through trying to finalize `ResultSet`:

```
java.util.concurrent.TimeoutException: com.couchbase.lite.ResultSet.finalize() timed out after 60 seconds
	at com.couchbase.lite.ResultSet.free(ResultSet.java:12)
	at com.couchbase.lite.ResultSet.finalize(ResultSet.java:0)
	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:250)
	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:237)
	at java.lang.Daemons$Daemon.run(Daemons.java:103)
	at java.lang.Thread.run(Thread.java:764)
```

Have seen similar exceptions with `AbstractQuery.free`. I'm wondering if this is a deadlock related to the `free()` methods locking the database?

Appreciate any advice on reproducing/fixing this.

**Comment by bmeike** [comment]
This is an obsolete repo.  My apologies that it is not so noted.  Will fix that ASAP.

Please leave further communications in https://github.com/couchbase/couchbase-lite-java-ce-root

**Comment by bmeike** [comment]
Tracked in https://issues.couchbase.com/browse/CBL-1051
