### ISSUE TITLE
NPE thrown when running ApiTest.testLiveQueryRun

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-java-core#296]
This exception has been seen when running ApiTest.testLiveQueryRun in couchbase-lite-java. When running the whole test suit, the exception will prevent the other tests to run (The test app stopped). The test will pass with the exception printed out when running the testLiveQueryRun alone.

Exception:
```
Oct 09, 2014 5:06:18 PM com.couchbase.lite.util.SystemLogger v
FINER: View: Query vu: SELECT key, value, docid, revs.sequence FROM maps, revs, docs WHERE maps.view_id=? AND key >= ? AND key <= ? AND revs.sequence = maps.sequence AND docs.doc_id = revs.doc_id ORDER BY key LIMIT ? OFFSET ? | args: [0, 23, 33, 2147483647, 0]
Oct 09, 2014 5:06:18 PM com.couchbase.lite.util.SystemLogger e
SEVERE: Query: Exception caught in runAsyncInternal
java.lang.NullPointerException
	at com.couchbase.lite.View.resultSetWithOptions(View.java:685)
	at com.couchbase.lite.View.queryWithOptions(View.java:853)
	at com.couchbase.lite.Database.queryViewNamed(Database.java:2062)
	at com.couchbase.lite.Query$1.run(Query.java:403)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```
Steps to reproduce:
1. Disable the sleep workaround at the end of the ApiTest.runLiveQuery() method
2. Run ApiTest.testLiveQueryRun

What is going on:
The test's tearDown() method is called (result to closing database) before the LiveQuery finished its async update that was rerun after the LiveQuery got result.

**Comment by tleyden** [comment]
I removed the workaround, but could not produce any issues when testing couchbase-lite-java.

**Comment by tleyden** [comment]
Now I'm seeing issues.  Re-opening.

```
Jan 16, 2015 10:39:00 AM com.couchbase.lite.util.SystemLogger e
SEVERE: Query: Exception caught in runAsyncInternal
java.lang.NullPointerException
	at com.couchbase.lite.View.resultSetWithOptions(View.java:747)
	at com.couchbase.lite.View.queryWithOptions(View.java:954)
	at com.couchbase.lite.Database.queryViewNamed(Database.java:2112)
	at com.couchbase.lite.Query$1.run(Query.java:448)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

```
