### ISSUE TITLE
java.lang.InterruptedException

### ISSUE THREAD

**Issue by QRPro** [couchbase/couchbase-lite-java-core#357]
Replication error

```
12-17 17:14:46.139: W/System.err(23986): java.lang.InterruptedException
12-17 17:14:46.140: W/System.err(23986): 	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireInterruptibly(AbstractQueuedSynchronizer.java:1197)
12-17 17:14:46.140: W/System.err(23986): 	at java.util.concurrent.locks.ReentrantLock.lockInterruptibly(ReentrantLock.java:306)
12-17 17:14:46.140: W/System.err(23986): 	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:407)
12-17 17:14:46.140: W/System.err(23986): 	at com.couchbase.lite.support.Batcher.processNow(Batcher.java:196)
12-17 17:14:46.140: W/System.err(23986): 	at com.couchbase.lite.support.Batcher.access$1(Batcher.java:171)
12-17 17:14:46.140: W/System.err(23986): 	at com.couchbase.lite.support.Batcher$1.run(Batcher.java:45)
12-17 17:14:46.140: W/System.err(23986): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
12-17 17:14:46.140: W/System.err(23986): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
12-17 17:14:46.140: W/System.err(23986): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
12-17 17:14:46.140: W/System.err(23986): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
12-17 17:14:46.140: W/System.err(23986): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
12-17 17:14:46.142: W/System.err(23986): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
12-17 17:14:46.142: W/System.err(23986): 	at java.lang.Thread.run(Thread.java:818)
```

**Comment by tleyden** [comment]
@QRPro - any update on this?

**Comment by hideki** [comment]
Hi @QRPro,
Do you have any updates about this issue?
Thanks!

**Comment by hideki** [comment]
Note to self:

[BlockingQueue.take()](http://docs.oracle.com/javase/7/docs/api/java/util/concurrent/BlockingQueue.html#take()) could be interrupted. But `processNow()` waits till inbox size becomes 0 by  `while(inbox.size() > 0)`. So, instead of e.printStackTrace(). We just need to show regular Log message.
