### ISSUE TITLE
ToDoLite: PushReplicator throws Exception

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-java-core#400]
Steps to reproduce
1. Run ToDo Lite App on mobile (point to sync-gateway on localhost)
2. Store some tasks in mobile db. Maybe with photos
3. Stop ToDo Lite App
4. Start Sync Gateway (on localhost with walrus)
5. Start ToDo Lite App on Mobile (point to sync-gateway on localhost)
6. observe some logs at mobile
7. observe following exceptions.

Note:
It seems casting issue, object is Integer, but try to cast to String.

```
01-28 00:32:52.233    2334-2385/com.couchbase.todolite E/CBLite﹕ Exception getting status from {error=forbidden, id=p:emaib@gmx.de, reason=wrong user, status=403}
    java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
            at com.couchbase.lite.replicator.ReplicationInternal.statusFromBulkDocsResponseItem(ReplicationInternal.java:1404)
            at com.couchbase.lite.replicator.PusherInternal$4.onCompletion(PusherInternal.java:500)
            at com.couchbase.lite.support.RemoteRequestRetry$1.completed(RemoteRequestRetry.java:193)
            at com.couchbase.lite.support.RemoteRequestRetry$1.onCompletion(RemoteRequestRetry.java:204)
            at com.couchbase.lite.support.RemoteRequest.respondWithResult(RemoteRequest.java:299)
            at com.couchbase.lite.support.RemoteRequest.executeRequest(RemoteRequest.java:249)
            at com.couchbase.lite.support.RemoteRequest.run(RemoteRequest.java:105)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
```

**Comment by tleyden** [comment]
@ajres have you re-deployed the demo cluster?  There was some changes made to the way sync gateway treats facebook users, which the clients will need an update for.  I wonder if that is what got broken here.

**Comment by ajres** [comment]
@tleyden No recent changes to SG on the demo cluster, I think it's still running 1.0.3

**Comment by tleyden** [comment]
I tried to repro but was not able to.  I was using the master branch with the genymotion emulator.  I uninstalled the app and then logged in.

**Comment by hideki** [comment]
My recent changes might cause this issue. After all PRs are merged, I will revisit this issue.

**Comment by hideki** [comment]
TODO: I should retest this issue with latest master branch.
