### ISSUE TITLE
testExcessiveCheckpointingDuringPushReplication failed(should be isolates/fixed?) 

### ISSUE THREAD

**Issue by andreibaranouski** [couchbase/couchbase-lite-java-core#420]
com.couchbase.lite.replicator.Replication2Test > testExcessiveCheckpointingDuringPushReplication[hudson_en-US_160_WVGA_android-19_armeabi-v7a_param(AVD) - 4.4.2] [31mFAILED [0m
	junit.framework.AssertionFailedError: expected:<6f23713a-9211-4358-9499-ac008655854f> but was:<0b414cd9-ee14-4612-92fb-d793ceb26255>
	at com.couchbase.lite.LiteTestCase.assertBulkDocJsonContainsDoc(LiteTestCase.java:735)

there is a commit to isolate this test but it still run  https://github.com/couchbase/couchbase-lite-android/commit/83cb67d1a0fe2a3def56a681fb2746e38678cf7a

http://172.23.113.52:8080/job/couchbase-lite-android-build/35/consoleFull
http://172.23.113.52:8080/job/couchbase-lite-android-build/35/artifact/logcat.txt

```
02-09 15:14:58.977 I/TestRunner( 1074): failed: testExcessiveCheckpointingDuringPushReplication(com.couchbase.lite.replicator.Replication2Test)
02-09 15:14:58.977 I/TestRunner( 1074): ----- begin exception -----
02-09 15:14:58.977 I/TestRunner( 1074): 
02-09 15:14:58.977 I/TestRunner( 1074): junit.framework.AssertionFailedError: expected:<6f23713a-9211-4358-9499-ac008655854f> but was:<0b414cd9-ee14-4612-92fb-d793ceb26255>
02-09 15:14:58.977 I/TestRunner( 1074): 	at junit.framework.Assert.fail(Assert.java:50)
02-09 15:14:58.977 I/TestRunner( 1074): 	at junit.framework.Assert.failNotEquals(Assert.java:287)
02-09 15:14:58.977 I/TestRunner( 1074): 	at junit.framework.Assert.assertEquals(Assert.java:67)
02-09 15:14:58.977 I/TestRunner( 1074): 	at junit.framework.Assert.assertEquals(Assert.java:74)
02-09 15:14:58.977 I/TestRunner( 1074): 	at com.couchbase.lite.LiteTestCase.assertBulkDocJsonContainsDoc(LiteTestCase.java:735)
02-09 15:14:58.977 I/TestRunner( 1074): 	at com.couchbase.lite.replicator.Replication2Test.testExcessiveCheckpointingDuringPushReplication(Replication2Test.java:108)
02-09 15:14:58.977 I/TestRunner( 1074): 	at java.lang.reflect.Method.invokeNative(Native Method)
02-09 15:14:58.977 I/TestRunner( 1074): 	at java.lang.reflect.Method.invoke(Method.java:515)
02-09 15:14:58.977 I/TestRunner( 1074): 	at junit.framework.TestCase.runTest(TestCase.java:168)
02-09 15:14:58.977 I/TestRunner( 1074): 	at junit.framework.TestCase.runBare(TestCase.java:134)
02-09 15:14:58.977 I/TestRunner( 1074): 	at junit.framework.TestResult$1.protect(TestResult.java:115)
02-09 15:14:58.977 I/TestRunner( 1074): 	at junit.framework.TestResult.runProtected(TestResult.java:133)
02-09 15:14:58.977 I/TestRunner( 1074): 	at junit.framework.TestResult.run(TestResult.java:118)
02-09 15:14:58.977 I/TestRunner( 1074): 	at junit.framework.TestCase.run(TestCase.java:124)
02-09 15:14:58.977 I/TestRunner( 1074): 	at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:191)
02-09 15:14:58.977 I/TestRunner( 1074): 	at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:176)
02-09 15:14:58.977 I/TestRunner( 1074): 	at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:554)
02-09 15:14:58.977 I/TestRunner( 1074): 	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1701)
02-09 15:14:58.977 I/TestRunner( 1074): ----- end exception -----
```

**Comment by hideki** [comment]
PR is for CBL Android Unit Test Case:  https://github.com/couchbase/couchbase-lite-android/pull/525

**Comment by pasin** [comment]
Merged.
