### ISSUE TITLE
testBatcherWaitsForProcessorDelay2 failed with the latest modification

### ISSUE THREAD

**Issue by andreibaranouski** [couchbase/couchbase-lite-java-core#421]
com.couchbase.lite.support.BatcherTest > testBatcherWaitsForProcessorDelay2[hudson_en-US_160_WVGA_android-19_armeabi-v7a_param(AVD) - 4.4.2] [31mFAILED [0m
	junit.framework.AssertionFailedError
	at com.couchbase.lite.support.BatcherTest.testBatcherWaitsForProcessorDelay2(BatcherTest.java:301)

https://github.com/couchbase/couchbase-lite-android/commit/83908045162a35650789f7ec327e8bde8dbc6ac4#diff-88a7d453965873d9ac5d0f5c6651611aL308
this commit 'broke' the test

http://172.23.113.52:8080/job/couchbase-lite-android-build/35/consoleFull
http://172.23.113.52:8080/job/couchbase-lite-android-build/35/artifact/logcat.txt

```
02-09 15:21:06.067 I/TestRunner( 1074): failed: testBatcherWaitsForProcessorDelay2(com.couchbase.lite.support.BatcherTest)
02-09 15:21:06.077 I/TestRunner( 1074): ----- begin exception -----
02-09 15:21:06.077 I/TestRunner( 1074): 
02-09 15:21:06.077 I/TestRunner( 1074): junit.framework.AssertionFailedError
02-09 15:21:06.077 I/TestRunner( 1074): 	at junit.framework.Assert.fail(Assert.java:48)
02-09 15:21:06.077 I/TestRunner( 1074): 	at junit.framework.Assert.assertTrue(Assert.java:20)
02-09 15:21:06.077 I/TestRunner( 1074): 	at junit.framework.Assert.assertTrue(Assert.java:27)
02-09 15:21:06.077 I/TestRunner( 1074): 	at com.couchbase.lite.support.BatcherTest.testBatcherWaitsForProcessorDelay2(BatcherTest.java:301)
02-09 15:21:06.077 I/TestRunner( 1074): 	at java.lang.reflect.Method.invokeNative(Native Method)
02-09 15:21:06.077 I/TestRunner( 1074): 	at java.lang.reflect.Method.invoke(Method.java:515)
02-09 15:21:06.077 I/TestRunner( 1074): 	at junit.framework.TestCase.runTest(TestCase.java:168)
02-09 15:21:06.077 I/TestRunner( 1074): 	at junit.framework.TestCase.runBare(TestCase.java:134)
02-09 15:21:06.077 I/TestRunner( 1074): 	at junit.framework.TestResult$1.protect(TestResult.java:115)
02-09 15:21:06.077 I/TestRunner( 1074): 	at junit.framework.TestResult.runProtected(TestResult.java:133)
02-09 15:21:06.077 I/TestRunner( 1074): 	at junit.framework.TestResult.run(TestResult.java:118)
02-09 15:21:06.077 I/TestRunner( 1074): 	at junit.framework.TestCase.run(TestCase.java:124)
02-09 15:21:06.077 I/TestRunner( 1074): 	at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:191)
02-09 15:21:06.077 I/TestRunner( 1074): 	at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:176)
02-09 15:21:06.077 I/TestRunner( 1074): 	at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:554)
02-09 15:21:06.077 I/TestRunner( 1074): 	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1701)
02-09 15:21:06.077 I/TestRunner( 1074): ----- end exception -----
```

**Comment by hideki** [comment]
Latest codes still fails with `BatcherTest.testBatcherWaitsForProcessorDelay2()`
```
// https://github.com/couchbase/couchbase-lite-java-core/issues/403
// Delay is not applied if docs are more than batcher capacity
if(k == 0) {
     assertTrue("delta is " + delta, delta >= processorDelay);
}
```
