### ISSUE TITLE
Sync fails to insert attachment during initial sync (null attachment key)

### ISSUE THREAD

**Issue by jcamp1** [couchbase/couchbase-lite-java-core#422]
Greetings,

During a clean sync process (database was empty before starting sync) I get the following error:

```
2-11 16:54:53.528    2269-2296/com.sightplan.residentapptest E/SQLiteLog﹕ (1299) abort at 11 in [INSERT INTO attachments(type,sequence,revpos,filename) VALUES (?,?,?,?)]: NOT NULL constraint failed: attachments.key
02-11 16:54:53.528    2269-2296/com.sightplan.residentapptest E/SQLiteDatabase﹕ Error inserting type=image/jpeg sequence=14150 revpos=247 filename=thumbnail
    android.database.sqlite.SQLiteConstraintException: NOT NULL constraint failed: attachments.key (code 1299)
            at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
            at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:782)
            at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
            at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
            at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1471)
            at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1341)
            at com.couchbase.lite.android.AndroidSQLiteStorageEngine.insert(AndroidSQLiteStorageEngine.java:116)
            at com.couchbase.lite.Database.insertAttachmentForSequenceWithNameAndType(Database.java:2540)
            at com.couchbase.lite.Database.insertAttachmentForSequence(Database.java:2497)
            at com.couchbase.lite.Database.processAttachmentsForRevision(Database.java:3027)
            at com.couchbase.lite.Database.forceInsert(Database.java:4028)
            at com.couchbase.lite.replicator.PullerInternal.insertDownloads(PullerInternal.java:510)
            at com.couchbase.lite.replicator.PullerInternal$1.process(PullerInternal.java:96)
            at com.couchbase.lite.support.Batcher.processNow(Batcher.java:221)
            at com.couchbase.lite.support.Batcher.access$100(Batcher.java:23)
            at com.couchbase.lite.support.Batcher$1.run(Batcher.java:44)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
02-11 16:54:53.528    2269-2296/com.sightplan.residentapptest E/CBLite﹕ Insert attachment failed (returned -1)
```
Sync then stops, waits for a minute, and tries again with the same result, creating an infinite loop of sync failing. The iOS client handles the same data without issue.

**Comment by jcamp1** [comment]
Added gist of logcat:

https://gist.githubusercontent.com/jcamp1/4caabfe0f222c866f396/raw/LogCat%20Output

**Comment by hideki** [comment]
Note to self:

From log message, there are two Exceptions.

1. NullPointerException at at com.couchbase.lite.Database.forceInsert(Database.java:4020)
2. SQLiteConstraintException at at com.couchbase.lite.Database.insertAttachmentForSequenceWithNameAndType(Database.java:2543)

##### NPE at forceInsert:
- `newRev.getAttachments()` is null, but code calls `newRev.getAttachments().size()`.
- `RevisionInternal.getAttachments()` returns `getProperties().get("_attachments")`. It seems the value of _attachments is null.
- From the codes, `_attachments`'s value should not be null.

=> Add null check.

##### SQLiteConstraintException at insertAttachmentForSequenceWithNameAndType:
- `attachments` table's `key` field should not be null. But, in `Database.insertAttachmentForSequenceWithNameAndType()`, `key` field is not set if given parameter `key` is null.
- `AttachmentInternal` object is prepared in `Database.getAttachmentsFromRevision()`
- `null` key could be generated in https://github.com/couchbase/couchbase-lite-java-core/blob/29414a8f41ddf76a6b668c3add88b857371f9a95/src/main/java/com/couchbase/lite/Database.java#L3845-L3868

**Comment by hideki** [comment]
Hi @jcamp1,

I think special condition you encounter creates [BlobKey](https://github.com/couchbase/couchbase-lite-java-core/blob/4bf559f0151d58e0bfb77248f3d90f64bc096a91/src/main/java/com/couchbase/lite/BlobKey.java#L32) with bytes variable with null in following code. Could you please debug to identify what causes it?

https://github.com/couchbase/couchbase-lite-java-core/blob/29414a8f41ddf76a6b668c3add88b857371f9a95/src/main/java/com/couchbase/lite/Database.java#L3845-L3868

I'd like to use [feature/branch](https://github.com/couchbase/couchbase-lite-java-core/tree/feature/issue_422_pull_repl_null_attachment) which has null check for NPE in `forceInsert()` method.

**Comment by hideki** [comment]
note to self:

in CBL iOS `- (CBLStatus) installAttachment: (CBL_Attachment*)attachment forInfo: (NSDictionary*)attachInfo` method always returns ERROR if any failure 
https://github.com/couchbase/couchbase-lite-ios/blob/release/1.0.4/Source/CBLDatabase%2BAttachments.m#L122-L152

In CBL Java Core `void installAttachment(AttachmentInternal attachment, Map<String, Object> attachInfo) throws CouchbaseLiteException` method returns ERROR for two scenarios.
https://github.com/couchbase/couchbase-lite-java-core/blob/29414a8f41ddf76a6b668c3add88b857371f9a95/src/main/java/com/couchbase/lite/Database.java#L2557-L2573

This difference might cause the error user encounters.

**Comment by jcamp1** [comment]
Hi @hideki,

Upon some poking around I found that the images that are causing the null exception are running in the 
```
else if (attachInfo.containsKey("follows") && ((Boolean)attachInfo.get("follows")).booleanValue() == true) {
```
block of code, not the code above it that creates the outblockkey.

**Comment by hideki** [comment]
Hi @jcamp1,
Thank you for debugging the issue. It makes me consider the implementation of `installAttachment()` method causes your issue.

**Comment by hideki** [comment]
Hi @jcamp1,

I added the code that potentially fixes the issue, and posted on the branch https://github.com/couchbase/couchbase-lite-java-core/tree/feature/issue_422_pull_repl_null_attachment
When you have time, could you please test it?

If this fixes issue, you can see following message in Log.
```
Log.w(Database.TAG, "No pending attachment for digest: " + digest);
```

**Comment by jcamp1** [comment]
Hi @hideki,

I ran a test against the 422 branch and I did see the warning log message you mentioned twice. Your fix appears to have fixed the null insert issue.

Thanks!

**Comment by hideki** [comment]
@jcamp1 Thank you for verifying the fix. I am glad to hear it.
