### ISSUE TITLE
NPE in Pull Replication

### ISSUE THREAD

**Issue by QRPro** [couchbase/couchbase-lite-java-core#449]
Replication, couchbase lite 1.0.4

```
02-19 17:11:05.580: E/RemoteRequest(14411): java.lang.NullPointerException
02-19 17:11:05.580: E/RemoteRequest(14411):     at com.couchbase.lite.replicator.PullerInternal.pullRemoteRevision(PullerInternal.java:588)
02-19 17:11:05.580: E/RemoteRequest(14411):     at com.couchbase.lite.replicator.PullerInternal.pullRemoteRevisions(PullerInternal.java:260)
02-19 17:11:05.580: E/RemoteRequest(14411):     at com.couchbase.lite.replicator.PullerInternal$7.onCompletion(PullerInternal.java:624)
02-19 17:11:05.580: E/RemoteRequest(14411):     at com.couchbase.lite.support.RemoteRequestRetry$1.completed(RemoteRequestRetry.java:178)
02-19 17:11:05.580: E/RemoteRequest(14411):     at com.couchbase.lite.support.RemoteRequestRetry$1.onCompletion(RemoteRequestRetry.java:189)
02-19 17:11:05.580: E/RemoteRequest(14411):     at com.couchbase.lite.support.RemoteRequest.respondWithResult(RemoteRequest.java:310)
02-19 17:11:05.580: E/RemoteRequest(14411):     at com.couchbase.lite.support.RemoteMultipartDownloaderRequest.executeRequest(RemoteMultipartDownloaderRequest.java:127)
02-19 17:11:05.580: E/RemoteRequest(14411):     at com.couchbase.lite.support.RemoteMultipartDownloaderRequest.run(RemoteMultipartDownloaderRequest.java:46)
02-19 17:11:05.580: E/RemoteRequest(14411):     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
02-19 17:11:05.580: E/RemoteRequest(14411):     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
02-19 17:11:05.580: E/RemoteRequest(14411):     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
02-19 17:11:05.580: E/RemoteRequest(14411):     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
02-19 17:11:05.580: E/RemoteRequest(14411):     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
02-19 17:11:05.580: E/RemoteRequest(14411):     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
02-19 17:11:05.580: E/RemoteRequest(14411):     at java.lang.Thread.run(Thread.java:841)
```

**Comment by hideki** [comment]
Some reason, rev (RevisionInternal) is null. Could you please explain how you caused this issue?

**Comment by pasin** [comment]
@QRPro Can you enable some Sync logging options and post the log messages?

```
Manager.enableLogging("Sync", Log.VERBOSE);
Manager.enableLogging("Sync", Log.DEBUG);
```

**Comment by QRPro** [comment]
Test app (Eclipse project):
https://yadi.sk/d/V-ufTKemf8wQM

During continious replication you get this error.

**Comment by hideki** [comment]
related issue => #448

**Comment by hideki** [comment]
Sample code was provided. Make sure if latest code still cause NPE.

**Comment by hideki** [comment]
ToDo: Test with supplied sample app.
