### ISSUE TITLE
Error after close DB client 

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-java-core#452]
https://github.com/couchbase/couchbase-lite-java/issues/52

```java
private void shutdownDatabase() {
        push.goOffline();
        pull.goOffline();
        pull.stop();
        push.stop();
        database.close();
        manager.close();
    }
````
in log:
```
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@32f4b68 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@5263919f[Shutting down, pool size = 1, active threads = 1, queued tasks = 6, completed tasks = 15]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:326)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:533)
	at java.util.concurrent.ScheduledThreadPoolExecutor.submit(ScheduledThreadPoolExecutor.java:632)
	at java.util.concurrent.Executors$DelegatedExecutorService.submit(Executors.java:678)
	at com.couchbase.lite.replicator.PullerInternal.changeTrackerStopped(PullerInternal.java:766)
	at com.couchbase.lite.replicator.ChangeTracker.stopped(ChangeTracker.java:512)
	at com.couchbase.lite.replicator.ChangeTracker.stop(ChangeTracker.java:498)
	at com.couchbase.lite.replicator.PullerInternal.goOffline(PullerInternal.java:994)
	at com.couchbase.lite.replicator.ReplicationInternal$15.doIt(ReplicationInternal.java:1101)
	at com.couchbase.lite.replicator.ReplicationInternal$15.doIt(ReplicationInternal.java:1098)
	at com.github.oxo42.stateless4j.StateConfiguration$3.doIt(StateConfiguration.java:130)
	at com.github.oxo42.stateless4j.StateConfiguration$3.doIt(StateConfiguration.java:127)
	at com.github.oxo42.stateless4j.StateRepresentation.executeEntryActions(StateRepresentation.java:123)
	at com.github.oxo42.stateless4j.StateRepresentation.enter(StateRepresentation.java:102)
	at com.github.oxo42.stateless4j.StateMachine.publicFire(StateMachine.java:199)
	at com.github.oxo42.stateless4j.StateMachine.fire(StateMachine.java:125)
	at com.couchbase.lite.replicator.ReplicationInternal$1.run(ReplicationInternal.java:191)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@4579bbfb rejected from java.util.concurrent.ScheduledThreadPoolExecutor@5263919f[Shutting down, pool size = 1, active threads = 1, queued tasks = 3, completed tasks = 18]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:326)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:533)
	at java.util.concurrent.ScheduledThreadPoolExecutor.submit(ScheduledThreadPoolExecutor.java:632)
	at java.util.concurrent.Executors$DelegatedExecutorService.submit(Executors.java:678)
	at com.couchbase.lite.replicator.ReplicationInternal.notifyChangeListeners(ReplicationInternal.java:983)
	at com.couchbase.lite.replicator.ReplicationInternal.notifyChangeListenersStateTransition(ReplicationInternal.java:1138)
	at com.couchbase.lite.replicator.ReplicationInternal.access$400(ReplicationInternal.java:61)
	at com.couchbase.lite.replicator.ReplicationInternal$16.doIt(ReplicationInternal.java:1109)
	at com.couchbase.lite.replicator.ReplicationInternal$16.doIt(ReplicationInternal.java:1105)
	at com.github.oxo42.stateless4j.StateRepresentation.executeExitActions(StateRepresentation.java:130)
	at com.github.oxo42.stateless4j.StateRepresentation.exit(StateRepresentation.java:112)
	at com.github.oxo42.stateless4j.StateMachine.publicFire(StateMachine.java:197)
	at com.github.oxo42.stateless4j.StateMachine.fire(StateMachine.java:125)
	at com.couchbase.lite.replicator.ReplicationInternal$1.run(ReplicationInternal.java:191)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by hideki** [comment]
This issue is reproducible with release/1.0.3 branch. However, it is not reproducible with master branch.
Once [PR](https://github.com/couchbase/couchbase-lite-android/pull/539) is merged into master, close this ticket.

**Comment by hideki** [comment]
User still encounters this issue with master branch.
https://github.com/couchbase/couchbase-lite-java/issues/52#issuecomment-77520768

**Comment by hideki** [comment]
Note to self:

##### Active threads at end of application.

```
// Push + Pull replicator
THREAD 0: Thread[Signal Dispatcher,9,system]
THREAD 1: Thread[Reference Handler,10,system]
THREAD 2: Thread[main,5,main]
THREAD 3: Thread[RefQueueWorker@org.apache.http.impl.conn.tsccm.ConnPoolByRoute@4c0a700f,5,main]
THREAD 4: Thread[RefQueueWorker@org.apache.http.impl.conn.tsccm.ConnPoolByRoute@2f81929d,5,main]
THREAD 5: Thread[CBLRequestWorker-84afb-0,5,main]
THREAD 6: Thread[process reaper,10,system]
THREAD 7: Thread[CBLManagerWorkExecutor,5,main]
THREAD 8: Thread[CBLRequestWorker-42b75-0,5,main]
THREAD 9: Thread[Finalizer,8,system]
THREAD 10: Thread[Monitor Ctrl-Break,5,main]
THREAD 11: Thread[RefQueueWorker@org.apache.http.impl.conn.tsccm.ConnPoolByRoute@240a0648,5,main]

// Pull only
THREAD 0: Thread[Reference Handler,10,system]
THREAD 1: Thread[RefQueueWorker@org.apache.http.impl.conn.tsccm.ConnPoolByRoute@6ab7b83,5,main]
THREAD 2: Thread[CBLRequestWorker-42b75-0,5,main]
THREAD 3: Thread[process reaper,10,system]
THREAD 4: Thread[Signal Dispatcher,9,system]
THREAD 5: Thread[Monitor Ctrl-Break,5,main]
THREAD 6: Thread[CBLManagerWorkExecutor,5,main]
THREAD 7: Thread[main,5,main]
THREAD 8: Thread[Finalizer,8,system]
THREAD 9: Thread[RefQueueWorker@org.apache.http.impl.conn.tsccm.ConnPoolByRoute@c8131c2,5,main]

// Push only
THREAD 0: Thread[RefQueueWorker@org.apache.http.impl.conn.tsccm.ConnPoolByRoute@60ca7fb5,5,main]
THREAD 1: Thread[Signal Dispatcher,9,system]
THREAD 2: Thread[Finalizer,8,system]
THREAD 3: Thread[main,5,main]
THREAD 4: Thread[Reference Handler,10,system]
THREAD 5: Thread[CBLRequestWorker-84afb-0,5,main]
THREAD 6: Thread[process reaper,10,system]
THREAD 7: Thread[Monitor Ctrl-Break,5,main]
THREAD 8: Thread[CBLManagerWorkExecutor,5,main]

// no replicator
THREAD 0: Thread[process reaper,10,system]
THREAD 1: Thread[Monitor Ctrl-Break,5,main]
THREAD 2: Thread[Signal Dispatcher,9,system]
THREAD 3: Thread[Finalizer,8,system]
THREAD 4: Thread[Reference Handler,10,system]
THREAD 5: Thread[main,5,main]
```

##### With calling workexecutor.shutdown() after replicator STOPPED
```
// push & pull repl
THREAD 0: Thread[Reference Handler,10,system]
THREAD 1: Thread[CBLRequestWorker-42b75-0,5,main]
THREAD 2: Thread[CBLRequestWorker-84afb-0,5,main]
THREAD 3: Thread[process reaper,10,system]
THREAD 4: Thread[Signal Dispatcher,9,system]
THREAD 5: Thread[Monitor Ctrl-Break,5,main]
THREAD 6: Thread[CBLManagerWorkExecutor,5,main]
THREAD 7: Thread[main,5,main]
THREAD 8: Thread[Finalizer,8,system]
THREAD 9: Thread[RefQueueWorker@org.apache.http.impl.conn.tsccm.ConnPoolByRoute@21e4bcdd,5,main]

// pull repl
THREAD 0: Thread[Reference Handler,10,system]
THREAD 1: Thread[RefQueueWorker@org.apache.http.impl.conn.tsccm.ConnPoolByRoute@2bf64a1c,5,main]
THREAD 2: Thread[CBLRequestWorker-42b75-0,5,main]
THREAD 3: Thread[process reaper,10,system]
THREAD 4: Thread[Signal Dispatcher,9,system]
THREAD 5: Thread[Monitor Ctrl-Break,5,main]
THREAD 6: Thread[CBLManagerWorkExecutor,5,]
THREAD 7: Thread[main,5,main]
THREAD 8: Thread[Finalizer,8,system]
THREAD 9: Thread[RefQueueWorker@org.apache.http.impl.conn.tsccm.ConnPoolByRoute@6359c6d9,5,main]

// push repl
THREAD 0: Thread[RefQueueWorker@org.apache.http.impl.conn.tsccm.ConnPoolByRoute@60ca7fb5,5,main]
THREAD 1: Thread[Finalizer,8,system]
THREAD 2: Thread[Reference Handler,10,system]
THREAD 3: Thread[main,5,main]
THREAD 4: Thread[CBLRequestWorker-84afb-0,5,main]
THREAD 5: Thread[Monitor Ctrl-Break,5,main]
THREAD 6: Thread[Signal Dispatcher,9,system]
THREAD 7: Thread[process reaper,10,system]
```

##### Note:
- Need to call workexecutor.shutdown() to finalize CBLRequestWorker thread
- Check Apache Http Connection Pool
- Check CBLRequestWorker

**Comment by hideki** [comment]
Simple CBL Java console app to reproduce this issue
https://gist.github.com/hideki/b0075c98d4fdee842ece

**Comment by tleyden** [comment]
I'm seeing a [unit test failure](http://mobile.jenkins.couchbase.com/job/couchbase-lite-android-build/65/console) on Jenkins:

```
com.couchbase.lite.ManagerTest > testClose[hudson_en-US_160_WVGA_android-19_armeabi-v7a_param(AVD) - 4.4.2] [31mFAILED [0m
	junit.framework.AssertionFailedError: expected:<0> but was:<1>
	at com.couchbase.lite.ManagerTest.testClose(ManagerTest.java:229)
```

**Comment by Lupen2002** [comment]
Thank you. This is work!

**Comment by Lupen2002** [comment]
I'm sorry(((( if your class Test run with:
```Thread.sleep(1000 * 30);```
then app don't close, with log:
```
SEVERE: Test: PULL replication event. Source: com.couchbase.lite.replicator.Replication@7388716e Total changes: 15374 Completed changes: 14447
мар 12, 2015 12:31:59 PM com.couchbase.lite.util.SystemLogger e
SEVERE: Test: PULL replication event. Source: com.couchbase.lite.replicator.Replication@7388716e Total changes: 15375 Completed changes: 14447
мар 12, 2015 12:31:59 PM com.couchbase.lite.util.SystemLogger e
SEVERE: Test: PULL replication event. Source: com.couchbase.lite.replicator.Replication@7388716e Total changes: 15376 Completed changes: 14447
мар 12, 2015 12:31:59 PM com.couchbase.lite.util.SystemLogger e
SEVERE: Test: PULL replication event. Source: com.couchbase.lite.replicator.Replication@7388716e Total changes: 15377 Completed changes: 14447
мар 12, 2015 12:31:59 PM com.couchbase.lite.util.SystemLogger e
SEVERE: Sync: ERROR: processInbox failed: 
java.lang.NullPointerException
	at com.couchbase.lite.replicator.PullerInternal.processInbox(PullerInternal.java:158)
	at com.couchbase.lite.replicator.ReplicationInternal$2.process(ReplicationInternal.java:298)
	at com.couchbase.lite.support.Batcher.processNow(Batcher.java:207)
	at com.couchbase.lite.support.Batcher.access$100(Batcher.java:23)
	at com.couchbase.lite.support.Batcher$1.run(Batcher.java:40)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

мар 12, 2015 12:31:59 PM com.couchbase.lite.util.SystemLogger e
SEVERE: Batcher: com.couchbase.lite.support.Batcher$1@7595b28: BatchProcessor throw exception
java.lang.RuntimeException: java.lang.NullPointerException
	at com.couchbase.lite.replicator.ReplicationInternal$2.process(ReplicationInternal.java:302)
	at com.couchbase.lite.support.Batcher.processNow(Batcher.java:207)
	at com.couchbase.lite.support.Batcher.access$100(Batcher.java:23)
	at com.couchbase.lite.support.Batcher$1.run(Batcher.java:40)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at com.couchbase.lite.replicator.PullerInternal.processInbox(PullerInternal.java:158)
	at com.couchbase.lite.replicator.ReplicationInternal$2.process(ReplicationInternal.java:298)
	... 10 more

мар 12, 2015 12:31:59 PM com.couchbase.lite.util.SystemLogger e
SEVERE: Test: PULL replication event. Source: com.couchbase.lite.replicator.Replication@7388716e Transition: STOPPING -> STOPPED Total changes: 15377 Completed changes: 14447
THREAD 0: Thread[Signal Dispatcher,9,system]
THREAD 1: Thread[Finalizer,8,system]
THREAD 2: Thread[Reference Handler,10,system]
THREAD 3: Thread[Monitor Ctrl-Break,5,main]
THREAD 4: Thread[process reaper,10,system]
THREAD 5: Thread[Thread-103,5,main]
THREAD 6: Thread[ChangeTracker-http://localhost:4984/mobicat/,5,main]
THREAD 7: Thread[main,5,main]
End Test
```

**Comment by hideki** [comment]
@Lupen2002  Could you please provide code snippet how you changed code?

**Comment by Lupen2002** [comment]
Yes.
```
import com.couchbase.lite.Database;
import com.couchbase.lite.DocumentChange;
import com.couchbase.lite.JavaContext;
import com.couchbase.lite.Manager;
import com.couchbase.lite.replicator.Replication;
import com.couchbase.lite.util.Log;

import java.net.URL;
import java.util.List;
import java.util.Set;

public class Test implements Database.ChangeListener, Replication.ChangeListener {
    public static String TAG = "Test";

    private static final String SYNC_URL = "http://localhost:4984/mobicat/";

    Manager manager = null;
    Database database = null;

    public void startCBL() throws Exception {
        manager = new Manager(new JavaContext(), Manager.DEFAULT_OPTIONS);
        database = manager.getDatabase("mobicat");

        URL syncUrl = new URL(SYNC_URL);

        Replication push = database.createPushReplication(syncUrl);
        push.setContinuous(true);
        push.addChangeListener(this);
        push.start();

        Replication pull = database.createPullReplication(syncUrl);
        pull.setContinuous(true);
        pull.addChangeListener(this);
        pull.start();
    }

    public void stopCBL() {
        manager.close();
    }

    public static void main(String[] args) {
        System.out.println("Begin Test");
        Test test = new Test();
        try {
            test.startCBL();

            Thread.sleep(1000 * 30);

            test.stopCBL();
        } catch (Exception e) {
            Log.e(TAG, e.getMessage());
        }

        // wait all threads
        int i = 0;
        Set<Thread> threadSet = Thread.getAllStackTraces().keySet();
        for (Thread t : threadSet) {
            System.out.println("THREAD " + (i++) + ": " + t);
        }
        System.out.println("End Test");
    }

    @Override
    public void changed(Database.ChangeEvent event) {
        List<DocumentChange> changes = event.getChanges();
        for (DocumentChange c : changes) {
            Log.d(TAG, c.toString());
        }
    }

    @Override
    public void changed(final Replication.ChangeEvent event) {
        if (event != null) {
            Log.e(TAG, event.toString());
        }
    }
}
```

**Comment by hideki** [comment]
@Lupen2002 Thanks for code. I will look into the issue.

**Comment by hideki** [comment]
@Lupen2002 
I tested both sleep 3 sec and 30 sec before closing Database (Manager). Both cases, I can not reproduce the issue anymore. Closing process takes time, please check again?
Thanks!

**Comment by Lupen2002** [comment]
Ok. I'm sorry. With lib from master branch app closed. But if connecting to sync_gateway has failed, then app doesn't closed.

**Comment by hideki** [comment]
Hi @Lupen2002,
Thank you for additional information. I could reproduce the issue. In case of failing the connection with server, CBL keeps retrying till retry counter reaches maximum. It blocks app terminates. We are working for this issue now.
Thanks!

**Comment by hideki** [comment]
Hi @Lupen2002 ,

We fixed the issue. However, in case of connection error, it might need to maximum 60 seconds for app to terminate. 60sec is for network timeout.

This will be tracked by different ticket. #532

Thanks,
Hideki

**Comment by Lupen2002** [comment]
Thank you!
