### ISSUE TITLE
revs table and insertRevision column mismatch

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-java-core#464]
Code
```
    @InterfaceAudience.Private
    public long insertRevision(RevisionInternal rev, long docNumericID, long parentSequence, boolean current, boolean hasAttachments, byte[] data) {
        long rowId = 0;
        try {
            ContentValues args = new ContentValues();
            args.put("doc_id", docNumericID);
            args.put("revid", rev.getRevId());
            if(parentSequence != 0) {
                args.put("parent", parentSequence);
            }
            args.put("current", current);
            args.put("deleted", rev.isDeleted());
            args.put("no_attachments",!hasAttachments);
            args.put("json", data);
            rowId = database.insert("revs", null, args);
            rev.setSequence(rowId);
        } catch (Exception e) {
            Log.e(Database.TAG, "Error inserting revision", e);
        }
        return rowId;
    }
```

Error message
```
    03-03 10:23:59.779      619-633/self.hideki.issue447 E/SQLiteDatabase﹕ Error inserting current=false parent=12213 no_attachments=true deleted=false json=null doc_id=718
    android.database.sqlite.SQLiteException: 7 values for 6 columns (code 1): , while compiling: INSERT INTO revs(current,parent,no_attachments,deleted,json,doc_id) VALUES (?,?,?,?,?,?,?)
            at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
            at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:882)
            at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:493)
            at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
            at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
            at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
            at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1467)
            at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1339)
            at com.couchbase.lite.android.AndroidSQLiteStorageEngine.insert(AndroidSQLiteStorageEngine.java:116)
            at com.couchbase.lite.Database.insertRevision(Database.java:3504)
            at com.couchbase.lite.Database.forceInsert(Database.java:4029)
            at com.couchbase.lite.replicator.PullerInternal.insertDownloads(PullerInternal.java:506)
            at com.couchbase.lite.replicator.PullerInternal$1.process(PullerInternal.java:97)
            at com.couchbase.lite.support.Batcher.processNow(Batcher.java:210)
            at com.couchbase.lite.support.Batcher.access$100(Batcher.java:23)
            at com.couchbase.lite.support.Batcher$1.run(Batcher.java:40)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:442)
            at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
            at java.util.concurrent.FutureTask.run(FutureTask.java:137)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:150)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:264)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
            at java.lang.Thread.run(Thread.java:856)
```

**Comment by hideki** [comment]
This could be related with out-of-memory issue #447
