### ISSUE TITLE
Unit Test failure on Jenkins server (ChangeTrackerTest)

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-java-core#483]
http://mobile.jenkins.couchbase.com/job/couchbase-lite-android-build/67/console

```
com.couchbase.lite.replicator.ChangeTrackerTest > testChangeTrackerBackoffExceptions[hudson_en-US_160_WVGA_android-19_armeabi-v7a_param(AVD) - 4.4.2] [31mFAILED [0m
    junit.framework.AssertionFailedError
    at com.couchbase.lite.replicator.ChangeTrackerTest.testChangeTrackerBackoff(ChangeTrackerTest.java:356)

com.couchbase.lite.replicator.ChangeTrackerTest > testChangeTrackerBackoffInvalidJson[hudson_en-US_160_WVGA_android-19_armeabi-v7a_param(AVD) - 4.4.2] [31mFAILED [0m
    junit.framework.AssertionFailedError
    at com.couchbase.lite.replicator.ChangeTrackerTest.testChangeTrackerBackoff(ChangeTrackerTest.java:356)

com.couchbase.lite.replicator.ReplicationTest > testMockPullBulkDocsSyncGw[hudson_en-US_160_WVGA_android-19_armeabi-v7a_param(AVD) - 4.4.2] [31mFAILED [0m
    junit.framework.AssertionFailedError
    at com.couchbase.lite.replicator.ReplicationTest.mockPullBulkDocs(ReplicationTest.java:3383)
```

**Comment by hideki** [comment]
this issue is not reproducible with real device and  genymotion.

**Comment by tleyden** [comment]
did you try the stock android emulator?

**Comment by hideki** [comment]
Not yet. I will try it tomorrow.

**Comment by hideki** [comment]
Emulator with API 19 and ARM configuration following test cases fail
- `ChangeTrackerTest.testChangeTrackerBackoff()`
- `ChangeTrackerTest.testChangeTrackerBackoffInvalidJson()`

Both CBL Android and Java Core are from master branch.

Unit Test Error Message
```
Testing started at 9:02 PM ...
Waiting for device.
Target device: Nexus_5_API_19 [emulator-5554]
Uploading file
	local path: /Users/hideki/github/couchbase-lite-android/build/outputs/apk/couchbase-lite-android-debug-test-unaligned.apk
	remote path: /data/local/tmp/com.couchbase.lite.test
No apk changes detected. Skipping file upload, force stopping package instead.
DEVICE SHELL COMMAND: am force-stop com.couchbase.lite.test
Running tests
Test running started
junit.framework.AssertionFailedError
at com.couchbase.lite.replicator.ChangeTrackerTest.testChangeTrackerBackoff(ChangeTrackerTest.java:356)
at com.couchbase.lite.replicator.ChangeTrackerTest.testChangeTrackerBackoffExceptions(ChangeTrackerTest.java:185)
at java.lang.reflect.Method.invokeNative(Native Method)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:191)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:176)
at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:554)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1701)


junit.framework.AssertionFailedError
at com.couchbase.lite.replicator.ChangeTrackerTest.testChangeTrackerBackoff(ChangeTrackerTest.java:356)
at com.couchbase.lite.replicator.ChangeTrackerTest.testChangeTrackerBackoffInvalidJson(ChangeTrackerTest.java:192)
at java.lang.reflect.Method.invokeNative(Native Method)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:191)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:176)
at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:554)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1701)

Finish
```

**Comment by andreibaranouski** [comment]
if adb.logs are useful here http://172.23.113.52:8080/job/couchbase-lite-android-build/75/artifact/emulator_adb.log
or appthwack http://172.23.113.52:8080/job/couchbase-lite-android-build/lastSuccessfulBuild/artifact/logcat.txt

**Comment by hideki** [comment]
@andreibaranouski Thanks a lot!

**Comment by hideki** [comment]
Note to self:
It seems that the default Android emulator with ARM configuration is too slow to send 25 requests in 2 seconds.
```
        // now find the delta in requests received in a 2s period
        int before = mockHttpClient.getCapturedRequests().size();
        Thread.sleep(2 * 1000);
        int after = mockHttpClient.getCapturedRequests().size();

        // assert that the delta is high, because at this point the change tracker should
        // be hammering away
        assertTrue((after - before) > 25);
```
https://github.com/couchbase/couchbase-lite-android/blob/02cbbd6e2aca0f2834468afd6981168f4b952f3e/src/androidTest/java/com/couchbase/lite/replicator/ChangeTrackerTest.java#L349-L356

**Comment by hideki** [comment]
Note to self:

Tested with using release/1.0.4 branch, tests can successfully pass.

This slowness is caused by change to recreate ObjectMapper instance whenever it is requested. It used to be reused always.
https://github.com/couchbase/couchbase-lite-java-core/commit/2f24d92abeb1a8aa3c9732c745dc226b78899dc9?diff=split

TODOs:
1. Reverted code for ObjectMapper
2. Retest out of memory issue #447 with modification.
3. If 2 does not work, create ManagerOption for ObjectMapper reuse option.
