### ISSUE TITLE
P2P: Cannot start a transaction within a transaction

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-java-core#484]
##### android.database.sqlite.SQLiteException: cannot start a transaction within a transaction (code 1)

This exception is thrown at listener side.

Steps to reproduce:
1. Create 100 docs on listener side and 100 docs on client side same time.

```
03-11 14:19:35.825  29324-29717/couchbase.com.myp2p E/Router﹕ Router unable to route request to do_POST_Document_bulk_docs
    java.lang.reflect.InvocationTargetException
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.couchbase.lite.router.Router.start(Router.java:472)
            at com.couchbase.lite.listener.LiteServlet.service(LiteServlet.java:128)
            at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)
            at Acme.Serve.Serve$ServeConnection.runServlet(Serve.java:2251)
            at Acme.Serve.Serve$ServeConnection.parseRequest(Serve.java:2176)
            at Acme.Serve.Serve$ServeConnection.run(Serve.java:1988)
            at Acme.Utils$ThreadPool$PooledThread.run(Utils.java:1223)
            at java.lang.Thread.run(Thread.java:818)
     Caused by: android.database.sqlite.SQLiteException: cannot start a transaction within a transaction (code 1)
            at android.database.sqlite.SQLiteConnection.nativeExecute(Native Method)
            at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:555)
            at android.database.sqlite.SQLiteSession.beginTransactionUnchecked(SQLiteSession.java:323)
            at android.database.sqlite.SQLiteSession.beginTransaction(SQLiteSession.java:298)
            at android.database.sqlite.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:505)
            at android.database.sqlite.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:416)
            at com.couchbase.lite.android.AndroidSQLiteStorageEngine.beginTransaction(AndroidSQLiteStorageEngine.java:78)
            at com.couchbase.lite.Database.beginTransaction(Database.java:1253)
            at com.couchbase.lite.router.Router.do_POST_Document_bulk_docs(Router.java:1080)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.couchbase.lite.router.Router.start(Router.java:472)
            at com.couchbase.lite.listener.LiteServlet.service(LiteServlet.java:128)
            at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)
            at Acme.Serve.Serve$ServeConnection.runServlet(Serve.java:2251)
            at Acme.Serve.Serve$ServeConnection.parseRequest(Serve.java:2176)
            at Acme.Serve.Serve$ServeConnection.run(Serve.java:1988)
            at Acme.Utils$ThreadPool$PooledThread.run(Utils.java:1223)
            at java.lang.Thread.run(Thread.java:818)
    --------- beginning of crash
03-11 14:19:35.840  29324-29324/couchbase.com.myp2p E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: couchbase.com.myp2p, PID: 29324
    java.lang.IllegalStateException: Cannot perform this operation because there is no current transaction.
            at android.database.sqlite.SQLiteSession.throwIfNoTransaction(SQLiteSession.java:915)
            at android.database.sqlite.SQLiteSession.setTransactionSuccessful(SQLiteSession.java:371)
            at android.database.sqlite.SQLiteDatabase.setTransactionSuccessful(SQLiteDatabase.java:540)
            at com.couchbase.lite.android.AndroidSQLiteStorageEngine.setTransactionSuccessful(AndroidSQLiteStorageEngine.java:88)
            at com.couchbase.lite.Database.endTransaction(Database.java:1288)
            at com.couchbase.lite.Database.putRevision(Database.java:3775)
            at com.couchbase.lite.Database.putRevision(Database.java:3548)
            at com.couchbase.lite.Document.putProperties(Document.java:417)
            at com.couchbase.lite.Document.putProperties(Document.java:252)
            at couchbase.com.myp2p.MainActivity$2.onClick(MainActivity.java:101)
            at android.view.View.performClick(View.java:4756)
            at android.view.View$PerformClick.run(View.java:19749)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

**Comment by hideki** [comment]
#481 I am not tested with ToDo Lite. This issue could be hard to reproduce with ToDo LIte if _bulk_docs's document count is low.

**Comment by amir-abdi** [comment]
Did you find the solution to this? I am facing the same error and can't figure out the logic behind it.

**Comment by hideki** [comment]
@amir-abdi,
Nested transaction issue was fixed a long time ago. If you are using 1.3.x, the issue should not be reproducible. If you observe the issue, please provide detailed information? Thanks!
