### ISSUE TITLE
ReplicationTest.testGoOffline fails sometimes.

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-java-core#488]
Not 100% reproducible, But I frequently observe `ReplicationTest.testGoOffline()`  unit test case fails.

Testing environment: Android Emulator API 19 with ARM architecture. Tested unit test suite. Not single method.

```
junit.framework.AssertionFailedError
at com.couchbase.lite.replicator.ReplicationTest.testGoOffline(ReplicationTest.java:2627)
at java.lang.reflect.Method.invokeNative(Native Method)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:191)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:176)
at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:554)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1701)
```

**Comment by hideki** [comment]
Note:
- This is not reproducible on development environment with using standard Android emulator that is configured with API 19 and ARM.
- I can add same workaround in the unit test if root cause is same with CBL Java unit test failure. ( https://github.com/couchbase/couchbase-lite-java-core/issues/446)

**Comment by hideki** [comment]
Log: https://gist.github.com/hideki/d0c5ebe01f8880131f66
