### ISSUE TITLE
Sync fails to complete initial sync when in continuous mode

### ISSUE THREAD

**Issue by jcamp1** [couchbase/couchbase-lite-java-core#498]
Greetings,

Continuous mode of sync seems to have some issues. I currently can not complete a full sync if the pull replicator is in continuous mode and the replicator seems to display some odd behavior.

I get through quite a few documents but currently I'm seeing the end result being 
```
03-16 13:37:45.930  25445-25483/com.app.appmobile.alpha E/Sync﹕ Change tracker stopped during continuous replication
03-16 13:37:45.930  25445-25483/com.app.appmobile.alpha W/Sync﹕ [fireTrigger()] => WAITING_FOR_CHANGES
03-16 13:37:45.930  25445-25483/com.app.appmobile.alpha D/app﹕ Replicator last error: java.lang.Exception: Change tracker stopped during continuous replication -> Change tracker stopped during continuous replication / Change tracker stopped during continuous replication
03-16 13:37:45.930  25445-25483/com.app.appmobile.alpha D/app﹕ Stopping all replications.
03-16 13:37:45.930  25445-25483/com.app.appmobile.alpha W/Sync﹕ [fireTrigger()] => STOP_GRACEFUL
03-16 13:37:45.930  25445-25483/com.app.appmobile.alpha W/Sync﹕ [fireTrigger()] => STOP_GRACEFUL
03-16 13:37:45.930  25445-25483/com.app.appmobile.alpha D/app﹕ Replicator last error: java.lang.Exception: Change tracker stopped during continuous replication -> Change tracker stopped during continuous replication / Change tracker stopped during continuous replication
03-16 13:37:45.940  25445-25483/com.app.appmobile.alpha D/app﹕ Stopping all replications.
03-16 13:37:45.940  25445-25483/com.app.appmobile.alpha W/Sync﹕ [fireTrigger()] => STOP_GRACEFUL
03-16 13:37:45.940  25445-25483/com.app.appmobile.alpha W/Sync﹕ [fireTrigger()] => STOP_GRACEFUL
03-16 13:37:45.940  25445-25483/com.app.appmobile.alpha D/app﹕ Replicator last error: java.lang.Exception: Change tracker stopped during continuous replication -> Change tracker stopped during continuous replication / Change tracker stopped during continuous replication
03-16 13:37:45.940  25445-25483/com.app.appmobile.alpha D/app﹕ Stopping all replications.
03-16 13:37:45.940  25445-25483/com.app.appmobile.alpha W/Sync﹕ [fireTrigger()] => STOP_GRACEFUL
03-16 13:37:45.940  25445-25483/com.app.appmobile.alpha W/Sync﹕ [fireTrigger()] => STOP_GRACEFUL
03-16 13:37:45.940  25445-25483/com.app.appmobile.alpha D/app﹕ Replicator last error: java.lang.Exception: Change tracker stopped during continuous replication -> Change tracker stopped during continuous replication / Change tracker stopped during continuous replication
03-16 13:37:45.940  25445-25483/com.app.appmobile.alpha D/app﹕ Stopping all replications.
03-16 13:37:45.950  25445-25483/com.app.appmobile.alpha W/Sync﹕ [fireTrigger()] => STOP_GRACEFUL
03-16 13:37:45.950  25445-25483/com.app.appmobile.alpha W/Sync﹕ [fireTrigger()] => STOP_GRACEFUL
03-16 13:37:46.190  25445-25500/com.app.appmobile.alpha W/Sync﹕ com.couchbase.lite.replicator.ReplicationInternal$7@4213af50: Database is null or closed, not calling db.setLastSequence()
03-16 13:37:46.190  25445-26067/com.app.appmobile.alpha W/Sync﹕ [fireTrigger()] => WAITING_FOR_CHANGES
03-16 13:37:46.240  25445-25483/com.app.appmobile.alpha D/app﹕ Replicator last error: java.lang.Exception: Change tracker stopped during continuous replication -> Change tracker stopped during continuous replication / Change tracker stopped during continuous replication
03-16 13:37:46.240  25445-25483/com.app.appmobile.alpha D/app﹕ Stopping all replications.
```

The pull replicator is also emitting callbacks during replication stating it's idle with 0/0 documents somewhat randomly, which is incorrect behavior. Possibly related to #456 .

Thanks,
Justin

**Comment by hideki** [comment]
Hi @jcamp1,
Is this issue reproducible with sync_gateway account you provided us before?
And is this 100% reproducible?
Thanks,
Hideki

**Comment by hideki** [comment]
Hi @jcam1,
Do you have any update about this issue? Is this still reproducible?
Thanks!

**Comment by hideki** [comment]
Note to self:

Pull replication causes NullPointerException middle of replication. It might caused by unexpected IDLE state or STOP requests.

```
04-15 20:09:27.246  23041-23158/self.hideki.issue498 E/Issue498﹕ PULL replication event. Source: com.couchbase.lite.replicator.Replication@527feb70 Total changes: 1953 Completed changes: 1890
04-15 20:09:27.250  23041-23158/self.hideki.issue498 E/Issue498﹕ PULL replication event. Source: com.couchbase.lite.replicator.Replication@527feb70 Total changes: 1953 Completed changes: 1891
04-15 20:09:27.250  23041-23171/self.hideki.issue498 W/ChangeTracker﹕ com.couchbase.lite.replicator.ChangeTracker@527fd61c: Change tracker calling changeTrackerStopped, client: com.couchbase.lite.replicator.PullerInternal@527fb274
04-15 20:09:27.254  23041-23857/self.hideki.issue498 W/Sync﹕ [fireTrigger()] => STOP_IMMEDIATE
04-15 20:09:27.254  23041-23857/self.hideki.issue498 E/Sync﹕ PullerInternal stopGraceful.run() finished
04-15 20:09:28.426  23041-23204/self.hideki.issue498 D/dalvikvm﹕ GC_FOR_ALLOC freed 1845K, 78% free 5177K/22968K, paused 5ms, total 5ms
04-15 20:09:30.006  23041-23204/self.hideki.issue498 D/dalvikvm﹕ GC_FOR_ALLOC freed 544K, 77% free 5357K/22968K, paused 4ms, total 4ms
04-15 20:09:32.882  23041-23204/self.hideki.issue498 D/dalvikvm﹕ GC_FOR_ALLOC freed 815K, 77% free 5323K/22968K, paused 5ms, total 5ms
04-15 20:09:37.410  23041-23204/self.hideki.issue498 D/dalvikvm﹕ GC_FOR_ALLOC freed 653K, 77% free 5443K/22968K, paused 5ms, total 5ms
04-15 20:09:38.922  23041-23204/self.hideki.issue498 D/dalvikvm﹕ GC_FOR_ALLOC freed 494K, 75% free 5762K/22968K, paused 4ms, total 4ms
04-15 20:09:40.382  23041-23204/self.hideki.issue498 D/dalvikvm﹕ GC_FOR_ALLOC freed 985K, 76% free 5696K/22968K, paused 4ms, total 4ms
04-15 20:09:43.406  23041-23204/self.hideki.issue498 D/dalvikvm﹕ GC_FOR_ALLOC freed 619K, 74% free 5974K/22968K, paused 4ms, total 4ms
04-15 20:09:44.970  23041-23204/self.hideki.issue498 D/dalvikvm﹕ GC_FOR_ALLOC freed 810K, 74% free 6154K/22968K, paused 4ms, total 4ms
04-15 20:09:47.826  23041-23204/self.hideki.issue498 D/dalvikvm﹕ GC_FOR_ALLOC freed 921K, 73% free 6262K/22968K, paused 4ms, total 4ms
04-15 20:09:49.670  23041-23204/self.hideki.issue498 D/dalvikvm﹕ GC_FOR_ALLOC freed 897K, 72% free 6451K/22968K, paused 5ms, total 6ms
04-15 20:09:56.902  23041-23204/self.hideki.issue498 D/dalvikvm﹕ GC_FOR_ALLOC freed 983K, 72% free 6616K/22968K, paused 5ms, total 5ms
04-15 20:09:58.374  23041-23204/self.hideki.issue498 D/dalvikvm﹕ GC_FOR_ALLOC freed 953K, 71% free 6866K/22968K, paused 4ms, total 4ms
04-15 20:10:01.474  23041-23204/self.hideki.issue498 D/dalvikvm﹕ GC_FOR_ALLOC freed 1049K, 70% free 7103K/22968K, paused 4ms, total 4ms
04-15 20:10:03.014  23041-23204/self.hideki.issue498 D/dalvikvm﹕ GC_FOR_ALLOC freed 1260K, 69% free 7209K/22968K, paused 4ms, total 4ms
04-15 20:10:05.854  23041-23659/self.hideki.issue498 W/Sync﹕ [fireTrigger()] => WAITING_FOR_CHANGES
04-15 20:10:05.854  23041-23158/self.hideki.issue498 E/Batcher﹕ com.couchbase.lite.support.Batcher$1@5280f778: BatchProcessor throw exception
    java.lang.NullPointerException
            at com.couchbase.lite.replicator.PullerInternal.insertDownloads(PullerInternal.java:497)
            at com.couchbase.lite.replicator.PullerInternal$1.process(PullerInternal.java:96)
            at com.couchbase.lite.support.Batcher.processNow(Batcher.java:207)
            at com.couchbase.lite.support.Batcher.access$100(Batcher.java:23)
            at com.couchbase.lite.support.Batcher$1.run(Batcher.java:40)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:841)
04-15 20:10:05.858  23041-23158/self.hideki.issue498 E/Issue498﹕ PULL replication event. Source: com.couchbase.lite.replicator.Replication@527feb70 Transition: STOPPING -> STOPPED Total changes: 1953 Completed changes: 1891
04-15 20:10:05.858  23041-24001/self.hideki.issue498 W/Sync﹕ [fireTrigger()] => WAITING_FOR_CHANGES
04-15 20:10:05.858  23041-24001/self.hideki.issue498 E/Sync﹕ PullerInternal stopGraceful.run() finished
```

Full log message
https://gist.github.com/hideki/7e57d3e407b2c489dce3

**Comment by hideki** [comment]
Note To Self:

Attachment causes the error, and when replicator becomes IDLE, a replicator will stop because of error.

```
04-16 20:03:20.721     837-1074/self.hideki.issue4982a W/CBLite﹕ Can't find inherited attachment thumbnail from seq# 9644 to copy to 9881
04-16 20:03:20.721     837-1074/self.hideki.issue4982a W/Sync﹕ com.couchbase.lite.replicator.PullerInternal@528664d4: failed to write {a43931f3-89c2-4889-949d-4cdd368bef5d #203-f490a009919efede232101b6a72f7f62}: status=404
```

**Comment by hideki** [comment]
Note to self:

Observed:
1. Replicator stops when replicator becomes IDLE because there is error during replication. NOTE: iOS version of replicator stops immediately after replication error.
1. Error is caused by `copyAttachmentNamedFromSequenceToSequence()` method because these is no attachment data which is associated with parent sequence number which is given.
1. `copyAttachmentNamedFromSequenceToSequence()` method is called because revision's attachment is stub.

Note:
- It seems `localParentSequence` in `forceInsert()` method is not correct.

Next Step:
- check `localRevs`, `localRev` and `revHistory`

**Comment by hideki** [comment]
Hi @jcamp1,

We fixed this issue. Could you please test with your environment?

Fix is in release/1.1.0 branch, we will merge this into master after 1.1.0 release.
https://github.com/couchbase/couchbase-lite-java-core/tree/release/1.1.0

**Comment by jcamp1** [comment]
Hi @hideki,

Sorry for the late response.

The continuous initial sync seemed to work a lot better. However there were a couple of issues I noticed. One, the replicator will report active:false docs/total 0/0 randomly throughout the sync when it still has much more syncing to do.
Two, I received many many errors all exactly the same as below:
```
04-29 22:01:27.076    1488-1511/com.app.app.alpha E/Batcher﹕ com.couchbase.lite.support.Batcher$1@b5b6d9a0: BatchProcessor throw exception
    java.lang.NullPointerException
            at com.couchbase.lite.replicator.PullerInternal.insertDownloads(SourceFile:497)
            at com.couchbase.lite.replicator.PullerInternal$1.process(SourceFile:96)
            at com.couchbase.lite.support.Batcher.processNow(SourceFile:207)
            at com.couchbase.lite.support.Batcher.access$100(SourceFile:23)
            at com.couchbase.lite.support.Batcher$1.run(SourceFile:40)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:442)
            at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
            at java.util.concurrent.FutureTask.run(FutureTask.java:137)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:150)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:264)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
            at java.lang.Thread.run(Thread.java:856)
```

Hope that helps.

Cheers!

**Comment by jcamp1** [comment]
Hi @hideki,

Please disregard my last comment, I mistakenly tested the master branch. I just finished testing the 1.1.0 release branch and I'm very happy to report it worked perfectly for me!

Thanks so much!

**Comment by hideki** [comment]
Hi @jcamp1,
Thank you very much for verifying the fix. Your test data helped us a lot to fix this issue and others. Please let us know what we can help you.
Thanks again!
