### ISSUE TITLE
Jenkins build failed

### ISSUE THREAD

**Issue by tleyden** [couchbase/couchbase-lite-java-core#508]
With "upload to maven" checked, this build failed: http://mobile.jenkins.couchbase.com/view/Couchbase_Lite/job/couchbase-lite-android-build/87/

The error message in the logs:

```
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 9.015s
[INFO] Finished at: Thu Mar 19 22:22:31 UTC 2015
[INFO] Final Memory: 11M/1963M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project couchbase-lite: Could not resolve dependencies for project com.couchbase:couchbase-lite:jar:0.0.0-502: The following artifacts could not be resolved: com.couchbase.lite:couchbase-lite-android:aar:0.0.0-502, com.couchbase.lite:couchbase-lite-java-core:jar:0.0.0-502: Could not find artifact com.couchbase.lite:couchbase-lite-android:aar:0.0.0-502 in couchbase.public.repo (http://files.couchbase.com/maven2) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project couchbase-lite: Could not resolve dependencies for project com.couchbase:couchbase-lite:jar:0.0.0-502: The following artifacts could not be resolved: com.couchbase.lite:couchbase-lite-android:aar:0.0.0-502, com.couchbase.lite:couchbase-lite-java-core:jar:0.0.0-502: Could not find artifact com.couchbase.lite:couchbase-lite-android:aar:0.0.0-502 in couchbase.public.repo (http://files.couchbase.com/maven2)
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:210)
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies(LifecycleDependencyResolver.java:117)
	at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved(MojoExecutor.java:258)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:201)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
```

**Comment by tleyden** [comment]
Note that this build (with a different version number) worked:

http://mobile.jenkins.couchbase.com/view/Couchbase_Lite/job/couchbase-lite-android-build/88/console

**Comment by hideki** [comment]
I don't observe this issue for a while.  I will keep eye open for this.
