### ISSUE TITLE
Upgrade Jackson version of couchbase-lite-java-javascript

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-java-core#537]
```
E/Router  ( 6270): Router unable to route request to do_GET_DesignDocument
E/Router  ( 6270): java.lang.reflect.InvocationTargetException
E/Router  ( 6270): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/Router  ( 6270): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/Router  ( 6270): 	at com.couchbase.lite.router.Router.start(Router.java:472)
E/Router  ( 6270): 	at com.couchbase.lite.listener.LiteServlet.service(LiteServlet.java:128)
E/Router  ( 6270): 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)
E/Router  ( 6270): 	at Acme.Serve.Serve$ServeConnection.runServlet(Serve.java:2251)
E/Router  ( 6270): 	at Acme.Serve.Serve$ServeConnection.parseRequest(Serve.java:2176)
E/Router  ( 6270): 	at Acme.Serve.Serve$ServeConnection.run(Serve.java:1988)
E/Router  ( 6270): 	at Acme.Utils$ThreadPool$PooledThread.run(Utils.java:1223)
E/Router  ( 6270): 	at java.lang.Thread.run(Thread.java:841)
E/Router  ( 6270): Caused by: java.lang.NoClassDefFoundError: org.codehaus.jackson.map.ObjectMapper
E/Router  ( 6270): 	at com.couchbase.lite.javascript.ViewMapBlockRhino.map(JavaScriptViewCompiler.java:117)
E/Router  ( 6270): 	at com.couchbase.lite.View.updateIndex(View.java:616)
E/Router  ( 6270): 	at com.couchbase.lite.router.Router.queryDesignDoc(Router.java:1857)
E/Router  ( 6270): 	at com.couchbase.lite.router.Router.do_GET_DesignDocument(Router.java:1888)
E/Router  ( 6270): 	... 10 more
```

**Comment by hideki** [comment]
Fixed by following commit
https://github.com/couchbase/couchbase-lite-java-javascript/commit/2865f0d6d73413583a76673e8f778b458898f3ea

- Updated submodule (couchbase-lite-java-core)
- Update Jackson's package (1.9.2 -> 2.5.0)
