### ISSUE TITLE
couchbase lite and java destop

### ISSUE THREAD

**Issue by ZeeshanNiazi** [couchbase/couchbase-lite-java-core#539]
created manager through code:

manager = new Manager(new JavaContext("data"), Manager.DEFAULT_OPTIONS);

after creation of manager , trying to get db thorough following code.
this db name "sync_gateway" is created in couchbase server, means this is couchbase bucket name.
Database db =  manager.getDatabase("sync_gateway");

after executing this code, i get the following exception:

Apr 01, 2015 7:45:05 PM com.couchbase.lite.util.SystemLogger e
SEVERE: Native: Library not found: /native/windows/amd64/CouchbaseLiteJavaNative.dll
Apr 01, 2015 7:45:05 PM com.couchbase.lite.util.SystemLogger e
SEVERE: Native: Error loading library: CouchbaseLiteJavaNative
java.lang.NullPointerException
	at com.couchbase.lite.util.NativeUtils.loadLibrary(NativeUtils.java:45)
	at com.couchbase.lite.storage.JavaSQLiteStorageEngine.<clinit>(JavaSQLiteStorageEngine.java:125)
	at com.couchbase.lite.storage.JavaSQLiteStorageEngineFactory.createStorageEngine(JavaSQLiteStorageEngineFactory.java:6)
	at com.couchbase.lite.Database.open(Database.java:907)
	at com.couchbase.lite.Manager.getDatabase(Manager.java:236)
	at javaapplication16.JavaApplication16.onCreate(JavaApplication16.java:42)
	at javaapplication16.JavaApplication16.main(JavaApplication16.java:67)

Exception in thread "main" java.lang.UnsatisfiedLinkError: com.couchbase.lite.storage.JavaSQLiteStorageEngine._open(Ljava/lang/String;)J
	at com.couchbase.lite.storage.JavaSQLiteStorageEngine._open(Native Method)
	at com.couchbase.lite.storage.JavaSQLiteStorageEngine.access$100(JavaSQLiteStorageEngine.java:8)
	at com.couchbase.lite.storage.JavaSQLiteStorageEngine$Connection.<init>(JavaSQLiteStorageEngine.java:23)
	at com.couchbase.lite.storage.JavaSQLiteStorageEngine$ConnectionPool.start(JavaSQLiteStorageEngine.java:46)
	at com.couchbase.lite.storage.JavaSQLiteStorageEngine.open(JavaSQLiteStorageEngine.java:138)
	at com.couchbase.lite.Database.open(Database.java:910)
	at com.couchbase.lite.Manager.getDatabase(Manager.java:236)
	at javaapplication16.JavaApplication16.onCreate(JavaApplication16.java:42)
	at javaapplication16.JavaApplication16.main(JavaApplication16.java:67)
Java Result: 1
BUILD SUCCESSFUL (total time: 2 seconds)

**Comment by hideki** [comment]
Hi @ZeeshanNiazi,

CBL Java download package does not includes native libraries for Windows platform. It only includes Linux binary. Could you please build couchbase-lite-java-native by yourself? Instruction is in README of https://github.com/couchbase/couchbase-lite-java-native .

@pasin  could you please follow up if necessary?

Thanks,
Hideki
