### ISSUE TITLE
ViewsTest.testStringPrefixMatch() fails Android Simulator with API 10 (Android 2.3.3)

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-java-core#541]
- Standard Android Emulator
- ARM
- API 10
- Android 2.3.3

UPDATE: API 14 Android 4.0 ARM or higher works fine.

```
04-01 15:22:33.801      509-518/com.couchbase.lite.test I/TestRunner﹕ failed: testStringPrefixMatch(com.couchbase.lite.ViewsTest)
04-01 15:22:33.811      509-518/com.couchbase.lite.test I/TestRunner﹕ ----- begin exception -----
04-01 15:22:33.811      509-518/com.couchbase.lite.test I/TestRunner﹕ junit.framework.AssertionFailedError: expected:<2> but was:<0>
            at junit.framework.Assert.fail(Assert.java:47)
            at junit.framework.Assert.failNotEquals(Assert.java:282)
            at junit.framework.Assert.assertEquals(Assert.java:64)
            at junit.framework.Assert.assertEquals(Assert.java:201)
            at junit.framework.Assert.assertEquals(Assert.java:207)
            at com.couchbase.lite.ViewsTest.testStringPrefixMatch(ViewsTest.java:1814)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:507)
            at junit.framework.TestCase.runTest(TestCase.java:154)
            at junit.framework.TestCase.runBare(TestCase.java:127)
            at junit.framework.TestResult$1.protect(TestResult.java:106)
            at junit.framework.TestResult.runProtected(TestResult.java:124)
            at junit.framework.TestResult.run(TestResult.java:109)
            at junit.framework.TestCase.run(TestCase.java:118)
            at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:169)
            at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:154)
            at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:529)
            at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1448)
04-01 15:22:33.811      509-518/com.couchbase.lite.test I/TestRunner﹕ ----- end exception -----
04-01 15:22:33.821      509-518/com.couchbase.lite.test I/TestRunner﹕ finished: testStringPrefixMatch(com.couchbase.lite.ViewsTest)
```

**Comment by hideki** [comment]
This issue is no longer reproducible with Custom SQLite. I will close this.
