### ISSUE TITLE
Logging formatting exception

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-java-core#556]
```
I/Database( 1616): Unable to format log: %s: Optimizing SQL indexes (curSeq=%lld, last run at %lld)
I/Database( 1616): java.util.UnknownFormatConversionException: Conversion: l
I/Database( 1616): 	at java.util.Formatter$FormatToken.unknownFormatConversionException(Formatter.java:1399)
I/Database( 1616): 	at java.util.Formatter$FormatToken.checkFlags(Formatter.java:1336)
I/Database( 1616): 	at java.util.Formatter.transform(Formatter.java:1442)
I/Database( 1616): 	at java.util.Formatter.doFormat(Formatter.java:1081)
I/Database( 1616): 	at java.util.Formatter.format(Formatter.java:1042)
I/Database( 1616): 	at java.util.Formatter.format(Formatter.java:1011)
I/Database( 1616): 	at java.lang.String.format(String.java:1999)
I/Database( 1616): 	at java.lang.String.format(String.java:1973)
I/Database( 1616): 	at com.couchbase.lite.util.Log.i(Log.java:259)
I/Database( 1616): 	at com.couchbase.lite.Database$9.run(Database.java:5091)
I/Database( 1616): 	at com.couchbase.lite.Database.runInTransaction(Database.java:680)
I/Database( 1616): 	at com.couchbase.lite.Database.optimizeSQLIndexes(Database.java:5088)
I/Database( 1616): 	at com.couchbase.lite.View.updateIndex(View.java:470)
I/Database( 1616): 	at com.couchbase.lite.router.Router.queryDesignDoc(Router.java:1933)
I/Database( 1616): 	at com.couchbase.lite.router.Router.do_GET_DesignDocument(Router.java:1964)
I/Database( 1616): 	at java.lang.reflect.Method.invokeNative(Native Method)
I/Database( 1616): 	at java.lang.reflect.Method.invoke(Method.java:515)
I/Database( 1616): 	at com.couchbase.lite.router.Router.start(Router.java:470)
I/Database( 1616): 	at com.couchbase.lite.listener.LiteServlet.service(LiteServlet.java:128)
I/Database( 1616): 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)
I/Database( 1616): 	at Acme.Serve.Serve$ServeConnection.runServlet(Serve.java:2251)
I/Database( 1616): 	at Acme.Serve.Serve$ServeConnection.parseRequest(Serve.java:2176)
I/Database( 1616): 	at Acme.Serve.Serve$ServeConnection.run(Serve.java:1988)
I/Database( 1616): 	at Acme.Utils$ThreadPool$PooledThread.run(Utils.java:1223)
I/Database( 1616): 	at java.lang.Thread.run(Thread.java:841)

```

**Comment by hideki** [comment]
I created duplicated ticket, https://github.com/couchbase/couchbase-lite-java-core/issues/559, already fixed the issue, and sent PR.
