### ISSUE TITLE
Retrieving attachment data fails on UnsavedRevision

### ISSUE THREAD

**Issue by sergio91pt** [couchbase/couchbase-lite-java-core#592]
Attachment#getContent() always fails to retrieve the data set on a previous revision (eg. the parent revision), if the Attachment object is retrieved through an UnsavedRevision.

The problem is the sequence number that is always 0 on UnsavedRevision and the parent sequence is not used. Should an UnsavedRevision even have a sequence number?

```
Caused by: com.couchbase.lite.CouchbaseLiteException
 	at com.couchbase.lite.Database.getAttachmentForSequence(Database.java:2820)
 	at com.couchbase.lite.Attachment.getContent(Attachment.java:130)
```

**Comment by sergio91pt** [comment]
Unit test to reproduce: sergio91pt/couchbase-lite-android@f3f70fa3c0f060bbce338ba3d860caebfedf9efd
