### ISSUE TITLE
ReplicationTest fails on branch release/1.1.0

### ISSUE THREAD

**Issue by sergio91pt** [couchbase/couchbase-lite-java-core#598]
Fails on `testPullReplicatonWithManyAttachmentRevisions()`.
Bisecting points to commit 1ef72c546edf0963ced3b3b11a115e54e4eb4b7b as the culprit.
Tested with API 22 emulator, using the x86_64 ABI.

JUnit Stacktrace:
```
com.couchbase.lite.CouchbaseLiteException
at com.couchbase.lite.Database.forceInsert(Database.java:4259)
at com.couchbase.lite.replicator.ReplicationTest.testPullReplicatonWithManyAttachmentRevisions(ReplicationTest.java:4558)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:191)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:176)
at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:555)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1853)
```

Logcat:
```
E/LiteTestCase﹕ saved => {11111 #2-623c85f8985690f2ab436219a7c2176d}
E/LiteTestCase﹕ revID => 2-623c85f8985690f2ab436219a7c2176d
E/LiteTestCase﹕ revID => 3-00
E/SQLiteLog﹕ (2067) abort at 37 in [INSERT INTO revs(doc_id,revid,no_attachments,deleted,current,json) VALUES (?,?,?,?,?,?)]: UNIQUE constraint failed: revs.doc_id, revs.revid
E/SQLiteDatabase﹕ Error inserting doc_id=1 revid=3-00 no_attachments=false deleted=false current=true json=[B@3dfc8777
    android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: revs.doc_id, revs.revid (code 2067)
            at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
            at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:782)
            at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
            at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
            at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1471)
            at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1341)
            at com.couchbase.lite.android.AndroidSQLiteStorageEngine.insert(AndroidSQLiteStorageEngine.java:133)
            at com.couchbase.lite.Database.insertRevision(Database.java:3693)
            at com.couchbase.lite.Database.forceInsert(Database.java:4256)
            at com.couchbase.lite.replicator.ReplicationTest.testPullReplicatonWithManyAttachmentRevisions(ReplicationTest.java:4558)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at junit.framework.TestCase.runTest(TestCase.java:168)
            at junit.framework.TestCase.runBare(TestCase.java:134)
            at junit.framework.TestResult$1.protect(TestResult.java:115)
            at junit.framework.TestResult.runProtected(TestResult.java:133)
            at junit.framework.TestResult.run(TestResult.java:118)
            at junit.framework.TestCase.run(TestCase.java:124)
            at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:191)
            at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:176)
            at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:555)
            at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1853)
```

**Comment by hideki** [comment]
It was Unit Test problem.
https://github.com/couchbase/couchbase-lite-android/pull/593
