### ISSUE TITLE
Push replication to rcouch fails on rev with attachments

### ISSUE THREAD

**Issue by sergio91pt** [couchbase/couchbase-lite-java-core#600]
The problem seems to be caused by `PusherInternal#uploadMultipartRevision(RevisionInternal)` as its the only method that calls a StringBody constructor capable of getting an NPE latter on.

Stacktrace:
```
Exception uploading multipart request
java.lang.NullPointerException: Attempt to get length of null array
	at com.couchbase.org.apache.http.entity.mime.content.StringBody.getContentLength(StringBody.java:183)
	at com.couchbase.org.apache.http.entity.mime.MultipartEntity.isRepeatable(MultipartEntity.java:139)
	at com.couchbase.org.apache.http.entity.mime.MultipartEntity.isChunked(MultipartEntity.java:147)
	at org.apache.http.protocol.RequestContent.process(RequestContent.java:84)
	at org.apache.http.protocol.BasicHttpProcessor.process(BasicHttpProcessor.java:295)
	at org.apache.http.protocol.HttpRequestExecutor.preProcess(HttpRequestExecutor.java:165)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:413)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:560)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:492)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:470)
	at com.couchbase.lite.support.RemoteRequest.executeRequest(RemoteRequest.java:183)
	at com.couchbase.lite.support.RemoteMultipartRequest.run(RemoteMultipartRequest.java:48)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
```

**Comment by hideki** [comment]
Hi @sergio91pt ,

Could you please provide more detailed information?

- Is this reproducible with CouchDB?
- How many revisions does a doc have?
- How many attachments?
- etc

**Comment by sergio91pt** [comment]
Hi @hideki,
The NPE was quite easy to fix, however I'm still unable to push this document, now it is the server that crashes.

In [this branch](https://github.com/sergio91pt/couchbase-lite-java-core/tree/issue_600_push_repl_no_gzip) I have the fix for the NPE above  and a related patch, to correct the filenames of the attachments present in the "parts", although I think [only the order matters](https://github.com/couchbaselabs/TouchDB-iOS/issues/133).

To answer your questions:

> Is this reproducible with CouchDB?

Yes, just tested with 1.6.1

> How many revisions does a doc have?

Two revisions. Attachments are only added in the second revision.
Both revisions are added in a transaction, so both should be pushed at the same time.

> How many attachments?

6 binary attachments. [Here is a zip](https://www.dropbox.com/s/v5qpc6ibw9ewzdj/issue_600_multipart_push.zip?dl=0) with a curl reproducible request and related server logs.
The request was sniffed from CBL Android with the 2 commits from the branch I linked. The request seems valid and the attachments are in order...

**Comment by sergio91pt** [comment]
The CouchDB crash was due to the '/' in the document id not being percent encoded in the url.

**Comment by hideki** [comment]
Hi @sergio91pt,
Does CBL Android not escape URL for database name?
Thanks!

**Comment by sergio91pt** [comment]
Its the document id that wasn't escaped [here](https://github.com/couchbase/couchbase-lite-java-core/blob/56c3d778971382e1e5d8c317d9e54ab64dff669a/src/main/java/com/couchbase/lite/replicator/PusherInternal.java#L626). The method right after it, does escape the id.

The id of the document I was testing with was `e7c50173-0fc8-49cc-9308-6c8651ef5b30/2015-04-27T17:52:51Z`. The ':' were escaped probably by `java.net.URL`, but the slash wasn't.

Regarding the database name, I have no idea. The ones I use don't require encoding, but I do it anyway, as I think it is the responsibility of the user to encode them (as we must specify a full URL).

**Comment by hideki** [comment]
CouchDB supports forward slash '/' for its database name. it could be reason that database name without  URL escape works. Needs to verify.

**Comment by sergio91pt** [comment]
@hideki You're right, and there's also the design documents (I remember seeing redirects on design documents, in packet captures). 

So I finally dug deeper on this:

```sh
# We should try to avoid these pointless roundtrips
$ curl -v http://127.0.0.1:5984/test_db/_design%2Ftest
< HTTP/1.1 301 Moved Permanently
< Server: CouchDB/1.6.1 (Erlang OTP/17)
< Location: http://127.0.0.1:5984/test_db/_design/test

# One can percent encode a database with forward slashes
# I was expecting a 404 but it works, not even a 301
$ curl -v http://127.0.0.1:5984/test_db%2Fwith_slash/doc1
< HTTP/1.1 200 OK
{"_id":"doc1","_rev":"1-43e806c27be1a6486e6d9425e9e659e4","testing":true}

# But if the '/' in '_design/' is percent encoded it results again in a 301
# Btw one cannot create a database that starts with a '_' (just tested)
$ curl -v http://127.0.0.1:5984/test_db%2Fwith_slash/_design%2Ftest
< HTTP/1.1 301 Moved Permanently
< Server: CouchDB/1.6.1 (Erlang OTP/17)
< Location: http://127.0.0.1:5984/test_db%2Fwith_slash/_design/test

# Well, actually encoding '/' in database names is mandatory or we get a 404
$ curl -v http://127.0.0.1:5984/test_db/with_slash/_design/test
< HTTP/1.1 404 Object Not Found
{"error":"not_found","reason":"missing"}

$ curl -v http://127.0.0.1:5984/test_db/with_slash/doc1
< HTTP/1.1 404 Object Not Found
{"error":"not_found","reason":"missing"}
```
