### ISSUE TITLE
On Windows, CBL Java Unit Test fails

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-java-core#624]
```
May 13, 2015 4:13:19 PM com.couchbase.lite.util.SystemLogger v
FINER: LiteTestCase: setUp

java.io.IOException: Unable to delete file: C:\Users\Administrator\github\couchbase-lite-java\couchbaselitetest\test\cblite-test.cblite
java.lang.RuntimeException: java.io.IOException: Unable to delete file: C:\Users\Administrator\github\couchbase-lite-java\couchbaselitetest\test\cblite-test.cblite
	at com.couchbase.lite.LiteTestContext.<init>(LiteTestContext.java:20)
	at com.couchbase.lite.LiteTestContext.<init>(LiteTestContext.java:38)
	at com.couchbase.lite.LiteTestContext.<init>(LiteTestContext.java:34)
	at com.couchbase.lite.LiteTestCase.startCBLite(LiteTestCase.java:92)
	at com.couchbase.lite.LiteTestCase.setUp(LiteTestCase.java:74)
	at junit.framework.TestCase.runBare(TestCase.java:139)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:255)
	at junit.framework.TestSuite.run(TestSuite.java:250)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:86)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:49)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:69)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:105)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:360)
	at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Unable to delete file: C:\Users\Administrator\github\couchbase-lite-java\couchbaselitetest\test\cblite-test.cblite
	at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:1643)
	at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1268)
	at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1200)
	at com.couchbase.lite.LiteTestContext.<init>(LiteTestContext.java:18)
	... 37 more
```

**Comment by hideki** [comment]
Note to self:

Some unittests fail to close database because of SQLITE_BUYS(5).
```
#define SQLITE_BUSY         5   /* The database file is locked */
```
in `com_couchbase_lite_storage_JavaSQLiteStorageEngine.c`
Needs to call `sqlite3_finalize(stmt);` if error occurs.
