### ISSUE TITLE
On Windows, Replication2Test.testExcessiveCheckpointingDuringPushreplication() fails

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-java-core#632]
It seems MockDispatcher has concurrent issue.

```
com.couchbase.lite.replicator.Replication2Test > testExcessiveCheckpointingDuringPushReplication FAILED
    junit.framework.AssertionFailedError
        at junit.framework.Assert.fail(Assert.java:55)
        at junit.framework.Assert.assertTrue(Assert.java:22)
        at junit.framework.Assert.assertNotNull(Assert.java:256)
        at junit.framework.Assert.assertNotNull(Assert.java:248)
        at junit.framework.TestCase.assertNotNull(TestCase.java:417)
        at com.couchbase.lite.replicator.Replication2Test.testExcessiveCheckpointingDuringPushReplication(Replication2Test.java:116)
```

Notes:
1. This test case fails with combination with other tests.
1. Not 100% reproducible

**Comment by hideki** [comment]
I have not see this test failure for a while. Fixes for other issue could fix this issue too.
