### ISSUE TITLE
Caused by: java.lang.NullPointerException: map == null

### ISSUE THREAD

**Issue by QRPro** [couchbase/couchbase-lite-java-core#634]
Caused by: java.lang.NullPointerException: map == null
at java.util.Collections.unmodifiableMap(Collections.java:2304)
at com.couchbase.lite.SavedRevision.getProperties(SavedRevision.java:142)
at com.couchbase.lite.Document.getProperties(Document.java:154)
at 
.....
document.getProperties()

Version: 0.0.0-524

**Comment by hideki** [comment]
Hi @QRPro,
Could you please provide more detailed information? We need steps to reproduce.
Thanks!

**Comment by QRPro** [comment]
We are creating a document, it push to server. Document changes the server, it comes back to us in the second revision. We read it. This operation occurs every 30 seconds. After 4-6 hours we get this error when reading.

**Comment by hideki** [comment]
It seems pull replication has memory leak. Then it might cause NPE. Fixing this issue, https://github.com/couchbase/couchbase-lite-android/issues/597 , might solve this problem too.
