### ISSUE TITLE
Exel: Push replication "losing" documents created when disconnected

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-java-core#636]
https://issues.couchbase.com/browse/CBSE-1850

The key steps to show the differences in behaviour between the nexus 4 (Android 4.3) and 5 (Android 5.0.1) are as follows:
Nexus 4: 
1) Wifi disabled 
2) Changes thrown by the ChangeTracker as the Network is unreachable 
3) Change tracker stops as it is going offline (GO_OFFLINE logged) 
4) Command sent 
5) Push replication tries to send command until retires exhausted 
6) Push replication change listener triggered. Replication status REPLICATION_OFFLINE, error details available. 
7) Device put back online 
8) Replication restarts with pull and push replication change listeners firing, both reporting a status of REPLICATION_ACTIVE and no error
Nexus 5 
1) Wifi disabled 
2) Changes thrown by the ChangeTracker as the Network is unreachable 
3) Debug reports going online (rather than offline). (GO_ONLINE logged) 
4) Command sent 
5) Push replication tries to send command until retires exhausted 
6) Push replication change listener triggered. Replication status REPLICATION_IDLE, error details available 
7) Device put back on line. 
8) GO_ONLINE is logged as debug but replication doesn’t start and the change listeners are not fired.
More detailed sections of the debug output are attached.

**Comment by hideki** [comment]
This issue is reproducible. Still not known what causes this issue.
```
05-26 14:58:51.161  30933-30933/self.hideki.issueandroid597 E/IssueAndroid597﹕ createDocs() is clicked
05-26 14:58:51.186  30933-30933/self.hideki.issueandroid597 E/IssueAndroid597﹕ [DocumentChange] docId: 2d434b78-3181-478c-8c7a-499d73047034 rev: 1-c08cf7defd4fa5a8041b19ebd13c35b7 isConflict: false sourceUrl: null
05-26 14:58:51.189  30933-31023/self.hideki.issueandroid597 E/IssueAndroid597﹕ [ReplicationChange] PUSH replication event. Source: com.couchbase.lite.replicator.Replication@3f63b09f Transition: IDLE -> RUNNING Total changes: 1 Completed changes: 1
05-26 14:58:51.195  30933-31024/self.hideki.issueandroid597 E/RemoteRequest﹕ io exception.  url: http://10.17.2.82:4984/db/_revs_diff
    org.apache.http.conn.HttpHostConnectException: Connection to http://10.17.2.82:4984 refused
            at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:188)
            at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:169)
            at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:124)
            at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:365)
            at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:560)
            at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:492)
            at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:470)
            at com.couchbase.lite.support.RemoteRequest.executeRequest(RemoteRequest.java:184)
            at com.couchbase.lite.support.RemoteRequest.run(RemoteRequest.java:103)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
     Caused by: java.net.ConnectException: failed to connect to /10.17.2.82 (port 4984) after 60000ms: connect failed: ENETUNREACH (Network is unreachable)
            at libcore.io.IoBridge.connect(IoBridge.java:124)
            at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
            at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:456)
            at java.net.Socket.connect(Socket.java:882)
            at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:124)
            at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:149)
            at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:169)
            at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:124)
            at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:365)
            at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:560)
            at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:492)
            at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:470)
            at com.couchbase.lite.support.RemoteRequest.executeRequest(RemoteRequest.java:184)
            at com.couchbase.lite.support.RemoteRequest.run(RemoteRequest.java:103)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
     Caused by: android.system.ErrnoException: connect failed: ENETUNREACH (Network is unreachable)
            at libcore.io.Posix.connect(Native Method)
            at libcore.io.BlockGuardOs.connect(BlockGuardOs.java:111)
            at libcore.io.IoBridge.connectErrno(IoBridge.java:154)
            at libcore.io.IoBridge.connect(IoBridge.java:122)
            at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
            at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:456)
            at java.net.Socket.connect(Socket.java:882)
            at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:124)
            at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:149)
            at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:169)
            at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:124)
            at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:365)
            at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:560)
            at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:492)
            at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:470)
            at com.couchbase.lite.support.RemoteRequest.executeRequest(RemoteRequest.java:184)
            at com.couchbase.lite.support.RemoteRequest.run(RemoteRequest.java:103)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
05-26 14:58:55.211  30933-31163/self.hideki.issueandroid597 E/RemoteRequest﹕ io exception.  url: http://10.17.2.82:4984/db/_revs_diff
    org.apache.http.conn.HttpHostConnectException: Connection to http://10.17.2.82:4984 refused
            at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:188)
            at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:169)
            at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:124)
            at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:365)
            at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:560)
            at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:492)
            at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:470)
            at com.couchbase.lite.support.RemoteRequest.executeRequest(RemoteRequest.java:184)
            at com.couchbase.lite.support.RemoteRequest.run(RemoteRequest.java:103)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
     Caused by: java.net.ConnectException: failed to connect to /10.17.2.82 (port 4984) after 60000ms: connect failed: ENETUNREACH (Network is unreachable)
            at libcore.io.IoBridge.connect(IoBridge.java:124)
            at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
            at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:456)
            at java.net.Socket.connect(Socket.java:882)
            at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:124)
            at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:149)
            at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:169)
            at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:124)
            at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:365)
            at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:560)
            at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:492)
            at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:470)
            at com.couchbase.lite.support.RemoteRequest.executeRequest(RemoteRequest.java:184)
            at com.couchbase.lite.support.RemoteRequest.run(RemoteRequest.java:103)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
     Caused by: android.system.ErrnoException: connect failed: ENETUNREACH (Network is unreachable)
            at libcore.io.Posix.connect(Native Method)
            at libcore.io.BlockGuardOs.connect(BlockGuardOs.java:111)
            at libcore.io.IoBridge.connectErrno(IoBridge.java:154)
            at libcore.io.IoBridge.connect(IoBridge.java:122)
            at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
            at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:456)
            at java.net.Socket.connect(Socket.java:882)
            at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:124)
            at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:149)
            at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:169)
            at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:124)
            at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:365)
            at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:560)
            at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:492)
            at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:470)
            at com.couchbase.lite.support.RemoteRequest.executeRequest(RemoteRequest.java:184)
            at com.couchbase.lite.support.RemoteRequest.run(RemoteRequest.java:103)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
05-26 14:59:03.216  30933-31206/self.hideki.issueandroid597 E/RemoteRequest﹕ io exception.  url: http://10.17.2.82:4984/db/_revs_diff
    org.apache.http.conn.HttpHostConnectException: Connection to http://10.17.2.82:4984 refused
            at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:188)
            at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:169)
            at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:124)
            at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:365)
            at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:560)
            at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:492)
            at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:470)
            at com.couchbase.lite.support.RemoteRequest.executeRequest(RemoteRequest.java:184)
            at com.couchbase.lite.support.RemoteRequest.run(RemoteRequest.java:103)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
     Caused by: java.net.ConnectException: failed to connect to /10.17.2.82 (port 4984) after 60000ms: connect failed: ENETUNREACH (Network is unreachable)
            at libcore.io.IoBridge.connect(IoBridge.java:124)
            at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
            at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:456)
            at java.net.Socket.connect(Socket.java:882)
            at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:124)
            at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:149)
            at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:169)
            at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:124)
            at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:365)
            at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:560)
            at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:492)
            at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:470)
            at com.couchbase.lite.support.RemoteRequest.executeRequest(RemoteRequest.java:184)
            at com.couchbase.lite.support.RemoteRequest.run(RemoteRequest.java:103)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
     Caused by: android.system.ErrnoException: connect failed: ENETUNREACH (Network is unreachable)
            at libcore.io.Posix.connect(Native Method)
            at libcore.io.BlockGuardOs.connect(BlockGuardOs.java:111)
            at libcore.io.IoBridge.connectErrno(IoBridge.java:154)
            at libcore.io.IoBridge.connect(IoBridge.java:122)
            at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
            at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:456)
            at java.net.Socket.connect(Socket.java:882)
            at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:124)
            at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:149)
            at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:169)
            at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:124)
            at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:365)
            at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:560)
            at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:492)
            at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:470)
            at com.couchbase.lite.support.RemoteRequest.executeRequest(RemoteRequest.java:184)
            at com.couchbase.lite.support.RemoteRequest.run(RemoteRequest.java:103)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
05-26 14:59:14.716  30933-30933/self.hideki.issueandroid597 E/IssueAndroid597﹕ startPushReplicator() is clicked
05-26 14:59:14.719  30933-31023/self.hideki.issueandroid597 E/IssueAndroid597﹕ [ReplicationChange] PUSH replication event. Source: com.couchbase.lite.replicator.Replication@f80b58b Transition: INITIAL -> RUNNING Total changes: 0 Completed changes: 0
05-26 14:59:15.376  30933-31023/self.hideki.issueandroid597 E/IssueAndroid597﹕ [ReplicationChange] PUSH replication event. Source: com.couchbase.lite.replicator.Replication@f80b58b Total changes: 1 Completed changes: 0
05-26 14:59:15.394  30933-31023/self.hideki.issueandroid597 E/IssueAndroid597﹕ [ReplicationChange] PUSH replication event. Source: com.couchbase.lite.replicator.Replication@f80b58b Total changes: 1 Completed changes: 1
05-26 14:59:15.394  30933-31023/self.hideki.issueandroid597 E/IssueAndroid597﹕ [ReplicationChange] PUSH replication event. Source: com.couchbase.lite.replicator.Replication@f80b58b Transition: RUNNING -> IDLE Total changes: 1 Completed changes: 1
05-26 14:59:20.402  30933-31023/self.hideki.issueandroid597 E/IssueAndroid597﹕ [ReplicationChange] PUSH replication event. Source: com.couchbase.lite.replicator.Replication@f80b58b Transition: IDLE -> RUNNING Total changes: 1 Completed changes: 1
05-26 14:59:20.511  30933-31023/self.hideki.issueandroid597 E/IssueAndroid597﹕ [ReplicationChange] PUSH replication event. Source: com.couchbase.lite.replicator.Replication@f80b58b Transition: RUNNING -> IDLE Total changes: 1 Completed changes: 1
```

**Comment by hideki** [comment]
Note to Self:

Push/Pull replication after disconnect and connect network

| Type | Android 4.3 | Android 5.0 |
| ------------- | ----------- | ----------- |
| Push  | Work | **Not Work** |
| Pull    | **Not Work** | Work     |

**Comment by couchbasebrian** [comment]
The customer who reported this issue stated that they used hardware for their test - there was not a way to reliably switch off connectivity through the simulator.  Airplane mode was not used.  Wi-Fi was switched off in the Android Settings.

**Comment by hideki** [comment]
Fixed with PR https://github.com/couchbase/couchbase-lite-android/pull/621
