### ISSUE TITLE
Race condition causing NPE when saving document shortly after adding attachment.

### ISSUE THREAD

**Issue by b-smets** [couchbase/couchbase-lite-java-core#669]
When saving a document shortly after adding an attachment I run into the following nullpointer (using v1.0.4):
`java.lang.NullPointerException
at com.couchbase.lite.Database.generateIDForRevision(Database.java:3223)
at com.couchbase.lite.Database.putRevision(Database.java:3622)
at com.couchbase.lite.Database.putRevision(Database.java:3465)
at com.couchbase.lite.Document.putProperties(Document.java:415)
at com.couchbase.lite.UnsavedRevision.save(UnsavedRevision.java:102)`

More specific the following line:
 `md5Digest.update(attachment.getBlobKey().getBytes());`

The problem is that I sometimes get attachments which have a SHA-1 digest and the "follows" attribute set to true when obtaining a document from the database and saving it in a new revision immediately after:
`Document doc = database.getDocument(documentID);
doc.createRevision().save();`

Because of the "follows" attribute, we take the installAttachment() route in Database#getAttachmentsFromRevision(). This creates an AttachmentInternal without a blob key as the digest of the attachment (SHA-1) does not appear in the list of pending attachments (identified by MD5 hash). 

Note that this happens only about once every 20 tries.

**Comment by hideki** [comment]
Hi @b-smets,

Thank you very much for reporting issue.

Is your code for adding an attachment similar with our sample? http://developer.couchbase.com/mobile/develop/guides/couchbase-lite/native-api/attachment/index.html#writing

If you can, could you please share the code snippet of adding the attachment.

Recently we released, v1.1.0, could you please retest this with v1.1.0 if you have time?

Thanks!
Hideki

**Comment by b-smets** [comment]
Hello Hideki,

Upgrading to v1.1.0 seems to have improved error handling in the way that I now get a normal error message instead of a NPE:

`06-23 17:14:50.442  24458-25002/******.android.app.forms W/CBLite﹕ No pending attachment for digest: sha1-OQ+MAtYUKQj5NGUP5azSb76/nhk=
06-23 17:14:50.452  24458-25002/******.android.app.forms W/System.err﹕ java.io.IOException: Unable to save the document
06-23 17:14:50.452  24458-25002/******.android.app.forms W/System.err﹕ at ******.android.internal.model.DefaultDocumentHandler.saveAbstractModel(DefaultDocumentHandler.java:105)
*Snipped stacktrace*
06-23 17:14:50.472  24458-25002/******.android.app.forms W/System.err﹕ at java.lang.Thread.run(Thread.java:841)
06-23 17:14:50.472  24458-25002/******.android.app.forms W/System.err﹕ Caused by: com.couchbase.lite.CouchbaseLiteException
06-23 17:14:50.472  24458-25002/******.android.app.forms W/System.err﹕ at com.couchbase.lite.Database.installAttachment(Database.java:2948)
06-23 17:14:50.472  24458-25002/******.android.app.forms W/System.err﹕ at com.couchbase.lite.Database.getAttachmentsFromRevision(Database.java:4285)
06-23 17:14:50.482  24458-25002/******.android.app.forms W/System.err﹕ at com.couchbase.lite.Database.putRevision(Database.java:4063)
06-23 17:14:50.482  24458-25002/******.android.app.forms W/System.err﹕ at com.couchbase.lite.Database.putRevision(Database.java:3923)
06-23 17:14:50.482  24458-25002/******.android.app.forms W/System.err﹕ at com.couchbase.lite.Document.putProperties(Document.java:420)
06-23 17:14:50.482  24458-25002/******.android.app.forms W/System.err﹕ at com.couchbase.lite.UnsavedRevision.save(UnsavedRevision.java:107)`

I'm using more or less the same code as in the sample. I will try to debug it a bit more tomorrow to find out why I end up with a SHA digest when the "follows" attribute is true.

**Comment by b-smets** [comment]
I have narrowed down where the SHA digest + follows attribute is set:

"<19> CBLRequestWorker-cc2dc-0@830038722304" prio=5 runnable
  java.lang.Thread.State: RUNNABLE
      at com.couchbase.lite.Database.getAttachmentsDictForSequenceWithContent(Database.java:3167)
      at com.couchbase.lite.Database.extraPropertiesForRevision(Database.java:1751)
      at com.couchbase.lite.Database.expandStoredJSONIntoRevisionWithAttachments(Database.java:1832)
      at com.couchbase.lite.Database.loadRevisionBody(Database.java:1957)
      at com.couchbase.lite.replicator.PusherInternal$3.onCompletion(PusherInternal.java:414)
      at com.couchbase.lite.support.RemoteRequestRetry$1.completed(RemoteRequestRetry.java:213)
      at com.couchbase.lite.support.RemoteRequestRetry$1.onCompletion(RemoteRequestRetry.java:231)
      at com.couchbase.lite.support.RemoteRequest.respondWithResult(RemoteRequest.java:300)
      at com.couchbase.lite.support.RemoteRequest.executeRequest(RemoteRequest.java:250)
      at com.couchbase.lite.support.RemoteRequest.run(RemoteRequest.java:103)
      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
      at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
      at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
      at java.lang.Thread.run(Thread.java:841)

My code triggering this:
```java
// This results in the document being loaded in the above thread stack
Document doc = fDatabase.getDocument(model.getId());
final UnsavedRevision rev = doc.createRevision();
rev.getProperties().putAll(convertedProperties);
try
{
    // This causes the actual error of the issue
    final SavedRevision savedRev = rev.save();
    
}
catch (final CouchbaseLiteException e)
{
    throw new IOException("Unable to save the document", e);
}
```

Might be interesting to note that I run this snippet before adding / updating the actual attachment.
The attachment itself has length 18140 which is bigger than `Database.kBigAttachmentLength` which causes the data suppression.

To be clear: the above snippet works fine the first time but after updating the attachment (same data so same length) just like in the [example](http://developer.couchbase.com/mobile/develop/guides/couchbase-lite/native-api/attachment/index.html#writing), the above snippet fails with the error of this issue.

**Comment by hideki** [comment]
Hi @b-smets,

Thank you for additional information.

The line of `rev.getProperties().putAll(convertedProperties);` could cause the problem you encounter. I assume the codes makes CBL reserved value changed.

Could you please try to follow the `Update Document` sample? There are two ways to updates doc.
http://developer.couchbase.com/mobile/develop/guides/couchbase-lite/native-api/document/index.html#updating

Let us know if it helps you.

**Comment by b-smets** [comment]
Hi @hideki,

I followed your guide for the update document (using the DocumentUpdater) and now I seem to be unable to reproduce the problem anymore. I don't exactly know why we were using internal api but I guess this caused some unexpected threading issue. I will close this issue for now until I can provide a decent reproducable case. 

Thanks for the help.
