### ISSUE TITLE
testContinuousPushReplicationGoesIdleTooSoon causes native crash if unit test run from command line on OSX

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-java-core#717]
Command:

`$ ./gradlew connectedAndroidTest --info`

Log:
```
com.couchbase.lite.replicator.ReplicationTest > testContinuousPushReplicationGoesIdleTooSoon[Google Nexus 4 - 4.4.4 - API 19 - 768x1280 - 4.4.4] FAILED 
Test failed to run to completion. Reason: 'Instrumentation run failed due to 'Process crashed.''. Check device logcat for details
Tests on Google Nexus 4 - 4.4.4 - API 19 - 768x1280 - 4.4.4 failed: Instrumentation run failed due to 'Process crashed.'
deleteDir(/Users/hideki/github/couchbase-lite-android/build/reports/androidTests/connected) returned: true
:connectedDebugAndroidTest FAILED
:connectedDebugAndroidTest (Thread[main,5,main]) completed. Took 7 mins 18.596 secs.
```

**Comment by hideki** [comment]
##### Test failure on Nexus 6
```
junit.framework.AssertionFailedError: expected:<25> but was:<20>
at com.couchbase.lite.replicator.ReplicationTest.testContinuousPushReplicationGoesIdleTooSoon(ReplicationTest.java:3652)
at com.couchbase.lite.LiteTestCase.runBare(LiteTestCase.java:844)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:191)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:176)
at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:555)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1853)
```


##### Native Crash on Nexus 6
`Test failed to run to completion. Reason: 'Instrumentation run failed due to 'Native crash''. Check device logcat for details
`

**Comment by hideki** [comment]
I can not reproduce the `testContinuousPushReplicationGoesIdleTooSoon()` test failure. All tests pass.

@pasin could you please re-run test with SQLiteStore?

**Comment by hideki** [comment]
```
com.couchbase.lite.replicator.ReplicationTest > testContinuousPushReplicationGoesIdleTooSoon[Nexus_4_API_19_arm(AVD) - 4.4.4] FAILED 
	junit.framework.AssertionFailedError: expected:<25> but was:<23>
	at com.couchbase.lite.replicator.ReplicationTest.testContinuousPushReplicationGoesIdleTooSoon(ReplicationTest.java:3652)

com.couchbase.lite.replicator.ReplicationTest > testPusherBatching[Nexus_4_API_19_arm(AVD) - 4.4.4] FAILED 
	junit.framework.AssertionFailedError: expected:<15> but was:<13>
	at com.couchbase.lite.replicator.ReplicationTest.testPusherBatching(ReplicationTest.java:1999)

com.couchbase.lite.replicator.ReplicationTest > testPusherBatching[Nexus_4_API_19_arm(AVD) - 4.4.4] FAILED 
	junit.framework.AssertionFailedError: expected:<15> but was:<14>
	at com.couchbase.lite.replicator.ReplicationTest.testPusherBatching(ReplicationTest.java:1999)
```

**Comment by hideki** [comment]
testPusherBatching - failed during getRevisionHistory
```java
09-21 15:38:24.856 2291-2310/com.couchbase.lite.test W/Database: [changesSince()] revID => 1-a951becdcd0abe51a96444189c0f4fa2
09-21 15:38:24.856 2291-2310/com.couchbase.lite.test W/Database: [changesSince()] revID => 1-a60dee3aada93de5ca734373f2b571ef
09-21 15:38:25.336 2291-2312/com.couchbase.lite.test E/CBForest: FORESTDB ERROR -39
09-21 15:38:25.426 2291-2312/com.couchbase.lite.test E/Database: %%%%% Error in getRevisionHistory() rev={49641dd7-b551-4bca-bb04-c0cf38692968 #1-8464c420c20b62b82e80d522859a1cf8}
09-21 15:38:25.426 2291-2312/com.couchbase.lite.test E/Database: java.lang.Exception: -39
09-21 15:38:25.426 2291-2312/com.couchbase.lite.test E/Database:     at com.couchbase.lite.cbforest.cbforestJNI.new_VersionedDocument__SWIG_0(Native Method)
09-21 15:38:25.426 2291-2312/com.couchbase.lite.test E/Database:     at com.couchbase.lite.cbforest.VersionedDocument.<init>(VersionedDocument.java:39)
09-21 15:38:25.426 2291-2312/com.couchbase.lite.test E/Database:     at com.couchbase.lite.store.ForestDBStore.getRevisionHistory(ForestDBStore.java:422)
09-21 15:38:25.426 2291-2312/com.couchbase.lite.test E/Database:     at com.couchbase.lite.Database.getRevisionHistory(Database.java:1762)
09-21 15:38:25.426 2291-2312/com.couchbase.lite.test E/Database:     at com.couchbase.lite.Database.getRevisionHistoryDictStartingFromAnyAncestor(Database.java:1216)
09-21 15:38:25.426 2291-2312/com.couchbase.lite.test E/Database:     at com.couchbase.lite.replicator.PusherInternal$3.onCompletion(PusherInternal.java:482)
09-21 15:38:25.426 2291-2312/com.couchbase.lite.test E/Database:     at com.couchbase.lite.support.RemoteRequestRetry$1.completed(RemoteRequestRetry.java:213)
09-21 15:38:25.426 2291-2312/com.couchbase.lite.test E/Database:     at com.couchbase.lite.support.RemoteRequestRetry$1.onCompletion(RemoteRequestRetry.java:231)
09-21 15:38:25.426 2291-2312/com.couchbase.lite.test E/Database:     at com.couchbase.lite.support.RemoteRequest.respondWithResult(RemoteRequest.java:300)
09-21 15:38:25.426 2291-2312/com.couchbase.lite.test E/Database:     at com.couchbase.lite.support.RemoteRequest.executeRequest(RemoteRequest.java:250)
09-21 15:38:25.426 2291-2312/com.couchbase.lite.test E/Database:     at com.couchbase.lite.support.RemoteRequest.run(RemoteRequest.java:103)
09-21 15:38:25.426 2291-2312/com.couchbase.lite.test E/Database:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
09-21 15:38:25.426 2291-2312/com.couchbase.lite.test E/Database:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
09-21 15:38:25.426 2291-2312/com.couchbase.lite.test E/Database:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
09-21 15:38:25.426 2291-2312/com.couchbase.lite.test E/Database:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
09-21 15:38:25.426 2291-2312/com.couchbase.lite.test E/Database:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
09-21 15:38:25.426 2291-2312/com.couchbase.lite.test E/Database:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
09-21 15:38:25.426 2291-2312/com.couchbase.lite.test E/Database:     at java.lang.Thread.run(Thread.java:841)
09-21 15:38:25.726 2291-2313/com.couchbase.lite.test E/RemoteRequest: Got error status: 404 for http://10.0.2.2:4984/db/_local/8ead10fa5c02ade2c8264963e7eeeff005528ecf.  Reason: NOT FOUND
09-21 15:38:25.736 2291-2313/com.couchbase.lite.test W/Sync: com.couchbase.lite.replicator.ReplicationInternal$7@b1d887e0: Unable to save remote checkpoint
```
