### ISSUE TITLE
Error when building couchbase-lite-java-forestdb on Linux

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-java-core#745]
Should use GCC

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':libraries:couchbase-lite-java-forestdb:compileCouchbaseLiteJavaForestDBSharedLibraryCouchbaseLiteJavaForestDBCpp'.
> Could not find C++ compiler 'clang++' in system path.
```

http://mobile.jenkins.couchbase.com/job/couchbase-lite-java-build/292/console

**Comment by hideki** [comment]
Clang is not available on Linux without installing clang.
- Install clang
` sudo apt-get install clang`

Current compilation error
```
hideki@linux:~/github/couchbase-lite-java-forestdb$ ./gradlew -Pspec=java assemble
Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/share/java/jayatanaag.jar 
:compileCouchbaseLiteJavaForestDBSharedLibraryCouchbaseLiteJavaForestDBCpp
/home/hideki/github/couchbase-lite-java-forestdb/vendor/cbforest/CBForest/Tokenizer.cc:117:9: error: unknown type name '__unused'
        __unused int err = sModule->xOpen(tokenizer.getTokenizer(),
        ^
/home/hideki/github/couchbase-lite-java-forestdb/vendor/cbforest/CBForest/Tokenizer.cc:117:18: error: expected unqualified-id
        __unused int err = sModule->xOpen(tokenizer.getTokenizer(),
                 ^
/home/hideki/github/couchbase-lite-java-forestdb/vendor/cbforest/CBForest/Tokenizer.cc:120:17: error: use of undeclared identifier 'err'
        assert(!err);
                ^
/usr/include/assert.h:89:5: note: expanded from macro 'assert'
  ((expr)                                                               \
    ^
3 errors generated.

/home/hideki/github/couchbase-lite-java-forestdb/jni/cbf_docenumerator.cc:18:10: error: use of undeclared identifier 'UINT_MAX'
        limit = UINT_MAX;
                ^
1 error generated.

:compileCouchbaseLiteJavaForestDBSharedLibraryCouchbaseLiteJavaForestDBCpp FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileCouchbaseLiteJavaForestDBSharedLibraryCouchbaseLiteJavaForestDBCpp'.
> Multiple build operations failed.
      C++ compiler failed while compiling Tokenizer.cc.
      C++ compiler failed while compiling cbf_docenumerator.cc.
  See the complete log at: file:///home/hideki/github/couchbase-lite-java-forestdb/build/tmp/compileCouchbaseLiteJavaForestDBSharedLibraryCouchbaseLiteJavaForestDBCpp/output.txt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 9.761 secs
```

**Comment by pasin** [comment]
In general, if clang doesn't exist, gradle should try to use the other compilers (in order) declared in build.gradle's toolChains. So did it not try to use gcc?

**Comment by hideki** [comment]
Gradle shows error "clang++ not found", instead of trying to use next compiler....

So, I installed clang on linux.

As CBForest is written with using Xcode, clang is ideal compiler for CBForest.

**Comment by hideki** [comment]
By updating build-java.gradle and one source code. Build passes now.
https://github.com/couchbaselabs/couchbase-lite-java-forestdb/commit/128dc7fa284735adf218af4024d47b08ab69841e

However, test is still fails because of SQLite native library loading issue.
```
Gradle Test Executor 1 started executing tests.

com.couchbase.lite.java.CollationTest > testCollateRevIds STANDARD_ERROR
    Sep 16, 2015 5:23:14 PM com.couchbase.lite.util.SystemLogger e
    SEVERE: Native: Library not found: /native/linux/amd64/libCouchbaseLiteJavaNative.so
    Sep 16, 2015 5:23:14 PM com.couchbase.lite.util.SystemLogger e
    SEVERE: Native: Error loading library: CouchbaseLiteJavaNative
    java.lang.NullPointerException
    	at com.couchbase.lite.util.NativeUtils.loadLibrary(NativeUtils.java:45)
    	at com.couchbase.lite.storage.JavaSQLiteStorageEngine.<clinit>(JavaSQLiteStorageEngine.java:125)
    	at com.couchbase.lite.java.CollationTest.testCollateRevIds(CollationTest.java:127)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:606)
    	at junit.framework.TestCase.runTest(TestCase.java:176)
    	at junit.framework.TestCase.runBare(TestCase.java:141)
    	at junit.framework.TestResult$1.protect(TestResult.java:122)
    	at junit.framework.TestResult.runProtected(TestResult.java:142)
    	at junit.framework.TestResult.run(TestResult.java:125)
    	at junit.framework.TestCase.run(TestCase.java:129)
    	at junit.framework.TestSuite.runTest(TestSuite.java:255)
    	at junit.framework.TestSuite.run(TestSuite.java:250)
    	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)
    	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:86)
    	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:49)
    	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:64)
    	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:50)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:606)
    	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
    	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    	at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
    	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
    	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
    	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:106)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:606)
    	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
    	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    	at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:360)
    	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
    	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    	at java.lang.Thread.run(Thread.java:745)


com.couchbase.lite.java.CollationTest > testCollateRevIds FAILED
    java.lang.UnsatisfiedLinkError: com.couchbase.lite.storage.JavaSQLiteStorageEngine.nativeTestCollateRevIds(Ljava/lang/String;Ljava/lang/String;)I
        at com.couchbase.lite.storage.JavaSQLiteStorageEngine.nativeTestCollateRevIds(Native Method)
        at com.couchbase.lite.storage.JavaSQLiteStorageEngine.testCollateRevIds(JavaSQLiteStorageEngine.java:512)
        at com.couchbase.lite.java.CollationTest.testCollateRevIds(CollationTest.java:127)

com.couchbase.lite.java.CollationTest > testCollateScalars FAILED
    java.lang.UnsatisfiedLinkError: com.couchbase.lite.storage.JavaSQLiteStorageEngine.nativeTestCollateJson(ILjava/lang/String;Ljava/lang/String;)I
        at com.couchbase.lite.storage.JavaSQLiteStorageEngine.nativeTestCollateJson(Native Method)
        at com.couchbase.lite.storage.JavaSQLiteStorageEngine.testCollateJSON(JavaSQLiteStorageEngine.java:500)
        at com.couchbase.lite.java.CollationTest.testCollateScalars(CollationTest.java:50)

com.couchbase.lite.java.CollationTest > testCollateUnicodeStrings FAILED
    java.lang.UnsatisfiedLinkError: com.couchbase.lite.storage.JavaSQLiteStorageEngine.nativeTestCollateJson(ILjava/lang/String;Ljava/lang/String;)I
        at com.couchbase.lite.storage.JavaSQLiteStorageEngine.nativeTestCollateJson(Native Method)
        at com.couchbase.lite.storage.JavaSQLiteStorageEngine.testCollateJSON(JavaSQLiteStorageEngine.java:500)
        at com.couchbase.lite.java.CollationTest.testCollateUnicodeStrings(CollationTest.java:115)
Gradle Test Executor 1 finished executing tests.

com.couchbase.lite.java.CollationTest > testCollateNestedArray FAILED
    java.lang.UnsatisfiedLinkError: com.couchbase.lite.storage.JavaSQLiteStorageEngine.nativeTestCollateJson(ILjava/lang/String;Ljava/lang/String;)I
        at com.couchbase.lite.storage.JavaSQLiteStorageEngine.nativeTestCollateJson(Native Method)
        at com.couchbase.lite.storage.JavaSQLiteStorageEngine.testCollateJSON(JavaSQLiteStorageEngine.java:500)
        at com.couchbase.lite.java.CollationTest.testCollateNestedArray(CollationTest.java:109)

com.couchbase.lite.java.CollationTest > testCollateASCII FAILED
    java.lang.UnsatisfiedLinkError: com.couchbase.lite.storage.JavaSQLiteStorageEngine.nativeTestCollateJson(ILjava/lang/String;Ljava/lang/String;)I
        at com.couchbase.lite.storage.JavaSQLiteStorageEngine.nativeTestCollateJson(Native Method)
        at com.couchbase.lite.storage.JavaSQLiteStorageEngine.testCollateJSON(JavaSQLiteStorageEngine.java:500)
        at com.couchbase.lite.java.CollationTest.testCollateASCII(CollationTest.java:69)

com.couchbase.lite.java.CollationTest > testCollateRaw FAILED
    java.lang.UnsatisfiedLinkError: com.couchbase.lite.storage.JavaSQLiteStorageEngine.nativeTestCollateJson(ILjava/lang/String;Ljava/lang/String;)I
        at com.couchbase.lite.storage.JavaSQLiteStorageEngine.nativeTestCollateJson(Native Method)
        at com.couchbase.lite.storage.JavaSQLiteStorageEngine.testCollateJSON(JavaSQLiteStorageEngine.java:500)
        at com.couchbase.lite.java.CollationTest.testCollateRaw(CollationTest.java:87)

com.couchbase.lite.java.CollationTest > testCollateArrays FAILED
    java.lang.UnsatisfiedLinkError: com.couchbase.lite.storage.JavaSQLiteStorageEngine.nativeTestCollateJson(ILjava/lang/String;Ljava/lang/String;)I
        at com.couchbase.lite.storage.JavaSQLiteStorageEngine.nativeTestCollateJson(Native Method)
        at com.couchbase.lite.storage.JavaSQLiteStorageEngine.testCollateJSON(JavaSQLiteStorageEngine.java:500)
        at com.couchbase.lite.java.CollationTest.testCollateArrays(CollationTest.java:97)

8 tests completed, 7 failed
Finished generating test XML results (0.066 secs) into: /home/hideki/github/couchbase-lite-java/build/test-results
Generating HTML test report...
Finished generating test html results (0.07 secs) into: /home/hideki/github/couchbase-lite-java/build/reports/tests
:test FAILED
:test (Thread[main,5,main]) completed. Took 1.534 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> There were failing tests. See the report at: file:///home/hideki/github/couchbase-lite-java/build/reports/tests/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.

BUILD FAILED

Total time: 9.292 secs

```
