### ISSUE TITLE
ReplicationTest failure with android emulator on Jenkins

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-java-core#773]
http://mobile.jenkins.couchbase.com/view/Couchbase_Lite/job/couchbase-lite-android-build/299/console

testMockPullBulkDocsSyncGw
```
junit.framework.AssertionFailedError
at com.couchbase.lite.LiteTestCaseWithDB.runReplication(LiteTestCaseWithDB.java:615)
at com.couchbase.lite.replicator.ReplicationTest.mockPullBulkDocs(ReplicationTest.java:3334)
at com.couchbase.lite.replicator.ReplicationTest.testMockPullBulkDocsSyncGw(ReplicationTest.java:3282)
at java.lang.reflect.Method.invokeNative(Native Method)
at com.couchbase.lite.LiteTestCase.runBare(LiteTestCase.java:20)
at com.couchbase.lite.LiteTestCaseWithDB.runBare(LiteTestCaseWithDB.java:77)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:191)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:176)
at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:554)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1701)
```

testStop
```
junit.framework.AssertionFailedError: expected:<-1> but was:<0>
at com.couchbase.lite.replicator.ReplicationTest.testStop(ReplicationTest.java:4842)
at java.lang.reflect.Method.invokeNative(Native Method)
at com.couchbase.lite.LiteTestCase.runBare(LiteTestCase.java:20)
at com.couchbase.lite.LiteTestCaseWithDB.runBare(LiteTestCaseWithDB.java:77)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:191)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:176)
at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:554)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1701)
```

**Comment by hideki** [comment]
duplicate with #809
