### ISSUE TITLE
invalid MIME body after starting pull replication

### ISSUE THREAD

**Issue by ahmedalkhashab** [couchbase/couchbase-lite-java-core#791]
i store image attachment
 i can get it on server
but i can't get it at android when i start pull replication 

* i can get it from iOS
~~~
10-20 17:35:19.768 3220-3656/com.smardex E/RemoteRequest: com.couchbase.lite.replicator.BulkDownloader[/smardex/_bulk_get]: executeRequest() Exception: 
10-20 17:35:19.768 3220-3656/com.smardex E/RemoteRequest: java.lang.IllegalStateException: Attachment 'large_picture:512d9eab-60b9-440e-9ed2-59f243429b53' does not appear in MIME body
10-20 17:35:19.768 3220-3656/com.smardex E/RemoteRequest:     at com.couchbase.lite.support.MultipartDocumentReader.registerAttachments(MultipartDocumentReader.java:169)
10-20 17:35:19.768 3220-3656/com.smardex E/RemoteRequest:     at com.couchbase.lite.support.MultipartDocumentReader.finish(MultipartDocumentReader.java:117)
10-20 17:35:19.768 3220-3656/com.smardex E/RemoteRequest:     at com.couchbase.lite.replicator.BulkDownloader.finishedPart(BulkDownloader.java:246)
10-20 17:35:19.768 3220-3656/com.smardex E/RemoteRequest:     at com.couchbase.lite.support.MultipartReader.appendData(MultipartReader.java:171)
10-20 17:35:19.768 3220-3656/com.smardex E/RemoteRequest:     at com.couchbase.lite.replicator.BulkDownloader.executeRequest(BulkDownloader.java:145)
10-20 17:35:19.768 3220-3656/com.smardex E/RemoteRequest:     at com.couchbase.lite.replicator.BulkDownloader.run(BulkDownloader.java:89)
10-20 17:35:19.768 3220-3656/com.smardex E/RemoteRequest:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
10-20 17:35:19.768 3220-3656/com.smardex E/RemoteRequest:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
10-20 17:35:19.768 3220-3656/com.smardex E/RemoteRequest:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
10-20 17:35:19.768 3220-3656/com.smardex E/RemoteRequest:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
10-20 17:35:19.768 3220-3656/com.smardex E/RemoteRequest:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
10-20 17:35:19.768 3220-3656/com.smardex E/RemoteRequest:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
10-20 17:35:19.768 3220-3656/com.smardex E/RemoteRequest:     at java.lang.Thread.run(Thread.java:818)
10-20 17:35:19.768 3220-3656/com.smardex E/Sync: com.couchbase.lite.replicator.PullerInternal@2d720ec1: Progress: set error = java.lang.IllegalStateException: Attachment 'large_picture:512d9eab-60b9-440e-9ed2-59f243429b53' does not appear in MIME body
~~~

**Comment by hideki** [comment]
HI @ahmedalkhashab,
Could you please provide Attachment file size, Sync Gateway version, and Couchbase Lite version.
Thanks!

**Comment by zgramana** [comment]
@ahmedalkhashab any updates? If not, we'll close this out next.

**Comment by aiurlano** [comment]
I had the same issue with an attachment and it was stopping the pull replication on Android.

In my case the problem was that the attachment name contained the ":" character. I changed the name from "image:0" to "image-0" and it started working.

Inspecting variables with a debugger suggested that Couchbase Lite sdk was cutting the attachment name from the ":" character to the end of the string.

**Comment by zgramana** [comment]
@aiurlano thanks for the additional info. We're looking into it.
