### ISSUE TITLE
C4DatabaseTest.testInsertRevisionWithHistory() test causes native crash on ARM v7a emulator

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-java-core#793]
```
10-27 14:13:01.853 3727-3742/com.couchbase.cbforest.test W/dalvikvm: JNI WARNING: threadid=12 using JNI after critical get (ReleaseStringUTFChars)
10-27 14:13:01.853 3727-3742/com.couchbase.cbforest.test W/dalvikvm:              in Lcom/couchbase/cbforest/Document;.insertRevisionWithHistory:(J[BZZ[Ljava/lang/String;)I (ReleaseStringUTFChars)
10-27 14:13:01.853 3727-3742/com.couchbase.cbforest.test I/dalvikvm: "Instr: android.test.InstrumentationTestRunner" prio=5 tid=12 NATIVE
10-27 14:13:01.853 3727-3742/com.couchbase.cbforest.test I/dalvikvm:   | group="main" sCount=0 dsCount=0 obj=0xb0fcbce8 self=0xb87a01a0
10-27 14:13:01.853 3727-3742/com.couchbase.cbforest.test I/dalvikvm:   | sysTid=3742 nice=-8 sched=0/0 cgrp=[fopen-error:2] handle=-1199962608
10-27 14:13:01.853 3727-3742/com.couchbase.cbforest.test I/dalvikvm:   | state=R schedstat=( 0 0 0 ) utm=1 stm=1 core=0
10-27 14:13:01.863 3727-3742/com.couchbase.cbforest.test I/dalvikvm:   #00  pc 000bd456  /system/lib/libdvm.so (dvmDumpNativeStack(DebugOutputTarget const*, int)+86)
10-27 14:13:01.863 3727-3742/com.couchbase.cbforest.test I/dalvikvm:   #01  pc 00098033  /system/lib/libdvm.so (dvmDumpThreadEx(DebugOutputTarget const*, Thread*, bool)+1155)
10-27 14:13:01.863 3727-3742/com.couchbase.cbforest.test I/dalvikvm:   #02  pc 00098326  /system/lib/libdvm.so (dvmDumpThread(Thread*, bool)+86)
10-27 14:13:01.863 3727-3742/com.couchbase.cbforest.test I/dalvikvm:   #03  pc 0004ce27  /system/lib/libdvm.so (ScopedCheck::checkThread(int)+455)
10-27 14:13:01.863 3727-3742/com.couchbase.cbforest.test I/dalvikvm:   #04  pc 00052235  /system/lib/libdvm.so
10-27 14:13:01.863 3727-3742/com.couchbase.cbforest.test I/dalvikvm:   #05  pc 0019e6ff  /data/app-lib/com.couchbase.cbforest.test-1/libCouchbaseLiteJavaForestDB.so (_JNIEnv::ReleaseStringUTFChars(_jstring*, char const*)+79)
10-27 14:13:01.863 3727-3742/com.couchbase.cbforest.test I/dalvikvm:   #06  pc 0019e687  /data/app-lib/com.couchbase.cbforest.test-1/libCouchbaseLiteJavaForestDB.so (forestdb::jni::jstringSlice::~jstringSlice()+87)
10-27 14:13:01.863 3727-3742/com.couchbase.cbforest.test I/dalvikvm:   #07  pc 0019b1af  /data/app-lib/com.couchbase.cbforest.test-1/libCouchbaseLiteJavaForestDB.so (Java_com_couchbase_cbforest_Document_insertRevisionWithHistory+1039)
10-27 14:13:01.873 3727-3742/com.couchbase.cbforest.test I/dalvikvm:   #08  pc 0002a0eb  /system/lib/libdvm.so (dvmPlatformInvoke+79)
10-27 14:13:01.873 3727-3742/com.couchbase.cbforest.test I/dalvikvm:     at com.couchbase.cbforest.Document.insertRevisionWithHistory(Native Method)
10-27 14:13:01.873 3727-3742/com.couchbase.cbforest.test I/dalvikvm:     at com.couchbase.cbforest.Document.insertRevisionWithHistory(Document.java:73)
10-27 14:13:01.873 3727-3742/com.couchbase.cbforest.test I/dalvikvm:     at com.couchbase.cbforest.C4DatabaseTest.testInsertRevisionWithHistory(C4DatabaseTest.java:254)
10-27 14:13:01.873 3727-3742/com.couchbase.cbforest.test I/dalvikvm:     at java.lang.reflect.Method.invokeNative(Native Method)
10-27 14:13:01.873 3727-3742/com.couchbase.cbforest.test I/dalvikvm:     at java.lang.reflect.Method.invoke(Method.java:515)
10-27 14:13:01.873 3727-3742/com.couchbase.cbforest.test I/dalvikvm:     at junit.framework.TestCase.runTest(TestCase.java:168)
10-27 14:13:01.873 3727-3742/com.couchbase.cbforest.test I/dalvikvm:     at junit.framework.TestCase.runBare(TestCase.java:134)
10-27 14:13:01.873 3727-3742/com.couchbase.cbforest.test I/dalvikvm:     at junit.framework.TestResult$1.protect(TestResult.java:115)
10-27 14:13:01.873 3727-3742/com.couchbase.cbforest.test I/dalvikvm:     at junit.framework.TestResult.runProtected(TestResult.java:133)
10-27 14:13:01.873 3727-3742/com.couchbase.cbforest.test I/dalvikvm:     at junit.framework.TestResult.run(TestResult.java:118)
10-27 14:13:01.873 3727-3742/com.couchbase.cbforest.test I/dalvikvm:     at junit.framework.TestCase.run(TestCase.java:124)
10-27 14:13:01.873 3727-3742/com.couchbase.cbforest.test I/dalvikvm:     at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:191)
10-27 14:13:01.873 3727-3742/com.couchbase.cbforest.test I/dalvikvm:     at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:176)
10-27 14:13:01.873 3727-3742/com.couchbase.cbforest.test I/dalvikvm:     at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:554)
10-27 14:13:01.873 3727-3742/com.couchbase.cbforest.test I/dalvikvm:     at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1701)
10-27 14:13:01.873 3727-3742/com.couchbase.cbforest.test E/dalvikvm: VM aborting
10-27 14:13:01.873 3727-3742/com.couchbase.cbforest.test A/libc: Fatal signal 6 (SIGABRT) at 0x00000e8f (code=-6), thread 3742 (ationTestRunner)
10-27 14:13:01.993 936-936/? I/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
10-27 14:13:01.993 936-936/? I/DEBUG: Build fingerprint: 'generic_x86/sdk_x86/generic_x86:4.4.4/KK/1743154:eng/test-keys'
10-27 14:13:01.993 936-936/? I/DEBUG: Revision: '0'
10-27 14:13:01.993 936-936/? I/DEBUG: pid: 3727, tid: 3742, name: ationTestRunner  >>> com.couchbase.cbforest.test <<<
10-27 14:13:01.993 936-936/? I/DEBUG: signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
10-27 14:13:02.123 936-936/? I/DEBUG:     eax 00000000  ebx 00000e8f  ecx 00000e9e  edx 00000006
10-27 14:13:02.123 936-936/? I/DEBUG:     esi 00000e9e  edi 00000002
10-27 14:13:02.123 936-936/? I/DEBUG:     xcs 00000073  xds 0000007b  xes 0000007b  xfs 00000000  xss 0000007b
10-27 14:13:02.123 936-936/? I/DEBUG:     eip b76e8c96  ebp b774dce0  esp a6b541a0  flags 00200207
10-27 14:13:02.123 936-936/? I/DEBUG:     #00  pc 0003bc96  /system/lib/libc.so (tgkill+22)
10-27 14:13:02.123 936-936/? I/DEBUG:     #01  pc 00000005  <unknown>
10-27 14:13:02.123 936-936/? I/DEBUG:          a6b54160  00000000  
10-27 14:13:02.123 936-936/? I/DEBUG:          a6b54164  b7749268  /system/lib/libc.so
10-27 14:13:02.123 936-936/? I/DEBUG:          a6b54168  00000000  
10-27 14:13:02.123 936-936/? I/DEBUG:          a6b5416c  b76baef9  /system/lib/libc.so (pthread_mutex_unlock+25)
10-27 14:13:02.133 936-936/? I/DEBUG:          a6b54170  b774918c  /system/lib/libc.so
10-27 14:13:02.133 936-936/? I/DEBUG:          a6b54174  b86bca70  [heap]
10-27 14:13:02.133 936-936/? I/DEBUG:          a6b54178  00000015  
10-27 14:13:02.133 936-936/? I/DEBUG:          a6b5417c  b76baef9  /system/lib/libc.so (pthread_mutex_unlock+25)
10-27 14:13:02.133 936-936/? I/DEBUG:          a6b54180  00000000  
10-27 14:13:02.133 936-936/? I/DEBUG:          a6b54184  b7707656  /system/lib/libc.so (funlockfile+6)
10-27 14:13:02.133 936-936/? I/DEBUG:          a6b54188  b7748fcc  /system/lib/libc.so
10-27 14:13:02.133 936-936/? I/DEBUG:          a6b5418c  b76f2c76  /system/lib/libc.so (__sflush_locked+150)
10-27 14:13:02.133 936-936/? I/DEBUG:          a6b54190  00000000  
10-27 14:13:02.133 936-936/? I/DEBUG:          a6b54194  00000000  
10-27 14:13:02.133 936-936/? I/DEBUG:          a6b54198  b76bad29  /system/lib/libc.so (pthread_mutex_lock+9)
10-27 14:13:02.133 936-936/? I/DEBUG:          a6b5419c  b7748fcc  /system/lib/libc.so
10-27 14:13:02.133 936-936/? I/DEBUG:     #00  a6b541a0  00000006  
10-27 14:13:02.133 936-936/? I/DEBUG:          a6b541a4  00000e9e  
10-27 14:13:02.133 936-936/? I/DEBUG:          a6b541a8  b7748fcc  /system/lib/libc.so
10-27 14:13:02.133 936-936/? I/DEBUG:          a6b541ac  b76c5436  /system/lib/libc.so (pthread_kill+102)
10-27 14:13:02.133 936-936/? I/DEBUG:          a6b541b0  00000e8f  
10-27 14:13:02.133 936-936/? I/DEBUG:          a6b541b4  00000e9e  
10-27 14:13:02.133 936-936/? I/DEBUG:          a6b541b8  00000006  
10-27 14:13:02.133 936-936/? I/DEBUG:          a6b541bc  00000000  
10-27 14:13:02.133 936-936/? I/DEBUG:          a6b541c0  b7749268  /system/lib/libc.so
10-27 14:13:02.133 936-936/? I/DEBUG:          a6b541c4  b4e46de1  /system/lib/libdvm.so
10-27 14:13:02.133 936-936/? I/DEBUG:          a6b541c8  b76c53d9  /system/lib/libc.so (pthread_kill+9)
10-27 14:13:02.133 936-936/? I/DEBUG:          a6b541cc  b7748fcc  /system/lib/libc.so
10-27 14:13:02.133 936-936/? I/DEBUG:          a6b541d0  a6b5421c  [stack:3742]
10-27 14:13:02.133 936-936/? I/DEBUG:          a6b541d4  a6b5445c  [stack:3742]
10-27 14:13:02.133 936-936/? I/DEBUG:          a6b541d8  00000001  
10-27 14:13:02.133 936-936/? I/DEBUG:          a6b541dc  b76c57fc  /system/lib/libc.so (raise+44)
10-27 14:13:02.173 1254-1276/system_process I/BootReceiver: Copying /data/tombstones/tombstone_05 to DropBox (SYSTEM_TOMBSTONE)
10-27 14:13:02.183 939-939/? D/Zygote: Process 3727 terminated by signal (6)
10-27 14:13:02.183 3718-3718/? D/AndroidRuntime: Shutting down VM
```

**Comment by hideki** [comment]
PR: https://github.com/couchbaselabs/cbforest/pull/41
