### ISSUE TITLE
Jenkins: testMockPullBulkDocsSyncGw fails on Jenkins

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-java-core#809]
http://mobile.jenkins.couchbase.com/job/couchbase-lite-android-build/413/

**Comment by hideki** [comment]
@tleyden Do you have any idea why this fails?

**Comment by tleyden** [comment]
@hideki I know one difference is the android emulator vs genymotion.  I would try reproducing on the android emulator.  Also, if that machine is running under a VM, using a bare metal or a more powerful VM might help

**Comment by hideki** [comment]
Thanks for your advise. I will ask @michaelkwok  to assign more processor and memory to VM.

**Comment by hideki** [comment]
This issue is also not reproducible with my development environment.  Stack Android Emulator with ARM and API 19 setting.

**Comment by hideki** [comment]
NOTE:
Build: http://mobile.jenkins.couchbase.com/job/couchbase-lite-android-build/444/artifact/logcat.txt/*view*/

testMockPullBulkDocsSyncGw succeeded.

**Comment by hideki** [comment]
http://mobile.jenkins.couchbase.com/job/couchbase-lite-android-build/445/artifact/logcat.txt/*view*/

```
12-01 05:48:35.800 D/Database( 1059): Closed com.couchbase.lite.Manager@b3219f90
12-01 05:48:35.800 I/TestRunner( 1059): failed: testMockPullBulkDocsSyncGw(com.couchbase.lite.replicator.ReplicationTest)
12-01 05:48:35.810 I/TestRunner( 1059): ----- begin exception -----
12-01 05:48:35.810 I/TestRunner( 1059): 
12-01 05:48:35.810 I/TestRunner( 1059): junit.framework.AssertionFailedError
12-01 05:48:35.810 I/TestRunner( 1059): 	at junit.framework.Assert.fail(Assert.java:48)
12-01 05:48:35.810 I/TestRunner( 1059): 	at junit.framework.Assert.assertTrue(Assert.java:20)
12-01 05:48:35.810 I/TestRunner( 1059): 	at junit.framework.Assert.assertTrue(Assert.java:27)
12-01 05:48:35.810 I/TestRunner( 1059): 	at com.couchbase.lite.replicator.ReplicationTest.mockPullBulkDocs(ReplicationTest.java:3355)
12-01 05:48:35.810 I/TestRunner( 1059): 	at com.couchbase.lite.replicator.ReplicationTest.testMockPullBulkDocsSyncGw(ReplicationTest.java:3282)
12-01 05:48:35.810 I/TestRunner( 1059): 	at java.lang.reflect.Method.invokeNative(Native Method)
12-01 05:48:35.810 I/TestRunner( 1059): 	at java.lang.reflect.Method.invoke(Method.java:515)
12-01 05:48:35.810 I/TestRunner( 1059): 	at junit.framework.TestCase.runTest(TestCase.java:168)
12-01 05:48:35.810 I/TestRunner( 1059): 	at junit.framework.TestCase.runBare(TestCase.java:134)
12-01 05:48:35.810 I/TestRunner( 1059): 	at com.couchbase.lite.LiteTestCase.runBare(LiteTestCase.java:20)
12-01 05:48:35.810 I/TestRunner( 1059): 	at com.couchbase.lite.LiteTestCaseWithDB.runBare(LiteTestCaseWithDB.java:84)
12-01 05:48:35.810 I/TestRunner( 1059): 	at junit.framework.TestResult$1.protect(TestResult.java:115)
12-01 05:48:35.810 I/TestRunner( 1059): 	at junit.framework.TestResult.runProtected(TestResult.java:133)
12-01 05:48:35.810 I/TestRunner( 1059): 	at junit.framework.TestResult.run(TestResult.java:118)
12-01 05:48:35.810 I/TestRunner( 1059): 	at junit.framework.TestCase.run(TestCase.java:124)
12-01 05:48:35.810 I/TestRunner( 1059): 	at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:191)
12-01 05:48:35.810 I/TestRunner( 1059): 	at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:176)
12-01 05:48:35.810 I/TestRunner( 1059): 	at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:554)
12-01 05:48:35.810 I/TestRunner( 1059): 	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1701)
12-01 05:48:35.810 I/TestRunner( 1059): ----- end exception -----
12-01 05:48:35.830 I/TestRunner( 1059): finished: testMockPullBulkDocsSyncGw(com.couchbase.lite.replicator.ReplicationTest)
12-01 05:48:35.860 I/TestRunner( 1059): started: testMockPullerRestart(com.couchbase.lite.replicator.ReplicationTest)
```
