### ISSUE TITLE
ApiTest.testConflict() test fails

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-java-core#818]
```
junit.framework.AssertionFailedError: expected:<0> but was:<2>
at com.couchbase.lite.ApiTest.testConflict(ApiTest.java:557)
at com.couchbase.lite.LiteTestCase.runBare(LiteTestCase.java:20)
at com.couchbase.lite.LiteTestCaseWithDB.runBare(LiteTestCaseWithDB.java:81)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:191)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:176)
at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:555)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1853)
```

**Comment by hideki** [comment]
PR: https://github.com/couchbaselabs/couchbase-lite-java-forestdb/pull/14
