### ISSUE TITLE
BulkDownloader[/db/_bulk_get]: executeRequest() Exception:  java.lang.IllegalStateException: _docReader is not defined

### ISSUE THREAD

**Issue by andreibaranouski** [couchbase/couchbase-lite-java-core#824]
from sg functional tests

http://qa.sc.couchbase.com/view/mobile/job/centos-sync-gateway-mobile-functional-tests-android-cb/lastSuccessfulBuild/artifact/01_adb.log

```
11-18 10:58:02.589 I/art     ( 2084): Background sticky concurrent mark sweep GC freed 4607(439KB) AllocSpace objects, 26(560KB) LOS objects, 20% free, 4MB/5MB, paused 7.146ms total 191.294ms
11-18 10:58:02.895 W/Sync    ( 2084): com.couchbase.lite.replicator.PullerInternal@f67f833: Received invalid doc ID from _changes: {seq=1, id=_user/, changes=[{rev=}]}
11-18 10:58:03.153 W/Sync    ( 2084): com.couchbase.lite.replicator.PusherInternal@19fd7b8d: removePending: sequence 1610 not in set, for rev {large-revisions-revslimit_9 #161-9dc57942fd1f76fbb39ea872f8082ff2}
11-18 10:58:03.575 E/RemoteRequest( 2084): com.couchbase.lite.replicator.BulkDownloader[/db/_bulk_get]: executeRequest() Exception: 
11-18 10:58:03.575 E/RemoteRequest( 2084): java.lang.IllegalStateException: _docReader is not defined
11-18 10:58:03.575 E/RemoteRequest( 2084): 	at com.couchbase.lite.replicator.BulkDownloader.appendToPart(BulkDownloader.java:239)
11-18 10:58:03.575 E/RemoteRequest( 2084): 	at com.couchbase.lite.support.MultipartReader.trimBuffer(MultipartReader.java:123)
11-18 10:58:03.575 E/RemoteRequest( 2084): 	at com.couchbase.lite.support.MultipartReader.appendData(MultipartReader.java:177)
11-18 10:58:03.575 E/RemoteRequest( 2084): 	at com.couchbase.lite.replicator.BulkDownloader.executeRequest(BulkDownloader.java:148)
11-18 10:58:03.575 E/RemoteRequest( 2084): 	at com.couchbase.lite.replicator.BulkDownloader.run(BulkDownloader.java:89)
11-18 10:58:03.575 E/RemoteRequest( 2084): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
11-18 10:58:03.575 E/RemoteRequest( 2084): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
11-18 10:58:03.575 E/RemoteRequest( 2084): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
11-18 10:58:03.575 E/RemoteRequest( 2084): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
11-18 10:58:03.575 E/RemoteRequest( 2084): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
11-18 10:58:03.575 E/RemoteRequest( 2084): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
11-18 10:58:03.575 E/RemoteRequest( 2084): 	at java.lang.Thread.run(Thread.java:818)
11-18 10:58:03.589 E/Sync    ( 2084): com.couchbase.lite.replicator.PullerInternal@f67f833: Progress: set error = java.lang.IllegalStateException: _docReader is not defined
11-18 10:58:04.223 I/art     ( 2084): Background partial concurrent mark sweep GC freed 19836(3MB) AllocSpace objects, 2(128KB) LOS objects, 24% free, 2MB/2MB, paused 3.364ms total 266.447ms
11-18 10:58:04.705 E/RemoteRequest( 2084): com.couchbase.lite.replicator.BulkDownloader[/db/_bulk_get]: executeRequest() Exception: 
11-18 10:58:04.705 E/RemoteRequest( 2084): java.lang.IllegalStateException: _docReader is not defined
11-18 10:58:04.705 E/RemoteRequest( 2084): 	at com.couchbase.lite.replicator.BulkDownloader.appendToPart(BulkDownloader.java:239)
11-18 10:58:04.705 E/RemoteRequest( 2084): 	at com.couchbase.lite.support.MultipartReader.trimBuffer(MultipartReader.java:123)
11-18 10:58:04.705 E/RemoteRequest( 2084): 	at com.couchbase.lite.support.MultipartReader.appendData(MultipartReader.java:177)
11-18 10:58:04.705 E/RemoteRequest( 2084): 	at com.couchbase.lite.replicator.BulkDownloader.executeRequest(BulkDownloader.java:148)
11-18 10:58:04.705 E/RemoteRequest( 2084): 	at com.couchbase.lite.replicator.BulkDownloader.run(BulkDownloader.java:89)
11-18 10:58:04.705 E/RemoteRequest( 2084): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
11-18 10:58:04.705 E/RemoteRequest( 2084): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
11-18 10:58:04.705 E/RemoteRequest( 2084): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
11-18 10:58:04.705 E/RemoteRequest( 2084): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
11-18 10:58:04.705 E/RemoteRequest( 2084): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
11-18 10:58:04.705 E/RemoteRequest( 2084): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
11-18 10:58:04.705 E/RemoteRequest( 2084): 	at java.lang.Thread.run(Thread.java:818)
11-18 10:58:04.706 E/Sync    ( 2084): com.couchbase.lite.replicator.PullerInternal@f67f833: Progress: set error = java.lang.IllegalStateException: _docReader is not defined
```

**Comment by hideki** [comment]
Hi @andreibaranouski,

Could you please post details of test condition?

**Comment by hideki** [comment]
Some reason _docReader is null.

```java
    public void appendToPart(final byte[] data, int off, int len) {
        if (_docReader == null) {
            throw new IllegalStateException("_docReader is not defined");
        }
        _docReader.appendData(data, off, len);
    }
```

**Comment by andreibaranouski** [comment]
This occurs in almost all replication tests, for example in https://github.com/couchbaselabs/sync-gateway-tests/blob/master/tests/cbl-replication.js#L119-L168
cblite logs - https://friendpaste.com/3uaQyc0el6PsULTRWj7QkO
test logs - https://friendpaste.com/3uaQyc0el6PsULTRWiqKXd

steps:
1) set push/pull replication to gateway
ok 4 { _replicate: 'cbl-replication1 -> http://10.0.2.2:9888/db' }
ok 5 { _replicate: 'cbl-replication7 <- http://10.0.2.2:9888/db' }
2) load liteServ database cbl-replication1

**Comment by joshblour** [comment]
I've just started seeing this too

**Comment by hegra** [comment]
Appeared after upgrading sync gateway to latest version for me.

**Comment by hideki** [comment]
Hi @andreibaranouski, @joshblour, and @hegra,

What version of Sync Gateway are you using? v1.1.0? or build from master branch?

Thanks!

**Comment by joshblour** [comment]
I built from master: ==== Couchbase Sync Gateway/master(7fce059+CHANGES) ====

**Comment by hideki** [comment]
@jamesmauss , Thanks!

**Comment by hegra** [comment]
master

**Comment by andreibaranouski** [comment]
yeap, I use master too

**Comment by hideki** [comment]
Note to self:

Current implementation of CBL Android does not support gzip for /_bulk_get with `multipart` document.
https://github.com/couchbase/couchbase-lite-java-core/blob/master/src/main/java/com/couchbase/lite/replicator/BulkDownloader.java#L141-L152

With latest `master` branch of sync_gateway returns gzipped `multipart` document for `/_bulk_get`.

It seems Sync Gateway 1.1.x or earlier returns non-gzipped  `multipart` document for `/_bulk_get`. 

master branch version of Sync Gateway
<img width="1044" alt="screen shot 2015-12-08 at 9 38 07 pm" src="https://cloud.githubusercontent.com/assets/15889/11677570/0070690c-9df4-11e5-8247-5046ce7e8278.png">

Sync Gateway v1.1.1
<img width="1061" alt="screen shot 2015-12-08 at 9 39 12 pm" src="https://cloud.githubusercontent.com/assets/15889/11677591/2ed1ccfa-9df4-11e5-9f81-e3b3489c7860.png">

**Comment by hideki** [comment]
Comments from Sync Gateway Engineer


>sounds like you're seeing this change: https://github.com/couchbase/sync_gateway/issues/1163
From the PR: "If a client passes the HTTP header "Accept-Encoding: gzip" then the header "X-Accept-Part-Encoding: gzip" will be ignored if it is passed and the entire HTTP response will be gzip compressed."
So for 1.1 and earlier, SG was gzip encoding the individual mime parts if the X-Accept-Part-Encoding header was set
on master, this behaviour should be the same
however, if the client passes Accept-Encoding:gzip, the entire response will be encoded instead

>


>Yes - as Jens describes on the ticket, Accept-Encoding:gzip is usually going to result in smaller overall download sizes for two reasons: the mime boundary information gets compressed, and common elements between docs will have better compression

**Comment by joshblour** [comment]
would you be able to make a build available that includes this fix?

**Comment by hideki** [comment]
@joshblour Could you please wait for a week or two from today? Thanks!

**Comment by joshblour** [comment]
@hideki sure, thank you
