### ISSUE TITLE
In case ChangeTracker stops with HTTP 401, Continuous pull replicator does not stop

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-java-core#851]
Start continuous pull replication with invalid SG session ID for custom authentication. SG returns HTTP 401, ChangeTracker stops, but Pull Replicator does not stop.
```
12-08 00:52:18.818 15504-16630/self.hideki.cbltestapp V/Sync: com.couchbase.lite.support.RemoteRequest@52854dd8: RemoteRequest finally block.  url: http://10.0.0.10:4984/db/_local/cdfd864da03e4858a4187cb2c3187a49a7bd3a2c
12-08 00:52:18.818 15504-16630/self.hideki.cbltestapp V/Sync: com.couchbase.lite.support.RemoteRequest@52854dd8: RemoteRequest run() finished, url: http://10.0.0.10:4984/db/_local/cdfd864da03e4858a4187cb2c3187a49a7bd3a2c
12-08 00:52:18.838 15504-16633/self.hideki.cbltestapp E/ChangeTracker: com.couchbase.lite.replicator.ChangeTracker@52830f1c: Change tracker got error 401
12-08 00:52:18.838 15504-15671/self.hideki.cbltestapp D/Sync: changeTrackerStopped.  lifecycle: CONTINUOUS
12-08 00:52:18.838 15504-15671/self.hideki.cbltestapp E/Sync: Change tracker stopped during continuous replication
12-08 00:52:18.838 15504-15671/self.hideki.cbltestapp D/Sync: [fireTrigger()] => WAITING_FOR_CHANGES
12-08 00:52:18.838 15504-15671/self.hideki.cbltestapp D/Sync: Scheduling change tracker restart in 10000 ms
12-08 00:52:18.838 15504-15671/self.hideki.cbltestapp D/Sync: firing trigger: WAITING_FOR_CHANGES
12-08 00:52:18.838 15504-15671/self.hideki.cbltestapp V/Sync: [onEntry()] RUNNING => IDLE
12-08 00:52:18.838 15504-15671/self.hideki.cbltestapp D/Sync: State transition: RUNNING -> IDLE (via WAITING_FOR_CHANGES).  this: com.couchbase.lite.replicator.PullerInternal@52822c04
12-08 00:52:18.838 15504-15671/self.hideki.cbltestapp I/CBLTestApp: PULL replication event. Source: com.couchbase.lite.replicator.Replication@5282111c Transition: RUNNING -> IDLE Total changes: 0 Completed changes: 0
12-08 00:52:18.842 15504-15671/self.hideki.cbltestapp E/CBLTestApp: REPLICATION ERROR
                                                                    java.lang.Exception: Change tracker stopped during continuous replication
                                                                        at com.couchbase.lite.replicator.PullerInternal.processChangeTrackerStopped(PullerInternal.java:827)
                                                                        at com.couchbase.lite.replicator.PullerInternal.access$300(PullerInternal.java:50)
                                                                        at com.couchbase.lite.replicator.PullerInternal$9.run(PullerInternal.java:793)
                                                                        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
                                                                        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                        at java.lang.Thread.run(Thread.java:841)
12-08 00:52:19.266 15504-16631/self.hideki.cbltestapp D/Sync: batcher.waitForPendingFutures()
12-08 00:52:19.266 15504-16631/self.hideki.cbltestapp D/Sync: waitPendingFuturesCompleted()
12-08 00:52:19.266 15504-16631/self.hideki.cbltestapp D/Sync: calling future.get() on com.couchbase.lite.support.RemoteRequestRetry@52854cfc
12-08 00:52:19.266 15504-16631/self.hideki.cbltestapp D/Sync: done calling future.get() on com.couchbase.lite.support.RemoteRequestRetry@52854cfc
12-08 00:52:20.266 15504-16631/self.hideki.cbltestapp D/Sync: downloadsToInsert.waitForPendingFutures()
12-08 00:52:20.266 15504-16631/self.hideki.cbltestapp D/Sync: [fireTrigger()] => WAITING_FOR_CHANGES
12-08 00:52:20.266 15504-16631/self.hideki.cbltestapp D/Sync: [waitForPendingFutures()] END - thread id: 130
12-08 00:52:20.270 15504-15671/self.hideki.cbltestapp D/Sync: firing trigger: WAITING_FOR_CHANGES
12-08 00:52:20.270 15504-15671/self.hideki.cbltestapp V/Sync: [onExit()] IDLE => IDLE
12-08 00:52:20.270 15504-15671/self.hideki.cbltestapp V/Sync: [onEntry()] IDLE => IDLE
```

**Comment by hideki** [comment]
After fixing #852, this issue is no longer reproducible. I will close this.
