### ISSUE TITLE
Unit Test: testRemoteConflictResolution failure

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-java-core#865]
```
junit.framework.AssertionFailedError
at com.couchbase.lite.replicator.ReplicationTest.testRemoteConflictResolution(ReplicationTest.java:1405)
at java.lang.reflect.Method.invokeNative(Native Method)
at com.couchbase.lite.LiteTestCase.runBare(LiteTestCase.java:20)
at com.couchbase.lite.LiteTestCaseWithDB.runBare(LiteTestCaseWithDB.java:85)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:191)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:176)
at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:554)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1701)
```

It seems dispatcher did not finish to process when replication stopped, 
```java
            // run pull replication
            Replication pullReplication = database.createPullReplication(server.getUrl("/db"));
            runReplication(pullReplication);
            assertNull(pullReplication.getLastError());

            // assertions about outgoing requests
            RecordedRequest changesRequest = dispatcher.takeRequest(MockHelper.PATH_REGEX_CHANGES);
            assertNotNull(changesRequest);
            RecordedRequest docRev3DeletedRequest = dispatcher.takeRequest(docRev3Deleted.getDocPathRegex());
            assertNotNull(docRev3DeletedRequest);
            RecordedRequest docRev3PromotedRequest = dispatcher.takeRequest(docRev3Promoted.getDocPathRegex());
            assertNotNull(docRev3PromotedRequest);
```

**Comment by hideki** [comment]
we can not reproduce this any more. I assume recent bug fixes also addressed this issue.
