### ISSUE TITLE
Conflict during putLocalDocument: Need to investigate

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-java-core#954]
Note to Self:

Need to investigate following Exception.

- Nexus 9
- ToDoLite with ForestDB
- How to reproduce: Just clean install and run.
- Not observed this every time.

```
01-26 13:03:29.346 2656-3650/com.couchbase.todolite E/Sync: Exception saving local doc
com.couchbase.lite.CouchbaseLiteException, Status: 409 (HTTP 409 conflict)
	at com.couchbase.lite.store.ForestDBStore.putLocalRevision(ForestDBStore.java:1187)
	at com.couchbase.lite.Database.putLocalRevision(Database.java:1867)
	at com.couchbase.lite.Database.putLocalDocument(Database.java:530)
	at com.couchbase.lite.support.PersistentCookieStore.addCookie(PersistentCookieStore.java:145)
	at org.apache.http.client.protocol.ResponseProcessCookies.processCookies(ResponseProcessCookies.java:129)
	at org.apache.http.client.protocol.ResponseProcessCookies.process(ResponseProcessCookies.java:106)
	at org.apache.http.protocol.BasicHttpProcessor.process(BasicHttpProcessor.java:309)
	at org.apache.http.protocol.HttpRequestExecutor.postProcess(HttpRequestExecutor.java:324)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:476)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:560)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:492)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:470)
	at com.couchbase.lite.support.RemoteRequest.executeRequest(RemoteRequest.java:182)
	at com.couchbase.lite.support.RemoteRequest.run(RemoteRequest.java:102)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)
01-26 13:03:29.347 2656-3650/com.couchbase.todolite E/RemoteRequest: com.couchbase.lite.support.RemoteRequest@b45b20: executeRequest() Exception: java.lang.RuntimeException: com.couchbase.lite.CouchbaseLiteException, Status: 409 (HTTP 409 conflict).  url: http://ec2-54-145-244-2.compute-1.amazonaws.com:4984/todolite-cc/_facebook
```

**Comment by hideki** [comment]
`PersistentCookieStore` is not thread-safe. However cookieStore could be accessed from pull replicator and push replicator simultaneously.

**Comment by hideki** [comment]
Note to Self:
By implementing #694, CookieStore might not be necessary to be thread-safe.

**Comment by hideki** [comment]
client log
```
01-27 00:26:19.273 7974-7974/com.couchbase.todolite I/Database: [getInfo()] Key("privateUUID") is not found.
01-27 00:26:19.280 7974-7974/com.couchbase.todolite I/Database: [getInfo()] Key("max_revs") is not found.
01-27 00:26:19.283 7974-7974/com.couchbase.todolite I/Database: [getLocalDocument()] docID("_local/_blobstore") is not found
01-27 00:26:19.322 7974-7974/com.couchbase.todolite I/Database: [getInfo()] Key("privateUUID") is not found.
01-27 00:26:19.327 7974-7974/com.couchbase.todolite I/Database: [getInfo()] Key("max_revs") is not found.
01-27 00:26:19.331 7974-7974/com.couchbase.todolite I/Database: [getLocalDocument()] docID("_local/_blobstore") is not found
01-27 00:26:19.443 7974-7974/com.couchbase.todolite I/Database: [getLocalDocument()] docID("_local/PersistentCookieStore") is not found
01-27 00:26:20.522 7974-8511/com.couchbase.todolite E/Sync: com.couchbase.lite.replicator.ReplicationInternal$4@2c980b7 checkSessionAtPath() response: {authentication_handlers=[default, cookie], ok=true, userCtx={channels={}, name=null}}
01-27 00:26:20.522 7974-8509/com.couchbase.todolite E/Sync: com.couchbase.lite.replicator.ReplicationInternal$4@55e6bb6 checkSessionAtPath() response: {authentication_handlers=[default, cookie], ok=true, userCtx={channels={}, name=null}}
01-27 00:26:20.694 7974-8509/com.couchbase.todolite I/Database: [getLocalDocument()] docID("_local/PersistentCookieStore") is not found
01-27 00:26:20.694 7974-8535/com.couchbase.todolite I/Database: [getLocalDocument()] docID("_local/PersistentCookieStore") is not found
01-27 00:26:20.694 7974-8535/com.couchbase.todolite I/Database: [getLocalDocument()] docID("_local/PersistentCookieStore") is not found
01-27 00:26:20.695 7974-8509/com.couchbase.todolite I/Database: [getLocalDocument()] docID("_local/PersistentCookieStore") is not found
01-27 00:26:20.705 7974-8509/com.couchbase.todolite E/Sync: Exception saving local doc
                                                            com.couchbase.lite.CouchbaseLiteException, Status: 409 (HTTP 409 conflict)
                                                                at com.couchbase.lite.store.ForestDBStore.putLocalRevision(ForestDBStore.java:1187)
                                                                at com.couchbase.lite.Database.putLocalRevision(Database.java:1867)
                                                                at com.couchbase.lite.Database.putLocalDocument(Database.java:530)
                                                                at com.couchbase.lite.support.PersistentCookieStore.addCookie(PersistentCookieStore.java:145)
                                                                at org.apache.http.client.protocol.ResponseProcessCookies.processCookies(ResponseProcessCookies.java:129)
                                                                at org.apache.http.client.protocol.ResponseProcessCookies.process(ResponseProcessCookies.java:106)
                                                                at org.apache.http.protocol.BasicHttpProcessor.process(BasicHttpProcessor.java:309)
                                                                at org.apache.http.protocol.HttpRequestExecutor.postProcess(HttpRequestExecutor.java:324)
                                                                at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:476)
                                                                at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:560)
                                                                at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:492)
                                                                at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:470)
                                                                at com.couchbase.lite.support.RemoteRequest.executeRequest(RemoteRequest.java:182)
                                                                at com.couchbase.lite.support.RemoteRequest.run(RemoteRequest.java:102)
                                                                at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                at java.lang.Thread.run(Thread.java:818)
01-27 00:26:20.706 7974-8509/com.couchbase.todolite E/RemoteRequest: com.couchbase.lite.support.RemoteRequest@2eb7153: executeRequest() Exception: java.lang.RuntimeException: com.couchbase.lite.CouchbaseLiteException, Status: 409 (HTTP 409 conflict).  url: http://10.0.0.20:4984/todolite/_facebook
01-27 00:26:20.706 7974-8535/com.couchbase.todolite I/Database: [getInfo()] Key("checkpoint/e1dca39a966c95ae3a6db43a75f09229576d6739") is not found.
01-27 00:26:20.707 7974-8509/com.couchbase.todolite E/Sync: com.couchbase.lite.replicator.PullerInternal@9613dcf: Progress: set error = java.lang.RuntimeException: com.couchbase.lite.CouchbaseLiteException, Status: 409 (HTTP 409 conflict)
01-27 00:26:20.722 7974-8511/com.couchbase.todolite W/Sync: Error converting lastSequence: null to long.  Using 0
```

sync_gateway log
```
2016-01-27T00:26:21.409-08:00 HTTP:  #067: GET /todolite/_session
2016-01-27T00:26:21.410-08:00 HTTP:  #068: GET /todolite/_session
2016-01-27T00:26:21.428-08:00 HTTP:  #069: POST /todolite/_facebook
2016-01-27T00:26:21.430-08:00 HTTP:  #070: POST /todolite/_facebook
2016-01-27T00:26:21.613-08:00 HTTP:  #071: GET /todolite/_local/e1dca39a966c95ae3a6db43a75f09229576d6739  (as 1398835190428562)
2016-01-27T00:26:21.613-08:00 HTTP: #071:     --> 404 missing  (0.2 ms)
2016-01-27T00:26:22.345-08:00 HTTP:  #072: POST /todolite/_revs_diff  (as 1398835190428562)
2016-01-27T00:26:27.446-08:00 HTTP:  #073: PUT /todolite/_local/e1dca39a966c95ae3a6db43a75f09229576d6739  (as 1398835190428562)
```

**Comment by hideki** [comment]
Note to self:

Conflict is caused by updating same local doc value from two replicators. This conflict error causes subsequent problem to replicator.

iOS historically run putLocalDoc in Transaction by 1.0.4 release:
https://github.com/couchbase/couchbase-lite-ios/blob/release/1.0.4/Source/API/CBLDatabase.m#L327-L342

From 1.1.0, iOS implementation call putLocalDoc with obeyMVCC=false to ignore prevRev
https://github.com/couchbase/couchbase-lite-ios/blob/release/1.1.0/Source/API/CBLDatabase.m#L346-L349

Note:
```
    @param obeyMVCC  If YES, the prevRevID must match the document's current revID (or nil if the
                    document doesn't exist) or a 409 error is returned. If NO, the prevRevID is
                    ignored and the operation always succeeds.
```
