### ISSUE TITLE
Failed to rebuild view : Status 500

### ISSUE THREAD

**Issue by sureshjoshi** [couchbase/couchbase-lite-java-core#983]
Hey all, I just ran into this error several times on com.couchbase.lite:couchbase-lite-android:1.1.0

After spending some time looking around, and breaking through the code, I found out that my mapper function was throwing an exception - however, nothing in the error messages, or on the internet alluded to that being the case.

Is there any documentation surrounding this? The 500 error appears to be a Status.INTERNAL_SERVER_ERROR so that confused me more than anything.

Thanks!

**Comment by hideki** [comment]
Hi @sureshjoshi ,

v1.1.0 `View.updateIndex()` does not catch the exception from mapper.

https://github.com/couchbase/couchbase-lite-java-core/blob/release/1.1.0/src/main/java/com/couchbase/lite/View.java#L621

https://github.com/couchbase/couchbase-lite-java-core/blob/release/1.1.0/src/main/java/com/couchbase/lite/Mapper.java#L32

Could you provide more information to understand this error deeper?

Thanks,
Hideki

**Comment by sureshjoshi** [comment]
Hi @hideki, I think I've given about all the info I have  :)

Inside a view mapper, I threw an exception of some sort... Something like doc.get("someKeyThatDidntExist").someAction

The above threw an NPE, and I can't recall if that crashed the app and gave me the status error, or just gave me the error and did not work (I want to say that it might have crashed the app) - the problem was, there was no usable stack trace to see it was coming from the mapper.

**Comment by hideki** [comment]
In general, Couchbase Lite code does not catch NPE or RuntimeException. Can you catch NPE or RuntimeException in `map()` function to avoid this problem?

If it crashes, I believe staracktracle should be printed in logcat. Can you look into it?

**Comment by sureshjoshi** [comment]
Hmm, I just tried it again, and now I'm getting a good stack trace - but I definitely wasn't getting one yesterday, otherwise it would have taken 2 seconds to debug. I couldn't replicate the exact mapper/caller I wrote yesterday - as that code was long gone and not source controlled, but here is something close.

```
        database.getView("hideki/byId")
                .setMap((doc, emitter) -> {
                    String docType = String.valueOf(doc.get("docType"));
                    if (docType.equals("profile")) {
                        long creationDateMillis = DateTime.parse(doc.get("doesNotExist").toString()).getMillis();
                        emitter.emit(doc.get("_id"), null);
                    }
                }, "2"); // Note: This number should be incremented if changes to the Map are made
```

```
public void crashTestDummy() {
        Query query = mDatabase.getView("hideki/byId").createQuery();
        try {
            QueryEnumerator results = query.run();
            while (results.hasNext()) {
                QueryRow row = results.next();
                if (row != null) {
                    ModelType modelType = ModelType.fromString(String.valueOf(row.getValue()));
                }
            }
        } catch (CouchbaseLiteException e) {
            e.printStackTrace();
        }
    }
```

```
com.example.android.debug W/View: Failed to rebuild view hideki/byId.  Result code: 500
com.example.android.debug D/AndroidRuntime: Shutting down VM
com.example.android.debug E/AndroidRuntime: FATAL EXCEPTION: main
      Process: com.example.android.debug, PID: 27879
      java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
          at com.example.android.core.managers.PersistenceManager.lambda$initializeDatabaseViews$21(PersistenceManager.java:205)
          at com.example.android.core.managers.PersistenceManager.access$lambda$3(PersistenceManager.java)
          at com.example.android.core.managers.PersistenceManager$$Lambda$6.map(Unknown Source)
          at com.couchbase.lite.View.updateIndex(View.java:621)
          at com.couchbase.lite.Database.queryViewNamed(Database.java:2495)
          at com.couchbase.lite.Query.run(Query.java:395)
          at com.example.android.core.managers.PersistenceManager.crashTestDummy(PersistenceManager.java:262)
          at com.example.android.activities.DeviceScanActivity.sync(DeviceScanActivity.java:60)
          at com.example.android.activities.DeviceScanActivity$$ViewBinder$2.doClick(DeviceScanActivity$$ViewBinder.java:29)
          at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)
          at android.view.View.performClick(View.java:5204)
          at android.view.View$PerformClick.run(View.java:21153)
          at android.os.Handler.handleCallback(Handler.java:739)
          at android.os.Handler.dispatchMessage(Handler.java:95)
          at android.os.Looper.loop(Looper.java:148)
          at android.app.ActivityThread.main(ActivityThread.java:5417)
          at java.lang.reflect.Method.invoke(Native Method)
          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

I'll close this issue, and re-open if I can re-create the issue in the future.
