### ISSUE TITLE
Router.java - IOException from BufferOutputStream

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-java-core#996]
```
02-07 00:34:44.599 27281-27640/com.emirates.skybook E/Router: IOException writing to internal streams
  java.io.IOException: Can't write to closed stream.
      at com.couchbase.lite.router.BufferOutputStream.write(BufferOutputStream.java:19)
      at java.io.OutputStream.write(OutputStream.java:106)
      at java.io.OutputStream.write(OutputStream.java:82)
      at com.couchbase.lite.router.Router.changed(Router.java:1509)
      at com.couchbase.lite.Database.postChangeNotifications(Database.java:2265)
      at com.couchbase.lite.Database.storageExitedTransaction(Database.java:701)
      at com.couchbase.lite.store.SQLiteStore.endTransaction(SQLiteStore.java:2144)
      at com.couchbase.lite.store.SQLiteStore.runInTransaction(SQLiteStore.java:678)
      at com.couchbase.lite.router.Router.do_POST_Document_bulk_docs(Router.java:1173)
      at java.lang.reflect.Method.invoke(Native Method)
      at java.lang.reflect.Method.invoke(Method.java:372)
      at com.couchbase.lite.router.Router.start(Router.java:489)
      at com.couchbase.lite.listener.LiteServlet.service(LiteServlet.java:128)
      at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)
      at Acme.Serve.Serve$ServeConnection.runServlet(Serve.java:2251)
      at Acme.Serve.Serve$ServeConnection.parseRequest(Serve.java:2176)
      at Acme.Serve.Serve$ServeConnection.run(Serve.java:1988)
      at Acme.Utils$ThreadPool$PooledThread.run(Utils.java:1223)
      at java.lang.Thread.run(Thread.java:818)
```

**Comment by hideki** [comment]
This exception could be thrown before applying the fix. I will close this.

**Comment by jamiltz** [comment]
Steps to reproduce issue:
- Start listener with patch from https://github.com/couchbase/couchbase-lite-java-core/pull/989
- Download sample JSON at http://cl.ly/163k1o3Y3z2k
- Run Curl command:

```
$ curl -H 'Content-Type: application/json' -vX POST 'http://localhost:5984/ek0073/_bulk_docs' -d @data.json
```

Exception in LogCat:

```
E/Router: IOException writing to internal streams
          java.io.IOException: Can't write to closed stream.
              at com.couchbase.lite.router.BufferOutputStream.write(BufferOutputStream.java:19)
              at java.io.OutputStream.write(OutputStream.java:106)
              at java.io.OutputStream.write(OutputStream.java:82)
              at com.couchbase.lite.router.Router.changed(Router.java:1509)
              at com.couchbase.lite.Database.postChangeNotifications(Database.java:2265)
              at com.couchbase.lite.Database.storageExitedTransaction(Database.java:701)
              at com.couchbase.lite.store.SQLiteStore.endTransaction(SQLiteStore.java:2144)
              at com.couchbase.lite.store.SQLiteStore.runInTransaction(SQLiteStore.java:678)
              at com.couchbase.lite.router.Router.do_POST_Document_bulk_docs(Router.java:1173)
              at java.lang.reflect.Method.invoke(Native Method)
              at java.lang.reflect.Method.invoke(Method.java:372)
              at com.couchbase.lite.router.Router.start(Router.java:489)
              at com.couchbase.lite.listener.LiteServlet.service(LiteServlet.java:128)
              at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)
              at Acme.Serve.Serve$ServeConnection.runServlet(Serve.java:2251)
              at Acme.Serve.Serve$ServeConnection.parseRequest(Serve.java:2176)
              at Acme.Serve.Serve$ServeConnection.run(Serve.java:1988)
              at Acme.Utils$ThreadPool$PooledThread.run(Utils.java:1223)
              at java.lang.Thread.run(Thread.java:818)
```

**Comment by jamiltz** [comment]
Also need to create database `ek0073`.

**Comment by pasin** [comment]
@jamiltz I'm curious if it's possible to have a _changes feed request coming while running the curl command?
